In [1]:
import pandas as pd

## Read Inventory

In [2]:
import pandas as pd
from pathlib import Path

# Root folder
root_folder = Path(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\inventory"
)

# Find all csv and excel files recursively
files = list(root_folder.rglob("*.csv")) + \
        list(root_folder.rglob("*.xlsx")) + \
        list(root_folder.rglob("*.xls"))

print(f"Total files found: {len(files)}")

dfs = []

for file in files:
    try:
        if file.suffix.lower() == ".csv":
            temp_df = pd.read_csv(file)
        else:
            temp_df = pd.read_excel(file)

        # Optional metadata
        temp_df["source_file"] = file.name
        temp_df["month"] = file.parent.name          # june, may, etc.
        temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
        temp_df["file_path"] = str(file)

        dfs.append(temp_df)

        print(f"✓ Loaded: {file.name}")

    except Exception as e:
        print(f"✗ Error reading {file}: {e}")

# Combine all files
df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

print("\nFinal Shape:", df.shape)

# Preview
df

Total files found: 10
✓ Loaded: noon_minutes-01_June_2026.csv
✓ Loaded: noon_minutes-02_June_2026.csv
✓ Loaded: noon_minutes-03_June_2026.csv
✓ Loaded: noon_minutes-04_June_2026.csv
✓ Loaded: noon_minutes-05_June_2026.csv
✓ Loaded: noon_minutes-08_June_2026.csv
✓ Loaded: noon_minutes-09_June_2026.csv
✓ Loaded: noon_minutes-10_June_2026.csv
✓ Loaded: noon_minutes-11_June_2026.csv
✓ Loaded: noon_minutes-12_June_2026.csv

Final Shape: (14737, 15)

,Warehouse,Warehouse Code,Category,ZSKU,Barcode,Brand,Product Title,Product Type,Product Sub-Type,Refresh Time,Stock,source_file,month,year,file_path
0,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,ZC22E01C3AED911BCDD94Z-1,4057278012422,pattex,Super Glue Liquid Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",266,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
1,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,Z4975C90C8900E6C933E5Z-1,4057278012453,pattex,Super Glue Power Gel Control 1 x 3g 1 x 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",195,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
2,Dubai South WH - Dubai South Logistics Distric...,W00833473AE,Stationery,ZC22E01C3AED911BCDD94Z-1,4057278012422,pattex,Super Glue Liquid Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",194,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,pattex,Super Glue Power Gel Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",136,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
4,Dubai South WH - Dubai South Logistics Distric...,W00833473AE,Stationery,Z4975C90C8900E6C933E5Z-1,4057278012453,pattex,Super Glue Power Gel Control 1 x 3g 1 x 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",103,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14732,Abu Shaghara,W00060249A,Stationery,Z6CF488BCCB75DA003E6BZ-1,4057278012507,pattex,No More Nails Invisible 40g 40g,adhesives_sealers_and_tapes,super_glue,"12 Jun 2026, 03:35:00",0,noon_minutes-12_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
14733,Downtown Dubai,W00050759A,Stationery,Z41917D6E86BF75D31B27Z-1,4057278012491,pattex,No More Nails Strong And Easy 50g,adhesives_sealers_and_tapes,super_glue,"12 Jun 2026, 03:35:00",0,noon_minutes-12_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
14734,Motor City,W00000165A,Stationery,Z41917D6E86BF75D31B27Z-1,4057278012491,pattex,No More Nails Strong And Easy 50g,adhesives_sealers_and_tapes,super_glue,"12 Jun 2026, 03:35:00",0,noon_minutes-12_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
14735,Al Rawda 3,W00048742A,Stationery,Z67A14260CB22A4D0A465Z-1,6295199302057,pritt,Original SRP Glue Sticks (22g) - Pack of 4 | S...,tape_adhesives_fasteners,glue_sticks,"12 Jun 2026, 03:35:00",0,noon_minutes-12_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
14736,Dubai South,W00089031A,Stationery,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,pattex,Super Glue Power Gel Tube 3g,adhesives_sealers_and_tapes,super_glue,"12 Jun 2026, 03:35:00",0,noon_minutes-12_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...

## Select Cols

In [3]:
df.rename(columns={"Refresh Time": "Date", "Stock": "Inventory", }, inplace=True)
cols_to_keep = [
    "Date",
    "Inventory",
    "ZSKU",
    "Warehouse Code",
]
df = df[cols_to_keep]
df

,Date,Inventory,ZSKU,Warehouse Code
0,"1 Jun 2026, 03:35:00",266,ZC22E01C3AED911BCDD94Z-1,W00068387A
1,"1 Jun 2026, 03:35:00",195,Z4975C90C8900E6C933E5Z-1,W00068387A
2,"1 Jun 2026, 03:35:00",194,ZC22E01C3AED911BCDD94Z-1,W00833473AE
3,"1 Jun 2026, 03:35:00",136,ZF1DE7A17A2F4DE0CC7AAZ-1,W00068387A
4,"1 Jun 2026, 03:35:00",103,Z4975C90C8900E6C933E5Z-1,W00833473AE
...,...,...,...,...
14732,"12 Jun 2026, 03:35:00",0,Z6CF488BCCB75DA003E6BZ-1,W00060249A
14733,"12 Jun 2026, 03:35:00",0,Z41917D6E86BF75D31B27Z-1,W00050759A
14734,"12 Jun 2026, 03:35:00",0,Z41917D6E86BF75D31B27Z-1,W00000165A
14735,"12 Jun 2026, 03:35:00",0,Z67A14260CB22A4D0A465Z-1,W00048742A
14736,"12 Jun 2026, 03:35:00",0,ZF1DE7A17A2F4DE0CC7AAZ-1,W00089031A

## GroupBy the data

In [4]:
import pandas as pd

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Format date as 01-June-2026
df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

# Group by Date and ZSKU and sum Inventory
df_inv = df.copy()
df_inv

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_38356\881166070.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_38356\881166070.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

               Date  Inventory                      ZSKU Warehouse Code
0      01-June-2026        266  ZC22E01C3AED911BCDD94Z-1     W00068387A
1      01-June-2026        195  Z4975C90C8900E6C933E5Z-1     W00068387A
2      01-June-2026        194  ZC22E01C3AED911BCDD94Z-1    W00833473AE
3      01-June-2026        136  ZF1DE7A17A2F4DE0CC7AAZ-1     W00068387A
4      01-June-2026        103  Z4975C90C8900E6C933E5Z-1    W00833473AE
...             ...        ...                       ...            ...
14732  12-June-2026          0  Z6CF488BCCB75DA003E6BZ-1     W00060249A
14733  12-June-2026          0  Z41917D6E86BF75D31B27Z-1     W00050759A
14734  12-June-2026          0  Z41917D6E86BF75D31B27Z-1     W00000165A
14735  12-June-2026          0  Z67A14260CB22A4D0A465Z-1     W00048742A
14736  12-June-2026          0  ZF1DE7A17A2F4DE0CC7AAZ-1     W00089031A

[14737 rows x 4 columns]

## Add product details

In [5]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\helper_file_noon_minutes.xlsx"
)

# Keep only required columns
helper_df = helper_df[['ZSKU', 'Product Name', 'Category', 'Pack Size','Brand']]

# Merge with df_inv
df_inv = df_inv.merge(
    helper_df,
    on='ZSKU',
    how='left'  # keeps all rows from df_inv
)

df_inv

,Date,Inventory,ZSKU,Warehouse Code,Product Name,Category,Pack Size,Brand
0,01-June-2026,266,ZC22E01C3AED911BCDD94Z-1,W00068387A,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex
1,01-June-2026,195,Z4975C90C8900E6C933E5Z-1,W00068387A,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex
2,01-June-2026,194,ZC22E01C3AED911BCDD94Z-1,W00833473AE,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex
3,01-June-2026,136,ZF1DE7A17A2F4DE0CC7AAZ-1,W00068387A,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex
4,01-June-2026,103,Z4975C90C8900E6C933E5Z-1,W00833473AE,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex
...,...,...,...,...,...,...,...,...
14732,12-June-2026,0,Z6CF488BCCB75DA003E6BZ-1,W00060249A,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1,Pattex
14733,12-June-2026,0,Z41917D6E86BF75D31B27Z-1,W00050759A,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1,Pattex
14734,12-June-2026,0,Z41917D6E86BF75D31B27Z-1,W00000165A,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1,Pattex
14735,12-June-2026,0,Z67A14260CB22A4D0A465Z-1,W00048742A,Pritt Glue Stick 22g (Pack of 4),Pritt Glue Stick,Pack of 4,Pritt
14736,12-June-2026,0,ZF1DE7A17A2F4DE0CC7AAZ-1,W00089031A,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex

## add warehouse

In [6]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\warehouse_code_mapping.xlsx"
)

# Keep only required columns
helper_df = helper_df[['Warehouse Code', 'Warehouse', 'Emirate']]

# Merge with df_inv
df_inv = df_inv.merge(
    helper_df,
    on='Warehouse Code',
    how='left'  # keeps all rows from df_inv
)

df_inv

,Date,Inventory,ZSKU,Warehouse Code,Product Name,Category,Pack Size,Brand,Warehouse,Emirate
0,01-June-2026,266,ZC22E01C3AED911BCDD94Z-1,W00068387A,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Noon grocery technopark - Jebel Ali,Dubai
1,01-June-2026,195,Z4975C90C8900E6C933E5Z-1,W00068387A,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Noon grocery technopark - Jebel Ali,Dubai
2,01-June-2026,194,ZC22E01C3AED911BCDD94Z-1,W00833473AE,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Dubai South WH - Dubai South Logistics Distric...,Dubai
3,01-June-2026,136,ZF1DE7A17A2F4DE0CC7AAZ-1,W00068387A,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Noon grocery technopark - Jebel Ali,Dubai
4,01-June-2026,103,Z4975C90C8900E6C933E5Z-1,W00833473AE,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Dubai South WH - Dubai South Logistics Distric...,Dubai
...,...,...,...,...,...,...,...,...,...,...
14922,12-June-2026,0,Z6CF488BCCB75DA003E6BZ-1,W00060249A,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1,Pattex,Abu Shaghara,Sharjah
14923,12-June-2026,0,Z41917D6E86BF75D31B27Z-1,W00050759A,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1,Pattex,Downtown Dubai,Dubai
14924,12-June-2026,0,Z41917D6E86BF75D31B27Z-1,W00000165A,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1,Pattex,Motor City,Dubai
14925,12-June-2026,0,Z67A14260CB22A4D0A465Z-1,W00048742A,Pritt Glue Stick 22g (Pack of 4),Pritt Glue Stick,Pack of 4,Pritt,Al Rawda 3,Ajman
14926,12-June-2026,0,ZF1DE7A17A2F4DE0CC7AAZ-1,W00089031A,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Pattex,Dubai South,Dubai

## now read sales

In [7]:
import pandas as pd
from pathlib import Path

# Root folder
root_folder = Path(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\orders"
)

# Find all csv and excel files recursively
files = list(root_folder.rglob("*.csv")) + \
        list(root_folder.rglob("*.xlsx")) + \
        list(root_folder.rglob("*.xls"))

print(f"Total files found: {len(files)}")

dfs = []

for file in files:
    try:
        if file.suffix.lower() == ".csv":
            temp_df = pd.read_csv(file)
        else:
            temp_df = pd.read_excel(file)

        # Optional metadata
        temp_df["source_file"] = file.name
        temp_df["month"] = file.parent.name          # june, may, etc.
        temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
        temp_df["file_path"] = str(file)

        dfs.append(temp_df)

        print(f"✓ Loaded: {file.name}")

    except Exception as e:
        print(f"✗ Error reading {file}: {e}")

# Combine all files
df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

print("\nFinal Shape:", df.shape)

# Preview
df

Total files found: 2
✓ Loaded: PATTEX_noon_minutes_sales_june_2026.csv
✓ Loaded: PATTEX_noon_minutes_sales_may_2026.csv

Final Shape: (3234, 20)

,Date,Month,Country,Platform,Warehouse,Warehouse Cod,Category,nsku,ZSKU,Barcode,Title,Brand,Type,Sub-Type,Qty,Revenue,source_file,month,year,file_path
0,1 Jun 2026,2026-06,AE,Minutes,Al Nasserya,SHJDS03,Stationery,N70158792V-1,ZC22E01C3AED911BCDD94Z-1,4057278012422,Super Glue Liquid TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,8.10,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
1,5 Jun 2026,2026-06,AE,Minutes,Emirates Hills,DXBDS23,Stationery,Z4975C90C8900E6C933E5Z-1,Z4975C90C8900E6C933E5Z-1,4057278012453,Super Glue Power Gel Control 1 x 3g,pattex,adhesives_sealers_and_tapes,super_glue,1,11.95,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
2,2 Jun 2026,2026-06,AE,Minutes,NaN,AUHDS29,Stationery,Z4975C90C8900E6C933E5Z-1,Z4975C90C8900E6C933E5Z-1,4057278012453,Super Glue Power Gel Control 1 x 3g,pattex,adhesives_sealers_and_tapes,super_glue,1,11.90,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3,7 Jun 2026,2026-06,AE,Minutes,JVC 5,DXBDS114,Stationery,N70158773V-1,Z41917D6E86BF75D31B27Z-1,4057278012491,No More Nails Strong And EasyClear,pattex,adhesives_sealers_and_tapes,super_glue,1,15.50,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
4,1 Jun 2026,2026-06,AE,Minutes,Al Nahda 2 - Sharjah,SHJDS16,Stationery,N70158792V-1,ZC22E01C3AED911BCDD94Z-1,4057278012422,Super Glue Liquid TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,8.15,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3229,15 May 2026,2026-05,AE,Minutes,Production City,DXBDS28,Stationery,N70158783V-1,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,Super Glue Power Gel TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,6.30,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3230,3 May 2026,2026-05,AE,Minutes,Town Square 2,DXBDS47,Stationery,N70158792V-1,ZC22E01C3AED911BCDD94Z-1,4057278012422,Super Glue Liquid TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,2,14.50,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3231,2 May 2026,2026-05,AE,Minutes,Hor Al Anz 2,DXBDS101,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,1,22.45,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3232,13 May 2026,2026-05,AE,Minutes,Khalifa City 2,AUHDS14,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,1,15.35,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3233,20 May 2026,2026-05,AE,Minutes,Muwaileh 3,SHJDS18,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,2,30.70,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...

## Select sales cols

In [8]:
df.rename(columns={"Qty": "qty_sold", "Revenue": "total_sales", "Warehouse Cod": "Warehouse Code" }, inplace=True)
cols_to_keep = [
    "Date",
    "qty_sold",
    "ZSKU",
    "total_sales",
    "Warehouse Code"
]
df = df[cols_to_keep]
df

,Date,qty_sold,ZSKU,total_sales,Warehouse Code
0,1 Jun 2026,1,ZC22E01C3AED911BCDD94Z-1,8.10,SHJDS03
1,5 Jun 2026,1,Z4975C90C8900E6C933E5Z-1,11.95,DXBDS23
2,2 Jun 2026,1,Z4975C90C8900E6C933E5Z-1,11.90,AUHDS29
3,7 Jun 2026,1,Z41917D6E86BF75D31B27Z-1,15.50,DXBDS114
4,1 Jun 2026,1,ZC22E01C3AED911BCDD94Z-1,8.15,SHJDS16
...,...,...,...,...,...
3229,15 May 2026,1,ZF1DE7A17A2F4DE0CC7AAZ-1,6.30,DXBDS28
3230,3 May 2026,2,ZC22E01C3AED911BCDD94Z-1,14.50,DXBDS47
3231,2 May 2026,1,Z3BCEB0AB181B08702C95Z-1,22.45,DXBDS101
3232,13 May 2026,1,Z3BCEB0AB181B08702C95Z-1,15.35,AUHDS14
3233,20 May 2026,2,Z3BCEB0AB181B08702C95Z-1,30.70,SHJDS18

## correct date

In [9]:
import pandas as pd

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Format date as 01-June-2026
df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

# Group by Date and ZSKU and sum Inventory
df_sales = df.copy()

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_38356\3717350964.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_38356\3717350964.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

## Add product details in sales

In [10]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\helper_file_noon_minutes.xlsx"
)

# Keep only required columns
helper_df = helper_df[['ZSKU', 'Product Name', 'Category', 'Pack Size']]

# Merge with df_inv
df_sales = df_sales.merge(
    helper_df,
    on='ZSKU',
    how='left'  # keeps all rows from df_inv
)

df_sales

,Date,qty_sold,ZSKU,total_sales,Warehouse Code,Product Name,Category,Pack Size
0,01-June-2026,1,ZC22E01C3AED911BCDD94Z-1,8.10,SHJDS03,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
1,05-June-2026,1,Z4975C90C8900E6C933E5Z-1,11.95,DXBDS23,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
2,02-June-2026,1,Z4975C90C8900E6C933E5Z-1,11.90,AUHDS29,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
3,07-June-2026,1,Z41917D6E86BF75D31B27Z-1,15.50,DXBDS114,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1
4,01-June-2026,1,ZC22E01C3AED911BCDD94Z-1,8.15,SHJDS16,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
...,...,...,...,...,...,...,...,...
3229,15-May-2026,1,ZF1DE7A17A2F4DE0CC7AAZ-1,6.30,DXBDS28,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
3230,03-May-2026,2,ZC22E01C3AED911BCDD94Z-1,14.50,DXBDS47,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
3231,02-May-2026,1,Z3BCEB0AB181B08702C95Z-1,22.45,DXBDS101,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1
3232,13-May-2026,1,Z3BCEB0AB181B08702C95Z-1,15.35,AUHDS14,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1
3233,20-May-2026,2,Z3BCEB0AB181B08702C95Z-1,30.70,SHJDS18,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1

In [11]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\warehouse_code_mapping.xlsx"
)

# Keep only required columns
helper_df = helper_df[['Warehouse Code', 'Warehouse', 'Emirate']]

# Merge with df_inv
df_sales = df_sales.merge(
    helper_df,
    on='Warehouse Code',
    how='left'  # keeps all rows from df_inv
)

df_sales

,Date,qty_sold,ZSKU,total_sales,Warehouse Code,Product Name,Category,Pack Size,Warehouse,Emirate
0,01-June-2026,1,ZC22E01C3AED911BCDD94Z-1,8.10,SHJDS03,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Al Nasserya,Sharjah
1,05-June-2026,1,Z4975C90C8900E6C933E5Z-1,11.95,DXBDS23,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Emirates Hills,Dubai
2,02-June-2026,1,Z4975C90C8900E6C933E5Z-1,11.90,AUHDS29,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,NaN,Abu Dhabi
3,07-June-2026,1,Z41917D6E86BF75D31B27Z-1,15.50,DXBDS114,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1,JVC 5,Dubai
4,01-June-2026,1,ZC22E01C3AED911BCDD94Z-1,8.15,SHJDS16,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Al Nahda 2 - Sharjah,Sharjah
...,...,...,...,...,...,...,...,...,...,...
3230,15-May-2026,1,ZF1DE7A17A2F4DE0CC7AAZ-1,6.30,DXBDS28,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Production City,Dubai
3231,03-May-2026,2,ZC22E01C3AED911BCDD94Z-1,14.50,DXBDS47,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1,Town Square 2,Dubai
3232,02-May-2026,1,Z3BCEB0AB181B08702C95Z-1,22.45,DXBDS101,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1,Hor Al Anz 2,Dubai
3233,13-May-2026,1,Z3BCEB0AB181B08702C95Z-1,15.35,AUHDS14,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1,Khalifa City 2,Abu Dhabi
3234,20-May-2026,2,Z3BCEB0AB181B08702C95Z-1,30.70,SHJDS18,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1,Muwaileh 3,Sharjah

In [12]:
df_sales.to_csv(r"C:\Users\Shubham Verma\Downloads\sale_dark_store.csv",index = False)

## last 30 day sale

In [13]:
import pandas as pd

# Ensure dates are datetime
df_inv['Date'] = pd.to_datetime(df_inv['Date'])
df_sales['Date'] = pd.to_datetime(df_sales['Date'])

# Create a copy with only required columns
sales = df_sales[['Date', 'ZSKU', 'Warehouse', 'qty_sold']].copy()

# Function to calculate last 30 day sales
def get_last_30_day_sales(row):
    end_date = row['Date'] - pd.Timedelta(days=2)
    start_date = row['Date'] - pd.Timedelta(days=31)

    mask = (
        (sales['ZSKU'] == row['ZSKU']) &
        (sales['Warehouse'] == row['Warehouse']) &
        (sales['Date'] >= start_date) &
        (sales['Date'] <= end_date)
    )

    return sales.loc[mask, 'qty_sold'].sum()

# Add column
df_inv['last_30_day_sale'] = df_inv.apply(get_last_30_day_sales, axis=1)

## DOS

In [14]:
import numpy as np

df_inv['DOS'] = np.where(
    df_inv['last_30_day_sale'] > 0,
    df_inv['Inventory'] * 30 / df_inv['last_30_day_sale'],
    np.nan
)

In [15]:
df_inv['DOS'] = df_inv['DOS'].astype(float).round(2)
df_inv["Alert"] = np.where(
    df_inv['DOS'] < 10,
    "Low Stock",
    ""
)

In [16]:
df_inv.to_csv(r"C:\Users\Shubham Verma\Downloads\noon_minutes_dark_Store_inventory.csv", index=False)

In [17]:
# df_inv.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\inventory\noon_minutes_inventory.csv", index=False)

# Sales

In [186]:
# df_sales.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\sales\noon_minutes_sales.csv", index=False)

## Marketing

In [187]:
# import pandas as pd
# from pathlib import Path

# # Root folder
# root_folder = Path(
#     r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\marketing"
# )

# # Find all csv and excel files recursively
# files = list(root_folder.rglob("*.csv")) + \
#         list(root_folder.rglob("*.xlsx")) + \
#         list(root_folder.rglob("*.xls"))

# print(f"Total files found: {len(files)}")

# dfs = []

# for file in files:
#     try:
#         if file.suffix.lower() == ".csv":
#             temp_df = pd.read_csv(file)
#         else:
#             temp_df = pd.read_excel(file)

#         # Optional metadata
#         temp_df["source_file"] = file.name
#         temp_df["month"] = file.parent.name          # june, may, etc.
#         temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
#         temp_df["file_path"] = str(file)

#         dfs.append(temp_df)

#         print(f"✓ Loaded: {file.name}")

#     except Exception as e:
#         print(f"✗ Error reading {file}: {e}")

# # Combine all files
# df_marketing = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

# print("\nFinal Shape:", df_marketing.shape)

# # Preview
# df_marketing

In [188]:
# cols_to_keep = [
#     "Date",
#     "SKU",
#     "Clicks",
#     "Spends",
#     "Revenue",
#     "Orders"
# ]
# df_marketing = df_marketing[cols_to_keep]
# df_marketing

In [189]:
# import pandas as pd

# # Convert Date column to datetime
# df_marketing['Date'] = pd.to_datetime(df_marketing['Date'])

# # Columns to be summed
# sum_cols = ['Clicks', 'Spends', 'Revenue', 'Orders']

# # Remove commas, convert to numeric, and handle invalid values
# for col in sum_cols:
#     df_marketing[col] = (
#         df_marketing[col]
#         .astype(str)
#         .str.replace(',', '', regex=False)
#     )
#     df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)

# # Group by Date and SKU and sum the specified columns
# df_marketing = (
#     df_marketing
#     .groupby(['Date', 'SKU'], as_index=False)[sum_cols]
#     .sum()
# )

# # Format date as 01-June-2026
# df_marketing['Date'] = df_marketing['Date'].dt.strftime('%d-%B-%Y')

# df_marketing.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\marketing\noon_minutes_marketing.csv", index=False)