# PO EXTRACTION in Flipkart

In [1]:
import os
import pandas as pd
import re
import hashlib

# ==========================================================
# 1. INPUT & OUTPUT PATHS
# ==========================================================
INPUT_DIR = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\E-commerce\India\India Retail- Quick Commerce - INDIA TEAM\flipkart\PO"
OUTPUT_DIR = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Quick_Comm_Project"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ==========================================================
# 2. UNIVERSAL COLUMN NAME MAPPING
# ==========================================================
column_mapping = {
    "S. no.": ["s. no", "sl no", "sr no", "serial"],
    "HSN/SA Code": ["hsn", "hsn/sa code", "hsn code", "hsn/sac"],
    "FSN/ISBN13": ["fsn", "fsn/isbn13", "isbn", "fsn code"],
    "Quantity": ["quantity", "qty", "order qty"],
    "Pending Quantity": ["pending qty", "pending quantity"],
    "UOM": ["uom", "unit"],
    "Title": ["item description", "title", "product title"],
    "Required by Date": ["required by date"],
    "Supplier MRP": ["mrp", "supplier mrp"],
    "Supplier Price": ["supplier price", "price", "rate"],
    "Taxable Value": ["taxable value"],
    "IGST Rate": ["igst rate", "igst%", "igst"],
    "IGST Amount(per unit)": ["igst amount(per unit)", "igst amount"],
    "SGST Rate": ["sgst/utgst rate", "sgst rate"],
    "SGST Amount(per unit)": ["sgst amount(per unit)"],
    "CGST Rate": ["cgst rate"],
    "CGST Amount(per unit)": ["cgst amount(per unit)"],
    "CESS Rate": ["cess rate"],
    "CESS Amount(per unit)": ["cess amount(per unit)"],
    "Tax Amount": ["tax amount"],
    "Total Amount": ["total amount", "total"]
}

# ==========================================================
# 3. FILE HASH (DUPLICATE FILE CHECK)
# ==========================================================
def file_md5(path):
    hasher = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hasher.update(chunk)
    return hasher.hexdigest()

# ==========================================================
# 4. HEADER ROW DETECTION
# ==========================================================
def detect_header_row(df):
    for i in range(0, 60):
        row_text = " ".join(str(x).lower() for x in df.iloc[i] if pd.notna(x))
        if "fsn" in row_text and "hsn" in row_text and "quantity" in row_text:
            return i
    return None

# ==========================================================
# 5. METADATA EXTRACTION
# ==========================================================
def extract_metadata(df):
    text = " ".join(df.astype(str).fillna("").values.flatten()).lower()

    po_number = re.search(r'po[#:\s]+([a-z0-9]+)', text)
    po_date = re.search(r'order\s*date[:\s]*([0-9/.\-]+)', text)
    po_expiry = re.search(r'(expiry\s*date|po\s*expiry)[:\s]*([0-9/.\-]+)', text)

    return (
        po_number.group(1) if po_number else "",
        po_date.group(1) if po_date else "",
        po_expiry.group(2) if po_expiry else ""
    )
def extract_po_addresses(df):
    text_lines = (
        df.astype(str)
        .fillna("")
        .values.flatten()
    )

    text = " ".join(text_lines)
    text = re.sub(r"\s+", " ", text)

    delivered_by = ""
    delivered_to = ""

    # -------- BILLED BY → PO Delivered By --------
    by_match = re.search(
        r"billed\s+by\s+(.*?)(gstin|state\s+code|shipped\s+from|billed\s+to\s+address)",
        text,
        re.IGNORECASE
    )
    if by_match:
        delivered_by = by_match.group(1).strip()

    # -------- BILLED TO ADDRESS → PO Delivered To --------
    to_match = re.search(
        r"billed\s+to\s+address\s+(.*?)(gstin|state\s+code|payment\s+details|mode\s+of\s+payment)",
        text,
        re.IGNORECASE
    )
    if to_match:
        delivered_to = to_match.group(1).strip()

    return delivered_by, delivered_to

# ==========================================================
# 6. PROCESS SINGLE PO FILE
# ==========================================================
def process_po_file(path):
    raw_df = pd.read_excel(path, header=None)
    po_num, po_date, po_expiry = extract_metadata(raw_df)
    po_delivered_by, po_delivered_to = extract_po_addresses(raw_df)
    header_row = detect_header_row(raw_df)
    if header_row is None:
        return [], po_num

    df = pd.read_excel(path, header=header_row).fillna("")
    df.columns = df.columns.astype(str).str.lower().str.strip()

    records = df.to_dict(orient="records")
    for r in records:
        r["po number"] = po_num
        r["po date"] = po_date
        r["po expiry"] = po_expiry
        r["po delivered by address"] = po_delivered_by
        r["po delivered to"] = po_delivered_to
    return records, po_num

# ==========================================================
# 7. LOAD FILES FROM INPUT DIRECTORY
# ==========================================================
excel_paths = [
    os.path.join(INPUT_DIR, f)
    for f in os.listdir(INPUT_DIR)
    if f.lower().endswith((".xlsx", ".xls"))
]

print(f"📂 Total Excel files found in input folder: {len(excel_paths)}")

if not excel_paths:
    print("❌ No Excel files found.")
    exit()


all_data = []
processed_hashes = set()
processed_po_numbers = set()

# ==========================================================
# 8. MAIN LOOP
# ==========================================================
for path in excel_paths:
    file_hash = file_md5(path)
    if file_hash in processed_hashes:
        print(f"🔁 Duplicate FILE skipped: {os.path.basename(path)}")
        continue

    processed_hashes.add(file_hash)

    preview_df = pd.read_excel(path, header=None)
    po_num, _, _ = extract_metadata(preview_df)

    if po_num in processed_po_numbers:
        print(f"🔁 Duplicate PO skipped: {po_num}")
        continue

    processed_po_numbers.add(po_num)

    print(f"📄 Processing: {os.path.basename(path)} | PO: {po_num}")
    rows, _ = process_po_file(path)
    all_data.extend(rows)

# ==========================================================
# 9. BUILD FINAL DATAFRAME
# ==========================================================
df_all = pd.DataFrame(all_data)
df_all.columns = df_all.columns.str.lower()

final_df = pd.DataFrame()

for final_col, patterns in column_mapping.items():
    matched = next((c for c in df_all.columns if any(p in c for p in patterns)), None)
    final_df[final_col] = df_all[matched] if matched else ""

final_df["PO Number"] = df_all.get("po number", "")
final_df["PO Date"] = df_all.get("po date", "")
final_df["PO Expiry"] = df_all.get("po expiry", "")
final_df["PO Delivered By Address"] = df_all.get("po delivered by address", "")
final_df["PO Delivered To"] = df_all.get("po delivered to", "")

# ==========================================================
# 10. FILTER VALID PRODUCT ROWS
# ==========================================================
def is_valid(row):
    return str(row["Quantity"]).replace(".", "", 1).isdigit()

final_df = final_df[final_df.apply(is_valid, axis=1)].reset_index(drop=True)

# ==========================================================
# 11. SAVE & DISPLAY
# ==========================================================
# output_file = os.path.join(OUTPUT_DIR, "Flipkart_All_POs.xlsx")
# final_df.to_excel(output_file, index=False)

pd.set_option("display.max_columns", None)
print("\n📊 Final DataFrame Preview:")
print(final_df.head(10))

print("\n🎉 COMPLETED SUCCESSFULLY")
# print("📁 Output saved at:", output_file)
print("📊 Total rows:", len(final_df))

📂 Total Excel files found in input folder: 445
📄 Processing: purchase_order_FAGWN07808591.xls | PO: fagwn07808591
📄 Processing: purchase_order_FAGWN07934808.xls | PO: fagwn07934808
📄 Processing: purchase_order_FASWN07894271.xls | PO: faswn07894271
📄 Processing: purchase_order_FASWN07894301.xls | PO: faswn07894301
📄 Processing: purchase_order_FASWN07900186.xls | PO: faswn07900186
📄 Processing: purchase_order_FASWN07900199.xls | PO: faswn07900199
📄 Processing: purchase_order_FBHWN05164815.xls | PO: fbhwn05164815
📄 Processing: purchase_order_FBHWN05164839.xls | PO: fbhwn05164839
📄 Processing: purchase_order_FBHWN05417273.xls | PO: fbhwn05417273
📄 Processing: purchase_order_FBHWN05417291.xls | PO: fbhwn05417291
📄 Processing: purchase_order_FBHWN05427883.xls | PO: fbhwn05427883
📄 Processing: purchase_order_FBHWN05428553.xls | PO: fbhwn05428553
📄 Processing: purchase_order_FBHWN05434758.xls | PO: fbhwn05434758
📄 Processing: purchase_order_FBHWN05458082.xls | PO: fbhwn05458082
📄 Processing: purchase_order_FBHWN05525057.xls | PO: fbhwn05525057
📄 Processing: purchase_order_FBHWN05537678.xls | PO: fbhwn05537678
📄 Processing: purchase_order_FBHWN05552025.xls | PO: fbhwn05552025
📄 Processing: purchase_order_FBHWN05552090.xls | PO: fbhwn05552090
📄 Processing: purchase_order_FBHWN05557647.xls | PO: fbhwn05557647
📄 Processing: purchase_order_FBHWN05558728.xls | PO: fbhwn05558728
📄 Processing: purchase_order_FBHWN05558794.xls | PO: fbhwn05558794
📄 Processing: purchase_order_FBHWN05565009.xls | PO: fbhwn05565009
📄 Processing: purchase_order_FBHWN05565029.xls | PO: fbhwn05565029
📄 Processing: purchase_order_FBHWN05565246.xls | PO: fbhwn05565246
📄 Processing: purchase_order_FBHWN05565260.xls | PO: fbhwn05565260
📄 Processing: purchase_order_FBHWN05586206.xls | PO: fbhwn05586206
📄 Processing: purchase_order_FBHWN05586222.xls | PO: fbhwn05586222
📄 Processing: purchase_order_FBHWN05590962.xls | PO: fbhwn05590962
📄 Processing: purchase_order_FBHWN05591209.xls | PO: fbhwn05591209
📄 Processing: purchase_order_FBHWN05602832.xls | PO: fbhwn05602832
📄 Processing: purchase_order_FBHWN05609591.xls | PO: fbhwn05609591
📄 Processing: purchase_order_FBHWN05718319.xls | PO: fbhwn05718319
📄 Processing: purchase_order_FBHWN05769303.xls | PO: fbhwn05769303
📄 Processing: purchase_order_FBHWN05849736.xls | PO: fbhwn05849736
📄 Processing: purchase_order_FBHWN06035784.xls | PO: fbhwn06035784
📄 Processing: purchase_order_FBHWN06286027.xls | PO: fbhwn06286027
📄 Processing: purchase_order_FBHWN06442645.xls | PO: fbhwn06442645
📄 Processing: purchase_order_FBHWN06449407.xls | PO: fbhwn06449407
📄 Processing: purchase_order_FBHWN06470095.xls | PO: fbhwn06470095
📄 Processing: purchase_order_FBHWN06470221.xls | PO: fbhwn06470221
📄 Processing: purchase_order_FBHWN06470225.xls | PO: fbhwn06470225
📄 Processing: purchase_order_FBHWN06470273.xls | PO: fbhwn06470273
📄 Processing: purchase_order_FBHWN06497296.xls | PO: fbhwn06497296
📄 Processing: purchase_order_FBHWN06513750.xls | PO: fbhwn06513750
📄 Processing: purchase_order_FBHWN06557457.xls | PO: fbhwn06557457
📄 Processing: purchase_order_FBHWN06618155.xls | PO: fbhwn06618155
📄 Processing: purchase_order_FBHWN06623733.xls | PO: fbhwn06623733
📄 Processing: purchase_order_FBHWN06636871.xls | PO: fbhwn06636871
📄 Processing: purchase_order_FBHWN06677790.xls | PO: fbhwn06677790
📄 Processing: purchase_order_FBHWN06785824.xls | PO: fbhwn06785824
📄 Processing: purchase_order_FBHWN06850844.xls | PO: fbhwn06850844
📄 Processing: purchase_order_FBHWN06850973.xls | PO: fbhwn06850973
📄 Processing: purchase_order_FBHWN06917592.xls | PO: fbhwn06917592
📄 Processing: purchase_order_FBHWN06918753.xls | PO: fbhwn06918753
📄 Processing: purchase_order_FBHWN06918939.xls | PO: fbhwn06918939
📄 Processing: purchase_order_FBHWN06955073.xls | PO: fbhwn06955073
📄 Processing: purchase_order_FBHWN06955100.xls | PO: fbhwn06955100
📄 Processing: purchase_order_FBHWN06982983.xls | PO: fbhwn06982983
📄 Processing: purchase_order_FBHWN06985411.xls | PO: fbhwn06985411
📄 Processing: purchase_order_FBHWN06985712.xls | PO: fbhwn06985712
📄 Processing: purchase_order_FBHWN06993360.xls | PO: fbhwn06993360
📄 Processing: purchase_order_FBHWN07001129.xls | PO: fbhwn07001129
📄 Processing: purchase_order_FBHWN07021595.xls | PO: fbhwn07021595
📄 Processing: purchase_order_FBHWN07023701.xls | PO: fbhwn07023701
📄 Processing: purchase_order_FBHWN07023899.xls | PO: fbhwn07023899
📄 Processing: purchase_order_FBHWN07036308.xls | PO: fbhwn07036308
📄 Processing: purchase_order_FBHWN07054250.xls | PO: fbhwn07054250
📄 Processing: purchase_order_FBHWN07054420.xls | PO: fbhwn07054420
📄 Processing: purchase_order_FBHWN07099431.xls | PO: fbhwn07099431
📄 Processing: purchase_order_FBHWN07133835.xls | PO: fbhwn07133835
📄 Processing: purchase_order_FBHWN07134015.xls | PO: fbhwn07134015
📄 Processing: purchase_order_FBHWN07193500.xls | PO: fbhwn07193500
📄 Processing: purchase_order_FBHWN07212442.xls | PO: fbhwn07212442
📄 Processing: purchase_order_FBHWN07223962.xls | PO: fbhwn07223962
📄 Processing: purchase_order_FBHWN07231361.xls | PO: fbhwn07231361
📄 Processing: purchase_order_FBHWN07282998.xls | PO: fbhwn07282998
📄 Processing: purchase_order_FBHWN07360591.xls | PO: fbhwn07360591
📄 Processing: purchase_order_FBHWN07397516.xls | PO: fbhwn07397516
📄 Processing: purchase_order_FBHWN07461619.xls | PO: fbhwn07461619
📄 Processing: purchase_order_FBHWN07461890.xls | PO: fbhwn07461890
📄 Processing: purchase_order_FBHWN07487716.xls | PO: fbhwn07487716
📄 Processing: purchase_order_FBHWN07497203.xls | PO: fbhwn07497203
📄 Processing: purchase_order_FBHWN07497555.xls | PO: fbhwn07497555
📄 Processing: purchase_order_FBHWN07537055.xls | PO: fbhwn07537055
📄 Processing: purchase_order_FBHWN07591288.xls | PO: fbhwn07591288
📄 Processing: purchase_order_FBHWN07709466.xls | PO: fbhwn07709466
📄 Processing: purchase_order_FBHWN07709696.xls | PO: fbhwn07709696
📄 Processing: purchase_order_FBHWN07738143.xls | PO: fbhwn07738143
📄 Processing: purchase_order_FBHWN07738194.xls | PO: fbhwn07738194
📄 Processing: purchase_order_FBHWN07754009.xls | PO: fbhwn07754009
📄 Processing: purchase_order_FBHWN07777113.xls | PO: fbhwn07777113
📄 Processing: purchase_order_FBHWN07780608.xls | PO: fbhwn07780608
📄 Processing: purchase_order_FBHWN07780631.xls | PO: fbhwn07780631
📄 Processing: purchase_order_FBHWN07852141.xls | PO: fbhwn07852141
📄 Processing: purchase_order_FBHWN07852225.xls | PO: fbhwn07852225
📄 Processing: purchase_order_FBHWN07868782.xls | PO: fbhwn07868782
📄 Processing: purchase_order_FBHWN07868785.xls | PO: fbhwn07868785
📄 Processing: purchase_order_FBHWN07876065.xls | PO: fbhwn07876065
📄 Processing: purchase_order_FBHWN07876265.xls | PO: fbhwn07876265
📄 Processing: purchase_order_FBHWN07898020.xls | PO: fbhwn07898020
📄 Processing: purchase_order_FBHWN07912375.xls | PO: fbhwn07912375
📄 Processing: purchase_order_FBHWN07912586.xls | PO: fbhwn07912586
📄 Processing: purchase_order_FBHWN07923320.xls | PO: fbhwn07923320
📄 Processing: purchase_order_FBHWN07934732.xls | PO: fbhwn07934732
📄 Processing: purchase_order_FBHWN07934919.xls | PO: fbhwn07934919
📄 Processing: purchase_order_FBHWN07940885.xls | PO: fbhwn07940885
📄 Processing: purchase_order_FBHWN07976158.xls | PO: fbhwn07976158
📄 Processing: purchase_order_FBHWN08023669.xls | PO: fbhwn08023669
📄 Processing: purchase_order_FBHWN08043741.xls | PO: fbhwn08043741
📄 Processing: purchase_order_FBHWN08063408.xls | PO: fbhwn08063408
📄 Processing: purchase_order_FBHWN08095503.xls | PO: fbhwn08095503
📄 Processing: purchase_order_FBHWN08122643.xls | PO: fbhwn08122643
📄 Processing: purchase_order_FBHWN08135117.xls | PO: fbhwn08135117
📄 Processing: purchase_order_FBHWN08241011.xls | PO: fbhwn08241011
📄 Processing: purchase_order_FBHWN08276316.xls | PO: fbhwn08276316
📄 Processing: purchase_order_FBPWN05164771.xls | PO: fbpwn05164771
📄 Processing: purchase_order_FBPWN05164797.xls | PO: fbpwn05164797
📄 Processing: purchase_order_FBPWN05427859.xls | PO: fbpwn05427859
📄 Processing: purchase_order_FBPWN05434809.xls | PO: fbpwn05434809
📄 Processing: purchase_order_FBPWN05524028.xls | PO: fbpwn05524028
📄 Processing: purchase_order_FBPWN05524552.xls | PO: fbpwn05524552
📄 Processing: purchase_order_FBPWN05537797.xls | PO: fbpwn05537797
📄 Processing: purchase_order_FBPWN05538301.xls | PO: fbpwn05538301
📄 Processing: purchase_order_FBPWN05552129.xls | PO: fbpwn05552129
📄 Processing: purchase_order_FBPWN05552147.xls | PO: fbpwn05552147
📄 Processing: purchase_order_FBPWN05557932.xls | PO: fbpwn05557932
📄 Processing: purchase_order_FBPWN05558378.xls | PO: fbpwn05558378
📄 Processing: purchase_order_FBPWN05558801.xls | PO: fbpwn05558801
📄 Processing: purchase_order_FBPWN05565028.xls | PO: fbpwn05565028
📄 Processing: purchase_order_FBPWN05565256.xls | PO: fbpwn05565256
📄 Processing: purchase_order_FBPWN05585908.xls | PO: fbpwn05585908
📄 Processing: purchase_order_FBPWN05586240.xls | PO: fbpwn05586240
📄 Processing: purchase_order_FBPWN05586267.xls | PO: fbpwn05586267
📄 Processing: purchase_order_FBPWN05590961.xls | PO: fbpwn05590961
📄 Processing: purchase_order_FBPWN05591207.xls | PO: fbpwn05591207
📄 Processing: purchase_order_FBPWN05602828.xls | PO: fbpwn05602828
📄 Processing: purchase_order_FBPWN05608592.xls | PO: fbpwn05608592
📄 Processing: purchase_order_FBPWN05609593.xls | PO: fbpwn05609593
📄 Processing: purchase_order_FBPWN05663642.xls | PO: fbpwn05663642
📄 Processing: purchase_order_FBPWN05667693.xls | PO: fbpwn05667693
📄 Processing: purchase_order_FBPWN05686313.xls | PO: fbpwn05686313
📄 Processing: purchase_order_FBPWN05718251.xls | PO: fbpwn05718251
📄 Processing: purchase_order_FBPWN05738182.xls | PO: fbpwn05738182
📄 Processing: purchase_order_FBPWN05769437.xls | PO: fbpwn05769437
📄 Processing: purchase_order_FBPWN05809629.xls | PO: fbpwn05809629
📄 Processing: purchase_order_FBPWN05810327.xls | PO: fbpwn05810327
📄 Processing: purchase_order_FBPWN05849743.xls | PO: fbpwn05849743
📄 Processing: purchase_order_FBPWN05853697.xls | PO: fbpwn05853697
📄 Processing: purchase_order_FBPWN05853712.xls | PO: fbpwn05853712
📄 Processing: purchase_order_FBPWN05936843.xls | PO: fbpwn05936843
📄 Processing: purchase_order_FBPWN06136562.xls | PO: fbpwn06136562
📄 Processing: purchase_order_FBPWN06136869.xls | PO: fbpwn06136869
📄 Processing: purchase_order_FBPWN06300578.xls | PO: fbpwn06300578
📄 Processing: purchase_order_FBPWN06304559.xls | PO: fbpwn06304559
📄 Processing: purchase_order_FBPWN06417248.xls | PO: fbpwn06417248
📄 Processing: purchase_order_FBPWN06417362.xls | PO: fbpwn06417362
📄 Processing: purchase_order_FBPWN06449420.xls | PO: fbpwn06449420
📄 Processing: purchase_order_FBPWN06469529.xls | PO: fbpwn06469529
📄 Processing: purchase_order_FBPWN06487436.xls | PO: fbpwn06487436
📄 Processing: purchase_order_FBPWN06528151.xls | PO: fbpwn06528151
📄 Processing: purchase_order_FBPWN06544148.xls | PO: fbpwn06544148
📄 Processing: purchase_order_FBPWN06557476.xls | PO: fbpwn06557476
📄 Processing: purchase_order_FBPWN06623968.xls | PO: fbpwn06623968
📄 Processing: purchase_order_FBPWN06636828.xls | PO: fbpwn06636828
📄 Processing: purchase_order_FBPWN06651480.xls | PO: fbpwn06651480
📄 Processing: purchase_order_FBPWN06746462.xls | PO: fbpwn06746462
📄 Processing: purchase_order_FBPWN06850965.xls | PO: fbpwn06850965
📄 Processing: purchase_order_FBPWN06917590.xls | PO: fbpwn06917590
📄 Processing: purchase_order_FBPWN06918818.xls | PO: fbpwn06918818
📄 Processing: purchase_order_FBPWN06918965.xls | PO: fbpwn06918965
📄 Processing: purchase_order_FBPWN06965585.xls | PO: fbpwn06965585
📄 Processing: purchase_order_FBPWN06966057.xls | PO: fbpwn06966057
📄 Processing: purchase_order_FBPWN06993131.xls | PO: fbpwn06993131
📄 Processing: purchase_order_FBPWN06993436.xls | PO: fbpwn06993436
📄 Processing: purchase_order_FBPWN07001164.xls | PO: fbpwn07001164
📄 Processing: purchase_order_FBPWN07023631.xls | PO: fbpwn07023631
📄 Processing: purchase_order_FBPWN07023887.xls | PO: fbpwn07023887
📄 Processing: purchase_order_FBPWN07099460.xls | PO: fbpwn07099460
📄 Processing: purchase_order_FBPWN07099655.xls | PO: fbpwn07099655
📄 Processing: purchase_order_FBPWN07163989.xls | PO: fbpwn07163989
📄 Processing: purchase_order_FBPWN07164120.xls | PO: fbpwn07164120
📄 Processing: purchase_order_FBPWN07212454.xls | PO: fbpwn07212454
📄 Processing: purchase_order_FBPWN07223973.xls | PO: fbpwn07223973
📄 Processing: purchase_order_FBPWN07258613.xls | PO: fbpwn07258613
📄 Processing: purchase_order_FBPWN07299719.xls | PO: fbpwn07299719
📄 Processing: purchase_order_FBPWN07299731.xls | PO: fbpwn07299731
📄 Processing: purchase_order_FBPWN07349130.xls | PO: fbpwn07349130
📄 Processing: purchase_order_FBPWN07397400.xls | PO: fbpwn07397400
📄 Processing: purchase_order_FBPWN07461673.xls | PO: fbpwn07461673
📄 Processing: purchase_order_FBPWN07487932.xls | PO: fbpwn07487932
📄 Processing: purchase_order_FBPWN07617920.xls | PO: fbpwn07617920
📄 Processing: purchase_order_FBPWN07738170.xls | PO: fbpwn07738170
📄 Processing: purchase_order_FBPWN07754110.xls | PO: fbpwn07754110
📄 Processing: purchase_order_FBPWN07760770.xls | PO: fbpwn07760770
📄 Processing: purchase_order_FBPWN07775795.xls | PO: fbpwn07775795
📄 Processing: purchase_order_FBPWN07780488.xls | PO: fbpwn07780488
📄 Processing: purchase_order_FBPWN07852175.xls | PO: fbpwn07852175
📄 Processing: purchase_order_FBPWN07852200.xls | PO: fbpwn07852200
📄 Processing: purchase_order_FBPWN07868783.xls | PO: fbpwn07868783
📄 Processing: purchase_order_FBPWN07876131.xls | PO: fbpwn07876131
📄 Processing: purchase_order_FBPWN07876230.xls | PO: fbpwn07876230
📄 Processing: purchase_order_FBPWN07890458.xls | PO: fbpwn07890458
📄 Processing: purchase_order_FBPWN07898026.xls | PO: fbpwn07898026
📄 Processing: purchase_order_FBPWN07912279.xls | PO: fbpwn07912279
📄 Processing: purchase_order_FBPWN07912581.xls | PO: fbpwn07912581
📄 Processing: purchase_order_FBPWN07934636.xls | PO: fbpwn07934636
📄 Processing: purchase_order_FBPWN07934914.xls | PO: fbpwn07934914
📄 Processing: purchase_order_FBPWN07976335.xls | PO: fbpwn07976335
📄 Processing: purchase_order_FBPWN08043733.xls | PO: fbpwn08043733
📄 Processing: purchase_order_FBPWN08095361.xls | PO: fbpwn08095361
📄 Processing: purchase_order_FBPWN08121584.xls | PO: fbpwn08121584
📄 Processing: purchase_order_FBPWN08122627.xls | PO: fbpwn08122627
📄 Processing: purchase_order_FBPWN08207721.xls | PO: fbpwn08207721
📄 Processing: purchase_order_FBSWN05776786.xls | PO: fbswn05776786
📄 Processing: purchase_order_FBSWN05809171.xls | PO: fbswn05809171
📄 Processing: purchase_order_FBSWN05849395.xls | PO: fbswn05849395
📄 Processing: purchase_order_FBSWN05849748.xls | PO: fbswn05849748
📄 Processing: purchase_order_FBSWN05933490.xls | PO: fbswn05933490
📄 Processing: purchase_order_FBSWN05935859.xls | PO: fbswn05935859
📄 Processing: purchase_order_FBSWN05936526.xls | PO: fbswn05936526
📄 Processing: purchase_order_FBSWN05972413.xls | PO: fbswn05972413
📄 Processing: purchase_order_FBSWN05972670.xls | PO: fbswn05972670
📄 Processing: purchase_order_FBSWN06096276.xls | PO: fbswn06096276
📄 Processing: purchase_order_FBSWN06096834.xls | PO: fbswn06096834
📄 Processing: purchase_order_FBSWN06249056.xls | PO: fbswn06249056
📄 Processing: purchase_order_FBSWN06249139.xls | PO: fbswn06249139
📄 Processing: purchase_order_FBSWN06286140.xls | PO: fbswn06286140
📄 Processing: purchase_order_FBSWN06300576.xls | PO: fbswn06300576
📄 Processing: purchase_order_FBSWN06352881.xls | PO: fbswn06352881
📄 Processing: purchase_order_FBSWN06353591.xls | PO: fbswn06353591
📄 Processing: purchase_order_FBSWN06372825.xls | PO: fbswn06372825
📄 Processing: purchase_order_FBSWN06469577.xls | PO: fbswn06469577
📄 Processing: purchase_order_FBSWN06497180.xls | PO: fbswn06497180
📄 Processing: purchase_order_FBSWN06513660.xls | PO: fbswn06513660
📄 Processing: purchase_order_FBSWN06544242.xls | PO: fbswn06544242
📄 Processing: purchase_order_FBSWN06556576.xls | PO: fbswn06556576
📄 Processing: purchase_order_FBSWN06623858.xls | PO: fbswn06623858
📄 Processing: purchase_order_FBSWN06651501.xls | PO: fbswn06651501
📄 Processing: purchase_order_FBSWN06662949.xls | PO: fbswn06662949
📄 Processing: purchase_order_FBSWN06785814.xls | PO: fbswn06785814
📄 Processing: purchase_order_FBSWN06917591.xls | PO: fbswn06917591
📄 Processing: purchase_order_FBSWN06918719.xls | PO: fbswn06918719
📄 Processing: purchase_order_FBSWN06955071.xls | PO: fbswn06955071
📄 Processing: purchase_order_FBSWN06982934.xls | PO: fbswn06982934
📄 Processing: purchase_order_FBSWN06985340.xls | PO: fbswn06985340
📄 Processing: purchase_order_FBSWN07054076.xls | PO: fbswn07054076
📄 Processing: purchase_order_FBSWN07099411.xls | PO: fbswn07099411
📄 Processing: purchase_order_FBSWN07208927.xls | PO: fbswn07208927
📄 Processing: purchase_order_FBSWN07209255.xls | PO: fbswn07209255
📄 Processing: purchase_order_FBSWN07212429.xls | PO: fbswn07212429
📄 Processing: purchase_order_FBSWN07212478.xls | PO: fbswn07212478
📄 Processing: purchase_order_FBSWN07349196.xls | PO: fbswn07349196
📄 Processing: purchase_order_FBSWN07397451.xls | PO: fbswn07397451
📄 Processing: purchase_order_FBSWN07397797.xls | PO: fbswn07397797
📄 Processing: purchase_order_FBSWN07405221.xls | PO: fbswn07405221
📄 Processing: purchase_order_FBSWN07428588.xls | PO: fbswn07428588
📄 Processing: purchase_order_FBSWN07428909.xls | PO: fbswn07428909
📄 Processing: purchase_order_FBSWN07461766.xls | PO: fbswn07461766
📄 Processing: purchase_order_FBSWN07536867.xls | PO: fbswn07536867
📄 Processing: purchase_order_FBSWN07537192.xls | PO: fbswn07537192
📄 Processing: purchase_order_FBSWN07591085.xls | PO: fbswn07591085
📄 Processing: purchase_order_FBSWN07591470.xls | PO: fbswn07591470
📄 Processing: purchase_order_FBSWN07709494.xls | PO: fbswn07709494
📄 Processing: purchase_order_FBSWN07723255.xls | PO: fbswn07723255
📄 Processing: purchase_order_FBSWN07738145.xls | PO: fbswn07738145
📄 Processing: purchase_order_FBSWN07738187.xls | PO: fbswn07738187
📄 Processing: purchase_order_FBSWN07754107.xls | PO: fbswn07754107
📄 Processing: purchase_order_FBSWN07765402.xls | PO: fbswn07765402
📄 Processing: purchase_order_FBSWN07777310.xls | PO: fbswn07777310
📄 Processing: purchase_order_FBSWN07780625.xls | PO: fbswn07780625
📄 Processing: purchase_order_FBSWN07852212.xls | PO: fbswn07852212
📄 Processing: purchase_order_FBSWN07868780.xls | PO: fbswn07868780
📄 Processing: purchase_order_FBSWN07868784.xls | PO: fbswn07868784
📄 Processing: purchase_order_FBSWN07876083.xls | PO: fbswn07876083
📄 Processing: purchase_order_FBSWN07876270.xls | PO: fbswn07876270
📄 Processing: purchase_order_FBSWN07898001.xls | PO: fbswn07898001
📄 Processing: purchase_order_FBSWN07912342.xls | PO: fbswn07912342
📄 Processing: purchase_order_FBSWN07912583.xls | PO: fbswn07912583
📄 Processing: purchase_order_FBSWN07923262.xls | PO: fbswn07923262
📄 Processing: purchase_order_FBSWN07934699.xls | PO: fbswn07934699
📄 Processing: purchase_order_FBSWN07934918.xls | PO: fbswn07934918
📄 Processing: purchase_order_FBSWN07955195.xls | PO: fbswn07955195
📄 Processing: purchase_order_FBSWN08013893.xls | PO: fbswn08013893
📄 Processing: purchase_order_FBSWN08034040.xls | PO: fbswn08034040
📄 Processing: purchase_order_FBSWN08063329.xls | PO: fbswn08063329
📄 Processing: purchase_order_FBSWN08095382.xls | PO: fbswn08095382
📄 Processing: purchase_order_FBSWN08110160.xls | PO: fbswn08110160
📄 Processing: purchase_order_FBSWN08122596.xls | PO: fbswn08122596
📄 Processing: purchase_order_FBSWN08184041.xls | PO: fbswn08184041
📄 Processing: purchase_order_FHGWN08203734.xls | PO: fhgwn08203734
📄 Processing: purchase_order_FJSWN07908971.xls | PO: fjswn07908971
📄 Processing: purchase_order_FKGWN07715613.xls | PO: fkgwn07715613
📄 Processing: purchase_order_FKGWN07715733.xls | PO: fkgwn07715733
📄 Processing: purchase_order_FNNWN05164778.xls | PO: fnnwn05164778
📄 Processing: purchase_order_FNNWN05164796.xls | PO: fnnwn05164796
📄 Processing: purchase_order_FNNWN05417283.xls | PO: fnnwn05417283
📄 Processing: purchase_order_FNNWN05427889.xls | PO: fnnwn05427889

In [2]:
final_df

,S. no.,HSN/SA Code,FSN/ISBN13,Quantity,Pending Quantity,UOM,Title,Required by Date,Supplier MRP,Supplier Price,Taxable Value,IGST Rate,IGST Amount(per unit),SGST Rate,SGST Amount(per unit),CGST Rate,CGST Amount(per unit),CESS Rate,CESS Amount(per unit),Tax Amount,Total Amount,PO Number,PO Date,PO Expiry,PO Delivered By Address,PO Delivered To
0,1,48237010.0,BWLH5FZYW9XZEX9F,192,192.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-10,119.0 INR,51.35 INR,9390.720000000001 INR,0.0%,0.0 INR,2.5%,,2.5%,1.22 INR,0.0%,0.0 INR,468.48 INR,9859.20,fagwn07808591,11-03-26,10-04-26,"nan 1st Phase, Plot No. 162-A, Road Number 33 ...","nan Flipkart India Private Limited, Survey No ..."
1,1,48237010.0,BWLH5FZYW9XZEX9F,128,128.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-23,119.0 INR,48.3 INR,5888.0 INR,0.0%,0.0 INR,2.5%,,2.5%,1.15 INR,0.0%,0.0 INR,294.4 INR,6182.40,fagwn07934808,01-04-26,23-04-26,"nan 1st Phase, Plot No. 162-A, Road Number 33 ...","nan Flipkart India Private Limited, Survey No ..."
2,1,48237010,BWLH5FZYW9XZEX9F,12,12.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-12,119.0 INR,48.3 INR,551.9999999999999 INR,5.0%,2.3 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,27.599999999999998 INR,579.60,faswn07894271,26-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
3,2,48237010,BWLH4H8YSGDZZX78,24,24.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-04-12,89.0 INR,35.0 INR,799.92 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,40.08 INR,840.00,faswn07894271,26-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
4,3,46021919aa,PTDGXQBHGS5QPZZQ,12,12.0,pcs,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,2026-04-12,199.0 INR,118.3 INR,1419.6 INR,0.0%,0.0 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,0.0 INR,1419.60,faswn07894271,26-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2,48236900.0,GLSH6KK67APTENYF,200,200.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-22,129.0 INR,62.3 INR,10560.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1900.0 INR,12460.00,fuswn08080464,29-04-26,22-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1151,1,48236900.0,GLSH6KK67APTENYF,320,320.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-24,129.0 INR,62.3 INR,16896.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,3040.0 INR,19936.00,fuswn08095377,01-05-26,25-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1152,1,48237010.0,BWLH4H8YSGDZZX78,80,80.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-05-22,89.0 INR,35.0 INR,2666.4 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,133.6 INR,2800.00,fuswn08122617,07-05-26,22-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1153,1,44191900.0,SPNH46S4G7HG3FWA,200,200.0,pcs,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,2026-07-04,99.0 INR,45.0 INR,8572.0 INR,5.0%,2.14 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,428.0 INR,9000.00,fuswn08276251,10-06-26,06-07-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1154,2,48236900.0,GLSH6KK67APTENYF,120,120.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-07-04,129.0 INR,62.3 INR,6336.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1140.0 INR,7476.00,fuswn08276251,10-06-26,06-07-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."

In [3]:
final_df['PO Date'] = pd.to_datetime(
    final_df['PO Date'],
    format='%d-%m-%y',
    errors='coerce'
)
final_df = final_df[final_df['PO Date'].dt.year != 2024]

# filter out 2024 year

In [4]:
final_df

,S. no.,HSN/SA Code,FSN/ISBN13,Quantity,Pending Quantity,UOM,Title,Required by Date,Supplier MRP,Supplier Price,Taxable Value,IGST Rate,IGST Amount(per unit),SGST Rate,SGST Amount(per unit),CGST Rate,CGST Amount(per unit),CESS Rate,CESS Amount(per unit),Tax Amount,Total Amount,PO Number,PO Date,PO Expiry,PO Delivered By Address,PO Delivered To
0,1,48237010.0,BWLH5FZYW9XZEX9F,192,192.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-10,119.0 INR,51.35 INR,9390.720000000001 INR,0.0%,0.0 INR,2.5%,,2.5%,1.22 INR,0.0%,0.0 INR,468.48 INR,9859.20,fagwn07808591,2026-03-11,10-04-26,"nan 1st Phase, Plot No. 162-A, Road Number 33 ...","nan Flipkart India Private Limited, Survey No ..."
1,1,48237010.0,BWLH5FZYW9XZEX9F,128,128.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-23,119.0 INR,48.3 INR,5888.0 INR,0.0%,0.0 INR,2.5%,,2.5%,1.15 INR,0.0%,0.0 INR,294.4 INR,6182.40,fagwn07934808,2026-04-01,23-04-26,"nan 1st Phase, Plot No. 162-A, Road Number 33 ...","nan Flipkart India Private Limited, Survey No ..."
2,1,48237010,BWLH5FZYW9XZEX9F,12,12.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-12,119.0 INR,48.3 INR,551.9999999999999 INR,5.0%,2.3 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,27.599999999999998 INR,579.60,faswn07894271,2026-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
3,2,48237010,BWLH4H8YSGDZZX78,24,24.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-04-12,89.0 INR,35.0 INR,799.92 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,40.08 INR,840.00,faswn07894271,2026-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
4,3,46021919aa,PTDGXQBHGS5QPZZQ,12,12.0,pcs,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,2026-04-12,199.0 INR,118.3 INR,1419.6 INR,0.0%,0.0 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,0.0 INR,1419.60,faswn07894271,2026-03-26,13-04-26,"nan Ground Floor, 1, Pinnac Apartment Bamboo G...","nan Flipkart India Private Limited, Hillway In..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2,48236900.0,GLSH6KK67APTENYF,200,200.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-22,129.0 INR,62.3 INR,10560.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1900.0 INR,12460.00,fuswn08080464,2026-04-29,22-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1151,1,48236900.0,GLSH6KK67APTENYF,320,320.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-24,129.0 INR,62.3 INR,16896.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,3040.0 INR,19936.00,fuswn08095377,2026-05-01,25-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1152,1,48237010.0,BWLH4H8YSGDZZX78,80,80.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-05-22,89.0 INR,35.0 INR,2666.4 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,133.6 INR,2800.00,fuswn08122617,2026-05-07,22-05-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1153,1,44191900.0,SPNH46S4G7HG3FWA,200,200.0,pcs,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,2026-07-04,99.0 INR,45.0 INR,8572.0 INR,5.0%,2.14 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,428.0 INR,9000.00,fuswn08276251,2026-06-10,06-07-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."
1154,2,48236900.0,GLSH6KK67APTENYF,120,120.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-07-04,129.0 INR,62.3 INR,6336.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1140.0 INR,7476.00,fuswn08276251,2026-06-10,06-07-26,"nan Billing Address: 305, Udyog Kendra, Extens...","nan Flipkart India Private Limited, ESR Wareho..."

In [5]:
def clean_nan_words(x):
    if isinstance(x, str):
        # remove standalone 'nan' (case-insensitive)
        x = re.sub(r"\bnan\b", "", x, flags=re.IGNORECASE)
        # normalize spaces
        x = re.sub(r"\s+", " ", x).strip()
    return x

final_df["PO Delivered By Address"] = final_df["PO Delivered By Address"].apply(clean_nan_words)
final_df["PO Delivered To"] = final_df["PO Delivered To"].apply(clean_nan_words)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\1926778745.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PO Delivered By Address"] = final_df["PO Delivered By Address"].apply(clean_nan_words)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\1926778745.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["PO Delivered To"] = final_df["PO Delivered To"].apply(clean_nan_words)

In [6]:
final_df

,S. no.,HSN/SA Code,FSN/ISBN13,Quantity,Pending Quantity,UOM,Title,Required by Date,Supplier MRP,Supplier Price,Taxable Value,IGST Rate,IGST Amount(per unit),SGST Rate,SGST Amount(per unit),CGST Rate,CGST Amount(per unit),CESS Rate,CESS Amount(per unit),Tax Amount,Total Amount,PO Number,PO Date,PO Expiry,PO Delivered By Address,PO Delivered To
0,1,48237010.0,BWLH5FZYW9XZEX9F,192,192.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-10,119.0 INR,51.35 INR,9390.720000000001 INR,0.0%,0.0 INR,2.5%,,2.5%,1.22 INR,0.0%,0.0 INR,468.48 INR,9859.20,fagwn07808591,2026-03-11,10-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,..."
1,1,48237010.0,BWLH5FZYW9XZEX9F,128,128.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-23,119.0 INR,48.3 INR,5888.0 INR,0.0%,0.0 INR,2.5%,,2.5%,1.15 INR,0.0%,0.0 INR,294.4 INR,6182.40,fagwn07934808,2026-04-01,23-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,..."
2,1,48237010,BWLH5FZYW9XZEX9F,12,12.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-12,119.0 INR,48.3 INR,551.9999999999999 INR,5.0%,2.3 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,27.599999999999998 INR,579.60,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust..."
3,2,48237010,BWLH4H8YSGDZZX78,24,24.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-04-12,89.0 INR,35.0 INR,799.92 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,40.08 INR,840.00,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust..."
4,3,46021919aa,PTDGXQBHGS5QPZZQ,12,12.0,pcs,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,2026-04-12,199.0 INR,118.3 INR,1419.6 INR,0.0%,0.0 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,0.0 INR,1419.60,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2,48236900.0,GLSH6KK67APTENYF,200,200.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-22,129.0 INR,62.3 INR,10560.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1900.0 INR,12460.00,fuswn08080464,2026-04-29,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin..."
1151,1,48236900.0,GLSH6KK67APTENYF,320,320.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-24,129.0 INR,62.3 INR,16896.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,3040.0 INR,19936.00,fuswn08095377,2026-05-01,25-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin..."
1152,1,48237010.0,BWLH4H8YSGDZZX78,80,80.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-05-22,89.0 INR,35.0 INR,2666.4 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,133.6 INR,2800.00,fuswn08122617,2026-05-07,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin..."
1153,1,44191900.0,SPNH46S4G7HG3FWA,200,200.0,pcs,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,2026-07-04,99.0 INR,45.0 INR,8572.0 INR,5.0%,2.14 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,428.0 INR,9000.00,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin..."
1154,2,48236900.0,GLSH6KK67APTENYF,120,120.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-07-04,129.0 INR,62.3 INR,6336.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1140.0 INR,7476.00,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin..."

# Invoice Extraction in Flipkart

In [7]:
import pdfplumber
import re
import os
import hashlib
import pandas as pd

# =======================================================
# 1. INPUT & OUTPUT PATHS
# =======================================================
INPUT_DIR = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\E-commerce\India\India Retail- Quick Commerce - INDIA TEAM\flipkart\Invoice"
OUTPUT_DIR = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Desktop\flipkart_code"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# =======================================================
# 2. HELPER FUNCTIONS
# =======================================================
def clean_text(t):
    t = re.sub(r"\s+", " ", t or "").strip()
    t = re.sub(r"\b(nan|null|none)\b", "", t, flags=re.I)
    return t.strip()

def file_md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()

# =======================================================
# 3. PO NUMBER EXTRACTION
# =======================================================
def extract_po_number(text, filename=""):
    patterns = [
        r"P\.?\s*O\.?\s*#?\s*[:\-]\s*([A-Z0-9]{8,})",
        r"PO\s*No\.?\s*[:\-]\s*([A-Z0-9]{8,})",
        r"(FUSWN[A-Z0-9]+)"
    ]
    for p in patterns:
        m = re.search(p, text, re.I)
        if m:
            return m.group(1)
    return ""

# =======================================================
# 4. ADDRESS EXTRACTION (ROBUST)
# =======================================================
def extract_invoice_metadata(text, filename=""):
    text = clean_text(text)

    inv = re.search(r"Invoice\s*(?:Number|No\.?)\s*[:\-]?\s*([A-Z0-9\/\-]+)", text, re.I)
    date = re.search(r"Invoice\s*Date\s*[:\-]?\s*([\d\/\-]+)", text, re.I)

    invoice_no = inv.group(1) if inv else ""
    invoice_date = date.group(1) if date else ""

    po_number = extract_po_number(text, filename)

    bill_to = ""
    ship_to = ""
    dispatch_from = ""

    # Pattern 1: Separate Bill To / Ship To blocks
    bill_match = re.search(r"Bill To\s*(.+?)(?=Ship To|Dispatch From|(?=GSTIN\b.+?Warehouse)|table|\n{3,})", text, re.S | re.I)
    if bill_match:
        bill_to = clean_text(bill_match.group(1))

    ship_match = re.search(r"Ship To\s*(.+?)(?=Dispatch From|GSTIN\b.+?Warehouse|table|\n{3,}|\Z)", text, re.S | re.I)
    if ship_match:
        ship_to = clean_text(ship_match.group(1))

    # Pattern 2: Dispatch From
    dispatch_match = re.search(r"Dispatch From\s*(.+?)(?=(Bill To|GSTIN\b|Invoice Number|table|\n{3,}|\Z))", text, re.S | re.I)
    if dispatch_match:
        dispatch_from = clean_text(dispatch_match.group(1))

    # Pattern 3: Combined "Bill To Ship To" (matches your sample)
    combined_match = re.search(r"Bill To\s+Ship To\s*(.+?)(?=(?=GSTIN\b.+?Warehouse)|table|Item Description|\n{3,}|\Z)", text, re.S | re.I)
    if combined_match:
        full_addr = clean_text(combined_match.group(1))
        if "GSTIN" in full_addr:
            # Split if GSTIN separates bill/ship (rare), else assign to both
            parts = re.split(r'(GSTIN \w+)', full_addr, 1)
            bill_to = clean_text(parts[0])
            ship_to = clean_text(full_addr)  # Full for ship_to as fallback
        else:
            bill_to = ship_to = full_addr

    # Pattern 4: Standalone "Warehouse" addresses (Flipkart common)
    if not ship_to and "Warehouse" in text:
        warehouse_match = re.search(r"(?:Warehouse|Flipkart)\s*,?\s*(.+?)(?=(GSTIN|HSN|Qty|table|\n{3,}|\Z))", text, re.S | re.I)
        if warehouse_match:
            ship_to = bill_to = clean_text(warehouse_match.group(1))

    # Clean up addresses: remove trailing GSTIN if duplicated
    for addr in [bill_to, ship_to, dispatch_from]:
        if addr:
            addr = re.sub(r'GSTIN\s*\w+\s*$', '', addr, flags=re.I).strip()

    return invoice_no, invoice_date, po_number, bill_to, ship_to, dispatch_from

# =======================================================
# 5. METADATA EXTRACTION
# =======================================================

# =======================================================
# 6. ITEM TABLE EXTRACTION (GST SAFE)
# =======================================================
def extract_invoice_items(pdf):
    items = []

    for page in pdf.pages:
        tables = page.extract_tables() or []
        for table in tables:
            table = [[clean_text(c) for c in row] for row in table if row]
            header = next((r for r in table if any("qty" in c.lower() for c in r)), None)
            if not header:
                continue

            headers = [h.lower() for h in header]
            start = table.index(header) + 1

            def idx(key):
                return next((i for i, h in enumerate(headers) if key in h), -1)

            has_igst = any("igst" in h for h in headers)
            has_cgst = any("cgst" in h for h in headers)
            has_sgst = any("sgst" in h for h in headers)

            for row in table[start:]:
                if not any(row):
                    continue

                item = {
                    "Invoice S.No": row[0] if row[0].isdigit() else "",
                    "Invoice Item & Description": row[idx("description")] if idx("description") >= 0 else "",
                    "Invoice SKU No": row[idx("sku")] if idx("sku") >= 0 else "",
                    "Invoice HSN/SAC": row[idx("hsn")] if idx("hsn") >= 0 else "",
                    "Invoice Case Qty": row[idx("qty")] if idx("qty") >= 0 else "",
                    "Invoice Rate": row[idx("rate")] if idx("rate") >= 0 else "",
                    "Invoice Amount": row[idx("amount")] if idx("amount") >= 0 else "",
                    "IGST %": "", "IGST Amount": "",
                    "CGST %": "", "CGST Amount": "",
                    "SGST %": "", "SGST Amount": ""
                }

                if has_igst:
                    i = idx("igst")
                    if i >= 0 and i + 1 < len(row):
                        item["IGST %"] = row[i]
                        item["IGST Amount"] = row[i + 1]

                if has_cgst and has_sgst:
                    c = idx("cgst")
                    s = idx("sgst")
                    if c >= 0:
                        item["CGST %"] = row[c]
                        item["CGST Amount"] = row[c + 1]
                    if s >= 0:
                        item["SGST %"] = row[s]
                        item["SGST Amount"] = row[s + 1]

                if item["Invoice Item & Description"]:
                    items.append(item)

    return items

# =======================================================
# 7. MAIN PROCESS
# =======================================================
all_data = []
processed = set()

pdf_files = [os.path.join(INPUT_DIR, f) for f in os.listdir(INPUT_DIR) if f.lower().endswith(".pdf")]
print("📂 Total PDFs:", len(pdf_files))

for file in pdf_files:
    if file_md5(file) in processed:
        continue
    processed.add(file_md5(file))

    print("📄 Processing:", os.path.basename(file))

    with pdfplumber.open(file) as pdf:
        text = "\n".join(p.extract_text() or "" for p in pdf.pages)

        inv_no, inv_date, po_no, bill_to, ship_to, dispatch_from = extract_invoice_metadata(
            text, os.path.basename(file)
        )

        items = extract_invoice_items(pdf)

        for item in items:
            item.update({
                "Invoice Date": inv_date,
                "Invoice Number": inv_no,
                "Invoice P.O.#": po_no,
                "Invoice Bill To": bill_to,
                "Invoice Ship To": ship_to,
                "Invoice Dispatch From": dispatch_from
            })
            all_data.append(item)

# =======================================================
# 8. FINAL DATAFRAME
# =======================================================
invoice_df = pd.DataFrame(all_data).drop_duplicates()
invoice_df = invoice_df[invoice_df["Invoice Item & Description"] != ""]

cols = [
    "Invoice Date", "Invoice Number", "Invoice P.O.#",
    "Invoice Bill To", "Invoice Ship To", "Invoice Dispatch From",
    "Invoice S.No", "Invoice Item & Description", "Invoice SKU No",
    "Invoice HSN/SAC", "Invoice Case Qty", "Invoice Rate",
    "IGST %", "IGST Amount",
    "CGST %", "CGST Amount",
    "SGST %", "SGST Amount",
    "Invoice Amount"
]

invoice_df = invoice_df[cols]

# =======================================================
# 9. SAVE OUTPUT
# =======================================================
output_file = os.path.join(OUTPUT_DIR, "FLIPKART_Invoice_With_GST.xlsx")
invoice_df.to_excel(output_file, index=False)

print("\n🎉 COMPLETED SUCCESSFULLY")
print("📁 Saved at:", output_file)
print("📊 Total rows:", len(invoice_df))

📂 Total PDFs: 262
📄 Processing: 20250409-70-huj9sy20241226004444234_54.pdf
📄 Processing: ESHBT261.pdf

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3836131085.py:82: DeprecationWarning: 'maxsplit' is passed as positional argument
  parts = re.split(r'(GSTIN \w+)', full_addr, 1)

📄 Processing: ESHBT26105.pdf
📄 Processing: ESHBT26106.pdf
📄 Processing: ESHBT26107.pdf
📄 Processing: ESHBT26139.pdf
📄 Processing: ESHBT26171.pdf
📄 Processing: ESHBT262.pdf
📄 Processing: ESHBT263.pdf
📄 Processing: ESHBT264.pdf
📄 Processing: ESHBT265.pdf
📄 Processing: ESHBT266.pdf
📄 Processing: ESHBT267.pdf
📄 Processing: ESHM26103.pdf
📄 Processing: ESHM26123.pdf
📄 Processing: ESHM2625.pdf
📄 Processing: ESHM2626.pdf
📄 Processing: ESHM2627.pdf
📄 Processing: ESHM2628.pdf
📄 Processing: ESHM263.pdf
📄 Processing: ESHM264.pdf
📄 Processing: ESHM265.pdf
📄 Processing: ESHM266.pdf
📄 Processing: ESHM2669.pdf
📄 Processing: ESHT2645.pdf
📄 Processing: ESHU2612.pdf
📄 Processing: ESHU2613.pdf
📄 Processing: ESHU2614.pdf
📄 Processing: ESHU26165.pdf
📄 Processing: ESHU26166.pdf
📄 Processing: ESHU26167.pdf
📄 Processing: ESHU26168.pdf
📄 Processing: ESHU26169.pdf
📄 Processing: ESHU2627.pdf
📄 Processing: ESHU2628.pdf
📄 Processing: ESHU26288.pdf
📄 Processing: ESHU26289.pdf
📄 Processing: ESHU2629.pdf
📄 Processing: ESHU26291.pdf
📄 Processing: ESHU2630.pdf
📄 Processing: ESHU2631.pdf
📄 Processing: ESHU2632.pdf
📄 Processing: ESHU2633.pdf
📄 Processing: ESHU2634.pdf
📄 Processing: ESHU2635.pdf
📄 Processing: ESHU2636.pdf
📄 Processing: ESHU2637.pdf
📄 Processing: ESHU26381.pdf
📄 Processing: ESHU26400.pdf
📄 Processing: ESHU26445.pdf
📄 Processing: FK- 036.pdf
📄 Processing: FK- 041.pdf
📄 Processing: FK- 044.pdf
📄 Processing: FK- 046.pdf
📄 Processing: FK- 049.pdf
📄 Processing: FK- 050.pdf
📄 Processing: FK-001_4.PDF
📄 Processing: FK-002.pdf
📄 Processing: FK-002_4.PDF
📄 Processing: FK-003 - 04-Sep-24 - FNNWN05164796 - DEL 1.pdf
📄 Processing: FK-004 - 09-Sep-24 - FBPWN05164797 - MAH 1.pdf
📄 Processing: FK-005 - 08-Sep-24 - FNNWN05164778 - DEL 1.pdf
📄 Processing: FK-006_3.PDF
📄 Processing: FK-007.pdf
📄 Processing: FK-009.pdf
📄 Processing: FK-010.pdf
📄 Processing: FK-011.pdf
📄 Processing: FK-012.pdf
📄 Processing: FK-013.pdf
📄 Processing: FK-016.pdf
📄 Processing: FK-017.pdf
📄 Processing: FK-018.pdf
📄 Processing: FK-019.pdf
📄 Processing: FK-020.pdf
📄 Processing: FK-034.pdf
📄 Processing: FK-035.pdf
📄 Processing: FK-037.pdf
📄 Processing: FK-038.pdf
📄 Processing: FK-039.pdf
📄 Processing: FK-040.pdf
📄 Processing: FK-042.pdf
📄 Processing: FK-043.pdf
📄 Processing: FK-046.pdf
📄 Processing: FK-047.pdf
📄 Processing: FK-051.pdf
📄 Processing: FK-052.pdf
📄 Processing: FK-053.pdf
📄 Processing: FK-054.pdf
📄 Processing: FK-057.pdf
📄 Processing: FK-058.pdf
📄 Processing: FK-059.pdf
📄 Processing: FK-060.pdf
📄 Processing: FK-061.pdf
📄 Processing: FK-062.pdf
📄 Processing: FK-064.pdf
📄 Processing: FK-066.pdf
📄 Processing: FK-077.pdf
📄 Processing: FK-082.pdf
📄 Processing: FK-083.pdf
📄 Processing: FK-085.pdf
📄 Processing: FK-086.pdf
📄 Processing: FK-087.pdf
📄 Processing: FK-088.pdf
📄 Processing: FK-089.pdf
📄 Processing: FK-090.pdf
📄 Processing: FK-091.pdf
📄 Processing: FK-093.pdf
📄 Processing: FK-094.pdf
📄 Processing: FK-095.pdf
📄 Processing: FK-096.pdf
📄 Processing: FK-097.pdf
📄 Processing: FK-098.pdf
📄 Processing: FK-099.pdf
📄 Processing: FK-10.2.pdf
📄 Processing: FK-101.pdf
📄 Processing: FK-102.pdf
📄 Processing: FK-103.pdf
📄 Processing: FK-104.pdf
📄 Processing: FK-105.pdf
📄 Processing: FK-118.pdf
📄 Processing: FK-119.pdf
📄 Processing: FK-120.pdf
📄 Processing: FK-122.pdf
📄 Processing: FK-2025-26-012.pdf
📄 Processing: FK-2025-26-013.pdf
📄 Processing: FK-2025-26-014.pdf
📄 Processing: FK-2025-26-024.pdf
📄 Processing: FK-25-26-025.pdf
📄 Processing: FK-25-26-026.pdf
📄 Processing: FK2025-26013.pdf
📄 Processing: FK2025-26014.pdf
📄 Processing: FK2025-26038.pdf
📄 Processing: FK2025-26039.pdf
📄 Processing: FK2025-26044.pdf
📄 Processing: FK2025-26048.pdf
📄 Processing: FK2025-26049.pdf
📄 Processing: FK2025-26050.pdf
📄 Processing: FK2025-26051.pdf
📄 Processing: FK2025-26052.pdf
📄 Processing: FK2025-26053.pdf
📄 Processing: FK2025-26054.pdf
📄 Processing: FK2025-26055.pdf
📄 Processing: FK2025-26056.pdf
📄 Processing: FK2025-26057.pdf
📄 Processing: FK2025-26058.pdf
📄 Processing: FK2025-26059.pdf
📄 Processing: FK2025-26060.pdf
📄 Processing: FK2025-26061.pdf
📄 Processing: FK2025-26063.pdf
📄 Processing: FK2025-26064.pdf
📄 Processing: FK2025-26065.pdf
📄 Processing: FK2025-26066.pdf
📄 Processing: FK2025-26068.pdf
📄 Processing: FK2025-26069.pdf
📄 Processing: FK2025-26070.pdf
📄 Processing: FK2025-26072.pdf
📄 Processing: FK2025-26073.pdf
📄 Processing: FK2025-26074.pdf
📄 Processing: FK2025-26075.pdf
📄 Processing: FK2025-26076.pdf
📄 Processing: FK2025-26077.pdf
📄 Processing: FK2025-26078.pdf
📄 Processing: FK2025-26079.pdf
📄 Processing: FK2025-26080.pdf
📄 Processing: FK2025-26081.pdf
📄 Processing: FK2025-26082.pdf
📄 Processing: FK2025-26083.pdf
📄 Processing: FK2025-26084.pdf
📄 Processing: FK2025-26085.pdf
📄 Processing: FK2025-26086.pdf
📄 Processing: FK2025-26087.pdf
📄 Processing: FK2025-26088.pdf
📄 Processing: FK2025-26089.pdf
📄 Processing: FK2025-26090.pdf
📄 Processing: FK2025-26091.pdf
📄 Processing: FK2025-26092.pdf
📄 Processing: FK2025-26093.pdf
📄 Processing: FK2025-26094.pdf
📄 Processing: FK2025-26095.pdf
📄 Processing: FK2025-26096.pdf
📄 Processing: FK2025-26097.pdf
📄 Processing: FK2025-26098.pdf
📄 Processing: FK2025-26099.pdf
📄 Processing: FK2025-26100.pdf
📄 Processing: FK2025-26101.pdf
📄 Processing: FK2025-26102.pdf
📄 Processing: FK2025-26103.pdf
📄 Processing: FK2025-26104.pdf
📄 Processing: FK2025-26105.pdf
📄 Processing: FK2025-26106.pdf
📄 Processing: FK2025-26107.pdf
📄 Processing: FK2025-26108.pdf
📄 Processing: FK2025-26109.pdf
📄 Processing: FK2025-26110.pdf
📄 Processing: FK2025-26111.pdf
📄 Processing: FK2025-26112.pdf
📄 Processing: FK2025-26113.pdf
📄 Processing: FK2025-26114.pdf
📄 Processing: FK2025-26115.pdf
📄 Processing: FK2025-26116.pdf
📄 Processing: FK2025-26117.pdf
📄 Processing: FK2025-26118.pdf
📄 Processing: FK2025-26119.pdf
📄 Processing: FK2025-26120.pdf
📄 Processing: FK2025-26121.pdf
📄 Processing: FK2025-26122.pdf
📄 Processing: FK2025-26123.pdf
📄 Processing: FK2025-26124.pdf
📄 Processing: FK2025-26125.pdf
📄 Processing: FK2025-26126.pdf
📄 Processing: FK2025-26127.pdf
📄 Processing: FK2025-26128.pdf
📄 Processing: FK2025-26129.pdf
📄 Processing: FK2025-26130.pdf
📄 Processing: FK2025-26131.pdf
📄 Processing: FK2025-26132.pdf
📄 Processing: FK2025-26133.pdf
📄 Processing: FK2025-26134.pdf
📄 Processing: FK2025-26135.pdf
📄 Processing: FK2025-26136.pdf
📄 Processing: FK2025-26137.pdf
📄 Processing: FK2025-26138.pdf
📄 Processing: FK2025-26139.pdf
📄 Processing: FK2025-26140.pdf
📄 Processing: FK2025-26141.pdf
📄 Processing: FK2025-26142.pdf
📄 Processing: FK2025-26143.pdf
📄 Processing: FK2025-26144.pdf
📄 Processing: FK2025-26145.pdf
📄 Processing: FK2025-26146.pdf
📄 Processing: FK2025-26147.pdf
📄 Processing: FK2025-26148.pdf
📄 Processing: FK2025-26149.pdf
📄 Processing: FK2025-26150.pdf
📄 Processing: FK2025-26151.pdf
📄 Processing: FK2025-26152.pdf
📄 Processing: FK2025-26153.pdf
📄 Processing: FK2025-26154.pdf
📄 Processing: FK2025-26155.pdf
📄 Processing: FK2025-26156.pdf
📄 Processing: FK2025-26157.pdf
📄 Processing: FK2025-26158.pdf
📄 Processing: FK2025-26159.pdf
📄 Processing: FK2025-26160.pdf
📄 Processing: FK2025-26161.pdf
📄 Processing: FK2025-26162.pdf
📄 Processing: FK2025-26163.pdf
📄 Processing: FK2025-26164.pdf
📄 Processing: FK2025-26166.pdf
📄 Processing: FK2025-26167.pdf
📄 Processing: FK2025-26168.pdf
📄 Processing: FK2025-26169.pdf
📄 Processing: FK2025-26170.pdf
📄 Processing: FK2025-26171.pdf
📄 Processing: Invoice FK-079.pdf

🎉 COMPLETED SUCCESSFULLY
📁 Saved at: C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Desktop\flipkart_code\FLIPKART_Invoice_With_GST.xlsx
📊 Total rows: 385

In [8]:
invoice_df

,Invoice Date,Invoice Number,Invoice P.O.#,Invoice Bill To,Invoice Ship To,Invoice Dispatch From,Invoice S.No,Invoice Item & Description,Invoice SKU No,Invoice HSN/SAC,Invoice Case Qty,Invoice Rate,IGST %,IGST Amount,CGST %,CGST Amount,SGST %,SGST Amount,Invoice Amount
0,05/04/2026,ESHBT/26/1,FBHWN07868785,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS50,44219990,200.00,57.142,,,2.5%,285.71,2.5%,285.71,"11,428.40"
1,29/04/2026,ESHBT/26/105,FBHWN07976158,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,140mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS140 MM50,44219990,200.00,42.857,,,2.5%,214.29,2.5%,214.29,"8,571.40"
2,29/04/2026,ESHBT/26/105,FBHWN07976158,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,120.00,52.796,,,9%,570.20,9%,570.20,"6,335.52"
3,29/04/2026,ESHBT/26/106,FBHWN08023669,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,320.00,52.796,,,9%,"1,520.52",9%,"1,520.52","16,894.72"
4,29/04/2026,ESHBT/26/107,FBHWN08043741,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,520.00,52.796,,,9%,"2,470.85",9%,"2,470.85","27,453.92"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,25/03/2026,FK/2025-26/168,FNNWN07852010,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Bagasse Bowl 180ml Round set of 25...,FG- CBB6RO2 5UB,48237010,64.00,48.90,5%,156.48,,,,,"3,129.60"
381,25/03/2026,FK/2025-26/168,FNNWN07852010,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
382,25/03/2026,FK/2025-26/169,FNNWN07852203,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB-BS50,44219990,100.00,57.14,5%,285.70,,,,,"5,714.00"
383,25/03/2026,FK/2025-26/170,FNNWN07860786,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
384,25/03/2026,FK/2025-26/171,FNNWN07866539,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,80.00,44.07,18%,634.61,,,,,"3,525.60"

# Filter out 2024 year

In [9]:
invoice_df['Invoice Date'] = pd.to_datetime(
    invoice_df['Invoice Date'],
    format='%d/%m/%Y',
    errors='coerce'
)
invoice_df['Invoice Date'] = (
    pd.to_datetime(
        invoice_df['Invoice Date'],
        dayfirst=True,
        errors='coerce'
    )
    .dt.normalize()
)

# Now this WILL work
invoice_df = invoice_df[invoice_df['Invoice Date'].dt.year != 2024]

# Save a dumped File

In [10]:
invoice_df

,Invoice Date,Invoice Number,Invoice P.O.#,Invoice Bill To,Invoice Ship To,Invoice Dispatch From,Invoice S.No,Invoice Item & Description,Invoice SKU No,Invoice HSN/SAC,Invoice Case Qty,Invoice Rate,IGST %,IGST Amount,CGST %,CGST Amount,SGST %,SGST Amount,Invoice Amount
0,2026-04-05,ESHBT/26/1,FBHWN07868785,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS50,44219990,200.00,57.142,,,2.5%,285.71,2.5%,285.71,"11,428.40"
1,2026-04-29,ESHBT/26/105,FBHWN07976158,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,140mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS140 MM50,44219990,200.00,42.857,,,2.5%,214.29,2.5%,214.29,"8,571.40"
2,2026-04-29,ESHBT/26/105,FBHWN07976158,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,120.00,52.796,,,9%,570.20,9%,570.20,"6,335.52"
3,2026-04-29,ESHBT/26/106,FBHWN08023669,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,320.00,52.796,,,9%,"1,520.52",9%,"1,520.52","16,894.72"
4,2026-04-29,ESHBT/26/107,FBHWN08043741,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,520.00,52.796,,,9%,"2,470.85",9%,"2,470.85","27,453.92"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,2026-03-25,FK/2025-26/168,FNNWN07852010,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Bagasse Bowl 180ml Round set of 25...,FG- CBB6RO2 5UB,48237010,64.00,48.90,5%,156.48,,,,,"3,129.60"
381,2026-03-25,FK/2025-26/168,FNNWN07852010,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
382,2026-03-25,FK/2025-26/169,FNNWN07852203,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB-BS50,44219990,100.00,57.14,5%,285.70,,,,,"5,714.00"
383,2026-03-25,FK/2025-26/170,FNNWN07860786,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
384,2026-03-25,FK/2025-26/171,FNNWN07866539,FLIPKART INDIA PVT LTD Flipkart India Private ...,FLIPKART INDIA PVT LTD Flipkart India Private ...,": EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# :...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,80.00,44.07,18%,634.61,,,,,"3,525.60"

In [11]:
def clean_nan_words(x):
    if isinstance(x, str):
        # remove standalone 'nan' (case-insensitive)
        x = re.sub(r"\bFlipkart\b", "", x, flags=re.IGNORECASE)
        # normalize spaces
        x = re.sub(r"\s+", " ", x).strip()
    return x

def clean_colon_words(x):
    if isinstance(x, str):
        # remove colon only if it appears at the start (with or without spaces)
        x = re.sub(r"^\s*:\s*", "", x)

        # normalize spaces
        x = re.sub(r"\s+", " ", x).strip()
    return x

invoice_df["Invoice Ship To"] = invoice_df["Invoice Ship To"].apply(clean_nan_words)
invoice_df["Invoice Bill To"] = invoice_df["Invoice Bill To"].apply(clean_nan_words)
invoice_df["Invoice Dispatch From"] = invoice_df["Invoice Dispatch From"].apply(clean_colon_words)

In [12]:
invoice_df

,Invoice Date,Invoice Number,Invoice P.O.#,Invoice Bill To,Invoice Ship To,Invoice Dispatch From,Invoice S.No,Invoice Item & Description,Invoice SKU No,Invoice HSN/SAC,Invoice Case Qty,Invoice Rate,IGST %,IGST Amount,CGST %,CGST Amount,SGST %,SGST Amount,Invoice Amount
0,2026-04-05,ESHBT/26/1,FBHWN07868785,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS50,44219990,200.00,57.142,,,2.5%,285.71,2.5%,285.71,"11,428.40"
1,2026-04-29,ESHBT/26/105,FBHWN07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,140mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS140 MM50,44219990,200.00,42.857,,,2.5%,214.29,2.5%,214.29,"8,571.40"
2,2026-04-29,ESHBT/26/105,FBHWN07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,120.00,52.796,,,9%,570.20,9%,570.20,"6,335.52"
3,2026-04-29,ESHBT/26/106,FBHWN08023669,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,320.00,52.796,,,9%,"1,520.52",9%,"1,520.52","16,894.72"
4,2026-04-29,ESHBT/26/107,FBHWN08043741,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,520.00,52.796,,,9%,"2,470.85",9%,"2,470.85","27,453.92"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,2026-03-25,FK/2025-26/168,FNNWN07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Bagasse Bowl 180ml Round set of 25...,FG- CBB6RO2 5UB,48237010,64.00,48.90,5%,156.48,,,,,"3,129.60"
381,2026-03-25,FK/2025-26/168,FNNWN07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
382,2026-03-25,FK/2025-26/169,FNNWN07852203,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB-BS50,44219990,100.00,57.14,5%,285.70,,,,,"5,714.00"
383,2026-03-25,FK/2025-26/170,FNNWN07860786,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
384,2026-03-25,FK/2025-26/171,FNNWN07866539,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,80.00,44.07,18%,634.61,,,,,"3,525.60"

In [13]:
po_df=final_df.copy()

In [14]:
po_df['FSN/ISBN13'].nunique()

30

# Use helper file to get SKU details for PO's

In [15]:
import pandas as pd

helper_path = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\E-commerce\India\India Retail- Quick Commerce - INDIA TEAM\helper_file.xlsx"

helper_df = pd.read_excel(helper_path)
po_df["FSN/ISBN13"] = po_df["FSN/ISBN13"].astype(str).str.strip()
helper_df["Item Code"] = helper_df["Item Code"].astype(str).str.strip()
helper_df = helper_df[
    ["Item Code", "SKU", "Material", "Category", "Sub Category","Box/Case"]
]
po_df = po_df.merge(
    helper_df,
    how="left",
    left_on="FSN/ISBN13",
    right_on="Item Code"
)
po_df.drop(columns=["Item Code"], inplace=True)
missing_fsn = (
    po_df.loc[po_df["SKU"].isna(), "FSN/ISBN13"]
    .dropna()
    .unique()
    .tolist()
)

print(f"❌ Total FSN/ISBN13 not found: {len(missing_fsn)}")

❌ Total FSN/ISBN13 not found: 1

In [16]:
missing_fsn

['CNSH47JACCHHYHZX']

In [17]:
po_df

,S. no.,HSN/SA Code,FSN/ISBN13,Quantity,Pending Quantity,UOM,Title,Required by Date,Supplier MRP,Supplier Price,Taxable Value,IGST Rate,IGST Amount(per unit),SGST Rate,SGST Amount(per unit),CGST Rate,CGST Amount(per unit),CESS Rate,CESS Amount(per unit),Tax Amount,Total Amount,PO Number,PO Date,PO Expiry,PO Delivered By Address,PO Delivered To,SKU,Material,Category,Sub Category,Box/Case
0,1,48237010.0,BWLH5FZYW9XZEX9F,192,192.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-10,119.0 INR,51.35 INR,9390.720000000001 INR,0.0%,0.0 INR,2.5%,,2.5%,1.22 INR,0.0%,0.0 INR,468.48 INR,9859.20,fagwn07808591,2026-03-11,10-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
1,1,48237010.0,BWLH5FZYW9XZEX9F,128,128.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-23,119.0 INR,48.3 INR,5888.0 INR,0.0%,0.0 INR,2.5%,,2.5%,1.15 INR,0.0%,0.0 INR,294.4 INR,6182.40,fagwn07934808,2026-04-01,23-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
2,1,48237010,BWLH5FZYW9XZEX9F,12,12.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-12,119.0 INR,48.3 INR,551.9999999999999 INR,5.0%,2.3 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,27.599999999999998 INR,579.60,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
3,2,48237010,BWLH4H8YSGDZZX78,24,24.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-04-12,89.0 INR,35.0 INR,799.92 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,40.08 INR,840.00,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",PLB5RO10,Palm Leaf,Home Essentials,Tableware,20.0
4,3,46021919aa,PTDGXQBHGS5QPZZQ,12,12.0,pcs,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,2026-04-12,199.0 INR,118.3 INR,1419.6 INR,0.0%,0.0 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,0.0 INR,1419.60,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",PLP10SQ10,Palm Leaf,Home Essentials,Tableware,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,2,48236900.0,GLSH6KK67APTENYF,200,200.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-22,129.0 INR,62.3 INR,10560.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1900.0 INR,12460.00,fuswn08080464,2026-04-29,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0
940,1,48236900.0,GLSH6KK67APTENYF,320,320.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-24,129.0 INR,62.3 INR,16896.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,3040.0 INR,19936.00,fuswn08095377,2026-05-01,25-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0
941,1,48237010.0,BWLH4H8YSGDZZX78,80,80.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-05-22,89.0 INR,35.0 INR,2666.4 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,133.6 INR,2800.00,fuswn08122617,2026-05-07,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PLB5RO10,Palm Leaf,Home Essentials,Tableware,20.0
942,1,44191900.0,SPNH46S4G7HG3FWA,200,200.0,pcs,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,2026-07-04,99.0 INR,45.0 INR,8572.0 INR,5.0%,2.14 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,428.0 INR,9000.00,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",BS140MM50,Bagasse,Home Essentials,Tableware,100.0
943,2,48236900.0,GLSH6KK67APTENYF,120,120.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-07-04,129.0 INR,62.3 INR,6336.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1140.0 INR,7476.00,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0

# Invoice file cleaning

In [18]:
invoice_df['Invoice P.O.#']=invoice_df['Invoice P.O.#'].str.lower()

In [19]:
invoice_df

,Invoice Date,Invoice Number,Invoice P.O.#,Invoice Bill To,Invoice Ship To,Invoice Dispatch From,Invoice S.No,Invoice Item & Description,Invoice SKU No,Invoice HSN/SAC,Invoice Case Qty,Invoice Rate,IGST %,IGST Amount,CGST %,CGST Amount,SGST %,SGST Amount,Invoice Amount
0,2026-04-05,ESHBT/26/1,fbhwn07868785,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS50,44219990,200.00,57.142,,,2.5%,285.71,2.5%,285.71,"11,428.40"
1,2026-04-29,ESHBT/26/105,fbhwn07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,140mm Birchwood Spoon - - Count of 50 - Beige ...,ZB- BS140 MM50,44219990,200.00,42.857,,,2.5%,214.29,2.5%,214.29,"8,571.40"
2,2026-04-29,ESHBT/26/105,fbhwn07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,120.00,52.796,,,9%,570.20,9%,570.20,"6,335.52"
3,2026-04-29,ESHBT/26/106,fbhwn08023669,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,320.00,52.796,,,9%,"1,520.52",9%,"1,520.52","16,894.72"
4,2026-04-29,ESHBT/26/107,fbhwn08043741,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ 25NL,48236900,520.00,52.796,,,9%,"2,470.85",9%,"2,470.85","27,453.92"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,2026-03-25,FK/2025-26/168,fnnwn07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Bagasse Bowl 180ml Round set of 25...,FG- CBB6RO2 5UB,48237010,64.00,48.90,5%,156.48,,,,,"3,129.60"
381,2026-03-25,FK/2025-26/168,fnnwn07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
382,2026-03-25,FK/2025-26/169,fnnwn07852203,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,ZB-BS50,44219990,100.00,57.14,5%,285.70,,,,,"5,714.00"
383,2026-03-25,FK/2025-26/170,fnnwn07860786,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,40.00,44.07,18%,317.30,,,,,"1,762.80"
384,2026-03-25,FK/2025-26/171,fnnwn07866539,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,ZB- PCL8OZ2 5NL,48236900,80.00,44.07,18%,634.61,,,,,"3,525.60"

# Check the duplicacy of SKU and PO Number

In [20]:
is_unique = ~po_df.duplicated(subset=["SKU", "PO Number"]).any()
print("Is (SKU + PO_quantity) unique?", is_unique)

Is (SKU + PO_quantity) unique? True

In [21]:
po_df.drop_duplicates(subset=['SKU', 'PO Number'], inplace=True)

# Check the duplicacy of SKU and Invoice Number

In [22]:
is_unique = ~invoice_df.duplicated(subset=["Invoice SKU No", "Invoice P.O.#"]).any()
print("Is (SKU + PO_quantity) unique?", is_unique)

Is (SKU + PO_quantity) unique? True

In [23]:
invoice_df.drop_duplicates(subset=['Invoice SKU No', 'Invoice P.O.#'], inplace=True)

In [24]:
invoice_df.columns

Index(['Invoice Date', 'Invoice Number', 'Invoice P.O.#', 'Invoice Bill To',
       'Invoice Ship To', 'Invoice Dispatch From', 'Invoice S.No',
       'Invoice Item & Description', 'Invoice SKU No', 'Invoice HSN/SAC',
       'Invoice Case Qty', 'Invoice Rate', 'IGST %', 'IGST Amount', 'CGST %',
       'CGST Amount', 'SGST %', 'SGST Amount', 'Invoice Amount'],
      dtype='object')

# Rename CGST, IGST, SGST

In [25]:
invoice_df = invoice_df.rename(columns={
    'CGST Amount': 'CGST Amt',
    'SGST Amount': 'SGST Amt',
    'IGST Amount': 'IGST Amt',
    'Invoice Bill To':'invoice_bill_to',
    'Invoice Ship To':'invoice_ship_to',
    'Invoice Dispatch From':'invoice_dispatch_from'
})

# Calculate Invoice amount Inc GST

In [26]:
import pandas as pd

# Columns involved in total calculation
gst_cols = ["Invoice Amount", "CGST Amt", "SGST Amt", "IGST Amt"]

# Step 1: Clean + convert object columns to numeric
for col in gst_cols:
    invoice_df[col] = (
        invoice_df[col]
        .astype(str)                      # ensure string
        .str.replace(",", "", regex=False)  # remove thousand separators
        .str.strip()
    )
    invoice_df[col] = pd.to_numeric(
        invoice_df[col],
        errors="coerce"
    ).fillna(0)

# Step 2: Create invoice amount including GST
invoice_df["invoice_amt_gst"] = (
    invoice_df["Invoice Amount"]
    + invoice_df["CGST Amt"]
    + invoice_df["SGST Amt"]
    + invoice_df["IGST Amt"]
)

# Optional: round to 2 decimals (recommended for invoices)
invoice_df["invoice_amt_gst"] = invoice_df["invoice_amt_gst"].round(2)

# Preview result
invoice_df[
    ["Invoice Amount", "CGST Amt", "SGST Amt", "IGST Amt", "invoice_amt_gst"]
].head()

   Invoice Amount  CGST Amt  SGST Amt  IGST Amt  invoice_amt_gst
0        11428.40    285.71    285.71       0.0         11999.82
1         8571.40    214.29    214.29       0.0          8999.98
2         6335.52    570.20    570.20       0.0          7475.92
3        16894.72   1520.52   1520.52       0.0         19935.76
4        27453.92   2470.85   2470.85       0.0         32395.62

In [27]:
invoice_df['invoice_amt_gst'].sum()

np.float64(2797994.6500000004)

# Rename columns in PO

In [28]:
po_df = po_df.rename(columns={
    'PO Number': 'PO No',
    'PO Expiry': 'PO Expiry Date',
    'Quantity': 'PO_quantity',
    'Total Amount': 'PO_Amount',
    'HSN/SA Code': 'HSN Code'
})

# Rename columns in invoice

In [29]:
invoice_df = invoice_df.rename(columns={
    'Invoice SKU No': 'SKU',
    'Invoice Case Qty': 'Invoice_Quantity',
    'Invoice Amount': 'Invoice_Amount',
    'Invoice P.O.#': 'PO No'
})

# SKU cleaning in Invoice

In [30]:
import re
import pandas as pd

def clean_sku(s):
    if pd.isna(s):
        return ""

    s = str(s).upper().strip()

    # 1. Remove starting prefixes like "ZB -" or "SP -"
    s = re.sub(r"^(ZB|SP)\s*-\s*", "", s)

    # 2. Remove spaces
    s = s.replace(" ", "")

    # 3. Remove hyphens anywhere
    s = s.replace("-", "")

    # 4. Remove trailing dot
    s = re.sub(r"\.$", "", s)

    # 5. Keep only A–Z and 0–9
    s = re.sub(r"[^A-Z0-9]", "", s)

    return s


invoice_df['SKU'] = invoice_df['SKU'].apply(clean_sku)

In [31]:
po_df.columns

Index(['S. no.', 'HSN Code', 'FSN/ISBN13', 'PO_quantity', 'Pending Quantity',
       'UOM', 'Title', 'Required by Date', 'Supplier MRP', 'Supplier Price',
       'Taxable Value', 'IGST Rate', 'IGST Amount(per unit)', 'SGST Rate',
       'SGST Amount(per unit)', 'CGST Rate', 'CGST Amount(per unit)',
       'CESS Rate', 'CESS Amount(per unit)', 'Tax Amount', 'PO_Amount',
       'PO No', 'PO Date', 'PO Expiry Date', 'PO Delivered By Address',
       'PO Delivered To', 'SKU', 'Material', 'Category', 'Sub Category',
       'Box/Case'],
      dtype='object')

In [32]:
invoice_df.columns

Index(['Invoice Date', 'Invoice Number', 'PO No', 'invoice_bill_to',
       'invoice_ship_to', 'invoice_dispatch_from', 'Invoice S.No',
       'Invoice Item & Description', 'SKU', 'Invoice HSN/SAC',
       'Invoice_Quantity', 'Invoice Rate', 'IGST %', 'IGST Amt', 'CGST %',
       'CGST Amt', 'SGST %', 'SGST Amt', 'Invoice_Amount', 'invoice_amt_gst'],
      dtype='object')

In [33]:
import pandas as pd

# Convert 'PO_Amount' from object to numeric safely
po_df['PO_Amount'] = (
    po_df['PO_Amount']
    .astype(str)
    .str.replace(r'[\s,]+', '', regex=True)  # remove spaces, \n, and commas
    .astype(float)
)

# Optional: round to 2 decimals
po_df["PO_Amount"] = po_df["PO_Amount"].round(2)

# Verify datatype
po_df["PO_Amount"].dtype

dtype('float64')

In [34]:
po_df['PO_Amount'].sum()

np.float64(5876417.75)

# Merge PO Invoice

In [35]:
merged_df = po_df.merge(
    invoice_df,
    on=['PO No', 'SKU'],
    how='left'   # use 'inner' if you want only matched records
)

In [36]:
invoice_df

,Invoice Date,Invoice Number,PO No,invoice_bill_to,invoice_ship_to,invoice_dispatch_from,Invoice S.No,Invoice Item & Description,SKU,Invoice HSN/SAC,Invoice_Quantity,Invoice Rate,IGST %,IGST Amt,CGST %,CGST Amt,SGST %,SGST Amt,Invoice_Amount,invoice_amt_gst
0,2026-04-05,ESHBT/26/1,fbhwn07868785,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,BS50,44219990,200.00,57.142,,0.00,2.5%,285.71,2.5%,285.71,11428.40,11999.82
1,2026-04-29,ESHBT/26/105,fbhwn07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,140mm Birchwood Spoon - - Count of 50 - Beige ...,BS140MM50,44219990,200.00,42.857,,0.00,2.5%,214.29,2.5%,214.29,8571.40,8999.98
2,2026-04-29,ESHBT/26/105,fbhwn07976158,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,120.00,52.796,,0.00,9%,570.20,9%,570.20,6335.52,7475.92
3,2026-04-29,ESHBT/26/106,fbhwn08023669,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,320.00,52.796,,0.00,9%,1520.52,9%,1520.52,16894.72,19935.76
4,2026-04-29,ESHBT/26/107,fbhwn08043741,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"Ecosoul Home Pvt Ltd 1st Phase, Plot No. P.O.#...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,520.00,52.796,,0.00,9%,2470.85,9%,2470.85,27453.92,32395.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380,2026-03-25,FK/2025-26/168,fnnwn07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Bagasse Bowl 180ml Round set of 25...,FGCBB6RO25UB,48237010,64.00,48.90,5%,156.48,,0.00,,0.00,3129.60,3286.08
381,2026-03-25,FK/2025-26/168,fnnwn07852010,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,40.00,44.07,18%,317.30,,0.00,,0.00,1762.80,2080.10
382,2026-03-25,FK/2025-26/169,fnnwn07852203,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,160mm Birchwood Spoon - - Count of 50 - Beige ...,BS50,44219990,100.00,57.14,5%,285.70,,0.00,,0.00,5714.00,5999.70
383,2026-03-25,FK/2025-26/170,fnnwn07860786,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,40.00,44.07,18%,317.30,,0.00,,0.00,1762.80,2080.10
384,2026-03-25,FK/2025-26/171,fnnwn07866539,INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,"EcoSoul Home Pvt Ltd Plot 305, Udyog P.O.# : F...",,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,PCL8OZ25NL,48236900,80.00,44.07,18%,634.61,,0.00,,0.00,3525.60,4160.21

In [37]:
po_df

,S. no.,HSN Code,FSN/ISBN13,PO_quantity,Pending Quantity,UOM,Title,Required by Date,Supplier MRP,Supplier Price,Taxable Value,IGST Rate,IGST Amount(per unit),SGST Rate,SGST Amount(per unit),CGST Rate,CGST Amount(per unit),CESS Rate,CESS Amount(per unit),Tax Amount,PO_Amount,PO No,PO Date,PO Expiry Date,PO Delivered By Address,PO Delivered To,SKU,Material,Category,Sub Category,Box/Case
0,1,48237010.0,BWLH5FZYW9XZEX9F,192,192.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-10,119.0 INR,51.35 INR,9390.720000000001 INR,0.0%,0.0 INR,2.5%,,2.5%,1.22 INR,0.0%,0.0 INR,468.48 INR,9859.2,fagwn07808591,2026-03-11,10-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
1,1,48237010.0,BWLH5FZYW9XZEX9F,128,128.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-23,119.0 INR,48.3 INR,5888.0 INR,0.0%,0.0 INR,2.5%,,2.5%,1.15 INR,0.0%,0.0 INR,294.4 INR,6182.4,fagwn07934808,2026-04-01,23-04-26,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
2,1,48237010,BWLH5FZYW9XZEX9F,12,12.0,pcs,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,2026-04-12,119.0 INR,48.3 INR,551.9999999999999 INR,5.0%,2.3 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,27.599999999999998 INR,579.6,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",CBB6RO25UB,Bagasse,Home Essentials,Kitchen Essentials,64.0
3,2,48237010,BWLH4H8YSGDZZX78,24,24.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-04-12,89.0 INR,35.0 INR,799.92 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,40.08 INR,840.0,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",PLB5RO10,Palm Leaf,Home Essentials,Tableware,20.0
4,3,46021919aa,PTDGXQBHGS5QPZZQ,12,12.0,pcs,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,2026-04-12,199.0 INR,118.3 INR,1419.6 INR,0.0%,0.0 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,0.0 INR,1419.6,faswn07894271,2026-03-26,13-04-26,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",PLP10SQ10,Palm Leaf,Home Essentials,Tableware,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,2,48236900.0,GLSH6KK67APTENYF,200,200.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-22,129.0 INR,62.3 INR,10560.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1900.0 INR,12460.0,fuswn08080464,2026-04-29,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0
940,1,48236900.0,GLSH6KK67APTENYF,320,320.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-05-24,129.0 INR,62.3 INR,16896.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,3040.0 INR,19936.0,fuswn08095377,2026-05-01,25-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0
941,1,48237010.0,BWLH4H8YSGDZZX78,80,80.0,pcs,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,2026-05-22,89.0 INR,35.0 INR,2666.4 INR,5.0%,1.67 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,133.6 INR,2800.0,fuswn08122617,2026-05-07,22-05-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PLB5RO10,Palm Leaf,Home Essentials,Tableware,20.0
942,1,44191900.0,SPNH46S4G7HG3FWA,200,200.0,pcs,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,2026-07-04,99.0 INR,45.0 INR,8572.0 INR,5.0%,2.14 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,428.0 INR,9000.0,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",BS140MM50,Bagasse,Home Essentials,Tableware,100.0
943,2,48236900.0,GLSH6KK67APTENYF,120,120.0,pcs,ECO SOUL_Glass Set_White_810103156647_25,2026-07-04,129.0 INR,62.3 INR,6336.0 INR,18.0%,9.5 INR,0.0%,,0.0%,0.0 INR,0.0%,0.0 INR,1140.0 INR,7476.0,fuswn08276251,2026-06-10,06-07-26,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",PCL8OZ25NL,Paper,Home Essentials,Kitchen Essentials,40.0

In [38]:
merged_df['invoice_amt_gst'].sum()

np.float64(2645358.23)

In [39]:
merged_df.columns

Index(['S. no.', 'HSN Code', 'FSN/ISBN13', 'PO_quantity', 'Pending Quantity',
       'UOM', 'Title', 'Required by Date', 'Supplier MRP', 'Supplier Price',
       'Taxable Value', 'IGST Rate', 'IGST Amount(per unit)', 'SGST Rate',
       'SGST Amount(per unit)', 'CGST Rate', 'CGST Amount(per unit)',
       'CESS Rate', 'CESS Amount(per unit)', 'Tax Amount', 'PO_Amount',
       'PO No', 'PO Date', 'PO Expiry Date', 'PO Delivered By Address',
       'PO Delivered To', 'SKU', 'Material', 'Category', 'Sub Category',
       'Box/Case', 'Invoice Date', 'Invoice Number', 'invoice_bill_to',
       'invoice_ship_to', 'invoice_dispatch_from', 'Invoice S.No',
       'Invoice Item & Description', 'Invoice HSN/SAC', 'Invoice_Quantity',
       'Invoice Rate', 'IGST %', 'IGST Amt', 'CGST %', 'CGST Amt', 'SGST %',
       'SGST Amt', 'Invoice_Amount', 'invoice_amt_gst'],
      dtype='object')

# Take required columns

In [40]:
required_columns = [
    'FSN/ISBN13',
    'HSN Code',
    'PO No',
    'PO Date',
    'Title',
    'PO Expiry Date',
    'PO Delivered By Address',
    'PO Delivered To',
    'Invoice Number',
    'Supplier Price',
    'invoice_bill_to',
    'invoice_ship_to',
    'invoice_dispatch_from',
    'Tax Amount',
    'Invoice Date',
    'Supplier MRP',
    'SKU',
    'Category',
    'Material',
    'Sub Category',
    'PO_quantity',
    'Box/Case',
    'Invoice_Quantity',
    'PO_Amount',
    'Invoice_Amount',
    'invoice_amt_gst',
    'SGST Amt',
    'IGST Amt',
    'CGST Amt',
    'Invoice Item & Description',
    'Invoice Rate',
    "IGST %",
    "CGST %",
    "SGST %"
]
existing_columns = [col for col in required_columns if col in merged_df.columns]
final_df = merged_df[existing_columns]

# Add status

In [41]:
import numpy as np
final_df['Invoice_Quantity'] = pd.to_numeric(
    final_df['Invoice_Quantity'], errors='coerce'
).fillna(0)

final_df['PO_quantity'] = pd.to_numeric(
    final_df['PO_quantity'], errors='coerce'
).fillna(0)

final_df['Status'] = np.where(
    final_df['Invoice Number'].isna(),
    'Unfulfilled',
    np.where(final_df['Invoice_Quantity'] < final_df['PO_quantity'], 'Short Shipped', 'Fulfilled')
)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\1972213374.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Invoice_Quantity'] = pd.to_numeric(
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\1972213374.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['PO_quantity'] = pd.to_numeric(
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\1972213374.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Status'] = np.where(

# Correct the format of date

In [42]:
final_df = final_df.rename(columns={
    "PO Date": "PO Creation Date",
    "PO No": "PO Number"
})

# Add clientID, Platform, Channel

In [43]:
final_df[['ClientID', 'Platform', 'Channel']] = [
    'TH-1755734939046', 'QuickCommerce', 'Flikart']

In [44]:
final_df.columns

Index(['FSN/ISBN13', 'HSN Code', 'PO Number', 'PO Creation Date', 'Title',
       'PO Expiry Date', 'PO Delivered By Address', 'PO Delivered To',
       'Invoice Number', 'Supplier Price', 'invoice_bill_to',
       'invoice_ship_to', 'invoice_dispatch_from', 'Tax Amount',
       'Invoice Date', 'Supplier MRP', 'SKU', 'Category', 'Material',
       'Sub Category', 'PO_quantity', 'Box/Case', 'Invoice_Quantity',
       'PO_Amount', 'Invoice_Amount', 'invoice_amt_gst', 'SGST Amt',
       'IGST Amt', 'CGST Amt', 'Invoice Item & Description', 'Invoice Rate',
       'IGST %', 'CGST %', 'SGST %', 'Status', 'ClientID', 'Platform',
       'Channel'],
      dtype='object')

# Correct Data Types

In [45]:
import pandas as pd

# === 1. Convert date columns to datetime (date format) ===
date_cols = ["PO Creation Date", "PO Expiry Date"]

for col in date_cols:
    final_df[col] = pd.to_datetime(
        final_df[col],
        errors="coerce"   # invalid dates → NaT
    ).dt.date           # keep only date part


# === 2. Convert quantity & amount columns to integer ===
int_cols = [
    "PO_quantity",
    "Invoice_Quantity",
    "PO_Amount",
    "Invoice_Amount"
]

for col in int_cols:
    final_df[col] = (
        final_df[col]
        .astype(str)
        .str.replace(r"[^\d.]", "", regex=True)  # remove commas, currency, etc.
        .replace("", pd.NA)
    )

    final_df[col] = (
        pd.to_numeric(final_df[col], errors="coerce")  # 🔥 safest step
        .fillna(0)
        .astype(int)
    )

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\2157732036.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  final_df[col] = pd.to_datetime(

In [46]:
final_df.columns

Index(['FSN/ISBN13', 'HSN Code', 'PO Number', 'PO Creation Date', 'Title',
       'PO Expiry Date', 'PO Delivered By Address', 'PO Delivered To',
       'Invoice Number', 'Supplier Price', 'invoice_bill_to',
       'invoice_ship_to', 'invoice_dispatch_from', 'Tax Amount',
       'Invoice Date', 'Supplier MRP', 'SKU', 'Category', 'Material',
       'Sub Category', 'PO_quantity', 'Box/Case', 'Invoice_Quantity',
       'PO_Amount', 'Invoice_Amount', 'invoice_amt_gst', 'SGST Amt',
       'IGST Amt', 'CGST Amt', 'Invoice Item & Description', 'Invoice Rate',
       'IGST %', 'CGST %', 'SGST %', 'Status', 'ClientID', 'Platform',
       'Channel'],
      dtype='object')

# Rename columns

In [47]:
final_df = final_df.rename(columns={
    "FSN/ISBN13":"PO Item Code",
    "Title":"PO Product Description",
    "Supplier Price":"PO Basic Cost Price",
    "Tax Amount":"PO Tax Amt",
    "Supplier MRP":"PO MRP",
})

In [48]:
final_df.columns

Index(['PO Item Code', 'HSN Code', 'PO Number', 'PO Creation Date',
       'PO Product Description', 'PO Expiry Date', 'PO Delivered By Address',
       'PO Delivered To', 'Invoice Number', 'PO Basic Cost Price',
       'invoice_bill_to', 'invoice_ship_to', 'invoice_dispatch_from',
       'PO Tax Amt', 'Invoice Date', 'PO MRP', 'SKU', 'Category', 'Material',
       'Sub Category', 'PO_quantity', 'Box/Case', 'Invoice_Quantity',
       'PO_Amount', 'Invoice_Amount', 'invoice_amt_gst', 'SGST Amt',
       'IGST Amt', 'CGST Amt', 'Invoice Item & Description', 'Invoice Rate',
       'IGST %', 'CGST %', 'SGST %', 'Status', 'ClientID', 'Platform',
       'Channel'],
      dtype='object')

In [49]:
merged_df=final_df.copy()

# Add NLC to calculate revenue

In [50]:
pricing_path = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Shambhavi's File\NLC All platform1.xlsx"



pricing_df = pd.read_excel(
    pricing_path,
    sheet_name="Flipkart"   # 🔥 THIS FIX
)


pricing_df = pricing_df[[
    "SKUs",
    "As per pricing sheetNLC",
    "MRP as per pricing sheet",
    "GST",
]].rename(columns={
    "SKUs": "SKU",
    "As per pricing sheetNLC":"NLC as per pricing sheet",
    "GST": "GST as per pricing sheet",
})
import re

def clean_sku(s):
    if pd.isna(s):
        return ""
    s = str(s).upper()
    s = re.sub(r"[^A-Z0-9]", "", s)
    return s
pricing_df["SKU_CLEAN"] = pricing_df["SKU"].apply(clean_sku)
merged_df["SKU_CLEAN"] = merged_df["SKU"].apply(clean_sku)
merged_df["SKU_CLEAN"] = merged_df["SKU"].apply(clean_sku)
merged_df = merged_df.merge(
    pricing_df,
    on="SKU_CLEAN",
    how="left"
)

In [51]:
pricing_df

,SKU,NLC as per pricing sheet,MRP as per pricing sheet,GST as per pricing sheet,SKU_CLEAN
0,BS140MM50,44.85,99,0.05,BS140MM50
1,BS50,64.35,149,0.05,BS50
2,BSF50,64.35,149,0.05,BSF50
3,BSP50,64.35,149,0.05,BSP50
4,CBB4SQ25UB,51.35,119,0.05,CBB4SQ25UB
5,CBB6RO25UB,51.35,119,0.05,CBB6RO25UB
6,CBDN1P100P01,38.35,89,0.18,CBDN1P100P01
7,CBP10RO25BL,213.00,399,0.00,CBP10RO25BL
8,CBP10RO3C25BL,213.00,399,0.00,CBP10RO3C25BL
9,CBP11RO4C10UB,90.35,199,0.05,CBP11RO4C10UB
10,CBP11RO4C25BL,278.00,529,0.00,CBP11RO4C25BL
11,CNB3CMT10UB,77.35,169,0.05,CNB3CMT10UB
12,CRC5OZ25NL,57.85,139,0.18,CRC5OZ25NL
13,CRC6OZ25NL-QC,64.35,149,0.18,CRC6OZ25NLQC
14,CRC8OZ10NL-QC,38.35,89,0.18,CRC8OZ10NLQC
15,CRC8OZ25NL,120.00,219,0.18,CRC8OZ25NL
16,PCL5OZ100NL,116.00,199,0.18,PCL5OZ100NL
17,PCL5OZ50NL-QC,44.85,99,0.18,PCL5OZ50NLQC
18,PCL6OZ25NL-QC,51.35,119,0.18,PCL6OZ25NLQC
19,PCL8OZ25NL-QC,57.85,129,0.18,PCL8OZ25NLQC
20,PCL8OZ50NL,116.00,199,0.18,PCL8OZ50NL
21,PLB5.5SQ10,90.35,199,0.00,PLB55SQ10
22,PLP10RO10,96.85,199,0.00,PLP10RO10
23,PLP10SQ10,96.85,199,0.00,PLP10SQ10
24,PLP10SQ25,343.00,649,0.00,PLP10SQ25
25,PLP12RO10D,109.85,229,0.00,PLP12RO10D
26,PLP6RO10,64.35,129,0.00,PLP6RO10
27,PLP6SQ10-QC,64.35,129,0.00,PLP6SQ10QC
28,PLP6SQ25,207.00,389,0.00,PLP6SQ25
29,PLP8RO10,83.85,169,0.00,PLP8RO10
30,PLP8SQ10,83.85,169,0.00,PLP8SQ10
31,CPN2P50P01,38.35,89,0.18,CPN2P50P01
32,CBTP3P160P02,64.35,149,0.18,CBTP3P160P02
33,CBTP3P160P06,174.85,399,0.18,CBTP3P160P06
34,CBKPT2P60P02,96.85,229,0.18,CBKPT2P60P02
35,CBKPT2P60P04,174.85,399,0.18,CBKPT2P60P04
36,CBFT2P100P01,51.35,129,0.18,CBFT2P100P01
37,BBW64P01,83.85,189,0.18,BBW64P01
38,CTBS15,51.35,119,0.18,CTBS15
39,CTBM15,57.85,129,0.18,CTBM15
40,CTBL15,96.85,229,0.18,CTBL15
41,CPS6MM50NB,38.35,89,0.18,CPS6MM50NB
42,CPS8MM50NB,38.35,89,0.18,CPS8MM50NB
43,CPSMC6MM50NB,38.35,89,0.18,CPSMC6MM50NB
44,CPSMC8MM50NB,38.35,89,0.18,CPSMC8MM50NB
45,CNB5CMT10UB,109.85,229,0.05,CNB5CMT10UB
46,BSF140MM50,44.85,99,0.05,BSF140MM50
47,CBP6SQ25UB,70.85,159,0.05,CBP6SQ25UB
48,CBP6RO25UB,64.35,149,0.05,CBP6RO25UB
49,CBP9RO10UB,64.35,149,0.05,CBP9RO10UB
50,CBP12RO10UB,96.85,229,0.05,CBP12RO10UB
51,CBP10RO3C10BL,70.85,159,0.05,CBP10RO3C10BL
52,PLB5RO10,38.35,89,0.00,PLB5RO10
53,PLB6RO10,70.85,169,0.00,PLB6RO10
54,PLB4SQ10,44.85,109,0.00,PLB4SQ10

# Calculate revenue

In [52]:
import numpy as np

# Ensure numeric types (very important)
merged_df['NLC as per pricing sheet'] = pd.to_numeric(merged_df['NLC as per pricing sheet'], errors='coerce')
merged_df['Invoice_Quantity'] = pd.to_numeric(merged_df['Invoice_Quantity'], errors='coerce')

# Create revenue column
merged_df['revenue'] = merged_df['NLC as per pricing sheet'] * merged_df['Invoice_Quantity']

# Drop unnecessary columns

In [53]:
merged_df.rename(columns={
    'SKU_x': 'SKU'
}, inplace=True)
merged_df.drop(columns='SKU_y', inplace=True)

columns_to_drop = [
    "SKU_CLEAN"
]

merged_df = merged_df.drop(columns=columns_to_drop, errors="ignore")

# Add Extra columns

In [54]:
extra_columns = [
    'grn_item_code',
    'PO Product UPC',
    'grn_product_description',
    'grn_mrp',
    'grn_tax_amount',
    'grn_quantity',
    'grn_total_amount',
    'grn_gmv_loss',
    'dn_date',
    'facility_name',
    'dn_id',
    'item_name',
    'vendor_invoice_id',
    'dn_quantity',
    'dn_value',
    'dn_reason',
    'dn_remark',
    'PO Landing Rate'
]

for col in extra_columns:
    merged_df[col] = ""

In [55]:
merged_df.columns

Index(['PO Item Code', 'HSN Code', 'PO Number', 'PO Creation Date',
       'PO Product Description', 'PO Expiry Date', 'PO Delivered By Address',
       'PO Delivered To', 'Invoice Number', 'PO Basic Cost Price',
       'invoice_bill_to', 'invoice_ship_to', 'invoice_dispatch_from',
       'PO Tax Amt', 'Invoice Date', 'PO MRP', 'SKU', 'Category', 'Material',
       'Sub Category', 'PO_quantity', 'Box/Case', 'Invoice_Quantity',
       'PO_Amount', 'Invoice_Amount', 'invoice_amt_gst', 'SGST Amt',
       'IGST Amt', 'CGST Amt', 'Invoice Item & Description', 'Invoice Rate',
       'IGST %', 'CGST %', 'SGST %', 'Status', 'ClientID', 'Platform',
       'Channel', 'NLC as per pricing sheet', 'MRP as per pricing sheet',
       'GST as per pricing sheet', 'revenue', 'grn_item_code',
       'PO Product UPC', 'grn_product_description', 'grn_mrp',
       'grn_tax_amount', 'grn_quantity', 'grn_total_amount', 'grn_gmv_loss',
       'dn_date', 'facility_name', 'dn_id', 'item_name', 'vendor_invoice_id',
       'dn_quantity', 'dn_value', 'dn_reason', 'dn_remark', 'PO Landing Rate'],
      dtype='object')

# Priorities the columns

In [56]:
priority_cols = [
    "PO Number",
    "PO Creation Date",
    "PO Expiry Date",
    "PO Delivered By Address",
    "PO Delivered To",
    "PO Item Code",
    "HSN Code",
    "PO Product UPC",
    "PO Product Description",
    "PO Basic Cost Price",
    "PO Tax Amt",
    "PO Landing Rate",
    "Invoice Number",
    "Invoice Date",
    "invoice_dispatch_from",
    "invoice_ship_to",
    "invoice_bill_to",
    "SKU",
    "Invoice Item & Description",
    "Category",
    "Material",
    "Sub Category",
    "PO_quantity",
    "Invoice_Quantity",
    "PO_Amount",
    "Invoice_Amount",
    "Invoice_amt_gst",
    "Status",
    "ClientID",
    "Platform",
    "Channel",
    "SGST %",
    "SGST Amt",
    "CGST %",
    "CGST Amt",
    "IGST %",
    "IGST Amt"
]
# Ensure we only use columns that actually exist
priority_cols_existing = [c for c in priority_cols if c in merged_df.columns]

# Remaining columns (everything else, original order preserved)
remaining_cols = [c for c in merged_df.columns if c not in priority_cols_existing]

# Final reordered dataframe
final_df = merged_df[priority_cols_existing + remaining_cols]

In [57]:
final_df.columns

Index(['PO Number', 'PO Creation Date', 'PO Expiry Date',
       'PO Delivered By Address', 'PO Delivered To', 'PO Item Code',
       'HSN Code', 'PO Product UPC', 'PO Product Description',
       'PO Basic Cost Price', 'PO Tax Amt', 'PO Landing Rate',
       'Invoice Number', 'Invoice Date', 'invoice_dispatch_from',
       'invoice_ship_to', 'invoice_bill_to', 'SKU',
       'Invoice Item & Description', 'Category', 'Material', 'Sub Category',
       'PO_quantity', 'Invoice_Quantity', 'PO_Amount', 'Invoice_Amount',
       'Status', 'ClientID', 'Platform', 'Channel', 'SGST %', 'SGST Amt',
       'CGST %', 'CGST Amt', 'IGST %', 'IGST Amt', 'PO MRP', 'Box/Case',
       'invoice_amt_gst', 'Invoice Rate', 'NLC as per pricing sheet',
       'MRP as per pricing sheet', 'GST as per pricing sheet', 'revenue',
       'grn_item_code', 'grn_product_description', 'grn_mrp', 'grn_tax_amount',
       'grn_quantity', 'grn_total_amount', 'grn_gmv_loss', 'dn_date',
       'facility_name', 'dn_id', 'item_name', 'vendor_invoice_id',
       'dn_quantity', 'dn_value', 'dn_reason', 'dn_remark'],
      dtype='object')

# Add appointmemt date & status from file

In [58]:
import pandas as pd

# Load flipkart file
flipkart_file = r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Anoop Kumar's files - Flipkart Delivery Sheet\ESH - Flipkart Delivery Details.xlsx"
flipkart_df = pd.read_excel(flipkart_file)  # ← FIXED!


# Select only required columns and rename them
flipkart_selected = flipkart_df[[
    'PO Number', 
    'Appt Date', 
    'PO Status', 
    'Req Appt Date'
]].copy()
import pandas as pd

# Rename columns as requested
flipkart_selected = flipkart_selected.rename(columns={
    'Appt Date': 'appt date', 
    'PO Status': 'PO_fulfilled_status_from_file',
    'Req Appt Date': 'requested_appt_date'
})
flipkart_selected['PO Number'] = flipkart_selected['PO Number'].str.lower()
# Merge with final_df (fix column name mismatch)
final_df['PO Number'] = final_df['PO Number'].astype(str)
flipkart_selected['PO Number'] = flipkart_selected['PO Number'].astype(str)

final_df = final_df.merge(
    flipkart_selected,
    on='PO Number',
    how='left'  # Keeps all rows from final_df
)


print("✅ Merge complete!")
print(f"New columns: appt date, PO_fulfilled_status_from_file, requested_appt_date")

✅ Merge complete!
New columns: appt date, PO_fulfilled_status_from_file, requested_appt_date

In [59]:
final_df['PO_fulfilled_status_from_file'].isna().sum()

np.int64(567)

In [60]:
final_df

,PO Number,PO Creation Date,PO Expiry Date,PO Delivered By Address,PO Delivered To,PO Item Code,HSN Code,PO Product UPC,PO Product Description,PO Basic Cost Price,PO Tax Amt,PO Landing Rate,Invoice Number,Invoice Date,invoice_dispatch_from,invoice_ship_to,invoice_bill_to,SKU,Invoice Item & Description,Category,Material,Sub Category,PO_quantity,Invoice_Quantity,PO_Amount,Invoice_Amount,Status,ClientID,Platform,Channel,SGST %,SGST Amt,CGST %,CGST Amt,IGST %,IGST Amt,PO MRP,Box/Case,invoice_amt_gst,Invoice Rate,NLC as per pricing sheet,MRP as per pricing sheet,GST as per pricing sheet,revenue,grn_item_code,grn_product_description,grn_mrp,grn_tax_amount,grn_quantity,grn_total_amount,grn_gmv_loss,dn_date,facility_name,dn_id,item_name,vendor_invoice_id,dn_quantity,dn_value,dn_reason,dn_remark,appt date,PO_fulfilled_status_from_file,requested_appt_date
0,fagwn07808591,2026-03-11,2026-10-04,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",BWLH5FZYW9XZEX9F,48237010.0,,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,51.35 INR,468.48 INR,,NaN,NaT,NaN,NaN,NaN,CBB6RO25UB,NaN,Home Essentials,Bagasse,Kitchen Essentials,192,0,9859,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,119.0 INR,64.0,NaN,NaN,51.35,119.0,0.05,0.0,,,,,,,,,,,,,,,,,Cancelled by Vendor,Cancelled by Vendor,Cancelled by Vendor
1,fagwn07934808,2026-04-01,2026-04-23,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Survey No 518,...",BWLH5FZYW9XZEX9F,48237010.0,,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,48.3 INR,294.4 INR,,NaN,NaT,NaN,NaN,NaN,CBB6RO25UB,NaN,Home Essentials,Bagasse,Kitchen Essentials,128,0,6182,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,119.0 INR,64.0,NaN,NaN,51.35,119.0,0.05,0.0,,,,,,,,,,,,,,,,,Cancelled by Vendor,Cancelled by Vendor,Cancelled by Vendor
2,faswn07894271,2026-03-26,2026-04-13,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",BWLH5FZYW9XZEX9F,48237010,,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,48.3 INR,27.599999999999998 INR,,NaN,NaT,NaN,NaN,NaN,CBB6RO25UB,NaN,Home Essentials,Bagasse,Kitchen Essentials,12,0,579,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,119.0 INR,64.0,NaN,NaN,51.35,119.0,0.05,0.0,,,,,,,,,,,,,,,,,Cancelled by Vendor,Cancelled by Vendor,Cancelled by Vendor
3,faswn07894271,2026-03-26,2026-04-13,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",BWLH4H8YSGDZZX78,48237010,,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,35.0 INR,40.08 INR,,NaN,NaT,NaN,NaN,NaN,PLB5RO10,NaN,Home Essentials,Palm Leaf,Tableware,24,0,840,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,89.0 INR,20.0,NaN,NaN,38.35,89.0,0.00,0.0,,,,,,,,,,,,,,,,,Cancelled by Vendor,Cancelled by Vendor,Cancelled by Vendor
4,faswn07894271,2026-03-26,2026-04-13,"Ground Floor, 1, Pinnac Apartment Bamboo Gali,...","Flipkart India Private Limited, Hillway Indust...",PTDGXQBHGS5QPZZQ,46021919aa,,ECO SOUL Square Palm Leaf 10 inch 10 Dinner Plate,118.3 INR,0.0 INR,,NaN,NaT,NaN,NaN,NaN,PLP10SQ10,NaN,Home Essentials,Palm Leaf,Tableware,12,0,1419,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,199.0 INR,20.0,NaN,NaN,96.85,199.0,0.00,0.0,,,,,,,,,,,,,,,,,Cancelled by Vendor,Cancelled by Vendor,Cancelled by Vendor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,fuswn08080464,2026-04-29,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1900.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,200,0,12460,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00
944,fuswn08095377,2026-05-01,2026-05-25,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,3040.0 INR,,ESHU/26/291,2026-05-12,"EcoSoul Home Pvt Ltd Plot 305, Udyog Kendra Ex...",INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,PCL8OZ25NL,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,Home Essentials,Paper,Kitchen Essentials,320,320,19936,16894,Fulfilled,TH-1755734939046,QuickCommerce,Flikart,,0.0,,0.0,18%,3041.05,129.0 INR,40.0,19935.77,52.796,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00
945,fuswn08122617,2026-05-07,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",BWLH4H8YSGDZZX78,48237010.0,,ECO SOUL_Compostable Palm Leaf Bowls - Round 5...,35.0 INR,133.6 INR,,NaN,NaT,NaN,NaN,NaN,PLB5RO10,NaN,Home Essentials,Palm Leaf,Tableware,80,0,2800,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,89.0 INR,20.0,NaN,NaN,38.35,89.0,0.00,0.0,,,,,,,,,,,,,,,,,NaN,Cancelled by Vendor,NaN
946,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",SPNH46S4G7HG3FWA,44191900.0,,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,45.0 INR,428.0 INR,,NaN,NaT,NaN,NaN,NaN,BS140MM50,NaN,Home Essentials,Bagasse,Tableware,200,0,9000,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,100.0,NaN,NaN,44.85,99.0,0.05,0.0,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required
947,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1140.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,120,0,7476,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required

In [61]:
final_df.columns

Index(['PO Number', 'PO Creation Date', 'PO Expiry Date',
       'PO Delivered By Address', 'PO Delivered To', 'PO Item Code',
       'HSN Code', 'PO Product UPC', 'PO Product Description',
       'PO Basic Cost Price', 'PO Tax Amt', 'PO Landing Rate',
       'Invoice Number', 'Invoice Date', 'invoice_dispatch_from',
       'invoice_ship_to', 'invoice_bill_to', 'SKU',
       'Invoice Item & Description', 'Category', 'Material', 'Sub Category',
       'PO_quantity', 'Invoice_Quantity', 'PO_Amount', 'Invoice_Amount',
       'Status', 'ClientID', 'Platform', 'Channel', 'SGST %', 'SGST Amt',
       'CGST %', 'CGST Amt', 'IGST %', 'IGST Amt', 'PO MRP', 'Box/Case',
       'invoice_amt_gst', 'Invoice Rate', 'NLC as per pricing sheet',
       'MRP as per pricing sheet', 'GST as per pricing sheet', 'revenue',
       'grn_item_code', 'grn_product_description', 'grn_mrp', 'grn_tax_amount',
       'grn_quantity', 'grn_total_amount', 'grn_gmv_loss', 'dn_date',
       'facility_name', 'dn_id', 'item_name', 'vendor_invoice_id',
       'dn_quantity', 'dn_value', 'dn_reason', 'dn_remark', 'appt date',
       'PO_fulfilled_status_from_file', 'requested_appt_date'],
      dtype='object')

# Dataframe with refined values with status of did not delivered or cancelled by vendor

In [62]:
final_df['PO_fulfilled_status_from_file'].unique()

array(['Cancelled by Vendor', nan, 'Fulfilled', 'Expired',
       'Active-Action Required'], dtype=object)

In [63]:
final_df = final_df[~final_df['PO_fulfilled_status_from_file']
                    .isin(['Did not deliver', 'Cancelled by Vendor'])]

In [64]:
len(final_df.columns)

63

# Save the file to the destination

In [65]:
final_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\E-commerce\India\India Retail- Quick Commerce - INDIA TEAM\quick_comm_final_output\flipkart_output.csv",index=False)

# Read the file

In [66]:
import pandas as pd
final_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\E-commerce\India\India Retail- Quick Commerce - INDIA TEAM\quick_comm_final_output\flipkart_output.csv")

In [67]:
final_df

,PO Number,PO Creation Date,PO Expiry Date,PO Delivered By Address,PO Delivered To,PO Item Code,HSN Code,PO Product UPC,PO Product Description,PO Basic Cost Price,PO Tax Amt,PO Landing Rate,Invoice Number,Invoice Date,invoice_dispatch_from,invoice_ship_to,invoice_bill_to,SKU,Invoice Item & Description,Category,Material,Sub Category,PO_quantity,Invoice_Quantity,PO_Amount,Invoice_Amount,Status,ClientID,Platform,Channel,SGST %,SGST Amt,CGST %,CGST Amt,IGST %,IGST Amt,PO MRP,Box/Case,invoice_amt_gst,Invoice Rate,NLC as per pricing sheet,MRP as per pricing sheet,GST as per pricing sheet,revenue,grn_item_code,grn_product_description,grn_mrp,grn_tax_amount,grn_quantity,grn_total_amount,grn_gmv_loss,dn_date,facility_name,dn_id,item_name,vendor_invoice_id,dn_quantity,dn_value,dn_reason,dn_remark,appt date,PO_fulfilled_status_from_file,requested_appt_date
10,fbhwn05718319,2025-01-09,2025-01-28,"Tower-B, 2nd Floor, Unit-B 202A, Sector 142, ,...","Flipkart India Private Limited, Sy no 18/2, 18...",CNSH5F7WSMGXZFQX,48236900.0,,ECO SOUL_Cup Set_White,42.0 INR,282.04 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ50NL,NaN,Home Essentials,Paper,Kitchen Essentials,44,0,1848,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,NaN,NaN,NaN
11,fbhwn05769303,2025-01-21,2025-11-02,"Tower-B, 2nd Floor, Unit-B 202A, Sector 142, ,...","Flipkart India Private Limited, Sy no 18/2, 18...",CNSH5F7WSMGXZFQX,48236900.0,,ECO SOUL_Cup Set_White,42.0 INR,0.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ50NL,NaN,Home Essentials,Paper,Kitchen Essentials,0,0,0,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,NaN,NaN,NaN
12,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",GLSH27KKZE99D6KH,48236900.0,,ECO SOUL_Glass_White_100,116.0 INR,3964.7999999999997 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ100NL,NaN,Home Essentials,Paper,Tableware,224,0,25984,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,599.0 INR,20.0,NaN,NaN,116.00,199.0,0.18,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN
13,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",GLSH27KQJNDBMGYD,48236900.0,,ECO SOUL_Glass_White_50,116.0 INR,14160.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ50NL,NaN,Home Essentials,Paper,Tableware,800,0,92800,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,549.0 INR,20.0,NaN,NaN,116.00,199.0,0.18,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN
14,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",BWLH5FZYW9XZEX9F,48237010.0,,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,51.35 INR,4576.0 INR,,NaN,NaT,NaN,NaN,NaN,CBB6RO25UB,NaN,Home Essentials,Bagasse,Kitchen Essentials,832,0,42723,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,119.0 INR,64.0,NaN,NaN,51.35,119.0,0.05,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,fuswn08080464,2026-04-29,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",SPNH46S4G7HG3FWA,44191900.0,,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,45.0 INR,214.0 INR,,NaN,NaT,NaN,NaN,NaN,BS140MM50,NaN,Home Essentials,Bagasse,Tableware,100,0,4500,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,100.0,NaN,NaN,44.85,99.0,0.05,0.0,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00
943,fuswn08080464,2026-04-29,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1900.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,200,0,12460,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00
944,fuswn08095377,2026-05-01,2026-05-25,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,3040.0 INR,,ESHU/26/291,2026-05-12,"EcoSoul Home Pvt Ltd Plot 305, Udyog Kendra Ex...",INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,PCL8OZ25NL,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,Home Essentials,Paper,Kitchen Essentials,320,320,19936,16894,Fulfilled,TH-1755734939046,QuickCommerce,Flikart,,0.0,,0.0,18%,3041.05,129.0 INR,40.0,19935.77,52.796,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00
946,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",SPNH46S4G7HG3FWA,44191900.0,,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,45.0 INR,428.0 INR,,NaN,NaT,NaN,NaN,NaN,BS140MM50,NaN,Home Essentials,Bagasse,Tableware,200,0,9000,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,100.0,NaN,NaN,44.85,99.0,0.05,0.0,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required
947,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1140.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,120,0,7476,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required

In [68]:
final_df['PO Creation Date'] = pd.to_datetime(
    final_df['PO Creation Date'],
    errors='coerce'
)
final_df['year_month'] = final_df['PO Creation Date'].dt.to_period('M').astype(str)
final_df['PO Creation Date'] = final_df['PO Creation Date'].dt.date

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3998501918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['PO Creation Date'] = pd.to_datetime(
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3998501918.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['year_month'] = final_df['PO Creation Date'].dt.to_period('M').astype(str)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3998501918.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['PO Creation Date'] = final_df['PO Creation Date'].dt.date

In [69]:
final_df

,PO Number,PO Creation Date,PO Expiry Date,PO Delivered By Address,PO Delivered To,PO Item Code,HSN Code,PO Product UPC,PO Product Description,PO Basic Cost Price,PO Tax Amt,PO Landing Rate,Invoice Number,Invoice Date,invoice_dispatch_from,invoice_ship_to,invoice_bill_to,SKU,Invoice Item & Description,Category,Material,Sub Category,PO_quantity,Invoice_Quantity,PO_Amount,Invoice_Amount,Status,ClientID,Platform,Channel,SGST %,SGST Amt,CGST %,CGST Amt,IGST %,IGST Amt,PO MRP,Box/Case,invoice_amt_gst,Invoice Rate,NLC as per pricing sheet,MRP as per pricing sheet,GST as per pricing sheet,revenue,grn_item_code,grn_product_description,grn_mrp,grn_tax_amount,grn_quantity,grn_total_amount,grn_gmv_loss,dn_date,facility_name,dn_id,item_name,vendor_invoice_id,dn_quantity,dn_value,dn_reason,dn_remark,appt date,PO_fulfilled_status_from_file,requested_appt_date,year_month
10,fbhwn05718319,2025-01-09,2025-01-28,"Tower-B, 2nd Floor, Unit-B 202A, Sector 142, ,...","Flipkart India Private Limited, Sy no 18/2, 18...",CNSH5F7WSMGXZFQX,48236900.0,,ECO SOUL_Cup Set_White,42.0 INR,282.04 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ50NL,NaN,Home Essentials,Paper,Kitchen Essentials,44,0,1848,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,NaN,NaN,NaN,2025-01
11,fbhwn05769303,2025-01-21,2025-11-02,"Tower-B, 2nd Floor, Unit-B 202A, Sector 142, ,...","Flipkart India Private Limited, Sy no 18/2, 18...",CNSH5F7WSMGXZFQX,48236900.0,,ECO SOUL_Cup Set_White,42.0 INR,0.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ50NL,NaN,Home Essentials,Paper,Kitchen Essentials,0,0,0,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,NaN,NaN,NaN,2025-01
12,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",GLSH27KKZE99D6KH,48236900.0,,ECO SOUL_Glass_White_100,116.0 INR,3964.7999999999997 INR,,NaN,NaT,NaN,NaN,NaN,PCL5OZ100NL,NaN,Home Essentials,Paper,Tableware,224,0,25984,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,599.0 INR,20.0,NaN,NaN,116.00,199.0,0.18,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN,2025-02
13,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",GLSH27KQJNDBMGYD,48236900.0,,ECO SOUL_Glass_White_50,116.0 INR,14160.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ50NL,NaN,Home Essentials,Paper,Tableware,800,0,92800,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,549.0 INR,20.0,NaN,NaN,116.00,199.0,0.18,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN,2025-02
14,fbhwn05849736,2025-02-11,2025-02-28,"1st Phase, Plot No. 162-A, Road Number 33 of K...","Flipkart India Private Limited, Sy no 18/2, 18...",BWLH5FZYW9XZEX9F,48237010.0,,ECO SOUL_180 ml_Serving Bowl_Beige_810103152366,51.35 INR,4576.0 INR,,NaN,NaT,NaN,NaN,NaN,CBB6RO25UB,NaN,Home Essentials,Bagasse,Kitchen Essentials,832,0,42723,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,119.0 INR,64.0,NaN,NaN,51.35,119.0,0.05,0.0,,,,,,,,,,,,,,,,,NaN,NaN,NaN,2025-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,fuswn08080464,2026-04-29,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",SPNH46S4G7HG3FWA,44191900.0,,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,45.0 INR,214.0 INR,,NaN,NaT,NaN,NaN,NaN,BS140MM50,NaN,Home Essentials,Bagasse,Tableware,100,0,4500,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,100.0,NaN,NaN,44.85,99.0,0.05,0.0,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00,2026-04
943,fuswn08080464,2026-04-29,2026-05-22,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1900.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,200,0,12460,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00,2026-04
944,fuswn08095377,2026-05-01,2026-05-25,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,3040.0 INR,,ESHU/26/291,2026-05-12,"EcoSoul Home Pvt Ltd Plot 305, Udyog Kendra Ex...",INDIA PVT LTD India Private Limited India Priv...,INDIA PVT LTD India Private Limited India Priv...,PCL8OZ25NL,Compostable Paper Cups 8 OZ - Set Of 25 NL SKU...,Home Essentials,Paper,Kitchen Essentials,320,320,19936,16894,Fulfilled,TH-1755734939046,QuickCommerce,Flikart,,0.0,,0.0,18%,3041.05,129.0 INR,40.0,19935.77,52.796,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,2026-05-19 00:00:00,Fulfilled,2026-05-19 00:00:00,2026-05
946,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",SPNH46S4G7HG3FWA,44191900.0,,ECO SOUL_140 mm Biodegradable_Soup Spoon_Beige...,45.0 INR,428.0 INR,,NaN,NaT,NaN,NaN,NaN,BS140MM50,NaN,Home Essentials,Bagasse,Tableware,200,0,9000,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,99.0 INR,100.0,NaN,NaN,44.85,99.0,0.05,0.0,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required,2026-06
947,fuswn08276251,2026-06-10,2026-06-07,"Billing Address: 305, Udyog Kendra, Extension ...","Flipkart India Private Limited, ESR Warehousin...",GLSH6KK67APTENYF,48236900.0,,ECO SOUL_Glass Set_White_810103156647_25,62.3 INR,1140.0 INR,,NaN,NaT,NaN,NaN,NaN,PCL8OZ25NL,NaN,Home Essentials,Paper,Kitchen Essentials,120,0,7476,0,Unfulfilled,TH-1755734939046,QuickCommerce,Flikart,NaN,NaN,NaN,NaN,NaN,NaN,129.0 INR,40.0,NaN,NaN,NaN,NaN,NaN,NaN,,,,,,,,,,,,,,,,,Active-Action Required,Active-Action Required,Active-Action Required,2026-06

In [70]:
float_cols = final_df.select_dtypes(include='float')

final_df[float_cols.columns] = final_df[float_cols.columns].round(2)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3474924535.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[float_cols.columns] = final_df[float_cols.columns].round(2)

In [71]:
import pandas as pd

final_df['year_month'] = pd.to_datetime(
    final_df['year_month'],
    errors='coerce'
)

final_df['year'] = final_df['year_month'].dt.year
final_df['month'] = final_df['year_month'].dt.strftime('%B')

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3797021220.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['year_month'] = pd.to_datetime(
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3797021220.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['year'] = final_df['year_month'].dt.year
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\3797021220.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['month'] = final_df['year_month'].dt.strftime('%B')

In [72]:
final_df['year'] = final_df['year'].astype(str)
final_df['month'] = final_df['month'].astype(str).str.zfill(2)

final_df['year_month'] = (
    final_df['year'] + '_' + final_df['month']
)
final_df['Invoice Date'] = final_df['Invoice Date'].dt.date

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\2757904007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['year'] = final_df['year'].astype(str)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\2757904007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['month'] = final_df['month'].astype(str).str.zfill(2)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\2757904007.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['year_month'] = (
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\2757904007.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Invoice Date'] = final_df['Invoice Date'].dt.date

In [73]:
final_df['Invoice Date'] = pd.to_datetime(final_df['Invoice Date']).dt.date

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_35988\4016713438.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Invoice Date'] = pd.to_datetime(final_df['Invoice Date']).dt.date

# Upload the file to SQL

In [74]:
import pandas as pd
import urllib.parse
import re
from sqlalchemy import create_engine, text, inspect

# ======================================================
# MYSQL CONFIG
# ======================================================
MYSQL_CONFIG = {
    "host": "192.168.50.148",
    "port": 3306,
    "user": "datahive_esh_test",
    "password": "Datahive@321!",
    "database": "datahive_esh_test",
}


DEPARTMENT = "quick_comm"
BASE_TABLE_NAME = "flipkart_orders"
TABLE_NAME = f"{DEPARTMENT}_{BASE_TABLE_NAME}"

# ======================================================
# CLEAN MYSQL COLUMN NAMES
# ======================================================
def clean_mysql_column(col):
    col = col.strip()
    col = col.replace(" ", "_")
    col = col.replace("%", "pct")
    col = col.replace("-", "_")
    col = col.replace("/", "_")
    col = col.replace("\\", "_")
    col = col.replace("(", "")
    col = col.replace(")", "")
    col = col.replace("[", "")
    col = col.replace("]", "")
    col = re.sub(r"__+", "_", col)
    col = re.sub(r"[^A-Za-z0-9_]", "", col)
    return col.lower()

# ======================================================
# CREATE MYSQL ENGINE
# ======================================================
password_encoded = urllib.parse.quote_plus(MYSQL_CONFIG["password"])

engine = create_engine(
    f"mysql+mysqlconnector://{MYSQL_CONFIG['user']}:{password_encoded}"
    f"@{MYSQL_CONFIG['host']}:{MYSQL_CONFIG['port']}/{MYSQL_CONFIG['database']}",
    pool_pre_ping=True
)

# ======================================================
# TEST MYSQL CONNECTION (OPTIONAL BUT RECOMMENDED)
# ======================================================
def test_mysql_connection():
    print("\n🔍 Testing MySQL connection...")
    try:
        with engine.connect() as conn:
            db = conn.execute(text("SELECT DATABASE();")).fetchone()
            print("✅ Connected to database:", db[0])
    except Exception as e:
        print("❌ Connection failed:", e)
        return False
    return True

# ======================================================
# SAVE final_df TO MYSQL
# ======================================================
def save_final_df_to_mysql(final_df: pd.DataFrame):
    print("\n🟦 Uploading final_df to MySQL...")

    df = final_df.copy()
    print("📊 Rows to upload:", len(df))

    # Clean column names
    df.columns = [clean_mysql_column(c) for c in df.columns]

    inspector = inspect(engine)
    table_exists = inspector.has_table(TABLE_NAME)

    try:
        with engine.begin() as conn:

            if table_exists:
                print("🗑 Truncating existing table...")
                conn.execute(text(f"TRUNCATE TABLE `{TABLE_NAME}`"))
                mode = "append"
            else:
                print("📌 Creating new table...")
                mode = "fail"

            print("⬆ Inserting rows...")
            df.to_sql(
                TABLE_NAME,
                con=conn,
                if_exists=mode,
                index=False,
                chunksize=1000,
                method="multi"
            )

        print("✅ Upload completed successfully!")

    except Exception as e:
        print("❌ Upload failed:", e)

# ======================================================
# RUN
# ======================================================
# final_df MUST already exist in memory

if test_mysql_connection():
    save_final_df_to_mysql(final_df)

🔍 Testing MySQL connection...
✅ Connected to database: datahive_esh_test

🟦 Uploading final_df to MySQL...
📊 Rows to upload: 873
🗑 Truncating existing table...
⬆ Inserting rows...
✅ Upload completed successfully!