# Inventory

## Read and save inventory files

In [2]:
import pandas as pd
import numpy as np
import os, re
from datetime import datetime, timedelta

In [3]:
# Get the current month and year
current_month_year = datetime.now().strftime("%b-%Y")
print(current_month_year)

Jun-2026

In [4]:
# Get the current month and year
current_year = datetime.now().strftime("%Y")
print(current_year)

2026

In [5]:
previous_month_year = (datetime.now() - timedelta(days=30)).strftime("%b-%Y")
print(previous_month_year)

May-2026

In [6]:
# ===============================
# 1️⃣ Calculate T-3 Date
# ===============================

t_minus_3_date = datetime.now() - timedelta(days=3)

t_minus_3_year = t_minus_3_date.strftime("%Y")
t_minus_3_month_year = t_minus_3_date.strftime("%b-%Y")
t_minus_3_month = t_minus_3_date.strftime("%b")
t_minus_3_datestr = t_minus_3_date.strftime("%d-%m-%Y")

print("T-2 Date:", t_minus_3_date)
print("T-2 Date String:", t_minus_3_datestr)
print("T-2 Month-Year:", t_minus_3_month_year)
print("T-2 Month Only", t_minus_3_month)
print("T-2 Year:", t_minus_3_year)

T-2 Date: 2026-06-09 10:02:16.978720
T-2 Date String: 09-06-2026
T-2 Month-Year: Jun-2026
T-2 Month Only Jun
T-2 Year: 2026

In [7]:
def to_snake(name: str) -> str:
    """Convert column name to snake_case format."""
    name = name.strip()
    name = name.lower()
    name = re.sub(r'[^a-z0-9]+', '_', name)
    name = re.sub(r'_+', '_', name)
    name = name.strip('_')
    return name

## Saving the inventory

In [8]:
# ===============================
# 2️⃣ Read Inventory File
# ===============================

inventory_file = pd.read_csv(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\pattex_inventory_uae.csv",
    skiprows=1)

inventory_file['date'] = t_minus_3_datestr

# ===============================
# 3️⃣ Define Base Saving Directory
# ===============================

base_directory = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input"

# Year folder (based on T-2 year)
year_folder = os.path.join(base_directory, t_minus_3_year)

# Month folder (based on T-2 month)
month_folder = os.path.join(year_folder, t_minus_3_month)

# Create folders if not exist
os.makedirs(month_folder, exist_ok=True)

# ===============================
# 4️⃣ Save File with T-2 Date
# ===============================

filename = f"pattex_inventory_{t_minus_3_datestr}.csv"
file_path = os.path.join(month_folder, filename)

inventory_file.to_csv(file_path, index=False)

print("File saved at:", file_path)

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\Jun\pattex_inventory_09-06-2026.csv

## Reading the inventorty file

In [9]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input"

dfs = []

today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))

    if os.path.exists(year_path):

        # convert 3 → mar
        month_name = calendar.month_abbr[month].lower()

        month_path = os.path.join(year_path, month_name)

        if os.path.exists(month_path):

            for file in os.listdir(month_path):

                if file.endswith(".csv"):

                    file_path = os.path.join(month_path, file)
                    print("Reading:", file_path)

                    df = pd.read_csv(file_path)
                    dfs.append(df)

# Combine data
if dfs:
    final_df = pd.concat(dfs, ignore_index=True)
    print("Total files read:", len(dfs))
    print("Final dataframe shape:", final_df.shape)
else:
    print("No CSV files found.")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_01-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_02-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_03-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_04-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_05-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_06-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_07-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_08-06-2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\input\2026\jun\pattex_inventory_09-06-2026.csv
Total files read: 9
Final dataframe shape: (465, 18)

In [10]:
final_df

,ASIN,Product Title,Brand,Category,Subcategory,Vendor Confirmation %,Net Received,Net Received Units,Open Purchase Order Quantity,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,Aged 90+ Days Sellable Units,Sellable On Hand Inventory,Sellable On Hand Units,Unsellable On Hand Inventory,Unsellable On Hand Units,date
0,B08B4T7CXB,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,Pattex,11000 Hand Tools,11039 Building tools,0.00%,AED 201.25,23,307,0.00%,0.0,"AED 2,253.60",224.0,"AED 2,601.06",262,AED 0.00,0.0,01-06-2026
1,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Pritt,"0200 Arts, Crafts & Sewing",0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,0.0,AED 236.50,11,AED 0.00,0.0,01-06-2026
2,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Pritt,"0200 Arts, Crafts & Sewing",0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2026
3,B0FKBMWL53,Pritt Glue Stick Original BUNDLE 4x22g Safe & ...,Pritt,UNKNOWN,UNKNOWN,0.00%,AED 0.00,0,24,0.00%,0.0,NaN,NaN,NaN,NaN,NaN,NaN,01-06-2026
4,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",Pritt,UNKNOWN,UNKNOWN,0.00%,AED 0.00,0,40,0.00%,0.0,AED 0.00,0.0,AED 123.50,13,AED 0.00,0.0,01-06-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B08XRX3PJX,Pattex Sl100 Acrylic Sealant in White - Joint ...,Pattex,UNKNOWN,UNKNOWN,0.00%,AED 0.00,0,NaN,0.00%,0.0,AED 0.00,0.0,"AED 1,052.10",63,AED 0.00,0.0,09-06-2026
461,B08W1WTZGB,Pattex PL 250 (Construction Adhesive) Is a pro...,Pattex,20000 Hardware,UNKNOWN,0.00%,AED 0.00,0,NaN,0.00%,0.0,"AED 1,790.80",46.0,"AED 12,098.31",312,AED 116.25,3.0,09-06-2026
462,B08MXBVG7Z,Henkel Pattex PL 100 Silicone (White),Pattex,20000 Hardware,UNKNOWN,0.00%,AED 0.00,0,1,0.00%,0.0,"AED 1,048.28",37.0,"AED 1,048.28",37,AED 0.00,0.0,09-06-2026
463,B08B4T7CXB,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,Pattex,11000 Hand Tools,11039 Building tools,0.00%,AED 0.00,0,133,0.00%,0.0,"AED 2,103.65",209.0,"AED 3,961.12",420,AED 0.00,0.0,09-06-2026
464,B001P5IT7A,PRITT FUNCOLOR 4x10G BL INT (12,Pritt,6000 Basic Supplies,6070 Glue & Adhesives,0.00%,AED 0.00,0,NaN,0.00%,0.0,AED 637.60,40.0,AED 637.60,40,AED 15.94,1.0,09-06-2026

In [11]:
final_df['Open Purchase Order Quantity'] = (
    final_df['Open Purchase Order Quantity']
    .astype(str)
    .str.replace(',', '', regex=False)   # remove commas
    .str.strip()                         # remove spaces
    .replace('', None)                   # handle empty values
    .pipe(pd.to_numeric, errors='coerce')# convert to numeric safely
    .fillna(0)                           # replace NaN
    .astype(int)                         # convert to int
)

In [12]:
final_df['date'] = pd.to_datetime(final_df['date'], format='%d-%m-%Y')
final_df['date'] = final_df['date'].dt.strftime('%d-%b-%Y')

### Remove columns and correct Data Types

In [13]:
final_df = final_df.drop(columns=['Product Title', 'Category'])

In [14]:
final_df

,ASIN,Brand,Subcategory,Vendor Confirmation %,Net Received,Net Received Units,Open Purchase Order Quantity,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,Aged 90+ Days Sellable Units,Sellable On Hand Inventory,Sellable On Hand Units,Unsellable On Hand Inventory,Unsellable On Hand Units,date
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 201.25,23,307,0.00%,0.0,"AED 2,253.60",224.0,"AED 2,601.06",262,AED 0.00,0.0,01-Jun-2026
1,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,0.0,AED 236.50,11,AED 0.00,0.0,01-Jun-2026
2,B0GN246XDP,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,NaN,NaN,NaN,NaN,NaN,NaN,01-Jun-2026
3,B0FKBMWL53,Pritt,UNKNOWN,0.00%,AED 0.00,0,24,0.00%,0.0,NaN,NaN,NaN,NaN,NaN,NaN,01-Jun-2026
4,B0FKBLF14N,Pritt,UNKNOWN,0.00%,AED 0.00,0,40,0.00%,0.0,AED 0.00,0.0,AED 123.50,13,AED 0.00,0.0,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B08XRX3PJX,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,AED 0.00,0.0,"AED 1,052.10",63,AED 0.00,0.0,09-Jun-2026
461,B08W1WTZGB,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,"AED 1,790.80",46.0,"AED 12,098.31",312,AED 116.25,3.0,09-Jun-2026
462,B08MXBVG7Z,Pattex,UNKNOWN,0.00%,AED 0.00,0,1,0.00%,0.0,"AED 1,048.28",37.0,"AED 1,048.28",37,AED 0.00,0.0,09-Jun-2026
463,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 0.00,0,133,0.00%,0.0,"AED 2,103.65",209.0,"AED 3,961.12",420,AED 0.00,0.0,09-Jun-2026
464,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 637.60,40.0,AED 637.60,40,AED 15.94,1.0,09-Jun-2026

### Item Master

In [15]:
import pandas as pd

# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")

# Convert ASIN to uppercase in both
final_df["ASIN"] = final_df["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
final_df = final_df.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
final_df["Pack Size"] = final_df["Pack Size"].fillna(0).astype(int)

print("Merge completed ✅")

Merge completed ✅

In [16]:
final_df

,ASIN,Brand,Subcategory,Vendor Confirmation %,Net Received,Net Received Units,Open Purchase Order Quantity,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Sellable On Hand Units,Unsellable On Hand Inventory,Unsellable On Hand Units,date,Product Name,Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 201.25,23,307,0.00%,0.0,"AED 2,253.60",...,262,AED 0.00,0.0,01-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50
1,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,11,AED 0.00,0.0,01-Jun-2026,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -
2,B0GN246XDP,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,NaN,...,NaN,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 2x43g,Pritt Glue Stick,Physical-Bundle,2,AED -,AED -
3,B0FKBMWL53,Pritt,UNKNOWN,0.00%,AED 0.00,0,24,0.00%,0.0,NaN,...,NaN,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 4x22g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -
4,B0FKBLF14N,Pritt,UNKNOWN,0.00%,AED 0.00,0,40,0.00%,0.0,AED 0.00,...,13,AED 0.00,0.0,01-Jun-2026,Pritt Original 4x11gm,Pritt Glue Stick,Physical-Bundle,4,AED -,AED 12.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B08XRX3PJX,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,AED 0.00,...,63,AED 0.00,0.0,09-Jun-2026,Pattex SL100 Acrylic Sealant (White),Sealant,Base ASIN,1,AED 34.00,AED 19.50
461,B08W1WTZGB,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,"AED 1,790.80",...,312,AED 116.25,3.0,09-Jun-2026,Pattex PL 250 (White),Construction Adhesive,Base ASIN,1,AED 64.00,AED 54.50
462,B08MXBVG7Z,Pattex,UNKNOWN,0.00%,AED 0.00,0,1,0.00%,0.0,"AED 1,048.28",...,37,AED 0.00,0.0,09-Jun-2026,Pattex PL100 (White),Construction Adhesive,Base ASIN,1,AED 48.00,AED 35.00
463,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 0.00,0,133,0.00%,0.0,"AED 2,103.65",...,420,AED 0.00,0.0,09-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50
464,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 637.60,...,40,AED 15.94,1.0,09-Jun-2026,NaN,NaN,NaN,0,NaN,NaN

### Remove Pritt

In [17]:
# final_df = final_df[final_df["Brand"] != "Pritt"]

In [18]:
final_df['Brand'] = final_df['Brand'].str.lower().str.capitalize()

### Rename Columns

In [19]:
final_df['Sales Channel'] = "Vendor Central"
final_df.rename(columns= {'Sellable On Hand Units' : 'Available Inventory',  'Category' : 'Product Category', 'Subcategory': 'Product Sub Category', 'Sellable On Hand Inventory' : 'Sellable Inventory Amount','Open Purchase Order Quantity' : 'Open POs','date' : 'Date'},inplace= True)

In [20]:
final_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Unsellable On Hand Inventory,Unsellable On Hand Units,Date,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 201.25,23,307,0.00%,0.0,"AED 2,253.60",...,AED 0.00,0.0,01-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50,Vendor Central
1,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,01-Jun-2026,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central
2,B0GN246XDP,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,NaN,...,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 2x43g,Pritt Glue Stick,Physical-Bundle,2,AED -,AED -,Vendor Central
3,B0FKBMWL53,Pritt,UNKNOWN,0.00%,AED 0.00,0,24,0.00%,0.0,NaN,...,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 4x22g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central
4,B0FKBLF14N,Pritt,UNKNOWN,0.00%,AED 0.00,0,40,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,01-Jun-2026,Pritt Original 4x11gm,Pritt Glue Stick,Physical-Bundle,4,AED -,AED 12.50,Vendor Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B08XRX3PJX,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,09-Jun-2026,Pattex SL100 Acrylic Sealant (White),Sealant,Base ASIN,1,AED 34.00,AED 19.50,Vendor Central
461,B08W1WTZGB,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,"AED 1,790.80",...,AED 116.25,3.0,09-Jun-2026,Pattex PL 250 (White),Construction Adhesive,Base ASIN,1,AED 64.00,AED 54.50,Vendor Central
462,B08MXBVG7Z,Pattex,UNKNOWN,0.00%,AED 0.00,0,1,0.00%,0.0,"AED 1,048.28",...,AED 0.00,0.0,09-Jun-2026,Pattex PL100 (White),Construction Adhesive,Base ASIN,1,AED 48.00,AED 35.00,Vendor Central
463,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 0.00,0,133,0.00%,0.0,"AED 2,103.65",...,AED 0.00,0.0,09-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50,Vendor Central
464,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 637.60,...,AED 15.94,1.0,09-Jun-2026,NaN,NaN,NaN,0,NaN,NaN,Vendor Central

In [21]:
import pandas as pd
import numpy as np



final_df["Available Inventory"] = (
    final_df["Available Inventory"]
        .astype(str)                       # ensure string
        .str.replace(",", "", regex=False) # remove commas
        .pipe(pd.to_numeric, errors="coerce")  # convert to numeric
        .replace([np.inf, -np.inf], 0)     # handle infinity
        .fillna(0)                        # replace NaN with 0
        .astype(int)                      # convert to int
)

In [22]:
final_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Unsellable On Hand Inventory,Unsellable On Hand Units,Date,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 201.25,23,307,0.00%,0.0,"AED 2,253.60",...,AED 0.00,0.0,01-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50,Vendor Central
1,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,01-Jun-2026,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central
2,B0GN246XDP,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,NaN,...,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 2x43g,Pritt Glue Stick,Physical-Bundle,2,AED -,AED -,Vendor Central
3,B0FKBMWL53,Pritt,UNKNOWN,0.00%,AED 0.00,0,24,0.00%,0.0,NaN,...,NaN,NaN,01-Jun-2026,Pritt Glue Stick Original 4x22g,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central
4,B0FKBLF14N,Pritt,UNKNOWN,0.00%,AED 0.00,0,40,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,01-Jun-2026,Pritt Original 4x11gm,Pritt Glue Stick,Physical-Bundle,4,AED -,AED 12.50,Vendor Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B08XRX3PJX,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,AED 0.00,...,AED 0.00,0.0,09-Jun-2026,Pattex SL100 Acrylic Sealant (White),Sealant,Base ASIN,1,AED 34.00,AED 19.50,Vendor Central
461,B08W1WTZGB,Pattex,UNKNOWN,0.00%,AED 0.00,0,0,0.00%,0.0,"AED 1,790.80",...,AED 116.25,3.0,09-Jun-2026,Pattex PL 250 (White),Construction Adhesive,Base ASIN,1,AED 64.00,AED 54.50,Vendor Central
462,B08MXBVG7Z,Pattex,UNKNOWN,0.00%,AED 0.00,0,1,0.00%,0.0,"AED 1,048.28",...,AED 0.00,0.0,09-Jun-2026,Pattex PL100 (White),Construction Adhesive,Base ASIN,1,AED 48.00,AED 35.00,Vendor Central
463,B08B4T7CXB,Pattex,11039 Building tools,0.00%,AED 0.00,0,133,0.00%,0.0,"AED 2,103.65",...,AED 0.00,0.0,09-Jun-2026,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,AED 25.02,AED 12.50,Vendor Central
464,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 637.60,...,AED 15.94,1.0,09-Jun-2026,NaN,NaN,NaN,0,NaN,NaN,Vendor Central

### Instock logic

In [23]:
# Create temporary datetime column for calculations
final_df['Date_temp'] = pd.to_datetime(final_df['Date'], format='%d-%b-%Y')

# Sort data
final_df = final_df.sort_values(["ASIN", "Date_temp"])

# Create month identifier (year + month)
final_df['year_month'] = final_df['Date_temp'].dt.to_period('M')

# Create in-stock flag
final_df["in_stock_flag"] = (final_df["Available Inventory"] > 0).astype(int)

# Cumulative in-stock days per ASIN per month
final_df["cumulative_instock_days"] = (
    final_df.groupby(["ASIN", "year_month"])["in_stock_flag"].cumsum()
)

# Extract day number within the month
final_df["day_of_month"] = final_df["Date_temp"].dt.day

# Calculate Instock Rate
final_df["Instock Rate"] = (
    final_df["cumulative_instock_days"] /
    final_df["day_of_month"] * 100
).round(2)

# Drop temporary helper columns if not needed
final_df.drop(columns=["Date_temp", "year_month"], inplace=True)

In [24]:
# # Convert to datetime temporarily for calculations
# final_df['Date_temp'] = pd.to_datetime(final_df['Date'], format='%d-%b-%Y')

# # Sort
# final_df = final_df.sort_values(["ASIN", "Date_temp"])

# # Create in-stock flag
# final_df["in_stock_flag"] = (final_df["Available Inventory"] > 0).astype(int)

# # Cumulative in-stock days per ASIN
# final_df["cumulative_instock_days"] = (
#     final_df.groupby("ASIN")["in_stock_flag"].cumsum()
# )

# # Extract calendar day
# final_df["day_of_month"] = final_df["Date_temp"].dt.day

# # Calculate Instock Rate
# final_df["Instock Rate"] = (
#     final_df["cumulative_instock_days"]
#     / final_df["day_of_month"]
#     * 100
# ).round(2)

# # Drop temporary column
# final_df.drop(columns=['Date_temp'], inplace=True)

In [25]:
final_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel,in_stock_flag,cumulative_instock_days,day_of_month,Instock Rate
48,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,1,1,100.0
100,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,2,2,100.0
152,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,3,3,100.0
204,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,4,4,100.0
256,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 940.46,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,5,5,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,5,5,100.0
265,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,6,6,100.0
310,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,7,7,100.0
361,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,8,8,100.0
413,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,9,9,100.0

In [26]:
inv_df = final_df.copy()

### Saving orders file

In [27]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# =====================================================
# STEP 1: SOURCE FILE (SALES)
# =====================================================
SOURCE_FILE = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\pattex_order_uae.csv"

BASE_PATH = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input"

# =====================================================
# STEP 2: GET TODAY & T-2 DATE
# =====================================================
today = datetime.today()
t_minus_2 = today - timedelta(days=3)

# =====================================================
# STEP 3: DECIDE TARGET MONTH FOLDER
# =====================================================
if today.day <= 3:
    # Save to previous month folder
    target_year = t_minus_2.year
    target_month = t_minus_2.month
else:
    # Save to current month folder
    target_year = today.year
    target_month = today.month

month_folder = calendar.month_abbr[target_month].lower()

# =====================================================
# STEP 4: CREATE FOLDER IF NOT EXISTS
# =====================================================
target_folder = os.path.join(BASE_PATH, str(target_year), month_folder)
os.makedirs(target_folder, exist_ok=True)

# =====================================================
# STEP 5: CREATE FILE NAME USING T-2 DATE
# =====================================================
file_name = f"pattex_order_uae_{t_minus_2.strftime('%d_%b_%Y').lower()}.csv"

destination_path = os.path.join(target_folder, file_name)

# =====================================================
# STEP 6: READ & SAVE FILE
# =====================================================
# df = pd.read_csv(SOURCE_FILE)
df = pd.read_csv(SOURCE_FILE, skiprows=1, encoding="utf-8-sig")

df.to_csv(destination_path, index=False)

print("✅ Sales file saved successfully")
print("📂 Location:", destination_path)

✅ Sales file saved successfully
📂 Location: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_09_jun_2026.csv

# Right logic for saving order file T-2

### Reading orders file

In [28]:
import os
import re
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
BASE_PATH = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input"

dfs = []

# -------- REGEX FOR DATE EXTRACTION --------
pattern = re.compile(r"_(\d{2})_([A-Za-z]{3})_(\d{4})")

# -------- GET TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- FIND PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- MONTHS TO READ --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- LOOP THROUGH REQUIRED MONTHS --------
for year, month in months_to_read:

    year_path = os.path.join(BASE_PATH, str(year))

    if not os.path.exists(year_path):
        continue

    # convert month number → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)

    if not os.path.exists(month_path):
        continue

    # -------- LOOP THROUGH FILES --------
    for file in os.listdir(month_path):

        if file.lower().endswith(".csv"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            # -------- APPLY SKIPROWS LOGIC --------
            if month_name in ["jan", "feb"]:
                df = pd.read_csv(file_path, skiprows=1)
            else:
                df = pd.read_csv(file_path)

            # -------- EXTRACT DATE FROM FILENAME --------
            match = pattern.search(file)

            if match:

                day_, month_str, year_str = match.groups()

                month_number = datetime.strptime(
                    month_str.title(), "%b"
                ).month

                date_value = datetime(
                    int(year_str),
                    int(month_number),
                    int(day_)
                ).date()

                df["Date"] = date_value

            else:
                print(f"⚠ Date not found in filename: {file}")
                df["Date"] = None

            dfs.append(df)

# -------- MERGE ALL FILES --------
if dfs:
    final_df = pd.concat(dfs, ignore_index=True)

    print("✅ All files merged successfully")
    print("Total files read:", len(dfs))
    print("Final dataframe shape:", final_df.shape)

else:
    print("❌ No CSV files found.")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_01_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_02_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_03_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_04_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_05_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_06_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_07_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_08_jun_2026.csv
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\input\2026\jun\pattex_order_uae_09_jun_2026.csv
✅ All files merged successfully
Total files read: 9
Final dataframe shape: (369, 14)

In [29]:
final_df

,ASIN,Product Title,Brand Code,Brand,Category,Subcategory,Parent ASIN,Shipped Revenue,Shipped COGS,Shipped Units,Customer Returns,Confirmed Units,Sales Discount,Date
0,B09KCHLFH4,Pattex Sanitary Antimould Transparent Pressure...,PA4TD,Pattex,0100 Art,0103 Painting Supplies,B0F54JXBTQ,AED 796.18,AED 701.14,22.0,2.0,0.0,AED 0.00,2026-06-01
1,B09KCFHH3T,"Pattex Super Glue Mini Dose, Strong All Purpos...",PA4TD,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,AED 487.92,AED 334.86,57.0,2.0,0.0,AED 18.76,2026-06-01
2,B09NKB9BJF,Pattex Sf525 Kitchen And Bath Premium Silicone...,0P0EK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B09NKB9BJF,AED 452.39,AED 463.03,19.0,NaN,0.0,AED 0.00,2026-06-01
3,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZL9NNNB,AED 308.61,AED 254.07,27.0,NaN,0.0,AED 0.00,2026-06-01
4,B0DDGV3T5C,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZL9NNNB,AED 169.38,AED 139.50,6.0,NaN,0.0,AED 2.83,2026-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,B0DDGS87JD,"Pattex Super Glue Liquid Control, All Purpose ...",BC0AK,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,NaN,NaN,NaN,NaN,25.0,NaN,2026-06-09
365,B09WD3WPF1,Pattex Contact Glue Premium - 650ml | Strong B...,BC0AK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B0GZLPDHJN,NaN,NaN,NaN,NaN,0.0,NaN,2026-06-09
366,B09KCHS3PH,Pattex No More Nails Invisible | All Purpose H...,BC0AK,Pattex,30000 Building Material,30190 Other,B0F54L5BS7,NaN,NaN,NaN,NaN,0.0,NaN,2026-06-09
367,B0969FQMXL,Pattex PL200 Construction Adhesive | Water-Bas...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,2026-06-09
368,B08MXBVG7Z,Henkel Pattex PL 100 Silicone (White),BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,2026-06-09

In [30]:
final_df['Date'] = pd.to_datetime(final_df['Date'], format='%Y-%m-%d')
final_df['Date'] = final_df['Date'].dt.strftime('%d-%b-%Y')

In [31]:
final_df

,ASIN,Product Title,Brand Code,Brand,Category,Subcategory,Parent ASIN,Shipped Revenue,Shipped COGS,Shipped Units,Customer Returns,Confirmed Units,Sales Discount,Date
0,B09KCHLFH4,Pattex Sanitary Antimould Transparent Pressure...,PA4TD,Pattex,0100 Art,0103 Painting Supplies,B0F54JXBTQ,AED 796.18,AED 701.14,22.0,2.0,0.0,AED 0.00,01-Jun-2026
1,B09KCFHH3T,"Pattex Super Glue Mini Dose, Strong All Purpos...",PA4TD,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,AED 487.92,AED 334.86,57.0,2.0,0.0,AED 18.76,01-Jun-2026
2,B09NKB9BJF,Pattex Sf525 Kitchen And Bath Premium Silicone...,0P0EK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B09NKB9BJF,AED 452.39,AED 463.03,19.0,NaN,0.0,AED 0.00,01-Jun-2026
3,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZL9NNNB,AED 308.61,AED 254.07,27.0,NaN,0.0,AED 0.00,01-Jun-2026
4,B0DDGV3T5C,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZL9NNNB,AED 169.38,AED 139.50,6.0,NaN,0.0,AED 2.83,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,B0DDGS87JD,"Pattex Super Glue Liquid Control, All Purpose ...",BC0AK,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,NaN,NaN,NaN,NaN,25.0,NaN,09-Jun-2026
365,B09WD3WPF1,Pattex Contact Glue Premium - 650ml | Strong B...,BC0AK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B0GZLPDHJN,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
366,B09KCHS3PH,Pattex No More Nails Invisible | All Purpose H...,BC0AK,Pattex,30000 Building Material,30190 Other,B0F54L5BS7,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
367,B0969FQMXL,Pattex PL200 Construction Adhesive | Water-Bas...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
368,B08MXBVG7Z,Henkel Pattex PL 100 Silicone (White),BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026

### Filter out Pritt

In [32]:
# final_df = final_df[final_df["Brand"] != "Pritt"]

### Renam Orders file

In [33]:
final_df.rename(columns= {'Product Title' : 'Product Name', 'Category' : 'Product Category', 'Subcategory': 'Product Sub Category', 'Shipped Revenue' : 'total_sales','Shipped Units' : 'total_units'},inplace= True)

In [34]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel,in_stock_flag,cumulative_instock_days,day_of_month,Instock Rate
48,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,1,1,100.0
100,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,2,2,100.0
152,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,3,3,100.0
204,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,4,4,100.0
256,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 940.46,...,NaN,NaN,0,NaN,NaN,Vendor Central,1,5,5,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,5,5,100.0
265,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,6,6,100.0
310,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,7,7,100.0
361,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,8,8,100.0
413,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Pritt Glue Stick,Physical-Bundle,4,AED -,AED -,Vendor Central,1,9,9,100.0

In [35]:
final_df

,ASIN,Product Name,Brand Code,Brand,Product Category,Product Sub Category,Parent ASIN,total_sales,Shipped COGS,total_units,Customer Returns,Confirmed Units,Sales Discount,Date
0,B09KCHLFH4,Pattex Sanitary Antimould Transparent Pressure...,PA4TD,Pattex,0100 Art,0103 Painting Supplies,B0F54JXBTQ,AED 796.18,AED 701.14,22.0,2.0,0.0,AED 0.00,01-Jun-2026
1,B09KCFHH3T,"Pattex Super Glue Mini Dose, Strong All Purpos...",PA4TD,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,AED 487.92,AED 334.86,57.0,2.0,0.0,AED 18.76,01-Jun-2026
2,B09NKB9BJF,Pattex Sf525 Kitchen And Bath Premium Silicone...,0P0EK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B09NKB9BJF,AED 452.39,AED 463.03,19.0,NaN,0.0,AED 0.00,01-Jun-2026
3,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZL9NNNB,AED 308.61,AED 254.07,27.0,NaN,0.0,AED 0.00,01-Jun-2026
4,B0DDGV3T5C,Pattex Super Glue Power Gel Control | All Purp...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZL9NNNB,AED 169.38,AED 139.50,6.0,NaN,0.0,AED 2.83,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,B0DDGS87JD,"Pattex Super Glue Liquid Control, All Purpose ...",BC0AK,Pattex,UNKNOWN,UNKNOWN,B0F66PZPM3,NaN,NaN,NaN,NaN,25.0,NaN,09-Jun-2026
365,B09WD3WPF1,Pattex Contact Glue Premium - 650ml | Strong B...,BC0AK,Pattex,20000 Hardware,"20200 Sealants, Glues & Adhesives",B0GZLPDHJN,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
366,B09KCHS3PH,Pattex No More Nails Invisible | All Purpose H...,BC0AK,Pattex,30000 Building Material,30190 Other,B0F54L5BS7,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
367,B0969FQMXL,Pattex PL200 Construction Adhesive | Water-Bas...,BC0AK,Pattex,UNKNOWN,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026
368,B08MXBVG7Z,Henkel Pattex PL 100 Silicone (White),BC0AK,Pattex,20000 Hardware,UNKNOWN,B0GZLKSQBG,NaN,NaN,NaN,NaN,0.0,NaN,09-Jun-2026

### Merge invenotry and orders

In [36]:
import pandas as pd

# # Ensure Date columns are datetime
# inv_df["Date"] = pd.to_datetime(inv_df["Date"])
# final_df["Date"] = pd.to_datetime(final_df["Date"])

# Merge total_sales and total_units using ASIN + Date
inv_df = inv_df.merge(
    final_df[["ASIN", "Date", "total_sales", "total_units"]],
    on=["ASIN", "Date"],
    how="left"
)

# Fill NaNs
inv_df["total_sales"] = inv_df["total_sales"].fillna(0)
inv_df["total_units"] = inv_df["total_units"].fillna(0)

# Convert total_units to int
inv_df["total_units"] = inv_df["total_units"].astype(int)

In [37]:
inv_df['total_sales'] = (
    inv_df['total_sales']
    .astype(str)
    .str.replace('AED', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.strip()
)

inv_df['total_sales'] = pd.to_numeric(inv_df['total_sales'], errors='coerce').fillna(0)

In [38]:
inv_df['total_sales'].sum()

np.float64(26969.620000000003)

In [39]:
inv_df['total_units'] = inv_df['total_units'].fillna(0).astype(int)

In [40]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel,in_stock_flag,cumulative_instock_days,day_of_month,Instock Rate,total_sales,total_units
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,0,NaN,NaN,Vendor Central,1,1,1,100.0,0.0,0
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,0,NaN,NaN,Vendor Central,1,2,2,100.0,0.0,0
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,0,NaN,NaN,Vendor Central,1,3,3,100.0,0.0,0
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,0,NaN,NaN,Vendor Central,1,4,4,100.0,0.0,0
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 940.46,...,0,NaN,NaN,Vendor Central,1,5,5,100.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,4,AED -,AED -,Vendor Central,1,5,5,100.0,0.0,0
461,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,4,AED -,AED -,Vendor Central,1,6,6,100.0,0.0,0
462,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,4,AED -,AED -,Vendor Central,1,7,7,100.0,0.0,0
463,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,4,AED -,AED -,Vendor Central,1,8,8,100.0,0.0,0
464,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,4,AED -,AED -,Vendor Central,1,9,9,100.0,0.0,0

In [41]:
inv_df['total_units'].sum()

np.int64(1669)

### Last 90 day sale for sell through

In [42]:
final_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\pattex_sales_dec_to_feb_2026.csv",header=1)
# final_df = final_df[final_df["Brand"] != "Pritt"]

final_df.rename(columns= {'Product Title' : 'Product Name', 'Category' : 'Product Category', 'Subcategory': 'Product Sub Category', 'Shipped Revenue' : 'total_sales','Shipped Units' : 'quantity'},inplace= True)
final_df["quantity"] = (
    final_df["quantity"]
        .astype(str)                       # ensure string
        .str.replace(",", "", regex=False) # remove commas
        .pipe(pd.to_numeric, errors="coerce")  # convert to numeric
        .replace([np.inf, -np.inf], 0)     # handle infinity
        .fillna(0)                        # replace NaN with 0
        .astype(int)                      # convert to int
)
final_df['quantity'] = final_df['quantity'].fillna(0).astype(int)

In [43]:
final_df

,ASIN,Product Name,Brand,total_sales,Shipped COGS,quantity,Customer Returns
0,B09KCHLFH4,Pattex Sanitary Antimould Transparent Pressure...,Pattex,"AED 34,958.94","AED 29,778.04",847,25.0
1,B09KCFHH3T,"Pattex Super Glue Mini Dose, Strong All Purpos...",Pattex,"AED 31,675.90","AED 24,827.47",3952,39.0
2,B08W1WTZGB,Pattex PL 250 (Construction Adhesive) Is a pro...,Pattex,"AED 18,691.62","AED 28,686.95",652,32.0
3,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,Pattex,"AED 15,824.57","AED 13,233.67",1539,28.0
4,B09NKB9BJF,Pattex Sf525 Kitchen And Bath Premium Silicone...,Pattex,"AED 13,155.72","AED 19,210.57",787,21.0
5,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",Pattex,"AED 12,859.21","AED 9,787.86",1342,18.0
6,B0BG2Q17ZC,Pattex Power Epoxy Universal Syringe | With Co...,Pattex,"AED 11,417.49","AED 9,375.66",783,20.0
7,B09T3LRLBJ,"Pattex Wood Express, Quick-Drying Wood Glue, W...",Pattex,"AED 11,193.66","AED 9,301.77",580,9.0
8,B0DDGV3T5C,"Pattex Super Glue Power Gel Control,Flexible S...",Pattex,"AED 5,348.56","AED 4,726.50",200,1.0
9,B09KCG9FZT,Pattex No More Nails Strong & Easy | All Purpo...,Pattex,"AED 4,961.39","AED 3,965.82",335,4.0
10,B0DDGRGWDC,"Pattex No More Nails Invisible,Heavy-Duty Clea...",Pattex,"AED 4,529.16","AED 3,941.96",180,5.0
11,B0DDGWMTY5,"Pattex No More Nails Strong & Easy,Heavy-Duty ...",Pattex,"AED 4,513.50","AED 3,890.28",180,2.0
12,B09KCGX8G3,Pattex Repair Extreme Gel | All Purpose Clear ...,Pattex,"AED 3,410.35","AED 2,857.33",309,NaN
13,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",Pattex,"AED 3,198.74","AED 2,641.02",454,9.0
14,B09KCG5JZS,"Pattex Sanitary Antimould White Pressure Pack,...",Pattex,"AED 2,938.72","AED 2,199.03",69,1.0
15,B0DDGXBJW1,"Pattex Superglue Liquide Control,Clear Glue fo...",Pattex,"AED 2,410.85","AED 2,026.12",140,1.0
16,B0DDGRFJ5W,"Pattex Universal, Strong All Purpose Adhesive ...",PATTEX,"AED 2,129.26","AED 1,855.18",185,2.0
17,B0FKBLF14N,Pritt Original 4x11gm Gluestick Safe & Child-F...,UNKNOWN,"AED 2,043.28","AED 1,643.50",173,1.0
18,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,Henkel,"AED 1,732.78","AED 1,327.10",230,1.0
19,B09KCHS3PH,Pattex No More Nails Invisible | All Purpose H...,Pattex,"AED 1,696.96","AED 1,491.06",117,6.0
20,B0DDHF3MJM,"Pattex 5 Minutes Power Epoxy Glue,epoxy resin ...",Pattex,"AED 1,504.36","AED 1,337.57",41,NaN
21,B09T3MS698,Pattex Wood Express Bottle 12x75g,Pattex,"AED 1,401.18","AED 1,062.00",144,4.0
22,B08B4T7CXB,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,Pattex,"AED 1,386.49","AED 1,203.72",135,6.0
23,B08MXBVG7Z,Henkel Pattex PL 100 Silicone (White),Pattex,"AED 1,297.95","AED 1,119.72",39,1.0
24,B0DDGS2LRT,Pattex Super Glue All Plastics | Bonds All Dif...,Pattex,"AED 1,286.99","AED 1,150.59",43,NaN
25,B09M1MKKJG,Pattex Henkel Mounting Tape 120kg,Henkel,"AED 1,257.59","AED 1,215.90",88,NaN
26,B0DDGSGRP6,"Pattex Super Glue Mini Dose,Strong All Purpose...",Pattex,"AED 1,196.14","AED 1,212.96",71,1.0
27,B0DDGS87JD,"Pattex Superglue Liquide Control, Clear Glue f...",Pattex,"AED 1,021.68",AED 871.40,42,NaN
28,B0DDGY7RWR,"Pattex Super Glue Power Gel Tube, All Purpose ...",Pattex,AED 930.30,AED 811.04,47,3.0
29,B0FKBMWL53,Pritt Glue Stick Original BUNDLE 4x22g Safe & ...,UNKNOWN,AED 835.65,AED 652.50,45,NaN
30,B0BG2KWV13,Pattex Super Glue All Plastics | Bonds All Dif...,Pattex,AED 708.60,AED 545.57,60,NaN
31,B0DDGT2V9J,Pattex PL150 Structural Adhesive (White) | Hig...,Pattex,AED 551.45,AED 564.31,10,NaN
32,B0DDH1SCT4,"Pritt Rainbow Coloured Glue Sticks, Safe & Chi...",Pritt,AED 540.00,AED 459.04,16,1.0
33,B09KCFJ9SR,Pattex Repair 100% | All Purpose Super Glue Fo...,Pattex,AED 516.33,AED 444.82,19,NaN
34,B0DDGVFM3L,Pattex PL100 Construction Adhesive (White) | W...,Pattex,AED 357.18,AED 306.44,6,NaN
35,B09KCJS3SH,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",Pritt,AED 267.07,AED 245.14,17,NaN
36,B08Y917ZRH,Pattex Seal-Bond-Fill Silicone Sealant Constru...,Pattex,AED 247.60,AED 218.65,5,NaN
37,B0DDH2T3Q1,Pattex Repair Extreme Strong All Purpose Adhes...,Pattex,AED 201.21,AED 175.33,7,NaN
38,B09WD3WPF1,Pattex Contact Adhesive Premium 650ml,Pattex,AED 177.58,AED 250.45,5,NaN
39,B0DVYZDCWZ,Pritt Glue stick 6X11g Safe and Children Frien...,UNKNOWN,AED 151.80,AED 128.25,9,NaN
40,B0DDGXTBT6,Henkel Pattex Tube Classic 50g (pack of 3),Pattex,AED 146.50,AED 132.93,5,NaN
41,B08YY29KDM,"Pattex SL212 Silicone, 280 ml, White",Pattex,AED 142.43,AED 150.25,6,NaN
42,B0DDH9KH86,"Pattex SL212 Transparent Silicone, 280 ml (pac...",Pattex,AED 141.63,AED 170.00,4,NaN
43,B0DDH22GD2,"Pattex No More Nails Mounting Tape, All Purpos...",PATTEX,AED 129.97,AED 123.75,3,NaN
44,B0969FQMXL,Pattex PL 200 Tr 12x290g (GCC) Transparent,Pattex,AED 121.98,AED 114.50,3,NaN
45,B001P5IT7A,PRITT FUNCOLOR 4x10G BL INT (12,Pritt,AED 112.50,AED 95.64,6,1.0
46,B0DDH9NX2T,"Pritt Rainbow Coloured Glue Sticks,Safe&Child-...",Pritt,AED 47.81,AED 40.64,1,NaN
47,B08XRYVJ25,SILICONE ADHESIVE PL150 (YELLOW) 380ML PATTEX ...,Pattex,AED 24.81,AED 34.15,1,NaN
48,B0DDH8RK64,Pattex No More Nails Mounting Tape | All Purpo...,Pattex,AED 24.15,AED 26.25,1,NaN

In [44]:
final_df['sell_through'] = (final_df['quantity'] / 90).round(2)

In [45]:
missing_asins = (
    set(inv_df["ASIN"].unique())
    - set(final_df["ASIN"].unique())
)

missing_asins = list(missing_asins)

print("ASINs not found in result_df:")
print(missing_asins)

ASINs not found in result_df:
['B0DVZ67X85', 'B0GN2C54ZK', 'B0937WZHZV', 'B0GN246XDP', 'B0DDGWXNHC', 'B08XRX3PJX', 'B0DDGZBDG8']

In [46]:
inv_df = inv_df.merge(
    final_df[["ASIN", "sell_through"]],
    on="ASIN",
    how="left"
)
inv_df["sell_through"] = inv_df["sell_through"].fillna(0)

### DOS

In [47]:
import numpy as np

# inv_df['DOS'] = np.where(
#     inv_df['sell_through'] > 0,
#     np.ceil(inv_df['Available Inventory'] / inv_df['sell_through']),
#     0
# ).astype(int)

# import numpy as np
# inv_df['DOS'] = inv_df['Available Inventory'] / inv_df['sell_through']
# inv_df['DOS'] = inv_df['DOS'].astype(int)

inv_df['DOS'] = np.where(
                                inv_df['sell_through'] > 0.1,
                                inv_df['Available Inventory'] / inv_df['sell_through'],0)
inv_df['DOS'] = inv_df['DOS'].astype(int)

In [48]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,VC Ideal Price,Sales Channel,in_stock_flag,cumulative_instock_days,day_of_month,Instock Rate,total_sales,total_units,sell_through,DOS
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,Vendor Central,1,1,1,100.0,0.0,0,0.07,0
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,Vendor Central,1,2,2,100.0,0.0,0,0.07,0
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,Vendor Central,1,3,3,100.0,0.0,0,0.07,0
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,NaN,Vendor Central,1,4,4,100.0,0.0,0,0.07,0
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 940.46,...,NaN,Vendor Central,1,5,5,100.0,0.0,0,0.07,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED -,Vendor Central,1,5,5,100.0,0.0,0,0.00,0
461,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED -,Vendor Central,1,6,6,100.0,0.0,0,0.00,0
462,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED -,Vendor Central,1,7,7,100.0,0.0,0,0.00,0
463,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED -,Vendor Central,1,8,8,100.0,0.0,0,0.00,0
464,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,AED -,Vendor Central,1,9,9,100.0,0.0,0,0.00,0

### OOS Date

In [49]:
import pandas as pd
from datetime import date

# Create temporary datetime column for calculations
inv_df["Date_temp"] = pd.to_datetime(inv_df["Date"], format="%d-%b-%Y")

today = date.today()
curr_month = today.month
curr_year = today.year


def calculate_oos(group):
    group = group.sort_values("Date_temp").copy()

    # keep only current month/year
    month_df = group[
        (group["Date_temp"].dt.month == curr_month) &
        (group["Date_temp"].dt.year == curr_year)
    ].copy()

    if month_df.empty:
        return pd.Series(["Instock"] * len(group), index=group.index)

    latest_row = month_df.iloc[-1]
    latest_date = latest_row["Date_temp"]
    latest_inv = latest_row["Available Inventory"]

    # ---------- CASE 1 : CURRENT INVENTORY = 0 ----------
    if latest_inv == 0:

        prev_positive = month_df[
            (month_df["Date_temp"] < latest_date) &
            (month_df["Available Inventory"] > 0)
        ]

        if not prev_positive.empty:
            oos_date = prev_positive.iloc[-1]["Date_temp"] + pd.Timedelta(days=1)
        else:
            zero_rows = month_df[month_df["Available Inventory"] == 0]
            oos_date = zero_rows.iloc[0]["Date_temp"]

    # ---------- CASE 2 : CURRENT INVENTORY > 0 ----------
    else:
        sell_through = latest_row["sell_through"]

        if pd.notna(sell_through) and sell_through > 0:
            days = int(latest_inv // sell_through)
            oos_date = latest_date + pd.Timedelta(days=days)
        else:
            oos_date = "Instock"

    return pd.Series([oos_date] * len(group), index=group.index)


# Apply per ASIN
inv_df["OOS Date"] = inv_df.groupby("ASIN", group_keys=False).apply(calculate_oos)

# Convert OOS Date to same format (if it's a date)
inv_df["OOS Date"] = inv_df["OOS Date"].apply(
    lambda x: x.strftime("%d-%b-%Y") if isinstance(x, pd.Timestamp) else x
)

# Remove temporary column
inv_df.drop(columns=["Date_temp"], inplace=True)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_13064\1393960216.py:56: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  inv_df["OOS Date"] = inv_df.groupby("ASIN", group_keys=False).apply(calculate_oos)

In [50]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,Net Received,Net Received Units,Open POs,Receive Fill %,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Sales Channel,in_stock_flag,cumulative_instock_days,day_of_month,Instock Rate,total_sales,total_units,sell_through,DOS,OOS Date
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,Vendor Central,1,1,1,100.0,0.0,0,0.07,0,01-Jan-2028
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,Vendor Central,1,2,2,100.0,0.0,0,0.07,0,01-Jan-2028
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,Vendor Central,1,3,3,100.0,0.0,0,0.07,0,01-Jan-2028
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 972.34,...,Vendor Central,1,4,4,100.0,0.0,0,0.07,0,01-Jan-2028
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,AED 0.00,0,0,0.00%,0.0,AED 940.46,...,Vendor Central,1,5,5,100.0,0.0,0,0.07,0,01-Jan-2028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Vendor Central,1,5,5,100.0,0.0,0,0.00,0,Instock
461,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Vendor Central,1,6,6,100.0,0.0,0,0.00,0,Instock
462,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Vendor Central,1,7,7,100.0,0.0,0,0.00,0,Instock
463,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Vendor Central,1,8,8,100.0,0.0,0,0.00,0,Instock
464,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,AED 0.00,0,4,0.00%,0.0,AED 0.00,...,Vendor Central,1,9,9,100.0,0.0,0,0.00,0,Instock

### stock status

In [51]:
inv_df['min_available_qty'] = (inv_df['sell_through'] * 30).round(2)
inv_df['max_available_qty'] = (inv_df['sell_through'] * 60).round(2)

import numpy as np

conditions = [
    (inv_df['Available Inventory'] > inv_df['min_available_qty']) &
    (inv_df['Available Inventory'] <= inv_df['max_available_qty']),
    
    (inv_df['Available Inventory'] > inv_df['max_available_qty']),
    
    (inv_df['Available Inventory'] <= inv_df['min_available_qty'])
]

choices = [
    'Healthy',
    'Overstock',
    'Understock'
]

inv_df['Stock_Status'] = np.select(conditions, choices, default='Unknown')

In [52]:
inv_df['total_units'].sum()

np.int64(1669)

### OOS wt/wtout OPEN POs

In [53]:
inv_df['Open POs'] = pd.to_numeric(inv_df['Open POs'], errors='coerce')
inv_df['Open POs'] = inv_df['Open POs'].fillna(0)
inv_df['No/Low Stock wt Open POs'] = (
    (inv_df['Stock_Status'] == 'Understock') &
    (inv_df['Open POs'] > 0)
).astype(int)
inv_df['No/Low Stock wt no Open POs'] = (
    (inv_df['Stock_Status'] == 'Understock') &
    (inv_df['Open POs'] <= 0)
).astype(int)

In [54]:
inv_df.rename(columns= {'Net Received' : 'PO_received_amount', 'Net Received Units' : 'PO_received_Units', 'Receive Fill %': 'Receive_Fill_Rate', 'Unsellable On Hand Inventory': 'Unsellable On Hand Inventory Amount'},inplace= True)

In [55]:
cols_to_clean = [
    'PO_received_amount',
    'Aged 90+ Days Sellable Inventory',
    'Sellable Inventory Amount',
    'Unsellable On Hand Inventory Amount'
]

for col in cols_to_clean:
    inv_df[col] = (
        inv_df[col]
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.strip()
        .astype(float)
        .fillna(0)
    )

In [56]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,total_sales,total_units,sell_through,DOS,OOS Date,min_available_qty,max_available_qty,Stock_Status,No/Low Stock wt Open POs,No/Low Stock wt no Open POs
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,940.46,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
461,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
462,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
463,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
464,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0

## Clean the datafrmae before saving

In [57]:
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]

for col in cols_to_clean:
    inv_df[col] = (
        inv_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        .astype(float)
    )

In [58]:
# Create ASIN -> first Product Sub Category mapping
asin_map = (
    inv_df.dropna(subset=['Product Sub Category'])
      .drop_duplicates(subset=['ASIN'])
      .set_index('ASIN')['Product Sub Category']
)

# Fill missing Product sub Category
inv_df['Product Sub Category'] = inv_df['Product Sub Category'].fillna(inv_df['ASIN'].map(asin_map))

In [59]:
inv_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,total_sales,total_units,sell_through,DOS,OOS Date,min_available_qty,max_available_qty,Stock_Status,No/Low Stock wt Open POs,No/Low Stock wt no Open POs
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,972.34,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0,0,0.00%,0.0,940.46,...,0.0,0,0.07,0,01-Jan-2028,2.1,4.2,Overstock,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
461,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
462,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
463,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0
464,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.0,0,4,0.00%,0.0,0.00,...,0.0,0,0.00,0,Instock,0.0,0.0,Overstock,0,0

## Save the output inv Dataframe

In [60]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\output\pattex_inventory.csv"

df = pd.read_csv(file_path)

previous_rows = len(df)

# Temp column (DO NOT TOUCH ORIGINAL)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

today = pd.Timestamp.today().normalize()  # ✅ FIX
current_day = today.day

first_day_current_month = today.replace(day=1)  # now time = 00:00:00

# Logic
if current_day <= 3:
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    df = df[df['_temp_date'] < first_day_current_month]

current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare inv_df
inv_df['_temp_date'] = pd.to_datetime(inv_df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

rows_appended = len(inv_df)

# Append
df = pd.concat([df, inv_df], ignore_index=True)

final_rows = len(df)

# Remove temp column
df.drop(columns=['_temp_date'], inplace=True)

# Save
df.to_csv(file_path, index=False)

# Metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 7550
Current rows: 7137
Rows deleted: 413
Rows appended: 465
Final rows: 7602

### Save inventory dataframe

# Revenue

## save SPAP report

In [61]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product\Sponsored_Products_Advertised_product_report.xlsx"

# -------- BASE DESTINATION PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product"

# -------- GET TODAY DATE --------
today = datetime.today()

# If day is 1,2,3 → go to previous month
if today.day <= 3:
    if today.month == 1:
        month = 12
        year = today.year - 1
    else:
        month = today.month - 1
        year = today.year
else:
    month = today.month
    year = today.year
    
# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

month_name = month_map[month]  # folder name (lowercase)
# for file name (Mar)

# -------- CREATE FOLDER PATH --------
folder_path = os.path.join(base_path, str(year), month_name)

# Create folder if not exists
os.makedirs(folder_path, exist_ok=True)

# -------- READ FILE --------
df = pd.read_excel(source_file)

# -------- CREATE FILE NAME --------
file_name = f"Sponsored_Products_Advertised_product_report_{month_name}_{year}.xlsx"


# -------- SAVE FILE --------
save_path = os.path.join(folder_path, file_name)
df.to_excel(save_path, index=False)

print("File saved at:", save_path)

c:\Users\Shubham Verma\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product\2026\jun\Sponsored_Products_Advertised_product_report_jun_2026.xlsx

## save sb

In [62]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign\Sponsored_Brands_Campaign_report.xlsx"

# -------- BASE DESTINATION PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign"

# -------- GET TODAY DATE --------
today = datetime.today()

# If day is 1,2,3 → go to previous month
if today.day <= 3:
    if today.month == 1:
        month = 12
        year = today.year - 1
    else:
        month = today.month - 1
        year = today.year
else:
    month = today.month
    year = today.year
    
    
# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

month_name = month_map[month]  # folder name (lowercase)
# for file name (Mar)

# -------- CREATE FOLDER PATH --------
folder_path = os.path.join(base_path, str(year), month_name)

# Create folder if not exists
os.makedirs(folder_path, exist_ok=True)

# -------- READ FILE --------
df = pd.read_excel(source_file)

# -------- CREATE FILE NAME --------
file_name = f"Sponsored_Brands_Campaign_report_{month_name}_{year}.xlsx"

# -------- SAVE FILE --------
save_path = os.path.join(folder_path, file_name)
df.to_excel(save_path, index=False)

print("File saved at:", save_path)

c:\Users\Shubham Verma\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign\2026\jun\Sponsored_Brands_Campaign_report_jun_2026.xlsx

# Save SD

In [63]:
# SD IS NOT RUNNING

## Read ADS

In [64]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_df1 = pd.concat(dfs, ignore_index=True)

    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_df1.shape)

else:
    print("❌ No files found")
ads_df1["Date"] = pd.to_datetime(ads_df1["Date"]).dt.strftime("%d-%b-%Y")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product\2026\jun\Sponsored_Products_Advertised_product_report_jun_2026.xlsx
✅ Ads data loaded
Total files read: 1
Shape: (2035, 18)

In [65]:
ads_df1['Impressions'] = (
    ads_df1['Impressions']
    .astype(str)                # ensure everything is string
    .str.replace(',', '', regex=False)  # remove commas
    .str.strip()                # remove spaces
    .replace('', '0')           # handle empty values
    .astype(int)                # convert to integer
)

In [66]:
ads_df1

,Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Country,Advertised ASIN,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Spend,14 Day Total Sales,Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),14 Day Total Orders (#),14 Day Total Units (#),14 Day Conversion Rate
0,01-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B08B4T7CXB,0,0,NaN,NaN,0.00,0.00,NaN,NaN,0,0,NaN
1,01-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B09M1MKKJG,29,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2,02-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B09M1MKKJG,1,1,1.000000,1.810000,1.81,0.00,NaN,0.000000,0,0,0.000000
3,01-Jun-2026,No Portfolio,AED,PATTEX-SP-M(BD),Phrase,United Arab Emirates,B0BG2MZ1ZX,124,3,0.024194,0.336667,1.01,47.51,0.021259,47.039604,2,3,0.666667
4,02-Jun-2026,No Portfolio,AED,PATTEX-SP-M(BD),Phrase,United Arab Emirates,B0BG2MZ1ZX,169,2,0.011834,0.235000,0.47,20.50,0.022927,43.617021,1,1,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,04-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,32,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2031,05-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,25,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2032,06-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,22,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2033,01-Jun-2026,No Portfolio,AED,Pattex | Superglue | SP | Manual Exact,Brand Offence,United Arab Emirates,B09KCGX8G3,16,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2034,02-Jun-2026,No Portfolio,AED,Pattex | Superglue | SP | Manual Exact,Brand Offence,United Arab Emirates,B09KCGX8G3,6,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN

### Read SB report

In [67]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_df2 = pd.concat(dfs, ignore_index=True)

    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_df2.shape)

else:
    print("❌ No files found")
ads_df2["Date"] = pd.to_datetime(ads_df2["Date"]).dt.strftime("%d-%b-%Y")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign\2026\jun\Sponsored_Brands_Campaign_report_jun_2026.xlsx
✅ Ads data loaded
Total files read: 1
Shape: (108, 56)

In [68]:
ads_df2['Impressions'] = (
    ads_df2['Impressions']
    .astype(str)                # ensure everything is string
    .str.replace(',', '', regex=False)  # remove commas
    .str.strip()                # remove spaces
    .replace('', '0')           # handle empty values
    .astype(int)                # convert to integer
)

In [69]:
ads_df2

,Date,Portfolio name,Currency,Campaign Name,Cost type,Country,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),...,Brand Store page views,14 Day ATC,14 Day ATC Clicks,14 Day ATCR,Effective cost per Add to Cart (eCPATC),Branded Searches click-through conversions,Branded Searches Rate,Effective cost per Branded Search,Long-Term Sales,Long-Term ROAS
0,01-Jun-2026,No Portfolio,AED,PATTEX-SB-M(VPP),CPC,United Arab Emirates,5377,30,0.005579,3.423667,...,0,20,20,0.003720,5.135500,1,0.000186,102.710000,336.16,3.272904
1,02-Jun-2026,No Portfolio,AED,PATTEX-SB-M(VPP),CPC,United Arab Emirates,3679,17,0.004621,3.450588,...,0,6,6,0.001631,9.776667,0,0.000000,NaN,124.55,2.123253
2,03-Jun-2026,No Portfolio,AED,PATTEX-SB-M(VPP),CPC,United Arab Emirates,2578,21,0.008146,3.390952,...,0,8,8,0.003103,8.901250,0,0.000000,NaN,315.86,4.435613
3,04-Jun-2026,No Portfolio,AED,PATTEX-SB-M(VPP),CPC,United Arab Emirates,2246,20,0.008905,3.385000,...,4,4,4,0.001781,16.925000,12,0.005343,5.641667,82.30,1.215657
4,05-Jun-2026,No Portfolio,AED,PATTEX-SB-M(VPP),CPC,United Arab Emirates,2517,19,0.007549,3.818421,...,0,5,5,0.001986,14.510000,2,0.000795,36.275000,97.97,1.350379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,05-Jun-2026,No Portfolio,AED,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,CPC,United Arab Emirates,125,1,0.008000,4.020000,...,0,0,0,0.000000,NaN,0,0.000000,NaN,1.83,0.455224
104,06-Jun-2026,No Portfolio,AED,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,CPC,United Arab Emirates,115,0,0.000000,NaN,...,0,0,0,0.000000,NaN,0,0.000000,NaN,0.00,NaN
105,07-Jun-2026,No Portfolio,AED,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,CPC,United Arab Emirates,138,0,0.000000,NaN,...,0,0,0,0.000000,NaN,0,0.000000,NaN,0.00,NaN
106,08-Jun-2026,No Portfolio,AED,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,CPC,United Arab Emirates,111,0,0.000000,NaN,...,0,0,0,0.000000,NaN,0,0.000000,NaN,0.00,NaN
107,09-Jun-2026,No Portfolio,AED,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,CPC,United Arab Emirates,85,1,0.011765,3.600000,...,0,0,0,0.000000,NaN,0,0.000000,NaN,1.80,0.500000

In [70]:
ads_df1['14 Day Total Sales '].sum()

np.float64(17569.2)

In [71]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Display_product"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_df3 = pd.concat(dfs, ignore_index=True)
    ads_df3["Date"] = pd.to_datetime(ads_df3["Date"]).dt.strftime("%d-%b-%Y")
    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_df3.shape)

else:
    print("❌ No files found")

Months to read: [(2026, 6)]
❌ No files found

In [72]:
ads_df2['Impressions'] = (
    ads_df2['Impressions']
    .astype(str)                # ensure everything is string
    .str.replace(',', '', regex=False)  # remove commas
    .str.strip()                # remove spaces
    .replace('', '0')           # handle empty values
    .astype(int)                # convert to integer
)

In [73]:
ads_df2['14 Day Total Sales '].sum()

np.float64(3583.3399999999997)

### Rename cols in ads

In [74]:
# Rename columns
ads_df1 = ads_df1.rename(columns={
    "14 Day Total Sales ": "ads_sales",
    "14 Day Total Units (#)": "ads_unit_sold",
    "Advertised ASIN": "ASIN",
    "Spend" : "ads_spend"
})

# Select required columns
ads_df1 = ads_df1[["Date","ASIN", "ads_sales", "ads_unit_sold","ads_spend"]]
# Rename columns
ads_df2 = ads_df2.rename(columns={
    "14 Day Total Sales ": "ads_sales",
    "14 Day Total Units (#)": "ads_unit_sold",
    "Spend" : "ads_spend"
})

# Select required columns
ads_df2 = ads_df2[["Date", "ads_sales", "ads_unit_sold","ads_spend"]]
ads_df2["ASIN"] = "Sponsored Brand"

# # Rename columns
# ads_df3 = ads_df3.rename(columns={
#     "14 Day Total Sales ": "ads_sales",
#     "14 Day Total Units (#)": "ads_unit_sold",
#     "Advertised ASIN": "ASIN",
#     "Spend" : "ads_spend"
# })

# # Select required columns
# ads_df3 = ads_df3[["Date","ASIN", "ads_sales", "ads_unit_sold","ads_spend"]]

In [75]:
ads_df1

             Date        ASIN  ads_sales  ads_unit_sold  ads_spend
0     01-Jun-2026  B08B4T7CXB       0.00              0       0.00
1     01-Jun-2026  B09M1MKKJG       0.00              0       0.00
2     02-Jun-2026  B09M1MKKJG       0.00              0       1.81
3     01-Jun-2026  B0BG2MZ1ZX      47.51              3       1.01
4     02-Jun-2026  B0BG2MZ1ZX      20.50              1       0.47
...           ...         ...        ...            ...        ...
2030  04-Jun-2026  B09KCHLFH4       0.00              0       0.00
2031  05-Jun-2026  B09KCHLFH4       0.00              0       0.00
2032  06-Jun-2026  B09KCHLFH4       0.00              0       0.00
2033  01-Jun-2026  B09KCGX8G3       0.00              0       0.00
2034  02-Jun-2026  B09KCGX8G3       0.00              0       0.00

[2035 rows x 5 columns]

In [76]:
ads_df2

            Date  ads_sales  ads_unit_sold  ads_spend             ASIN
0    01-Jun-2026     273.16             10     102.71  Sponsored Brand
1    02-Jun-2026     102.14              4      58.66  Sponsored Brand
2    03-Jun-2026     277.08              7      71.21  Sponsored Brand
3    04-Jun-2026      49.55              2      67.70  Sponsored Brand
4    05-Jun-2026      64.84              4      72.55  Sponsored Brand
..           ...        ...            ...        ...              ...
103  05-Jun-2026       0.00              0       4.02  Sponsored Brand
104  06-Jun-2026       0.00              0       0.00  Sponsored Brand
105  07-Jun-2026       0.00              0       0.00  Sponsored Brand
106  08-Jun-2026       0.00              0       0.00  Sponsored Brand
107  09-Jun-2026       0.00              0       3.60  Sponsored Brand

[108 rows x 5 columns]

In [77]:
# ads_df = pd.concat([ads_df1, ads_df2,ads_df3], ignore_index=True)
ads_df = pd.concat([ads_df1, ads_df2], ignore_index=True)

In [78]:
ads_df

             Date             ASIN  ads_sales  ads_unit_sold  ads_spend
0     01-Jun-2026       B08B4T7CXB       0.00              0       0.00
1     01-Jun-2026       B09M1MKKJG       0.00              0       0.00
2     02-Jun-2026       B09M1MKKJG       0.00              0       1.81
3     01-Jun-2026       B0BG2MZ1ZX      47.51              3       1.01
4     02-Jun-2026       B0BG2MZ1ZX      20.50              1       0.47
...           ...              ...        ...            ...        ...
2138  05-Jun-2026  Sponsored Brand       0.00              0       4.02
2139  06-Jun-2026  Sponsored Brand       0.00              0       0.00
2140  07-Jun-2026  Sponsored Brand       0.00              0       0.00
2141  08-Jun-2026  Sponsored Brand       0.00              0       0.00
2142  09-Jun-2026  Sponsored Brand       0.00              0       3.60

[2143 rows x 5 columns]

In [79]:
ads_df['ads_sales'].sum()

np.float64(21152.54)

## They have different campaign soo that's why we grouped

In [80]:
ads_df["Date"] = pd.to_datetime(ads_df["Date"]).dt.normalize()
ads_grouped = (
    ads_df
    .groupby(["ASIN", "Date"], as_index=False)[["ads_sales", "ads_unit_sold","ads_spend"]]
    .sum()
)
ads_grouped["Date"] = pd.to_datetime(ads_grouped["Date"]).dt.strftime("%d-%b-%Y")

In [81]:
ads_grouped

                ASIN         Date  ads_sales  ads_unit_sold  ads_spend
0         B08B4T7CXB  01-Jun-2026      12.69              1      16.42
1         B08B4T7CXB  02-Jun-2026       0.00              0      15.76
2         B08B4T7CXB  03-Jun-2026      14.07              1      15.36
3         B08B4T7CXB  04-Jun-2026      10.48              1      13.90
4         B08B4T7CXB  05-Jun-2026      20.96              2      15.94
..               ...          ...        ...            ...        ...
329  Sponsored Brand  05-Jun-2026     242.88             19     149.32
330  Sponsored Brand  06-Jun-2026     694.41             34     189.38
331  Sponsored Brand  07-Jun-2026     339.83             19     207.27
332  Sponsored Brand  08-Jun-2026     410.08             20     129.08
333  Sponsored Brand  09-Jun-2026     313.85             25     136.24

[334 rows x 5 columns]

In [82]:
ads_df['ads_unit_sold'].sum()

np.int64(1351)

### Merge ads, inv and sale for revenue page

In [83]:
inv_df["ASIN"] = inv_df["ASIN"].astype(str).str.strip().str.upper()
ads_grouped["ASIN"] = ads_grouped["ASIN"].astype(str).str.strip().str.upper()   


merged_df = inv_df.merge(
    ads_grouped,
    on=["ASIN", "Date"],
    how="outer"
)

In [84]:
merged_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,OOS Date,min_available_qty,max_available_qty,Stock_Status,No/Low Stock wt Open POs,No/Low Stock wt no Open POs,_temp_date,ads_sales,ads_unit_sold,ads_spend
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-01,NaN,NaN,NaN
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-02,NaN,NaN,NaN
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-03,NaN,NaN,NaN
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-04,NaN,NaN,NaN
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-05,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,242.88,19.0,149.32
517,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,694.41,34.0,189.38
518,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,339.83,19.0,207.27
519,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,410.08,20.0,129.08
520,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,313.85,25.0,136.24

### Check all KPIs

In [85]:
merged_df['total_sales'].sum()

np.float64(26969.62)

In [86]:
merged_df['ads_sales'].sum()

np.float64(21152.54)

In [87]:
merged_df['total_units'].sum()

np.float64(1669.0)

In [88]:
merged_df['ads_unit_sold'].sum()

np.float64(1351.0)

In [89]:
merged_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,OOS Date,min_available_qty,max_available_qty,Stock_Status,No/Low Stock wt Open POs,No/Low Stock wt no Open POs,_temp_date,ads_sales,ads_unit_sold,ads_spend
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-01,NaN,NaN,NaN
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-02,NaN,NaN,NaN
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-03,NaN,NaN,NaN
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-04,NaN,NaN,NaN
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,01-Jan-2028,2.1,4.2,Overstock,0.0,0.0,2026-06-05,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,242.88,19.0,149.32
517,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,694.41,34.0,189.38
518,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,339.83,19.0,207.27
519,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,410.08,20.0,129.08
520,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,313.85,25.0,136.24

### Create organic revenue column

In [90]:
merged_df['total_sales'] = merged_df['total_sales'].fillna(0)
merged_df['ads_sales'] = merged_df['ads_sales'].fillna(0)

merged_df['organic_sale'] = (merged_df['total_sales'] - merged_df['ads_sales']).round(2)
merged_df['ads_spend'] = merged_df['ads_spend'].round(2)
merged_df['organic_sale'].sum()

np.float64(5817.080000000001)

In [91]:
merged_df['ads_spend'].sum()

np.float64(10419.810000000001)

In [92]:
merged_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,min_available_qty,max_available_qty,Stock_Status,No/Low Stock wt Open POs,No/Low Stock wt no Open POs,_temp_date,ads_sales,ads_unit_sold,ads_spend,organic_sale
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,2.1,4.2,Overstock,0.0,0.0,2026-06-01,0.00,NaN,NaN,0.00
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,2.1,4.2,Overstock,0.0,0.0,2026-06-02,0.00,NaN,NaN,0.00
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,2.1,4.2,Overstock,0.0,0.0,2026-06-03,0.00,NaN,NaN,0.00
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,2.1,4.2,Overstock,0.0,0.0,2026-06-04,0.00,NaN,NaN,0.00
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,2.1,4.2,Overstock,0.0,0.0,2026-06-05,0.00,NaN,NaN,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,242.88,19.0,149.32,-242.88
517,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,694.41,34.0,189.38,-694.41
518,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,339.83,19.0,207.27,-339.83
519,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,410.08,20.0,129.08,-410.08
520,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaT,313.85,25.0,136.24,-313.85

In [93]:
len(merged_df.columns)

42

In [94]:
merged_df = merged_df.drop(columns=['Product Name', 'Product Category', 'Pack Type', 'Pack Size',  'SC Ideal Price', 'VC Ideal Price'])

In [95]:
import pandas as pd

# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")

# Convert ASIN to uppercase in both
merged_df["ASIN"] = merged_df["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
merged_df = merged_df.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
merged_df["Pack Size"] = merged_df["Pack Size"].fillna(0).astype(int)
cols_to_fill = ["Product Name", "Category", "Pack Type", "Pack Size", "SC Ideal Price", "VC Ideal Price"]
merged_df[cols_to_fill] = merged_df[cols_to_fill].astype(str)

merged_df.loc[merged_df["ASIN"] == "SPONSORED BRAND", cols_to_fill] = "SPONSORED BRAND"

merged_df.rename(columns= {'Category' : 'Product Category'},inplace= True)

print("Merge completed ✅")

Merge completed ✅

In [96]:
# Create ASIN -> first Product Sub Category mapping
asin_map = (
    merged_df.dropna(subset=['Product Sub Category'])
      .drop_duplicates(subset=['ASIN'])
      .set_index('ASIN')['Product Sub Category']
)

# Fill missing Product sub Category
merged_df['Product Sub Category'] = merged_df['Product Sub Category'].fillna(merged_df['ASIN'].map(asin_map))

In [97]:

cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]

for col in cols_to_clean:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )

In [98]:
merged_df['Brand'] = "Pattex"
merged_df['Sales Channel'] = "Vendor Central"
cols = [
    "Product Name",
    "Product Category",
    "Product Sub Category",
    "Pack Type"
]

merged_df[cols] = merged_df[cols].fillna("Unavailable")
merged_df = merged_df.fillna(0)

In [99]:
merged_df[["SC Ideal Price", "VC Ideal Price"]] = (
    merged_df[["SC Ideal Price", "VC Ideal Price"]]
    .replace(['nan', 'NaN', None], 0)
    .fillna(0)
)

In [100]:
merged_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,ads_sales,ads_unit_sold,ads_spend,organic_sale,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.00,0.0,0.00,0.00,nan,nan,nan,0,0,0
1,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.00,0.0,0.00,0.00,nan,nan,nan,0,0,0
2,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.00,0.0,0.00,0.00,nan,nan,nan,0,0,0
3,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.00,0.0,0.00,0.00,nan,nan,nan,0,0,0
4,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,0.00,0.0,0.00,0.00,nan,nan,nan,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,242.88,19.0,149.32,-242.88,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
517,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,694.41,34.0,189.38,-694.41,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
518,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,339.83,19.0,207.27,-339.83,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
519,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,410.08,20.0,129.08,-410.08,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
520,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,313.85,25.0,136.24,-313.85,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND

## Save correct format of revenue page

In [101]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\output\pattex_revenue.csv"

# Read existing CSV
df = pd.read_csv(file_path)

previous_rows = len(df)

# Create temp date column (DO NOT TOUCH ORIGINAL)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

# Today's normalized date
today = pd.Timestamp.today().normalize()
current_day = today.day

# First day of current month (no time)
first_day_current_month = today.replace(day=1)

# Apply logic
if current_day <= 3:
    # Keep only <= last day of previous-to-previous month
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    # Remove current month data
    df = df[df['_temp_date'] < first_day_current_month]

# Metrics after deletion
current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare merged_df
merged_df['_temp_date'] = pd.to_datetime(merged_df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

rows_appended = len(merged_df)

# Append new data
df = pd.concat([df, merged_df], ignore_index=True)

final_rows = len(df)

# Drop temp column before saving
df.drop(columns=['_temp_date'], inplace=True)

# Save back
df.to_csv(file_path, index=False)

# Print metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 8754
Current rows: 8291
Rows deleted: 463
Rows appended: 521
Final rows: 8812

# Marketing

## Read SPAP report

In [102]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_spap = pd.concat(dfs, ignore_index=True)

    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_spap.shape)

else:
    print("❌ No files found")
ads_spap["Date"] = pd.to_datetime(ads_spap["Date"]).dt.strftime("%d-%b-%Y")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Advertised_Product\2026\jun\Sponsored_Products_Advertised_product_report_jun_2026.xlsx
✅ Ads data loaded
Total files read: 1
Shape: (2035, 18)

In [103]:
ads_spap

,Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Country,Advertised ASIN,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Spend,14 Day Total Sales,Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),14 Day Total Orders (#),14 Day Total Units (#),14 Day Conversion Rate
0,01-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B08B4T7CXB,0,0,NaN,NaN,0.00,0.00,NaN,NaN,0,0,NaN
1,01-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B09M1MKKJG,29,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2,02-Jun-2026,No Portfolio,AED,Pattex | SP | Mounting Tape | Manual Phrase,Generic | Phrase,United Arab Emirates,B09M1MKKJG,1,1,1.000000,1.810000,1.81,0.00,NaN,0.000000,0,0,0.000000
3,01-Jun-2026,No Portfolio,AED,PATTEX-SP-M(BD),Phrase,United Arab Emirates,B0BG2MZ1ZX,124,3,0.024194,0.336667,1.01,47.51,0.021259,47.039604,2,3,0.666667
4,02-Jun-2026,No Portfolio,AED,PATTEX-SP-M(BD),Phrase,United Arab Emirates,B0BG2MZ1ZX,169,2,0.011834,0.235000,0.47,20.50,0.022927,43.617021,1,1,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,04-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,32,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2031,05-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,25,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2032,06-Jun-2026,No Portfolio,AED,Pattex | SP | Pressure Pack | Manual Exact,Generic Use Case KWs,United Arab Emirates,B09KCHLFH4,22,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2033,01-Jun-2026,No Portfolio,AED,Pattex | Superglue | SP | Manual Exact,Brand Offence,United Arab Emirates,B09KCGX8G3,16,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN
2034,02-Jun-2026,No Portfolio,AED,Pattex | Superglue | SP | Manual Exact,Brand Offence,United Arab Emirates,B09KCGX8G3,6,0,0.000000,NaN,0.00,0.00,NaN,NaN,0,0,NaN

In [104]:
ads_spap['Campaign Name'] = ads_spap['Campaign Name'].fillna('Unavailable')
ads_spap['Portfolio name'] = ads_spap['Portfolio name'].fillna('No Portfolio')

In [105]:

ads_spap['Impressions'] = (
    ads_spap['Impressions']
    .astype(str)                # ensure everything is string
    .str.replace(',', '', regex=False)  # remove commas
    .str.strip()                # remove spaces
    .replace('', '0')           # handle empty values
    .astype(int)                # convert to integer
)

In [106]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_sb = pd.concat(dfs, ignore_index=True)

    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_sb.shape)

else:
    print("❌ No files found")
ads_sb["Date"] = pd.to_datetime(ads_sb["Date"]).dt.strftime("%d-%b-%Y")

Months to read: [(2026, 6)]
Reading: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Brand_campaign\2026\jun\Sponsored_Brands_Campaign_report_jun_2026.xlsx
✅ Ads data loaded
Total files read: 1
Shape: (108, 56)

In [107]:
ads_sb['Campaign Name'] = ads_sb['Campaign Name'].fillna('Unavailable')
ads_sb['Portfolio name'] = ads_sb['Portfolio name'].fillna('No Portfolio')

In [108]:
ads_sb['Impressions'] = (
    ads_sb['Impressions']
    .astype(str)                # ensure everything is string
    .str.replace(',', '', regex=False)  # remove commas
    .str.strip()                # remove spaces
    .replace('', '0')           # handle empty values
    .astype(int)                # convert to integer
)

In [109]:
import os
import pandas as pd
from datetime import datetime, timedelta
import calendar

# -------- BASE PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\input\Display_product"

dfs = []

# -------- TODAY DATE --------
today = datetime.today()
day = today.day
current_month = today.month
current_year = today.year

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE MONTHS --------
months_to_read = []

if day <= 3:
    months_to_read.append((prev_year, prev_month))
    months_to_read.append((current_year, current_month))
else:
    months_to_read.append((current_year, current_month))

print("Months to read:", months_to_read)

# -------- READ FILES --------
for year, month in months_to_read:

    year_path = os.path.join(base_path, str(year))
    if not os.path.exists(year_path):
        continue

    # Convert month → jan/feb/mar
    month_name = calendar.month_abbr[month].lower()

    month_path = os.path.join(year_path, month_name)
    if not os.path.exists(month_path):
        continue

    for file in os.listdir(month_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(month_path, file)
            print("Reading:", file_path)

            df = pd.read_excel(file_path)
            dfs.append(df)

# -------- COMBINE --------
if dfs:
    ads_sd = pd.concat(dfs, ignore_index=True)
    ads_sd["Date"] = pd.to_datetime(ads_df3["Date"]).dt.strftime("%d-%b-%Y")
    # -------- FORMAT DATE --------

    print("✅ Ads data loaded")
    print("Total files read:", len(dfs))
    print("Shape:", ads_sd.shape)

else:
    print("❌ No files found")

Months to read: [(2026, 6)]
❌ No files found

In [110]:
# ads_sd['Impressions'] = (
#     ads_sd['Impressions']
#     .astype(str)                # ensure everything is string
#     .str.replace(',', '', regex=False)  # remove commas
#     .str.strip()                # remove spaces
#     .replace('', '0')           # handle empty values
#     .astype(int)                # convert to integer
# )

### Read SB report

### Rename SPAP and SB

In [111]:
# Rename columns
ads_spap = ads_spap.rename(columns={
    "14 Day Total Sales ": "ads_sales",
    "14 Day Total Units (#)": "ads_unit_sold",
    "Advertised ASIN": "ASIN",
    "Spend" : "ads_spend",
    "14 Day Conversion Rate": "CVR"
})

# Select required columns
ads_spap = ads_spap[["Date","ASIN", "ads_sales", "ads_unit_sold","ads_spend","Campaign Name","Impressions", "Clicks", "Click-Thru Rate (CTR)", "Cost Per Click (CPC)"
                     , "Total Advertising Cost of Sales (ACOS) ", "Total Return on Advertising Spend (ROAS)","CVR", "Portfolio name"]]

# Rename columns
ads_sb = ads_sb.rename(columns={
    "14 Day Total Sales ": "ads_sales",
    "14 Day Total Units (#)": "ads_unit_sold",
    "Advertised ASIN": "ASIN",
    "Spend" : "ads_spend",
    "14 Day Conversion Rate": "CVR"
    })

# Select required columns
ads_sb = ads_sb[["Date", "ads_sales", "ads_unit_sold","ads_spend","Campaign Name","Impressions", "Clicks", "Click-Thru Rate (CTR)", "Cost Per Click (CPC)"
                     , "Total Advertising Cost of Sales (ACOS) ", "Total Return on Advertising Spend (ROAS)","CVR", "Portfolio name"]]
ads_sb['ASIN'] = 'Sponsored Brand'
# ads_sd = ads_sd.rename(columns={
#     "14 Day Total Sales ": "ads_sales",
#     "14 Day Total Units (#)": "ads_unit_sold",
#     "Advertised ASIN": "ASIN",
#     "Spend" : "ads_spend",
    
# })

# # Select required columns
# ads_sd = ads_sd[["Date","ASIN", "ads_sales", "ads_unit_sold","ads_spend","Campaign Name","Impressions", "Clicks", "Click-Thru Rate (CTR)", "Cost Per Click (CPC)"
#                      , "Total Advertising Cost of Sales (ACOS) ", "Total Return on Advertising Spend (ROAS)","Portfolio name"]]


ads_spap['Campaign Type'] = "SP"
ads_sb['Campaign Type'] = "SB"
# ads_sd['Campaign Type'] = "SD"

In [112]:
ads_spap

,Date,ASIN,ads_sales,ads_unit_sold,ads_spend,Campaign Name,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Portfolio name,Campaign Type
0,01-Jun-2026,B08B4T7CXB,0.00,0,0.00,Pattex | SP | Mounting Tape | Manual Phrase,0,0,NaN,NaN,NaN,NaN,NaN,No Portfolio,SP
1,01-Jun-2026,B09M1MKKJG,0.00,0,0.00,Pattex | SP | Mounting Tape | Manual Phrase,29,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2,02-Jun-2026,B09M1MKKJG,0.00,0,1.81,Pattex | SP | Mounting Tape | Manual Phrase,1,1,1.000000,1.810000,NaN,0.000000,0.000000,No Portfolio,SP
3,01-Jun-2026,B0BG2MZ1ZX,47.51,3,1.01,PATTEX-SP-M(BD),124,3,0.024194,0.336667,0.021259,47.039604,0.666667,No Portfolio,SP
4,02-Jun-2026,B0BG2MZ1ZX,20.50,1,0.47,PATTEX-SP-M(BD),169,2,0.011834,0.235000,0.022927,43.617021,0.500000,No Portfolio,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,04-Jun-2026,B09KCHLFH4,0.00,0,0.00,Pattex | SP | Pressure Pack | Manual Exact,32,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2031,05-Jun-2026,B09KCHLFH4,0.00,0,0.00,Pattex | SP | Pressure Pack | Manual Exact,25,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2032,06-Jun-2026,B09KCHLFH4,0.00,0,0.00,Pattex | SP | Pressure Pack | Manual Exact,22,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2033,01-Jun-2026,B09KCGX8G3,0.00,0,0.00,Pattex | Superglue | SP | Manual Exact,16,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2034,02-Jun-2026,B09KCGX8G3,0.00,0,0.00,Pattex | Superglue | SP | Manual Exact,6,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP

In [113]:
ads_sb

,Date,ads_sales,ads_unit_sold,ads_spend,Campaign Name,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Portfolio name,ASIN,Campaign Type
0,01-Jun-2026,273.16,10,102.71,PATTEX-SB-M(VPP),5377,30,0.005579,3.423667,0.376007,2.659527,0.300000,No Portfolio,Sponsored Brand,SB
1,02-Jun-2026,102.14,4,58.66,PATTEX-SB-M(VPP),3679,17,0.004621,3.450588,0.574310,1.741221,0.235294,No Portfolio,Sponsored Brand,SB
2,03-Jun-2026,277.08,7,71.21,PATTEX-SB-M(VPP),2578,21,0.008146,3.390952,0.257002,3.891027,0.285714,No Portfolio,Sponsored Brand,SB
3,04-Jun-2026,49.55,2,67.70,PATTEX-SB-M(VPP),2246,20,0.008905,3.385000,1.366297,0.731905,0.100000,No Portfolio,Sponsored Brand,SB
4,05-Jun-2026,64.84,4,72.55,PATTEX-SB-M(VPP),2517,19,0.007549,3.818421,1.118908,0.893728,0.210526,No Portfolio,Sponsored Brand,SB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,05-Jun-2026,0.00,0,4.02,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,125,1,0.008000,4.020000,NaN,0.000000,0.000000,No Portfolio,Sponsored Brand,SB
104,06-Jun-2026,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,115,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,Sponsored Brand,SB
105,07-Jun-2026,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,138,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,Sponsored Brand,SB
106,08-Jun-2026,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,111,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,Sponsored Brand,SB
107,09-Jun-2026,0.00,0,3.60,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,85,1,0.011765,3.600000,NaN,0.000000,0.000000,No Portfolio,Sponsored Brand,SB

In [114]:
# ads_df = pd.concat([ads_spap, ads_sb, ads_sd], ignore_index=True)
ads_df = pd.concat([ads_spap, ads_sb], ignore_index=True)

In [115]:
ads_df

,Date,ASIN,ads_sales,ads_unit_sold,ads_spend,Campaign Name,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Portfolio name,Campaign Type
0,01-Jun-2026,B08B4T7CXB,0.00,0,0.00,Pattex | SP | Mounting Tape | Manual Phrase,0,0,NaN,NaN,NaN,NaN,NaN,No Portfolio,SP
1,01-Jun-2026,B09M1MKKJG,0.00,0,0.00,Pattex | SP | Mounting Tape | Manual Phrase,29,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SP
2,02-Jun-2026,B09M1MKKJG,0.00,0,1.81,Pattex | SP | Mounting Tape | Manual Phrase,1,1,1.000000,1.810000,NaN,0.000000,0.000000,No Portfolio,SP
3,01-Jun-2026,B0BG2MZ1ZX,47.51,3,1.01,PATTEX-SP-M(BD),124,3,0.024194,0.336667,0.021259,47.039604,0.666667,No Portfolio,SP
4,02-Jun-2026,B0BG2MZ1ZX,20.50,1,0.47,PATTEX-SP-M(BD),169,2,0.011834,0.235000,0.022927,43.617021,0.500000,No Portfolio,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,05-Jun-2026,Sponsored Brand,0.00,0,4.02,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,125,1,0.008000,4.020000,NaN,0.000000,0.000000,No Portfolio,SB
2139,06-Jun-2026,Sponsored Brand,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,115,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SB
2140,07-Jun-2026,Sponsored Brand,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,138,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SB
2141,08-Jun-2026,Sponsored Brand,0.00,0,0.00,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,111,0,0.000000,NaN,NaN,NaN,NaN,No Portfolio,SB
2142,09-Jun-2026,Sponsored Brand,0.00,0,3.60,PATTEX | SBV | Wood Glue | CPC | G+BD+BO,85,1,0.011765,3.600000,NaN,0.000000,0.000000,No Portfolio,SB

In [116]:
ads_df.columns

Index(['Date', 'ASIN', 'ads_sales', 'ads_unit_sold', 'ads_spend',
       'Campaign Name', 'Impressions', 'Clicks', 'Click-Thru Rate (CTR)',
       'Cost Per Click (CPC)', 'Total Advertising Cost of Sales (ACOS) ',
       'Total Return on Advertising Spend (ROAS)', 'CVR', 'Portfolio name',
       'Campaign Type'],
      dtype='object')

In [117]:
grouped_df = ads_df.groupby(['ASIN', 'Date'], as_index=False).agg({
    'ads_sales': 'sum',
    'ads_unit_sold': 'sum',
    'ads_spend': 'sum',
    'Impressions': 'sum',
    'Clicks': 'sum',

    # Remaining metric columns
    'Click-Thru Rate (CTR)': 'sum',
    'Cost Per Click (CPC)': 'sum',
    'Total Advertising Cost of Sales (ACOS) ': 'sum',
    'Total Return on Advertising Spend (ROAS)': 'sum',
    'CVR': 'sum',

    # Text columns
    'Campaign Name': 'first',
    'Campaign Type': 'first',
    'Portfolio name': 'first'
})

In [118]:
grouped_df

,ASIN,Date,ads_sales,ads_unit_sold,ads_spend,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Campaign Name,Campaign Type,Portfolio name
0,B08B4T7CXB,01-Jun-2026,12.69,1,16.42,777,5,0.006831,3.284000,1.293932,0.772838,0.200000,Pattex | SP | Mounting Tape | Manual Phrase,SP,No Portfolio
1,B08B4T7CXB,02-Jun-2026,0.00,0,15.76,824,3,0.003831,5.253333,0.000000,0.000000,0.000000,PATTEX-SP-M(BD),SP,No Portfolio
2,B08B4T7CXB,03-Jun-2026,14.07,1,15.36,727,4,0.005970,3.840000,1.091684,0.916016,0.250000,PATTEX-SP-M(BD),SP,No Portfolio
3,B08B4T7CXB,04-Jun-2026,10.48,1,13.90,694,4,0.006154,3.475000,1.326336,0.753957,0.250000,PATTEX-SP-M(BD),SP,No Portfolio
4,B08B4T7CXB,05-Jun-2026,20.96,2,15.94,765,8,0.038586,2.277143,0.760496,1.314931,0.142857,PATTEX-SP-M(BD),SP,No Portfolio
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,Sponsored Brand,05-Jun-2026,242.88,19,149.32,5101,52,0.118137,25.816569,1.417380,4.244124,0.543860,PATTEX-SB-M(VPP),SB,No Portfolio
330,Sponsored Brand,06-Jun-2026,694.41,34,189.38,6304,72,0.108721,15.308727,1.074709,20.743605,3.110806,PATTEX-SB-M(VPP),SB,No Portfolio
331,Sponsored Brand,07-Jun-2026,339.83,19,207.27,7538,69,0.057766,16.782164,1.099305,3.807633,0.443277,PATTEX-SB-M(VPP),SB,No Portfolio
332,Sponsored Brand,08-Jun-2026,410.08,20,129.08,6448,58,0.062265,15.589474,1.129090,8.780352,1.128289,PATTEX-SB-M(VPP),SB,No Portfolio
333,Sponsored Brand,09-Jun-2026,313.85,25,136.24,6110,50,0.088999,20.088835,1.800968,14.711544,2.720644,PATTEX-SB-M(VPP),SB,No Portfolio

In [119]:
grouped_df['Impressions'].sum()

np.int64(241627)

In [120]:
inv_df["ASIN"] = inv_df["ASIN"].astype(str).str.strip().str.upper()
grouped_df["ASIN"] = grouped_df["ASIN"].astype(str).str.strip().str.upper()   


marketing_df = inv_df.merge(
    grouped_df,
    on=["ASIN", "Date"],
    how="outer"
)

### Marketing dataframe

In [121]:
marketing_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Campaign Name,Campaign Type,Portfolio name
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5101.0,52.0,0.118137,25.816569,1.417380,4.244124,0.543860,PATTEX-SB-M(VPP),SB,No Portfolio
517,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6304.0,72.0,0.108721,15.308727,1.074709,20.743605,3.110806,PATTEX-SB-M(VPP),SB,No Portfolio
518,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7538.0,69.0,0.057766,16.782164,1.099305,3.807633,0.443277,PATTEX-SB-M(VPP),SB,No Portfolio
519,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6448.0,58.0,0.062265,15.589474,1.129090,8.780352,1.128289,PATTEX-SB-M(VPP),SB,No Portfolio
520,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6110.0,50.0,0.088999,20.088835,1.800968,14.711544,2.720644,PATTEX-SB-M(VPP),SB,No Portfolio

In [122]:
marketing_df = marketing_df.drop(columns=['Product Name', 'Product Category', 'Pack Type', 'Pack Size',  'SC Ideal Price', 'VC Ideal Price'])

In [123]:
import pandas as pd
# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")

# Convert ASIN to uppercase in both
marketing_df["ASIN"] = marketing_df["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
marketing_df = marketing_df.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
marketing_df["Pack Size"] = marketing_df["Pack Size"].fillna(0).astype(int)
cols_to_fill = ["Product Name", "Category", "Pack Type", "Pack Size", "SC Ideal Price", "VC Ideal Price"]
marketing_df[cols_to_fill] = marketing_df[cols_to_fill].astype(str)
marketing_df.loc[marketing_df["ASIN"] == "SPONSORED BRAND", cols_to_fill] = "SPONSORED BRAND"

marketing_df.rename(columns= {'Category' : 'Product Category'},inplace= True)

print("Merge completed ✅")

Merge completed ✅

In [124]:
marketing_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,CVR,Campaign Name,Campaign Type,Portfolio name,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,nan,nan,nan,0,nan,nan
1,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,nan,nan,nan,0,nan,nan
2,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,nan,nan,nan,0,nan,nan
3,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,NaN,NaN,NaN,NaN,nan,nan,nan,0,nan,nan
4,B001P5IT7A,Pritt,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,NaN,NaN,NaN,NaN,nan,nan,nan,0,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.543860,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
517,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.110806,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
518,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.443277,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
519,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.128289,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
520,SPONSORED BRAND,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.720644,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND

In [125]:
# Create ASIN -> first Product Sub Category mapping
asin_map = (
    marketing_df.dropna(subset=['Product Sub Category'])
      .drop_duplicates(subset=['ASIN'])
      .set_index('ASIN')['Product Sub Category']
)

# Fill missing Product sub Category
marketing_df['Product Sub Category'] = marketing_df['Product Sub Category'].fillna(marketing_df['ASIN'].map(asin_map))
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]

for col in cols_to_clean:
    marketing_df[col] = (
        marketing_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )
marketing_df['Brand'] = "Pattex"
marketing_df['Sales Channel'] = "Vendor Central"
cols = [
    "Product Name",
    "Product Category",
    "Product Sub Category",
    "Pack Type"
]

marketing_df[cols] = marketing_df[cols].fillna("Unavailable")
marketing_df = marketing_df.fillna(0)

In [126]:
marketing_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,CVR,Campaign Name,Campaign Type,Portfolio name,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,nan,nan
1,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,nan,nan
2,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,nan,nan
3,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,nan,nan
4,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,0.000000,0,0,0,nan,nan,nan,0,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,0.543860,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
517,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,3.110806,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
518,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,0.443277,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
519,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,1.128289,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
520,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,2.720644,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND

### Save marketing DataFrame

In [127]:
# marketing_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\output\pattex_marketing.csv",index = False)

In [128]:
marketing_df[["SC Ideal Price", "VC Ideal Price"]] = (
    marketing_df[["SC Ideal Price", "VC Ideal Price"]]
    .replace(['nan', 'NaN', None], 0)
    .fillna(0)
)

In [129]:
marketing_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,CVR,Campaign Name,Campaign Type,Portfolio name,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,0,0
1,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,0,0
2,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,0,0
3,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,972.34,...,0.000000,0,0,0,nan,nan,nan,0,0,0
4,B001P5IT7A,Pattex,6070 Glue & Adhesives,0.00%,0.0,0.0,0.0,0.00%,0.0,940.46,...,0.000000,0,0,0,nan,nan,nan,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,0.543860,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
517,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,3.110806,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
518,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,0.443277,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
519,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,1.128289,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND
520,SPONSORED BRAND,Pattex,Unavailable,0,0.0,0.0,0.0,0,0.0,0.00,...,2.720644,PATTEX-SB-M(VPP),SB,No Portfolio,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND,SPONSORED BRAND

## Save marketing dataframe

In [130]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\output\pattex_marketing.csv"

# Read existing CSV
df = pd.read_csv(file_path)

previous_rows = len(df)

# Create temp column (DO NOT modify original Date)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

# Get today's date (normalized)
today = pd.Timestamp.today().normalize()
current_day = today.day

# First day of current month (00:00:00)
first_day_current_month = today.replace(day=1)

# Apply logic
if current_day <= 3:
    # Keep only <= last day of previous-to-previous month
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    # Remove current month data
    df = df[df['_temp_date'] < first_day_current_month]

# Metrics after deletion
current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare marketing_df
marketing_df['_temp_date'] = pd.to_datetime(marketing_df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

rows_appended = len(marketing_df)

# Append new data
df = pd.concat([df, marketing_df], ignore_index=True)

final_rows = len(df)

# Drop temp column before saving
df.drop(columns=['_temp_date'], inplace=True)

# Save back to same file
df.to_csv(file_path, index=False)

# Print metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 8754
Current rows: 8291
Rows deleted: 463
Rows appended: 521
Final rows: 8812

# BuyBox

## Buybox Scrapping

In [1]:
import os
import time
import random
import datetime
import pandas as pd

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import selenium.common.exceptions as se

# ==============================
# INPUT FILE
# ==============================

INPUT_FILE = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\input\pattex_buybox_asins.xlsx"

DOMAIN = "ae"
CURRENCY = "AED"

# ==============================
# DATE
# ==============================

now = datetime.datetime.now()
run_date = now.strftime("%Y-%m-%d")
run_time = now.strftime("%H:%M:%S")

# ==============================
# LOAD ASINS
# ==============================

df = pd.read_excel(INPUT_FILE)
asins = df["ASIN"].dropna().astype(str).unique()
print("Total ASINs:", len(asins))

# ==============================
# SELENIUM SETUP
# ==============================

options = Options()
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument("--start-maximized")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_experimental_option("excludeSwitches", ["enable-automation"])
options.add_experimental_option('useAutomationExtension', False)

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)

# Hide webdriver detection
driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

results = []

# ==============================
# PRICE FUNCTION (PDP)
# ==============================

def get_price():
    try:
        whole = driver.find_element(By.CLASS_NAME, "a-price-whole").text
        frac = driver.find_element(By.CLASS_NAME, "a-price-fraction").text
        return f"{whole}.{frac}".replace(",", "")
    except:
        return ""

# ==============================
# MOQ FUNCTION
# ==============================

def get_moq():
    try:
        text = driver.find_element(
            By.XPATH,
            "//*[contains(text(),'Minimum order quantity')]"
        ).text
        moq = text.split(":")[-1].strip()
        return moq
    except:
        return "1"

# ==============================
# SCRAPE LOOP
# ==============================

for asin in asins:
    print("\n" + "="*50)
    print(f"Processing: {asin}")
    print("="*50)

    # ==============================
    # PRODUCT PAGE (PDP)
    # ==============================

    url = f"https://www.amazon.{DOMAIN}/dp/{asin}"

    try:
        driver.get(url)
    except se.TimeoutException as e:
        print(f"[ERROR] Timeout loading PDP for {asin}, skipping ASIN. {e}")
        continue

    time.sleep(random.uniform(4, 6))

    # PRODUCT TITLE
    try:
        title = WebDriverWait(driver, 20).until(
            EC.presence_of_element_located((By.ID, "productTitle"))
        ).text.strip()
        print(f"Title: {title[:60]}...")
    except:
        print(f"[WARN] Could not find productTitle for {asin}, skipping ASIN.")
        continue

    # PRICE (PDP)
    price = get_price()

    # ==============================
    # SELLER (BUYBOX) - ROBUST
    # ==============================

    seller = "Amazon.ae"

    # 1) Classic seller profile trigger
    try:
        seller_el = driver.find_element(By.ID, "sellerProfileTriggerId")
        txt = seller_el.text.strip()
        if txt:
            seller = txt
    except:
        pass

    # 2) Generic "Sold by" pattern (anchor)
    if not seller or seller == "Amazon.ae":
        try:
            seller_el = driver.find_element(
                By.XPATH,
                "//*[contains(normalize-space(text()),'Sold by')]/following::a[1]"
            )
            txt = seller_el.text.strip()
            if txt:
                seller = txt
        except:
            pass

    # 3) Tabular buybox pattern
    if not seller or seller == "Amazon.ae":
        try:
            seller_el = driver.find_element(
                By.XPATH,
                "//div[@id='tabular-buybox']//span[contains(@class,'tabular-buybox-text') and contains(.,'Sold by')]/following::a[1]"
            )
            txt = seller_el.text.strip()
            if txt:
                seller = txt
        except:
            pass

    # 4) Merchant info pattern
    if not seller or seller == "Amazon.ae":
        try:
            seller_el = driver.find_element(
                By.XPATH,
                "//div[@id='merchant-info']//a[contains(@href,'seller')]"
            )
            txt = seller_el.text.strip()
            if txt:
                seller = txt
        except:
            pass

    seller = seller.strip() if seller else "Amazon.ae"
    print(f"BuyBox Seller: {seller}")

    # MOQ
    moq = get_moq()

    # SAVE BUYBOX ROW
    results.append({
        "Date": run_date,
        "Time": run_time,
        "ASIN": asin,
        "Title": title,
        "Seller": seller,
        "Price": price,
        "MOQ": moq,
        "BuyBox": "YES",
        "Link": url
    })

    buybox_seller = seller

    # ==============================
    # OFFER LISTING PAGE (AOD) WITH RETRIES
    # ==============================

    offer_url = f"https://www.amazon.{DOMAIN}/gp/offer-listing/{asin}"
    max_retries = 3
    offers_loaded = False

    for attempt in range(1, max_retries + 1):
        try:
            print(f"\n[INFO] Loading offer page (attempt {attempt}/{max_retries})...")
            driver.get(offer_url)
            
            # Wait for offer container to load
            try:
                WebDriverWait(driver, 15).until(
                    EC.presence_of_element_located((By.ID, "aod-container"))
                )
                print("[INFO] Offer container loaded")
            except:
                print("[WARN] Offer container not found, trying alternate selectors")
            
            time.sleep(random.uniform(3, 5))
            offers_loaded = True
            break
            
        except (se.TimeoutException, se.WebDriverException) as e:
            print(f"[WARN] Timeout loading offers for {asin} (attempt {attempt}/{max_retries}): {e}")
            if attempt < max_retries:
                time.sleep(5)
            else:
                print(f"[ERROR] Skipping offers for {asin} after {max_retries} failed attempts.")
                offers_loaded = False

    if not offers_loaded:
        continue

    # ==============================
    # FIND OFFERS - MULTIPLE APPROACHES
    # ==============================

    offers = []
    
    # Approach 1: Standard aod-offer divs
    offers_approach1 = driver.find_elements(By.XPATH, "//div[contains(@id,'aod-offer')]")
    if offers_approach1:
        print(f"[INFO] Found {len(offers_approach1)} offers using approach 1")
        offers = offers_approach1
    
    # Approach 2: aod-offer-list divs
    if not offers:
        offers_approach2 = driver.find_elements(By.XPATH, "//div[@id='aod-offer-list']//div[contains(@class,'aod-offer')]")
        if offers_approach2:
            print(f"[INFO] Found {len(offers_approach2)} offers using approach 2")
            offers = offers_approach2
    
    # Approach 3: Generic offer containers
    if not offers:
        offers_approach3 = driver.find_elements(By.XPATH, "//div[contains(@class,'a-section aod-offer')]")
        if offers_approach3:
            print(f"[INFO] Found {len(offers_approach3)} offers using approach 3")
            offers = offers_approach3

    # Approach 4: pinned-offer and other offers
    if not offers:
        offers_approach4 = driver.find_elements(By.XPATH, "//div[@id='aod-pinned-offer'] | //div[contains(@id,'aod-offer-')]")
        if offers_approach4:
            print(f"[INFO] Found {len(offers_approach4)} offers using approach 4")
            offers = offers_approach4

    if not offers:
        print(f"[WARN] No offers found for {asin} on offer listing page")
        
        # Debug: Save page source
        try:
            debug_file = f"debug_{asin}.html"
            with open(debug_file, "w", encoding="utf-8") as f:
                f.write(driver.page_source)
            print(f"[DEBUG] Page source saved to {debug_file}")
        except:
            pass
        continue

    print(f"[INFO] Processing {len(offers)} offers...")
    
    seen_sellers = set()
    offers_count = 0

    for idx, offer in enumerate(offers):
        try:
            seller = ""

            # 1) Seller as link - anchor with href to seller profile or seller page
            links = offer.find_elements(
                By.XPATH,
                ".//div[contains(@id,'aod-offer-soldBy') or contains(@class,'soldBy')]//a[not(contains(@href,'/product-reviews/'))]"
            )
            if links:
                txt = links[0].text.strip()
                if txt and txt != "":
                    seller = txt

            # 2) If link text empty, try title attribute
            if (not seller) and links:
                title_attr = (links[0].get_attribute("title") or "").strip()
                if title_attr:
                    seller = title_attr

            # 3) Fallback: soldBy container text
            if not seller:
                try:
                    sold_by_containers = offer.find_elements(
                        By.XPATH,
                        ".//div[contains(@id,'aod-offer-soldBy') or contains(@class,'soldBy')]"
                    )
                    if sold_by_containers:
                        txt = (sold_by_containers[0].get_attribute("innerText") or "").strip()
                        if txt:
                            lines = [l.strip() for l in txt.split("\n") if l.strip()]
                            # Filter out rating/feedback lines
                            clean_lines = [
                                l for l in lines
                                if "positive over last 12 months" not in l.lower()
                                and "positive in the last 12 months" not in l.lower()
                                and "feedback" not in l.lower()
                                and "ratings" not in l.lower()
                                and "sold by" not in l.lower()
                                and "%" not in l
                            ]
                            if clean_lines:
                                seller = clean_lines[0]
                except:
                    pass

            # 4) Try merchant-info if available
            if not seller:
                try:
                    merchant = offer.find_element(
                        By.XPATH,
                        ".//div[contains(@id,'merchant-info')]//a"
                    )
                    seller = merchant.text.strip()
                except:
                    pass

            seller = seller.strip()

            if not seller:
                print(f"  [WARN] Offer {idx+1}: Could not extract seller name")
                continue

            # PRICE on offer row
            price = ""
            try:
                # Try whole and fraction separately
                whole = offer.find_element(By.CSS_SELECTOR, ".a-price-whole").text
                frac = offer.find_element(By.CSS_SELECTOR, ".a-price-fraction").text
                price = f"{whole}.{frac}".replace(",", "")
            except:
                try:
                    # Try getting full price text
                    price_elem = offer.find_element(By.CSS_SELECTOR, ".a-price .a-offscreen")
                    price = price_elem.get_attribute("textContent").strip().replace(CURRENCY, "").strip()
                except:
                    try:
                        # Alternative price selector
                        price_elem = offer.find_element(By.XPATH, ".//span[contains(@class,'a-price')]//span[@class='a-offscreen']")
                        price = price_elem.get_attribute("textContent").strip().replace(CURRENCY, "").strip()
                    except:
                        pass

            # Skip empty price
            if not price:
                print(f"  [WARN] Offer {idx+1}: {seller} - No price found")
                continue

            # Skip BuyBox seller
            if seller.lower() == buybox_seller.lower():
                print(f"  [SKIP] Offer {idx+1}: {seller} (BuyBox seller)")
                continue

            # Skip duplicates
            if seller.lower() in [s.lower() for s in seen_sellers]:
                print(f"  [SKIP] Offer {idx+1}: {seller} (duplicate)")
                continue

            seen_sellers.add(seller)
            offers_count += 1

            results.append({
                "Date": run_date,
                "Time": run_time,
                "ASIN": asin,
                "Title": title,
                "Seller": seller,
                "Price": price,
                "MOQ": "1",
                "BuyBox": "NO",
                "Link": url
            })

            print(f"  [✓] Offer {idx+1}: {seller} - {CURRENCY} {price}")

        except Exception as e:
            print(f"  [ERROR] Offer {idx+1}: {e}")
            pass

    print(f"\n[SUMMARY] {asin}: BuyBox + {offers_count} other sellers = {offers_count + 1} total")

# ==============================
# CLOSE BROWSER
# ==============================

driver.quit()

# ==============================
# SAVE OUTPUT
# ==============================

df_out = pd.DataFrame(results)
# output_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\amazon_buybox_scrape_result.xlsx"
# df_out.to_excel(output_file, index=False)
# print(f"\n{'='*50}")
# print(f"SCRAPING COMPLETE!")
# print(f"{'='*50}")
# print(f"Total rows collected: {len(results)}")
# print(f"Saved to: {output_file}")

Total ASINs: 57

==================================================
Processing: B0DDGRFJ5W
==================================================
Title: Pattex Super Glue Liquid Tube, All Purpose Clear Adhesive wi...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 26 offers using approach 1
[INFO] Processing 26 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 27.99
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name

[SUMMARY] B0DDGRFJ5W: BuyBox + 1 other sellers = 2 total

==================================================
Processing: B0DDGWXNHC
==================================================
Title: Pattex Super Glue Liquid Tube, All Purpose Clear Adhesive wi...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 1 offers using approach 1
[INFO] Processing 1 offers...
  [WARN] Offer 1: Could not extract seller name

[SUMMARY] B0DDGWXNHC: BuyBox + 0 other sellers = 1 total

==================================================
Processing: B0BG2MZ1ZX
==================================================
Title: Pattex Superglue Liquide Control, Clear Glue for Various Mat...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 46 offers using approach 1
[INFO] Processing 46 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 25.49
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [✓] Offer 27: SMART-FZC - AED 35.00
  [WARN] Offer 28: Could not extract seller name
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name
  [✓] Offer 37: Westline Store - AED 34.00
  [WARN] Offer 38: Could not extract seller name
  [WARN] Offer 39: Could not extract seller name
  [WARN] Offer 40: Could not extract seller name
  [WARN] Offer 41: Could not extract seller name
  [WARN] Offer 42: Could not extract seller name
  [WARN] Offer 43: Could not extract seller name
  [WARN] Offer 44: Could not extract seller name
  [WARN] Offer 45: Could not extract seller name
  [WARN] Offer 46: Could not extract seller name

[SUMMARY] B0BG2MZ1ZX: BuyBox + 3 other sellers = 4 total

==================================================
Processing: B0DDGXBJW1
==================================================
Title: Pattex Super Glue Liquid Control, All Purpose Clear Adhesive...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 26 offers using approach 1
[INFO] Processing 26 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 33.99
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name

[SUMMARY] B0DDGXBJW1: BuyBox + 1 other sellers = 2 total

==================================================
Processing: B0DDGS87JD
==================================================
Title: Pattex Super Glue Liquid Control, All Purpose Clear Adhesive...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 38 offers using approach 1
[INFO] Processing 38 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: MySyara Shop - AED 28.00
  [SKIP] Offer 15: MySyara Shop (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [✓] Offer 27: ADD 2 CART_UAE - AED 41.49
  [WARN] Offer 28: Could not extract seller name
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name
  [WARN] Offer 37: Could not extract seller name
  [WARN] Offer 38: Could not extract seller name

[SUMMARY] B0DDGS87JD: BuyBox + 2 other sellers = 3 total

==================================================
Processing: B09KCHGRZF
==================================================
Title: Pattex Super Glue Power Gel, Strong All Purpose Adhesive For...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 38 offers using approach 1
[INFO] Processing 38 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 24.79
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [✓] Offer 27: Westline Store - AED 25.10
  [WARN] Offer 28: Could not extract seller name
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name
  [WARN] Offer 37: Could not extract seller name
  [WARN] Offer 38: Could not extract seller name

[SUMMARY] B09KCHGRZF: BuyBox + 2 other sellers = 3 total

==================================================
Processing: B0DDGY7RWR
==================================================
Title: Pattex Super Glue Power Gel Tube, All Purpose Adhesive For F...
BuyBox Seller: ADD 2 CART_UAE

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 39 offers using approach 1
[INFO] Processing 39 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [WARN] Offer 14: Could not extract seller name
  [WARN] Offer 15: Could not extract seller name
  [✓] Offer 16: SMART-FZC - AED 21.52
  [✓] Offer 17: Amazon.ae - AED 21.52
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [WARN] Offer 27: Could not extract seller name
  [SKIP] Offer 28: SMART-FZC (duplicate)
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name
  [WARN] Offer 37: Could not extract seller name
  [WARN] Offer 38: Could not extract seller name
  [WARN] Offer 39: Could not extract seller name

[SUMMARY] B0DDGY7RWR: BuyBox + 2 other sellers = 3 total

==================================================
Processing: B09KCGPSPG
==================================================
Title: Pattex Super Glue Power Gel Control | All Purpose Clear Adhe...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 36 offers using approach 1
[INFO] Processing 36 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 24.99
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [✓] Offer 27: SMART-FZC - AED 35.00
  [WARN] Offer 28: Could not extract seller name
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name

[SUMMARY] B09KCGPSPG: BuyBox + 2 other sellers = 3 total

==================================================
Processing: B0DDGV3T5C
==================================================
Title: Pattex Super Glue Power Gel Control | All Purpose Clear Adhe...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 26 offers using approach 1
[INFO] Processing 26 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 54.99
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name

[SUMMARY] B0DDGV3T5C: BuyBox + 1 other sellers = 2 total

==================================================
Processing: B0BG2KWV13
==================================================
Title: Pattex Super Glue All Plastics | Bonds All Difficult-to-Bond...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 36 offers using approach 1
[INFO] Processing 36 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name
  [WARN] Offer 7: Could not extract seller name
  [WARN] Offer 8: Could not extract seller name
  [WARN] Offer 9: Could not extract seller name
  [WARN] Offer 10: Could not extract seller name
  [WARN] Offer 11: Could not extract seller name
  [WARN] Offer 12: Could not extract seller name
  [WARN] Offer 13: Could not extract seller name
  [✓] Offer 14: ADD 2 CART_UAE - AED 24.99
  [SKIP] Offer 15: ADD 2 CART_UAE (duplicate)
  [WARN] Offer 16: Could not extract seller name
  [WARN] Offer 17: Could not extract seller name
  [WARN] Offer 18: Could not extract seller name
  [WARN] Offer 19: Could not extract seller name
  [WARN] Offer 20: Could not extract seller name
  [WARN] Offer 21: Could not extract seller name
  [WARN] Offer 22: Could not extract seller name
  [WARN] Offer 23: Could not extract seller name
  [WARN] Offer 24: Could not extract seller name
  [WARN] Offer 25: Could not extract seller name
  [WARN] Offer 26: Could not extract seller name
  [✓] Offer 27: Westline Store - AED 39.80
  [WARN] Offer 28: Could not extract seller name
  [WARN] Offer 29: Could not extract seller name
  [WARN] Offer 30: Could not extract seller name
  [WARN] Offer 31: Could not extract seller name
  [WARN] Offer 32: Could not extract seller name
  [WARN] Offer 33: Could not extract seller name
  [WARN] Offer 34: Could not extract seller name
  [WARN] Offer 35: Could not extract seller name
  [WARN] Offer 36: Could not extract seller name

[SUMMARY] B0BG2KWV13: BuyBox + 2 other sellers = 3 total

==================================================
Processing: B0DDGS2LRT
==================================================
Title: Pattex Super Glue All Plastics | Bonds All Difficult-to-Bond...
BuyBox Seller: Amazon.ae

[INFO] Loading offer page (attempt 1/3)...
[INFO] Offer container loaded
[INFO] Found 26 offers using approach 1
[INFO] Processing 26 offers...
  [WARN] Offer 1: Could not extract seller name
  [WARN] Offer 2: Could not extract seller name
  [WARN] Offer 3: Could not extract seller name
  [WARN] Offer 4: Could not extract seller name
  [WARN] Offer 5: Could not extract seller name
  [WARN] Offer 6: Could not extract seller name

In [2]:
df_temp = df_out.copy()

In [3]:
df_out = df_temp.copy()

In [4]:
df_out

,Date,Time,ASIN,Title,Seller,Price,MOQ,BuyBox,Link
0,2026-06-15,09:16:27,B0DDGRFJ5W,"Pattex Super Glue Liquid Tube, All Purpose Cle...",Amazon.ae,12.83,1,YES,https://www.amazon.ae/dp/B0DDGRFJ5W
1,2026-06-15,09:16:27,B0DDGRFJ5W,"Pattex Super Glue Liquid Tube, All Purpose Cle...",ADD 2 CART_UAE,27.99,1,NO,https://www.amazon.ae/dp/B0DDGRFJ5W
2,2026-06-15,09:16:27,B0DDGWXNHC,"Pattex Super Glue Liquid Tube, All Purpose Cle...",Amazon.ae,25..98,1,YES,https://www.amazon.ae/dp/B0DDGWXNHC
3,2026-06-15,09:16:27,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",Amazon.ae,11.79,1,YES,https://www.amazon.ae/dp/B0BG2MZ1ZX
4,2026-06-15,09:16:27,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",ADD 2 CART_UAE,25.49,1,NO,https://www.amazon.ae/dp/B0BG2MZ1ZX
...,...,...,...,...,...,...,...,...,...
186,2026-06-15,09:16:27,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,ADD 2 CART_UAE,30.99,1,NO,https://www.amazon.ae/dp/B09KCHP2CV
187,2026-06-15,09:16:27,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",ADD 2 CART_UAE,14.49,1,YES,https://www.amazon.ae/dp/B0GN246XDP
188,2026-06-15,09:16:27,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Amazon.ae,15.00,1,NO,https://www.amazon.ae/dp/B0GN246XDP
189,2026-06-15,09:16:27,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Amazon.ae,29.00,1,YES,https://www.amazon.ae/dp/B0GN2C54ZK
190,2026-06-15,09:16:27,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",ADD 2 CART_UAE,35.99,1,NO,https://www.amazon.ae/dp/B0GN2C54ZK

In [5]:
# df_out['Date'] = (pd.to_datetime(df_out['Date']) - pd.Timedelta(days=1)).dt.strftime('%Y-%m-%d')

In [6]:
df_out["Date"] = pd.to_datetime(df_out["Date"], format="%Y-%m-%d").dt.strftime("%d-%b-%Y")

In [7]:
df_out

,Date,Time,ASIN,Title,Seller,Price,MOQ,BuyBox,Link
0,15-Jun-2026,09:16:27,B0DDGRFJ5W,"Pattex Super Glue Liquid Tube, All Purpose Cle...",Amazon.ae,12.83,1,YES,https://www.amazon.ae/dp/B0DDGRFJ5W
1,15-Jun-2026,09:16:27,B0DDGRFJ5W,"Pattex Super Glue Liquid Tube, All Purpose Cle...",ADD 2 CART_UAE,27.99,1,NO,https://www.amazon.ae/dp/B0DDGRFJ5W
2,15-Jun-2026,09:16:27,B0DDGWXNHC,"Pattex Super Glue Liquid Tube, All Purpose Cle...",Amazon.ae,25..98,1,YES,https://www.amazon.ae/dp/B0DDGWXNHC
3,15-Jun-2026,09:16:27,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",Amazon.ae,11.79,1,YES,https://www.amazon.ae/dp/B0BG2MZ1ZX
4,15-Jun-2026,09:16:27,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",ADD 2 CART_UAE,25.49,1,NO,https://www.amazon.ae/dp/B0BG2MZ1ZX
...,...,...,...,...,...,...,...,...,...
186,15-Jun-2026,09:16:27,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,ADD 2 CART_UAE,30.99,1,NO,https://www.amazon.ae/dp/B09KCHP2CV
187,15-Jun-2026,09:16:27,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",ADD 2 CART_UAE,14.49,1,YES,https://www.amazon.ae/dp/B0GN246XDP
188,15-Jun-2026,09:16:27,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Amazon.ae,15.00,1,NO,https://www.amazon.ae/dp/B0GN246XDP
189,15-Jun-2026,09:16:27,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",Amazon.ae,29.00,1,YES,https://www.amazon.ae/dp/B0GN2C54ZK
190,15-Jun-2026,09:16:27,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",ADD 2 CART_UAE,35.99,1,NO,https://www.amazon.ae/dp/B0GN2C54ZK

In [8]:
# buybox_df = df_out.copy()

In [9]:
df_out.to_csv("fake_buybox_data.csv", index=False)

In [10]:
buybox_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\amazon_buybox_final_result.csv")

In [11]:
buybox_df = pd.concat([buybox_df, df_out], ignore_index=True)

In [12]:
buybox_df['MOQ'] = buybox_df['MOQ'].replace('2 (Minimum order quantity)', '2')

In [13]:
buybox_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\amazon_buybox_final_result.csv",index = False)

In [14]:
buybox_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\amazon_buybox_final_result.csv")

In [144]:
buybox_df

,Date,ASIN,Seller,Price,MOQ,BuyBox,Time,Title,Link
0,06-Mar-26,B0DDGRFJ5W,Amazon.ae,12.83,1,YES,NaN,NaN,NaN
1,06-Mar-26,B0DDGRFJ5W,ADD 2 CART_UAE,15.99,1,NO,NaN,NaN,NaN
2,06-Mar-26,B0DDGWXNHC,Amazon.ae,7..90,1,YES,NaN,NaN,NaN
3,06-Mar-26,B0BG2MZ1ZX,Amazon.ae,11,2,YES,NaN,NaN,NaN
4,06-Mar-26,B0BG2MZ1ZX,ADD 2 CART_UAE,23.99,1,NO,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
16634,12-Jun-2026,B09KCHP2CV,ADD 2 CART_UAE,.,1,NO,09:35:46,PATTEX SG LIQUID TUBE 1 x 3g,https://www.amazon.ae/dp/B09KCHP2CV
16635,12-Jun-2026,B0GN246XDP,ADD 2 CART_UAE,14.49,1,YES,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN246XDP
16636,12-Jun-2026,B0GN246XDP,Amazon.ae,.,1,NO,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN246XDP
16637,12-Jun-2026,B0GN2C54ZK,Amazon.ae,29.00,1,YES,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK
16638,12-Jun-2026,B0GN2C54ZK,ADD 2 CART_UAE,.,1,NO,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK

### Correct the dataframe

In [145]:
buybox_df.columns

Index(['Date', 'ASIN', 'Seller', 'Price', 'MOQ', 'BuyBox', 'Time', 'Title',
       'Link'],
      dtype='object')

In [146]:
import pandas as pd


rows = []

for (asin, date), group in buybox_df.groupby(['ASIN','Date']):

    row = {
        "ASIN": asin,
        "Date": date,
        "Time": group['Time'].iloc[0],
        "Title": group['Title'].iloc[0],
        "Link": group['Link'].iloc[0]
    }

    # Owner
    owner = group[group['BuyBox'] == 'YES']

    if not owner.empty:
        owner = owner.iloc[0]
        row["Current Owner"] = owner["Seller"]
        row["Current Owner Price"] = owner["Price"]
        row["Current Owner MOQ"] = owner["MOQ"]

    # Hijackers
    hijackers = group[group['BuyBox'] != 'YES']

    for i, (_, r) in enumerate(hijackers.iterrows(), start=1):
        row[f'Hijacker {i}'] = r['Seller']
        row[f'Hijacker {i} Price'] = r['Price']
        row[f'Hijacker {i} MOQ'] = r['MOQ']

    rows.append(row)

buybox_transposed = pd.DataFrame(rows)

In [147]:
buybox_transposed

,ASIN,Date,Time,Title,Link,Current Owner,Current Owner Price,Current Owner MOQ,Hijacker 1,Hijacker 1 Price,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,01-Apr-26,09:36:01,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,14,1,MySyara Shop,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B08B4T7CXB,01-Jun-2026,10:01:51,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,12.50,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B08B4T7CXB,01-May-26,09:37:56,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,11.29,1,Sold by,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B08B4T7CXB,02-Apr-26,09:52:44,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,11,1,83% positive over last 12 months,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B08B4T7CXB,02-Jun-2026,09:26:58,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,14.77,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5459,B0GN2C54ZK,30-Apr-26,09:28:34,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29,1,ADD 2 CART_UAE,40.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5460,B0GN2C54ZK,30-Mar-26,09:56:31,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5461,B0GN2C54ZK,30-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5462,B0GN2C54ZK,31-Mar-26,09:56:36,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5463,B0GN2C54ZK,31-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [148]:
buybox_df = buybox_transposed.copy()

### Merge Inv and BuyBox

In [149]:
# Convert to string
buybox_transposed['Current Owner Price'] = buybox_transposed['Current Owner Price'].astype(str)

# Condition: detect double dots
mask = buybox_transposed['Current Owner Price'].str.contains(r'\.\.')

# Apply updates
buybox_transposed.loc[mask, 'Current Owner'] = 'Unavailable'
buybox_transposed.loc[mask, 'Current Owner MOQ'] = 0
buybox_transposed.loc[mask, 'Current Owner Price'] = "0"

In [150]:
buybox_transposed

,ASIN,Date,Time,Title,Link,Current Owner,Current Owner Price,Current Owner MOQ,Hijacker 1,Hijacker 1 Price,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,01-Apr-26,09:36:01,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,14,1,MySyara Shop,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B08B4T7CXB,01-Jun-2026,10:01:51,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,12.50,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B08B4T7CXB,01-May-26,09:37:56,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,11.29,1,Sold by,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B08B4T7CXB,02-Apr-26,09:52:44,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,11,1,83% positive over last 12 months,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B08B4T7CXB,02-Jun-2026,09:26:58,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,14.77,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5459,B0GN2C54ZK,30-Apr-26,09:28:34,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29,1,ADD 2 CART_UAE,40.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5460,B0GN2C54ZK,30-Mar-26,09:56:31,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5461,B0GN2C54ZK,30-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5462,B0GN2C54ZK,31-Mar-26,09:56:36,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5463,B0GN2C54ZK,31-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
buybox_transposed.to_csv("buybox.csv",index = False)

In [152]:
buybox_final_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\output\pattex_inventory.csv")

In [153]:
buybox_final_df.columns

Index(['ASIN', 'Brand', 'Product Sub Category', 'Vendor Confirmation %',
       'PO_received_amount', 'PO_received_Units', 'Open POs',
       'Receive_Fill_Rate', 'Overall Vendor Lead Time (days)',
       'Aged 90+ Days Sellable Inventory', 'Aged 90+ Days Sellable Units',
       'Sellable Inventory Amount', 'Available Inventory',
       'Unsellable On Hand Inventory Amount', 'Unsellable On Hand Units',
       'Date', 'Product Name', 'Product Category', 'Pack Type', 'Pack Size',
       'SC Ideal Price', 'VC Ideal Price', 'Sales Channel', 'in_stock_flag',
       'cumulative_instock_days', 'day_of_month', 'Instock Rate',
       'total_sales', 'total_units', 'sell_through', 'DOS', 'OOS Date',
       'min_available_qty', 'max_available_qty', 'Stock_Status',
       'No/Low Stock wt Open POs', 'No/Low Stock wt no Open POs', 'Date_temp'],
      dtype='object')

In [154]:
buybox_df

,ASIN,Date,Time,Title,Link,Current Owner,Current Owner Price,Current Owner MOQ,Hijacker 1,Hijacker 1 Price,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,01-Apr-26,09:36:01,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,14,1,MySyara Shop,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B08B4T7CXB,01-Jun-2026,10:01:51,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,12.50,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B08B4T7CXB,01-May-26,09:37:56,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,ADD 2 CART_UAE,11.29,1,Sold by,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B08B4T7CXB,02-Apr-26,09:52:44,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,11,1,83% positive over last 12 months,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B08B4T7CXB,02-Jun-2026,09:26:58,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,https://www.amazon.ae/dp/B08B4T7CXB,Amazon.ae,14.77,1,MySyara Shop,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5459,B0GN2C54ZK,30-Apr-26,09:28:34,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29,1,ADD 2 CART_UAE,40.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5460,B0GN2C54ZK,30-Mar-26,09:56:31,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5461,B0GN2C54ZK,30-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5462,B0GN2C54ZK,31-Mar-26,09:56:36,Pritt Glue Stick Safe & Child-Friendly Craft G...,https://www.amazon.ae/dp/B0GN2C54ZK,ADD 2 CART_UAE,40.5,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5463,B0GN2C54ZK,31-May-2026,09:36:41,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK,Amazon.ae,29.00,1,ADD 2 CART_UAE,35.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
buybox_df = buybox_df.drop(columns=['Time', 'Title','Link'])

In [156]:
# buybox_final_df['Date'] = pd.to_datetime(
#     buybox_final_df['Date'],
#     format='mixed',
#     dayfirst=True
# ).dt.date

# buybox_df['Date'] = pd.to_datetime(
#     buybox_df['Date'],
#     format='mixed',
#     dayfirst=True
# ).dt.date


# Create temporary datetime columns
# Create temporary datetime columns
# Convert mixed formats → datetime → standard format
buybox_final_df["Date"] = pd.to_datetime(
    buybox_final_df["Date"], format="mixed", dayfirst=True
).dt.strftime("%d-%b-%Y")

buybox_df["Date"] = pd.to_datetime(
    buybox_df["Date"], format="mixed", dayfirst=True
).dt.strftime("%d-%b-%Y")

buybox_final_df = pd.merge(
    buybox_final_df,
    buybox_df,
    on=["ASIN", "Date"],
    how="left"
)

In [157]:
buybox_final_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,255.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,244.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,1009.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B08B4T7CXB,Pattex,11039 Building tools,0.00%,244.26,23,106,0.00%,12.43,1020.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,106,0.00%,0.00,1020.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7598,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7599,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7600,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7601,B0GN2C54ZK,Pritt,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
# Create ASIN -> first Product Sub Category mapping
asin_map = (
    buybox_final_df.dropna(subset=['Product Sub Category'])
      .drop_duplicates(subset=['ASIN'])
      .set_index('ASIN')['Product Sub Category']
)

# Fill missing Product sub Category
buybox_final_df['Product Sub Category'] = buybox_final_df['Product Sub Category'].fillna(buybox_final_df['ASIN'].map(asin_map))
buybox_final_df['Brand'] = "Pattex"
buybox_final_df['Sales Channel'] = "Vendor Central"
cols = [
    "Product Name",
    "Product Category",
    "Product Sub Category",
    "Pack Type"
]
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]
for col in cols_to_clean:
    buybox_final_df[col] = (
        buybox_final_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )

buybox_final_df[cols] = buybox_final_df[cols].fillna("Unavailable")
buybox_final_df= buybox_final_df.fillna(0)

In [159]:
buybox_final_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\pattex_dashboard_amazon_buybox.csv",index = False)

In [160]:
buybox_final_df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,255.11,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
1,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,244.48,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
2,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,1009.84,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
3,B08B4T7CXB,Pattex,11039 Building tools,0.00%,244.26,23,106,0.00%,12.43,1020.47,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
4,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,106,0.00%,0.00,1020.47,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7598,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7599,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7600,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7601,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0