In [1]:
import pandas as pd

## Read Inventory

In [2]:
import pandas as pd
from pathlib import Path

# Root folder
root_folder = Path(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\inventory"
)

# Find all csv and excel files recursively
files = list(root_folder.rglob("*.csv")) + \
        list(root_folder.rglob("*.xlsx")) + \
        list(root_folder.rglob("*.xls"))

print(f"Total files found: {len(files)}")

dfs = []

for file in files:
    try:
        if file.suffix.lower() == ".csv":
            temp_df = pd.read_csv(file)
        else:
            temp_df = pd.read_excel(file)

        # Optional metadata
        temp_df["source_file"] = file.name
        temp_df["month"] = file.parent.name          # june, may, etc.
        temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
        temp_df["file_path"] = str(file)

        dfs.append(temp_df)

        print(f"✓ Loaded: {file.name}")

    except Exception as e:
        print(f"✗ Error reading {file}: {e}")

# Combine all files
df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

print("\nFinal Shape:", df.shape)

# Preview
df

Total files found: 12
✓ Loaded: noon_minutes-01_June_2026.csv
✓ Loaded: noon_minutes-02_June_2026.csv
✓ Loaded: noon_minutes-03_June_2026.csv
✓ Loaded: noon_minutes-04_June_2026.csv
✓ Loaded: noon_minutes-05_June_2026.csv
✓ Loaded: noon_minutes-08_June_2026.csv
✓ Loaded: noon_minutes-09_June_2026.csv
✓ Loaded: noon_minutes-10_June_2026.csv
✓ Loaded: noon_minutes-11_June_2026.csv
✓ Loaded: noon_minutes-12_June_2026.csv
✓ Loaded: noon_minutes-13_June_2026.csv
✓ Loaded: noon_minutes-14_June_2026.csv

Final Shape: (17693, 15)

,Warehouse,Warehouse Code,Category,ZSKU,Barcode,Brand,Product Title,Product Type,Product Sub-Type,Refresh Time,Stock,source_file,month,year,file_path
0,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,ZC22E01C3AED911BCDD94Z-1,4057278012422,pattex,Super Glue Liquid Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",266,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
1,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,Z4975C90C8900E6C933E5Z-1,4057278012453,pattex,Super Glue Power Gel Control 1 x 3g 1 x 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",195,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
2,Dubai South WH - Dubai South Logistics Distric...,W00833473AE,Stationery,ZC22E01C3AED911BCDD94Z-1,4057278012422,pattex,Super Glue Liquid Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",194,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3,Noon grocery technopark - Jebel Ali,W00068387A,Stationery,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,pattex,Super Glue Power Gel Tube 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",136,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
4,Dubai South WH - Dubai South Logistics Distric...,W00833473AE,Stationery,Z4975C90C8900E6C933E5Z-1,4057278012453,pattex,Super Glue Power Gel Control 1 x 3g 1 x 3g,adhesives_sealers_and_tapes,super_glue,"1 Jun 2026, 03:35:00",103,noon_minutes-01_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17688,Town Square,W00000124A,Stationery,ZBA399C7DC228834F3B65Z-1,4057278012439,pattex,Super Glue Liquid Control 3g 3g,adhesives_sealers_and_tapes,super_glue,"14 Jun 2026, 16:35:01",0,noon_minutes-14_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
17689,Furjan,W00060246A,Stationery,Z1A9DB3085D9B3E2F976AZ-1,6295199302040,pritt,Glue Sticks Pack of 4 | 11g each Pack of 4 | 1...,tape_adhesives_fasteners,glue_sticks,"14 Jun 2026, 16:35:01",0,noon_minutes-14_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
17690,Dubai Hills,W00048862A,Stationery,Z6CF488BCCB75DA003E6BZ-1,4057278012507,pattex,No More Nails Invisible Adhesive 40g 40g,adhesives_sealers_and_tapes,super_glue,"14 Jun 2026, 16:35:01",0,noon_minutes-14_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
17691,Al Majaz 3,W00828323AE,Stationery,Z4975C90C8900E6C933E5Z-1,4057278012453,pattex,Super Glue Power Gel Control 3g 3g,adhesives_sealers_and_tapes,super_glue,"14 Jun 2026, 16:35:01",0,noon_minutes-14_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
17692,Jebel Ali Village - Dubai,W00056049A,Stationery,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,pattex,Super Glue Power Gel 3g,adhesives_sealers_and_tapes,super_glue,"14 Jun 2026, 16:35:01",0,noon_minutes-14_June_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...

## Select Cols

In [3]:
df.rename(columns={"Refresh Time": "Date", "Stock": "Inventory", }, inplace=True)
cols_to_keep = [
    "Date",
    "Inventory",
    "ZSKU",
]
df = df[cols_to_keep]
df

                        Date  Inventory                      ZSKU
0       1 Jun 2026, 03:35:00        266  ZC22E01C3AED911BCDD94Z-1
1       1 Jun 2026, 03:35:00        195  Z4975C90C8900E6C933E5Z-1
2       1 Jun 2026, 03:35:00        194  ZC22E01C3AED911BCDD94Z-1
3       1 Jun 2026, 03:35:00        136  ZF1DE7A17A2F4DE0CC7AAZ-1
4       1 Jun 2026, 03:35:00        103  Z4975C90C8900E6C933E5Z-1
...                      ...        ...                       ...
17688  14 Jun 2026, 16:35:01          0  ZBA399C7DC228834F3B65Z-1
17689  14 Jun 2026, 16:35:01          0  Z1A9DB3085D9B3E2F976AZ-1
17690  14 Jun 2026, 16:35:01          0  Z6CF488BCCB75DA003E6BZ-1
17691  14 Jun 2026, 16:35:01          0  Z4975C90C8900E6C933E5Z-1
17692  14 Jun 2026, 16:35:01          0  ZF1DE7A17A2F4DE0CC7AAZ-1

[17693 rows x 3 columns]

## GroupBy the data

In [4]:
import pandas as pd

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Format date as 01-June-2026
df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

# Group by Date and ZSKU and sum Inventory
df_inv = df.groupby(['Date', 'ZSKU'], as_index=False)['Inventory'].sum()

df_inv

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1322732787.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1322732787.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

             Date                      ZSKU  Inventory
0    01-June-2026  Z02597565A8FB4D9EE9EAZ-1         50
1    01-June-2026  Z1A9DB3085D9B3E2F976AZ-1        154
2    01-June-2026  Z3BCEB0AB181B08702C95Z-1        301
3    01-June-2026  Z41917D6E86BF75D31B27Z-1        156
4    01-June-2026  Z4975C90C8900E6C933E5Z-1        535
..            ...                       ...        ...
115  14-June-2026  Z67A14260CB22A4D0A465Z-1          5
116  14-June-2026  Z6CF488BCCB75DA003E6BZ-1        155
117  14-June-2026  ZBA399C7DC228834F3B65Z-1        376
118  14-June-2026  ZC22E01C3AED911BCDD94Z-1       1169
119  14-June-2026  ZF1DE7A17A2F4DE0CC7AAZ-1        528

[120 rows x 3 columns]

## Add product details

In [5]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\helper_file_noon_minutes.xlsx"
)

# Keep only required columns
helper_df = helper_df[['ZSKU', 'Product Name', 'Category', 'Pack Size']]

# Merge with df_inv
df_inv = df_inv.merge(
    helper_df,
    on='ZSKU',
    how='left'  # keeps all rows from df_inv
)

df_inv

,Date,ZSKU,Inventory,Product Name,Category,Pack Size
0,01-June-2026,Z02597565A8FB4D9EE9EAZ-1,50,Pritt Glue Stick 43g (Pack of 4),Pritt Glue Stick,Pack of 4
1,01-June-2026,Z1A9DB3085D9B3E2F976AZ-1,154,Pritt Rainbow Coloured Glue Sticks 4x10g (Pack...,Pritt Glue Stick,Pack of 4
2,01-June-2026,Z3BCEB0AB181B08702C95Z-1,301,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1
3,01-June-2026,Z41917D6E86BF75D31B27Z-1,156,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1
4,01-June-2026,Z4975C90C8900E6C933E5Z-1,535,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
...,...,...,...,...,...,...
115,14-June-2026,Z67A14260CB22A4D0A465Z-1,5,Pritt Glue Stick 22g (Pack of 4),Pritt Glue Stick,Pack of 4
116,14-June-2026,Z6CF488BCCB75DA003E6BZ-1,155,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1
117,14-June-2026,ZBA399C7DC228834F3B65Z-1,376,Superglue Liquid Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
118,14-June-2026,ZC22E01C3AED911BCDD94Z-1,1169,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
119,14-June-2026,ZF1DE7A17A2F4DE0CC7AAZ-1,528,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1

## now read sales

In [6]:
import pandas as pd
from pathlib import Path

# Root folder
root_folder = Path(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\orders"
)

# Find all csv and excel files recursively
files = list(root_folder.rglob("*.csv")) + \
        list(root_folder.rglob("*.xlsx")) + \
        list(root_folder.rglob("*.xls"))

print(f"Total files found: {len(files)}")

dfs = []

for file in files:
    try:
        if file.suffix.lower() == ".csv":
            temp_df = pd.read_csv(file)
        else:
            temp_df = pd.read_excel(file)

        # Optional metadata
        temp_df["source_file"] = file.name
        temp_df["month"] = file.parent.name          # june, may, etc.
        temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
        temp_df["file_path"] = str(file)

        dfs.append(temp_df)

        print(f"✓ Loaded: {file.name}")

    except Exception as e:
        print(f"✗ Error reading {file}: {e}")

# Combine all files
df = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

print("\nFinal Shape:", df.shape)

# Preview
df

Total files found: 2
✓ Loaded: PATTEX_noon_minutes_sales_june_2026.csv
✓ Loaded: PATTEX_noon_minutes_sales_may_2026.csv

Final Shape: (3598, 20)

,Date,Month,Country,Platform,Warehouse,Warehouse Cod,Category,nsku,ZSKU,Barcode,Title,Brand,Type,Sub-Type,Qty,Revenue,source_file,month,year,file_path
0,7 Jun 2026,2026-06,AE,Minutes,Business Bay 2,DXBDS57,Stationery,Z4975C90C8900E6C933E5Z-1,Z4975C90C8900E6C933E5Z-1,4057278012453,Super Glue Power Gel Control 1 x 3g,pattex,adhesives_sealers_and_tapes,super_glue,1,9.80,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
1,8 Jun 2026,2026-06,AE,Minutes,JVC 5,DXBDS114,Stationery,ZBA399C7DC228834F3B65Z-1,ZBA399C7DC228834F3B65Z-1,4057278012439,Super Glue Liquid Control 3g,pattex,adhesives_sealers_and_tapes,super_glue,1,8.70,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
2,13 Jun 2026,2026-06,AE,Minutes,Qusais 2,DXBDS33,Stationery,N70158792V-1,ZC22E01C3AED911BCDD94Z-1,4057278012422,Super Glue LiquidClear,pattex,adhesives_sealers_and_tapes,super_glue,1,5.30,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3,4 Jun 2026,2026-06,AE,Minutes,Muhaisnah,DXBDS88,Stationery,N70158783V-1,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,Super Glue Power Gel TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,9.95,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
4,5 Jun 2026,2026-06,AE,Minutes,Al Mu'tarid,AINDS04,Stationery,N70158783V-1,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,Super Glue Power Gel TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,9.95,PATTEX_noon_minutes_sales_june_2026.csv,june,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3593,15 May 2026,2026-05,AE,Minutes,Production City,DXBDS28,Stationery,N70158783V-1,ZF1DE7A17A2F4DE0CC7AAZ-1,4057278012446,Super Glue Power Gel TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,1,6.30,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3594,3 May 2026,2026-05,AE,Minutes,Town Square 2,DXBDS47,Stationery,N70158792V-1,ZC22E01C3AED911BCDD94Z-1,4057278012422,Super Glue Liquid TubeClear,pattex,adhesives_sealers_and_tapes,super_glue,2,14.50,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3595,2 May 2026,2026-05,AE,Minutes,Hor Al Anz 2,DXBDS101,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,1,22.45,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3596,13 May 2026,2026-05,AE,Minutes,Khalifa City 2,AUHDS14,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,1,15.35,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3597,20 May 2026,2026-05,AE,Minutes,Muwaileh 3,SHJDS18,Stationery,N70158788V-1,Z3BCEB0AB181B08702C95Z-1,6001091345906,No More Nails Mounting Tape,pattex,adhesives_sealers_and_tapes,adhesive_transfer_tape,2,30.70,PATTEX_noon_minutes_sales_may_2026.csv,may,2026,C:\Users\Shubham Verma\OneDrive - Incircle Eco...

## Select sales cols

In [7]:
df.rename(columns={"Qty": "qty_sold", "Revenue": "total_sales", }, inplace=True)
cols_to_keep = [
    "Date",
    "qty_sold",
    "ZSKU",
    "total_sales"
]
df = df[cols_to_keep]
df

             Date  qty_sold                      ZSKU  total_sales
0      7 Jun 2026         1  Z4975C90C8900E6C933E5Z-1         9.80
1      8 Jun 2026         1  ZBA399C7DC228834F3B65Z-1         8.70
2     13 Jun 2026         1  ZC22E01C3AED911BCDD94Z-1         5.30
3      4 Jun 2026         1  ZF1DE7A17A2F4DE0CC7AAZ-1         9.95
4      5 Jun 2026         1  ZF1DE7A17A2F4DE0CC7AAZ-1         9.95
...           ...       ...                       ...          ...
3593  15 May 2026         1  ZF1DE7A17A2F4DE0CC7AAZ-1         6.30
3594   3 May 2026         2  ZC22E01C3AED911BCDD94Z-1        14.50
3595   2 May 2026         1  Z3BCEB0AB181B08702C95Z-1        22.45
3596  13 May 2026         1  Z3BCEB0AB181B08702C95Z-1        15.35
3597  20 May 2026         2  Z3BCEB0AB181B08702C95Z-1        30.70

[3598 rows x 4 columns]

## Group by sales

In [8]:
import pandas as pd

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Format date as 01-June-2026
df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

# Group by Date and ZSKU and sum Inventory
df_sales = df.groupby(['Date', 'ZSKU'], as_index=False)[['qty_sold', 'total_sales']].sum()
df_sales

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\2401122350.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'])
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\2401122350.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].dt.strftime('%d-%B-%Y')

             Date                      ZSKU  qty_sold  total_sales
0    01-June-2026  Z1A9DB3085D9B3E2F976AZ-1         5        59.25
1    01-June-2026  Z3BCEB0AB181B08702C95Z-1         4        90.00
2    01-June-2026  Z41917D6E86BF75D31B27Z-1         5        67.50
3    01-June-2026  Z4975C90C8900E6C933E5Z-1        18       214.30
4    01-June-2026  Z6CF488BCCB75DA003E6BZ-1         2        30.80
..            ...                       ...       ...          ...
332   31-May-2026  Z4975C90C8900E6C933E5Z-1        29       284.20
333   31-May-2026  Z6CF488BCCB75DA003E6BZ-1         4        50.20
334   31-May-2026  ZBA399C7DC228834F3B65Z-1         8        68.80
335   31-May-2026  ZC22E01C3AED911BCDD94Z-1        31       253.30
336   31-May-2026  ZF1DE7A17A2F4DE0CC7AAZ-1        13       104.90

[337 rows x 4 columns]

## Add product details in sales

In [9]:
import pandas as pd

# Read helper file
helper_df = pd.read_excel(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\helper_file_noon_minutes.xlsx"
)

# Keep only required columns
helper_df = helper_df[['ZSKU', 'Product Name', 'Category', 'Pack Size']]

# Merge with df_inv
df_sales = df_sales.merge(
    helper_df,
    on='ZSKU',
    how='left'  # keeps all rows from df_inv
)

df_sales

,Date,ZSKU,qty_sold,total_sales,Product Name,Category,Pack Size
0,01-June-2026,Z1A9DB3085D9B3E2F976AZ-1,5,59.25,Pritt Rainbow Coloured Glue Sticks 4x10g (Pack...,Pritt Glue Stick,Pack of 4
1,01-June-2026,Z3BCEB0AB181B08702C95Z-1,4,90.00,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1
2,01-June-2026,Z41917D6E86BF75D31B27Z-1,5,67.50,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1
3,01-June-2026,Z4975C90C8900E6C933E5Z-1,18,214.30,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
4,01-June-2026,Z6CF488BCCB75DA003E6BZ-1,2,30.80,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1
...,...,...,...,...,...,...,...
332,31-May-2026,Z4975C90C8900E6C933E5Z-1,29,284.20,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
333,31-May-2026,Z6CF488BCCB75DA003E6BZ-1,4,50.20,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1
334,31-May-2026,ZBA399C7DC228834F3B65Z-1,8,68.80,Superglue Liquid Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
335,31-May-2026,ZC22E01C3AED911BCDD94Z-1,31,253.30,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
336,31-May-2026,ZF1DE7A17A2F4DE0CC7AAZ-1,13,104.90,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1

## last 30 day sale

In [10]:
import pandas as pd

# Convert dates to datetime
df_inv['Date'] = pd.to_datetime(df_inv['Date'])
df_sales['Date'] = pd.to_datetime(df_sales['Date'])

def get_last_30_day_sales(row):
    # Exclude current day and previous day
    start_date = row['Date'] - pd.Timedelta(days=31)
    end_date = row['Date'] - pd.Timedelta(days=2)

    return df_sales.loc[
        (df_sales['ZSKU'] == row['ZSKU']) &
        (df_sales['Date'] >= start_date) &
        (df_sales['Date'] <= end_date),
        'qty_sold'
    ].sum()

# Create new column
df_inv['last_30_day_sale_qty'] = df_inv.apply(
    get_last_30_day_sales,
    axis=1
)

## DOS

In [11]:
import numpy as np

df_inv['DOS'] = np.where(
    df_inv['last_30_day_sale_qty'] > 0,
    df_inv['Inventory'] * 30 / df_inv['last_30_day_sale_qty'],
    np.nan
)

In [12]:
df_inv.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\inventory\noon_minutes_inventory.csv", index=False)

# Sales

In [13]:
df_sales.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\sales\noon_minutes_sales.csv", index=False)

## Marketing

In [14]:
import pandas as pd
from pathlib import Path

# Root folder
root_folder = Path(
    r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\input\marketing"
)

# Find all csv and excel files recursively
files = list(root_folder.rglob("*.csv")) + \
        list(root_folder.rglob("*.xlsx")) + \
        list(root_folder.rglob("*.xls"))

print(f"Total files found: {len(files)}")

dfs = []

for file in files:
    try:
        if file.suffix.lower() == ".csv":
            temp_df = pd.read_csv(file)
        else:
            temp_df = pd.read_excel(file)

        # Optional metadata
        temp_df["source_file"] = file.name
        temp_df["month"] = file.parent.name          # june, may, etc.
        temp_df["year"] = file.parent.parent.name    # 2026, 2027, etc.
        temp_df["file_path"] = str(file)

        dfs.append(temp_df)

        print(f"✓ Loaded: {file.name}")

    except Exception as e:
        print(f"✗ Error reading {file}: {e}")

# Combine all files
df_marketing = pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

print("\nFinal Shape:", df_marketing.shape)

# Preview
df_marketing

Total files found: 2
✓ Loaded: PATTEX Min - Marketing (1-14 Jun).csv
✓ Loaded: PATTEX_noon_minutes_marketing_may_2026.csv

Final Shape: (435, 18)

,Date,Campaign Code,Campaign Name,Ad Type,SKU,Product Name,Views,Clicks,CTR %,ROAS,CPC,Revenue,Spends,Orders,source_file,month,year,file_path
0,2026-06-03,CPQTQ288TB,PATTEX | SP | SuperGlue | CT,Recommendation Ads,Z4975C90C8900E6C933E5Z-1,Super Glue Power Gel Control 3g,45,1,2.22,0.00,2.50,0.0,2.50,0,PATTEX Min - Marketing (1-14 Jun).csv,june,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
1,2026-06-03,CP2F54NT3V,PATTEX | SP | SuperGlue | Exact (Super Glue),Product Listing Ads,Z4975C90C8900E6C933E5Z-1,Super Glue Power Gel Control 3g,391,20,5.12,1.83,2.62,95.6,52.36,8,PATTEX Min - Marketing (1-14 Jun).csv,june,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
2,2026-06-03,CP6X6FET6P,PATTEX | SP | SuperGlue | Phrase(BO),Product Listing Ads,ZF1DE7A17A2F4DE0CC7AAZ-1,Super Glue Power Gel,11,0,0.00,0.00,0.00,0.0,0.00,0,PATTEX Min - Marketing (1-14 Jun).csv,june,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
3,2026-06-03,CPWVFSUS77,PATTEX | SP | NMN | CT,Recommendation Ads,Z41917D6E86BF75D31B27Z-1,Heavy-Duty Mounting Adhesive,18,0,0.00,0.00,0.00,0.0,0.00,0,PATTEX Min - Marketing (1-14 Jun).csv,june,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
4,2026-06-03,CP2F54NT3V,PATTEX | SP | SuperGlue | Exact (Super Glue),Product Listing Ads,ZBA399C7DC228834F3B65Z-1,Super Glue Liquid Control 3g,242,8,3.31,2.51,2.87,57.5,22.95,5,PATTEX Min - Marketing (1-14 Jun).csv,june,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,2026-05-31,CPWSTC6DLE,PATTEX | SP | Mounting Tape | CT,Recommendation Ads,Z3BCEB0AB181B08702C95Z-1,No More Nails Mounting Tape,4,0,0.00,0.00,0.00,0.0,0.00,0,PATTEX_noon_minutes_marketing_may_2026.csv,may,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
431,2026-05-31,CP2F54NT3V,PATTEX | SP | SuperGlue | Exact(G),Product Listing Ads,ZBA399C7DC228834F3B65Z-1,Super Glue Liquid Control 3g,11,2,18.18,0.00,2.00,0.0,4.00,0,PATTEX_noon_minutes_marketing_may_2026.csv,may,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
432,2026-05-31,CP2F54NT3V,PATTEX | SP | SuperGlue | Exact(G),Product Listing Ads,Z4975C90C8900E6C933E5Z-1,Super Glue Power Gel Control 1 x 3g,16,1,6.25,4.90,2.00,9.8,2.00,1,PATTEX_noon_minutes_marketing_may_2026.csv,may,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
433,2026-05-31,CP6X6FET6P,PATTEX | SP | SuperGlue | Phrase(BO),Product Listing Ads,ZF1DE7A17A2F4DE0CC7AAZ-1,Super Glue Power Gel Tube,4,3,75.00,0.00,0.00,0.0,0.00,0,PATTEX_noon_minutes_marketing_may_2026.csv,may,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...
434,2026-05-31,CP6X6FET6P,PATTEX | SP | SuperGlue | Phrase(BO),Product Listing Ads,Z4975C90C8900E6C933E5Z-1,Super Glue Power Gel Control 1 x 3g,3,2,66.67,0.00,0.00,0.0,0.00,0,PATTEX_noon_minutes_marketing_may_2026.csv,may,marketing,C:\Users\Shubham Verma\OneDrive - Incircle Eco...

In [15]:
cols_to_keep = [
    "Date",
    "SKU",
    "Clicks",
    "Spends",
    "Revenue",
    "Orders"
]
df_marketing = df_marketing[cols_to_keep]
df_marketing

           Date                       SKU  Clicks  Spends  Revenue  Orders
0    2026-06-03  Z4975C90C8900E6C933E5Z-1       1    2.50      0.0       0
1    2026-06-03  Z4975C90C8900E6C933E5Z-1      20   52.36     95.6       8
2    2026-06-03  ZF1DE7A17A2F4DE0CC7AAZ-1       0    0.00      0.0       0
3    2026-06-03  Z41917D6E86BF75D31B27Z-1       0    0.00      0.0       0
4    2026-06-03  ZBA399C7DC228834F3B65Z-1       8   22.95     57.5       5
..          ...                       ...     ...     ...      ...     ...
430  2026-05-31  Z3BCEB0AB181B08702C95Z-1       0    0.00      0.0       0
431  2026-05-31  ZBA399C7DC228834F3B65Z-1       2    4.00      0.0       0
432  2026-05-31  Z4975C90C8900E6C933E5Z-1       1    2.00      9.8       1
433  2026-05-31  ZF1DE7A17A2F4DE0CC7AAZ-1       3    0.00      0.0       0
434  2026-05-31  Z4975C90C8900E6C933E5Z-1       2    0.00      0.0       0

[435 rows x 6 columns]

In [16]:
import pandas as pd

# Convert Date column to datetime
df_marketing['Date'] = pd.to_datetime(df_marketing['Date'])

# Columns to be summed
sum_cols = ['Clicks', 'Spends', 'Revenue', 'Orders']

# Remove commas, convert to numeric, and handle invalid values
for col in sum_cols:
    df_marketing[col] = (
        df_marketing[col]
        .astype(str)
        .str.replace(',', '', regex=False)
    )
    df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)

# Group by Date and SKU and sum the specified columns
df_marketing = (
    df_marketing
    .groupby(['Date', 'SKU'], as_index=False)[sum_cols]
    .sum()
)

# Format date as 01-June-2026
df_marketing['Date'] = df_marketing['Date'].dt.strftime('%d-%B-%Y')

df_marketing.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\noon_minutes\uae\output\marketing\noon_minutes_marketing.csv", index=False)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing['Date'] = pd.to_datetime(df_marketing['Date'])
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = (
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = (
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = (
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = (
C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_33720\1386903630.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_marketing[col] = pd.to_numeric(df_marketing[col], errors='coerce').fillna(0)

In [17]:
df_marketing

             Date                       SKU  Clicks  Spends  Revenue  Orders
0     01-May-2026  Z3BCEB0AB181B08702C95Z-1      14   28.00    56.20       3
1     01-May-2026  Z41917D6E86BF75D31B27Z-1       3    6.00    37.10       2
2     01-May-2026  Z4975C90C8900E6C933E5Z-1      32   64.00   200.75      17
3     01-May-2026  Z67A14260CB22A4D0A465Z-1       1    2.00     0.00       0
4     01-May-2026  Z6CF488BCCB75DA003E6BZ-1       0    0.00     0.00       0
..            ...                       ...     ...     ...      ...     ...
182  14-June-2026  Z67A14260CB22A4D0A465Z-1       0    0.00     0.00       0
183  14-June-2026  Z6CF488BCCB75DA003E6BZ-1       8   17.02    56.75       4
184  14-June-2026  ZBA399C7DC228834F3B65Z-1      35   70.21   172.00      14
185  14-June-2026  ZC22E01C3AED911BCDD94Z-1      20   40.00    84.25      10
186  14-June-2026  ZF1DE7A17A2F4DE0CC7AAZ-1      75  150.00   271.00      42

[187 rows x 6 columns]

In [18]:
df_sales

,Date,ZSKU,qty_sold,total_sales,Product Name,Category,Pack Size
0,2026-06-01,Z1A9DB3085D9B3E2F976AZ-1,5,59.25,Pritt Rainbow Coloured Glue Sticks 4x10g (Pack...,Pritt Glue Stick,Pack of 4
1,2026-06-01,Z3BCEB0AB181B08702C95Z-1,4,90.00,Mounting Tape 120kg (Pack of 1),Mounting Tape,Pack of 1
2,2026-06-01,Z41917D6E86BF75D31B27Z-1,5,67.50,No More Nails Strong & Easy 50g (Pack of 1),Construction Adhesive,Pack of 1
3,2026-06-01,Z4975C90C8900E6C933E5Z-1,18,214.30,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
4,2026-06-01,Z6CF488BCCB75DA003E6BZ-1,2,30.80,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1
...,...,...,...,...,...,...,...
332,2026-05-31,Z4975C90C8900E6C933E5Z-1,29,284.20,Super Glue Power Gel Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
333,2026-05-31,Z6CF488BCCB75DA003E6BZ-1,4,50.20,No More Nails Invisible 40g (Pack of 1),Construction Adhesive,Pack of 1
334,2026-05-31,ZBA399C7DC228834F3B65Z-1,8,68.80,Superglue Liquid Control 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
335,2026-05-31,ZC22E01C3AED911BCDD94Z-1,31,253.30,Superglue Liquid 3g (Pack of 1),All Purpose SuperGlue,Pack of 1
336,2026-05-31,ZF1DE7A17A2F4DE0CC7AAZ-1,13,104.90,Super Glue Power Gel Tube 3g (Pack of 1),All Purpose SuperGlue,Pack of 1