# Inventory

In [1]:
import pandas as pd
import pandas as pd
from datetime import datetime
import os

## Saving Manage FBA File

In [2]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
input_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\manager_fba_inventory\pattex_manage_fba.csv"

# -------- BASE OUTPUT PATH --------
base_output_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\manager_fba_inventory"

# -------- READ FILE --------
df = pd.read_csv(input_path)

# -------- GET TODAY DATE --------
today = datetime.today()

day = today.day
month_num = today.month
year = today.year

# Convert month → apr, mar, etc.
month_name = today.strftime("%b").lower()

# -------- CREATE FOLDER PATH --------
year_path = os.path.join(base_output_path, str(year))
month_path = os.path.join(year_path, month_name)

# Create folders if not exist
os.makedirs(month_path, exist_ok=True)

# -------- CREATE FILE NAME --------
file_name = f"manage_fba_inventory_Pattex_{day:02d}-{month_name}-{year}.csv"

output_path = os.path.join(month_path, file_name)

# -------- SAVE FILE --------
df.to_csv(output_path, index=False)

print("✅ File saved at:", output_path)

✅ File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\manager_fba_inventory\2026\jun\manage_fba_inventory_Pattex_12-jun-2026.csv

## Read manage FBA File

In [3]:
import os
import pandas as pd
from datetime import datetime, timedelta
import re

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\manager_fba_inventory"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- FIND PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Current month
folders_to_read.append((year, month))

# Add previous month if day <= 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP THROUGH SELECTED FOLDERS --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        file_path = os.path.join(folder_path, file)

        if file.endswith(".csv"):
            df = pd.read_csv(file_path)

        elif file.endswith(".xlsx") or file.endswith(".xls"):
            df = pd.read_excel(file_path)

        else:
            continue

        # -------- EXTRACT DATE FROM FILENAME --------
        match = re.search(r"\d{1,2}-[A-Za-z]{3}-\d{4}", file)

        if match:
            file_date = pd.to_datetime(
                match.group(), format="%d-%b-%Y"
            ).strftime("%d-%b-%Y")

            df["Date"] = file_date

        df_list.append(df)

# -------- COMBINE --------
df_mng = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_mng.empty:
    df_mng = df_mng[
        df_mng['product-name'].str.contains('pattex|pritt', case=False, na=False)
    ]

print("Total rows loaded:", len(df_mng))

Folders to read: [(2026, 6)]
Total rows loaded: 708

In [4]:
df_mng

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,afn-total-quantity,per-unit-volume,afn-inbound-working-quantity,afn-inbound-shipped-quantity,afn-inbound-receiving-quantity,afn-researching-quantity,afn-reserved-future-supply,afn-future-supply-buyable,store,Date
654,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,NaN,Yes,1,...,1,447.20,0,0,0,0,0,0,NaN,01-Jun-2026
655,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,NaN,Yes,59,...,59,513.41,0,0,0,0,0,0,NaN,01-Jun-2026
656,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,NaN,Yes,59,...,59,442.78,0,0,0,0,0,0,NaN,01-Jun-2026
657,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,NaN,Yes,63,...,63,233.68,0,0,0,0,0,0,NaN,01-Jun-2026
658,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,NaN,Yes,60,...,60,445.40,0,0,0,0,0,0,NaN,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11711,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,NaN,Yes,16,...,16,306.27,0,0,0,0,0,0,NaN,12-Jun-2026
11712,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,NaN,Yes,20,...,20,468.01,0,0,0,0,0,0,NaN,12-Jun-2026
11715,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,NaN,Yes,20,...,20,158.30,0,0,0,0,0,0,NaN,12-Jun-2026
11716,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,NaN,Yes,16,...,16,200.09,0,0,0,0,0,0,NaN,12-Jun-2026
11717,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,NaN,Yes,19,...,19,416.89,0,0,0,0,0,0,NaN,12-Jun-2026

# Saving RSVD file

In [5]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
input_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\reserved_inventory\pattex_reserved_inventory.csv"

# -------- BASE OUTPUT PATH --------
base_output_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\reserved_inventory"

# -------- READ FILE --------
df = pd.read_csv(input_path)

# -------- GET TODAY DATE --------
today = datetime.today()

day = today.day
month_num = today.month
year = today.year

# Convert month → apr, mar, etc.
month_name = today.strftime("%b").lower()

# -------- CREATE FOLDER PATH --------
year_path = os.path.join(base_output_path, str(year))
month_path = os.path.join(year_path, month_name)

# Create folders if not exist
os.makedirs(month_path, exist_ok=True)

# -------- CREATE FILE NAME --------
file_name = f"reserved_inventory_Pattex_{day:02d}-{month_name}-{year}.csv"

output_path = os.path.join(month_path, file_name)

# -------- SAVE FILE --------
df.to_csv(output_path, index=False)

print("✅ File saved at:", output_path)

✅ File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\reserved_inventory\2026\jun\reserved_inventory_Pattex_12-jun-2026.csv

## Read reserved inventory

In [6]:
import os
import pandas as pd
from datetime import datetime, timedelta
import re

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\reserved_inventory"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP THROUGH SELECTED FOLDERS --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        file_path = os.path.join(folder_path, file)

        if file.endswith(".csv"):
            df = pd.read_csv(file_path)

        elif file.endswith(".xlsx") or file.endswith(".xls"):
            df = pd.read_excel(file_path)

        else:
            continue

        # -------- EXTRACT DATE FROM FILENAME --------
        match = re.search(r"\d{1,2}-[A-Za-z]{3}-\d{4}", file)

        if match:
            file_date = pd.to_datetime(
                match.group(), format="%d-%b-%Y"
            ).strftime("%d-%b-%Y")

            df["Date"] = file_date

        df_list.append(df)

# -------- COMBINE --------
df_rsv = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_rsv.empty:
    df_rsv = df_rsv[
        df_rsv['product-name'].str.contains('pattex|pritt', case=False, na=False)
    ]

print("Total rows loaded:", len(df_rsv))

Folders to read: [(2026, 6)]
Total rows loaded: 145

In [7]:
df_rsv

,sku,fnsku,asin,product-name,reserved_qty,reserved_customerorders,reserved_fc-transfers,reserved_fc-processing,program,Date
69,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",1,0,0,1,NaN,01-Jun-2026
70,30137844,X001ZD8NT9,B08B4T7CXB,PATTEX DOUBLE SIDE FOAM TAPE=80KG-,2,0,0,2,NaN,01-Jun-2026
71,30137836,X001ZD6SC3,B09KCFHH3T,"Pattex Super Glue Mini Dose, Strong All Purpos...",2,0,0,2,NaN,01-Jun-2026
72,30137846,X0020MHC0P,B08MXD1DCV,Henkel Pattex Tube Classic 50g,1,0,0,1,NaN,01-Jun-2026
73,30137853,X001ZD8LFF,B08W1WTZGB,Pattex PL 250 (Construction Adhesive) Is a pro...,7,0,0,7,NaN,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...
1194,30157619,X002G3GJ1V,B08XRX1PNS,Pattex PU Foam Pro Max Spray 750ml | High Yiel...,1,0,0,1,NaN,12-Jun-2026
1203,90102778,X0025X8SLV,B0DDGZBDG8,"Pattex SL212 Acetoxy Sealant (White) | UV, Wat...",1,0,0,1,NaN,12-Jun-2026
1204,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",1,0,0,1,NaN,12-Jun-2026
1205,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",1,0,0,1,NaN,12-Jun-2026
1207,90102777,X0025X5OPT,B0DDH9KH86,Pattex SL212 Acetoxy Silicone Sealant (Transpa...,1,0,0,1,NaN,12-Jun-2026

In [8]:
df_mng

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,afn-total-quantity,per-unit-volume,afn-inbound-working-quantity,afn-inbound-shipped-quantity,afn-inbound-receiving-quantity,afn-researching-quantity,afn-reserved-future-supply,afn-future-supply-buyable,store,Date
654,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,NaN,Yes,1,...,1,447.20,0,0,0,0,0,0,NaN,01-Jun-2026
655,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,NaN,Yes,59,...,59,513.41,0,0,0,0,0,0,NaN,01-Jun-2026
656,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,NaN,Yes,59,...,59,442.78,0,0,0,0,0,0,NaN,01-Jun-2026
657,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,NaN,Yes,63,...,63,233.68,0,0,0,0,0,0,NaN,01-Jun-2026
658,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,NaN,Yes,60,...,60,445.40,0,0,0,0,0,0,NaN,01-Jun-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11711,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,NaN,Yes,16,...,16,306.27,0,0,0,0,0,0,NaN,12-Jun-2026
11712,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,NaN,Yes,20,...,20,468.01,0,0,0,0,0,0,NaN,12-Jun-2026
11715,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,NaN,Yes,20,...,20,158.30,0,0,0,0,0,0,NaN,12-Jun-2026
11716,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,NaN,Yes,16,...,16,200.09,0,0,0,0,0,0,NaN,12-Jun-2026
11717,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,NaN,Yes,19,...,19,416.89,0,0,0,0,0,0,NaN,12-Jun-2026

## Merge manage FBA and reserved inventory

In [9]:
cols_to_merge = [
    'asin',
    'reserved_qty',
    'reserved_customerorders',
    'reserved_fc-transfers',
    'reserved_fc-processing'
]

# Create temporary datetime columns
df_mng["Date_temp"] = pd.to_datetime(df_mng["Date"], format="mixed", dayfirst=True)
df_rsv["Date_temp"] = pd.to_datetime(df_rsv["Date"], format="mixed", dayfirst=True)

# Merge on asin + date
df_inv = df_mng.merge(
    df_rsv[cols_to_merge + ["Date_temp"]],
    left_on=["asin", "Date_temp"],
    right_on=["asin", "Date_temp"],
    how="left"
)

# Remove temporary columns
df_inv.drop(columns=["Date_temp"], inplace=True)
df_rsv.drop(columns=["Date_temp"], inplace=True)

# Fill missing values
df_inv = df_inv.fillna(0)

In [10]:
df_inv['Available Inventory'] = df_inv['afn-fulfillable-quantity'] + df_inv['reserved_fc-transfers']

In [11]:
df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,afn-researching-quantity,afn-reserved-future-supply,afn-future-supply-buyable,store,Date,reserved_qty,reserved_customerorders,reserved_fc-transfers,reserved_fc-processing,Available Inventory
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,0,0,0,0.0,01-Jun-2026,1.0,0.0,0.0,1.0,0.0
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,0,0,0,0.0,01-Jun-2026,0.0,0.0,0.0,0.0,59.0
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,0,0,0,0.0,01-Jun-2026,0.0,0.0,0.0,0.0,59.0
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,0,0,0,0.0,01-Jun-2026,3.0,0.0,0.0,3.0,60.0
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,0,0,0,0.0,01-Jun-2026,0.0,0.0,0.0,0.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,0,0,0,0.0,12-Jun-2026,1.0,0.0,0.0,1.0,15.0
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,0,0,0,0.0,12-Jun-2026,0.0,0.0,0.0,0.0,20.0
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,0,0,0,0.0,12-Jun-2026,0.0,0.0,0.0,0.0,20.0
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,0,0,0,0.0,12-Jun-2026,1.0,0.0,0.0,1.0,15.0
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,0,0,0,0.0,12-Jun-2026,0.0,0.0,0.0,0.0,19.0

## DOS

## Save FBA inventory

In [12]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
input_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\fba_inventory\pattex_FBA_inventory.csv"

# -------- BASE OUTPUT PATH --------
base_output_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\fba_inventory"

# -------- READ FILE --------
df = pd.read_csv(input_path)

# -------- GET TODAY DATE --------
today = datetime.today()

day = today.day
month_num = today.month
year = today.year

# Convert month → apr, mar, etc.
month_name = today.strftime("%b").lower()

# -------- CREATE FOLDER PATH --------
year_path = os.path.join(base_output_path, str(year))
month_path = os.path.join(year_path, month_name)

# Create folders if not exist
os.makedirs(month_path, exist_ok=True)

# -------- CREATE FILE NAME --------
file_name = f"fba_inventory_Pattex_{day:02d}-{month_name}-{year}.csv"

output_path = os.path.join(month_path, file_name)

# -------- SAVE FILE --------
df.to_csv(output_path, index=False)

print("✅ File saved at:", output_path)

✅ File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\fba_inventory\2026\jun\fba_inventory_Pattex_12-jun-2026.csv

In [13]:
import os
import pandas as pd
from datetime import datetime, timedelta
import re

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\fba_inventory"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP THROUGH SELECTED FOLDERS --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        file_path = os.path.join(folder_path, file)

        if file.endswith(".csv"):
            df = pd.read_csv(file_path)

        elif file.endswith(".xlsx") or file.endswith(".xls"):
            df = pd.read_excel(file_path)

        else:
            continue

        # -------- EXTRACT DATE FROM FILENAME --------
        match = re.search(r"\d{1,2}-[A-Za-z]{3}-\d{4}", file)

        if match:
            file_date = pd.to_datetime(
                match.group(), format="%d-%b-%Y"
            ).strftime("%d-%b-%Y")

            df["Date"] = file_date

        df_list.append(df)

# -------- COMBINE --------
df_fba = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_fba.empty:
    df_fba = df_fba[
        df_fba['product-name'].str.contains('pattex|pritt', case=False, na=False)
    ]

print("Total rows loaded:", len(df_fba))

Folders to read: [(2026, 6)]
Total rows loaded: 825

In [14]:
cols_to_merge = [
    'asin',
    'units-shipped-t30',
    'units-shipped-t60',
    'units-shipped-t90',
    'inbound-quantity'
]

# Create temporary datetime columns
df_inv["Date_temp"] = pd.to_datetime(df_inv["Date"], format="mixed", dayfirst=True)
df_fba["Date_temp"] = pd.to_datetime(df_fba["Date"], format="mixed", dayfirst=True)

# -------- FIX DUPLICATES IN FBA --------
df_fba_clean = (
    df_fba[cols_to_merge + ["Date_temp"]]
    .groupby(["asin", "Date_temp"], as_index=False)
    .sum()
)

# -------- MERGE --------
df_inv = df_inv.merge(
    df_fba_clean,
    left_on=["asin", "Date_temp"],
    right_on=["asin", "Date_temp"],
    how="left"
)

# -------- CLEANUP --------
df_inv.drop(columns=["Date_temp"], inplace=True)
df_fba.drop(columns=["Date_temp"], inplace=True)

df_inv = df_inv.rename(columns={'inbound-quantity': 'Open POs'})
df_inv = df_inv.fillna(0)

In [15]:

df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,Date,reserved_qty,reserved_customerorders,reserved_fc-transfers,reserved_fc-processing,Available Inventory,units-shipped-t30,units-shipped-t60,units-shipped-t90,Open POs
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,01-Jun-2026,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,01-Jun-2026,0.0,0.0,0.0,0.0,59.0,0.0,0.0,0.0,0.0
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,01-Jun-2026,0.0,0.0,0.0,0.0,59.0,1.0,15.0,17.0,0.0
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,01-Jun-2026,3.0,0.0,0.0,3.0,60.0,5.0,5.0,5.0,0.0
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,01-Jun-2026,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,12-Jun-2026,1.0,0.0,0.0,1.0,15.0,3.0,4.0,4.0,0.0
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,12-Jun-2026,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,12-Jun-2026,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,12-Jun-2026,1.0,0.0,0.0,1.0,15.0,5.0,7.0,17.0,0.0
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,12-Jun-2026,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0

In [16]:
df_inv['sell_through'] = (
    (df_inv['units-shipped-t30'] / 30) +
    (df_inv['units-shipped-t60'] / 60) +
    (df_inv['units-shipped-t90'] / 90)
) / 3

df_inv.loc[df_inv['sell_through'] == 0, 'sell_through'] = 1
df_inv['sell_through'] = df_inv['sell_through'].round(2)

In [17]:
df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,reserved_qty,reserved_customerorders,reserved_fc-transfers,reserved_fc-processing,Available Inventory,units-shipped-t30,units-shipped-t60,units-shipped-t90,Open POs,sell_through
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.00
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,0.0,0.0,0.0,0.0,59.0,0.0,0.0,0.0,0.0,1.00
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,0.0,0.0,0.0,0.0,59.0,1.0,15.0,17.0,0.0,0.16
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,3.0,0.0,0.0,3.0,60.0,5.0,5.0,5.0,0.0,0.10
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,1.0,0.0,0.0,1.0,15.0,3.0,4.0,4.0,0.0,0.07
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,1.00
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,1.00
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,1.0,0.0,0.0,1.0,15.0,5.0,7.0,17.0,0.0,0.16
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,0.0,0.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,1.00

In [18]:
import numpy as np
# df_inv['DOS'] = df_inv['Available Inventory'] / df_inv['sell_through']
# df_inv['DOS'] = df_inv['DOS'].astype(int)

df_inv['DOS'] = np.where(
                                df_inv['sell_through'] > 0.1,
                                df_inv['Available Inventory'] / df_inv['sell_through'],0)
df_inv['DOS'] = df_inv['DOS'].astype(int)

## Stock Status

In [19]:
df_inv['min_available_qty'] = (df_inv['sell_through'] * 30).round(2)
df_inv['max_available_qty'] = (df_inv['sell_through'] * 60).round(2)

import numpy as np

conditions = [
    (df_inv['Available Inventory'] > df_inv['min_available_qty']) &
    (df_inv['Available Inventory'] <= df_inv['max_available_qty']),
    
    (df_inv['Available Inventory'] > df_inv['max_available_qty']),
    
    (df_inv['Available Inventory'] <= df_inv['min_available_qty'])
]

choices = [
    'Healthy',
    'Overstock',
    'Understock'
]

df_inv['Stock_Status'] = np.select(conditions, choices, default='Unknown')

## Instock Rate

## Save inventory ledger

In [20]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\inventory_ledger\inventory_ledger_Pattex.csv"

# -------- BASE DESTINATION PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\inventory_ledger"

# -------- GET TODAY DATE --------
today = datetime.today()
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

month_name = month_map[month]  # folder name (lowercase)
month_name_cap = month_name.capitalize()  # for file name (Mar)

# -------- CREATE FOLDER PATH --------
folder_path = os.path.join(base_path, str(year), month_name)

# Create folder if not exists
os.makedirs(folder_path, exist_ok=True)

# -------- READ FILE --------
df = pd.read_csv(source_file)

# -------- CREATE FILE NAME --------
file_name = f"inventory_ledger_Pattex_{month_name_cap}-{year}.csv"

# -------- SAVE FILE --------
save_path = os.path.join(folder_path, file_name)
df.to_csv(save_path, index=False)

print("File saved at:", save_path)

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\inventory_ledger\2026\jun\inventory_ledger_Pattex_Jun-2026.csv

## Read inventory ledger file

In [21]:
import os
import pandas as pd
from datetime import datetime, timedelta

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\inventory\inventory_ledger"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP THROUGH SELECTED FOLDERS --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        if file.endswith(".csv"):

            file_path = os.path.join(folder_path, file)

            df = pd.read_csv(file_path)
            df_list.append(df)

# -------- COMBINE --------
df_ledger = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_ledger.empty:
    df_ledger = df_ledger[
        df_ledger['Title'].str.contains('pattex|pritt', case=False, na=False)
    ]

    # -------- DATE FORMAT --------
    df_ledger["Date"] = pd.to_datetime(
        df_ledger["Date"],
        format="%m/%d/%Y",
        errors="coerce"
    ).dt.strftime("%d-%b-%Y")

print("Total ledger rows:", len(df_ledger))

Folders to read: [(2026, 6)]
Total ledger rows: 584

In [22]:
df_ledger.columns

Index(['Date', 'FNSKU', 'ASIN', 'MSKU', 'Title', 'Disposition',
       'Starting Warehouse Balance', 'In Transit Between Warehouses',
       'Receipts', 'Customer Shipments', 'Customer Returns', 'Vendor Returns',
       'Warehouse Transfer In/Out', 'Found', 'Lost', 'Damaged', 'Disposed',
       'Other Events', 'Ending Warehouse Balance', 'Unknown Events',
       'Location'],
      dtype='object')

In [23]:
df_inv.columns

Index(['sku', 'fnsku', 'asin', 'product-name', 'condition', 'your-price',
       'mfn-listing-exists', 'mfn-fulfillable-quantity', 'afn-listing-exists',
       'afn-warehouse-quantity', 'afn-fulfillable-quantity',
       'afn-unsellable-quantity', 'afn-reserved-quantity',
       'afn-total-quantity', 'per-unit-volume', 'afn-inbound-working-quantity',
       'afn-inbound-shipped-quantity', 'afn-inbound-receiving-quantity',
       'afn-researching-quantity', 'afn-reserved-future-supply',
       'afn-future-supply-buyable', 'store', 'Date', 'reserved_qty',
       'reserved_customerorders', 'reserved_fc-transfers',
       'reserved_fc-processing', 'Available Inventory', 'units-shipped-t30',
       'units-shipped-t60', 'units-shipped-t90', 'Open POs', 'sell_through',
       'DOS', 'min_available_qty', 'max_available_qty', 'Stock_Status'],
      dtype='object')

In [24]:
import pandas as pd

# -------------------------------
# STEP 1: Prepare df_ledger
# -------------------------------

# Temporary datetime column (keeps original Date intact)
df_ledger["Date_temp"] = pd.to_datetime(df_ledger["Date"], format="%d-%b-%Y")

# Create year_month column
df_ledger["year_month"] = df_ledger["Date_temp"].dt.to_period("M")

# Ensure ASIN column name matches
df_ledger.rename(columns={'ASIN': 'asin'}, inplace=True)

# -------------------------------
# STEP 2: Merge min_available_qty
# -------------------------------

df_ledger = df_ledger.merge(
    df_inv[['asin', 'min_available_qty']],
    on='asin',
    how='left'
)

# -------------------------------
# STEP 3: Create in-stock flag
# -------------------------------

df_ledger['in_stock_flag'] = (
    df_ledger['Ending Warehouse Balance'] > df_ledger['min_available_qty']
).astype(int)

# -------------------------------
# STEP 4: Calculate Instock Days
# -------------------------------

# Days in stock
days_instock = (
    df_ledger[df_ledger['in_stock_flag'] == 1]
    .groupby(['asin', 'year_month'])['Date_temp']
    .nunique()
    .reset_index(name='days_instock')
)

# Total days
total_days = (
    df_ledger.groupby(['asin', 'year_month'])['Date_temp']
    .nunique()
    .reset_index(name='total_days')
)

# Merge both
Instock_Rate_df = days_instock.merge(
    total_days,
    on=['asin', 'year_month'],
    how='right'
)

# -------------------------------
# STEP 5: Calculate Instock Rate
# -------------------------------

Instock_Rate_df['Instock Rate'] = (
    Instock_Rate_df['days_instock'].fillna(0) /
    Instock_Rate_df['total_days'] * 100
).round(2)

# Keep only required columns
Instock_Rate_df = Instock_Rate_df[['asin', 'year_month', 'Instock Rate']]

# -------------------------------
# STEP 6: Prepare df_inv for merge
# -------------------------------
df_inv["Date_temp"] = pd.to_datetime(
    df_inv["Date"],
    format='mixed',
    dayfirst=True,
    errors='coerce'   # prevents crash
)
df_inv["year_month"] = df_inv["Date_temp"].dt.to_period("M")

# -------------------------------
# STEP 7: Correct Merge (FIXED)
# -------------------------------

df_inv = df_inv.merge(
    Instock_Rate_df,
    on=['asin', 'year_month'],   # ✅ FIX: include year_month
    how='left'
)

# -------------------------------
# STEP 8: Fill missing values
# -------------------------------

df_inv['Instock Rate'] = df_inv['Instock Rate'].fillna(0)

# -------------------------------
# STEP 9: Cleanup
# -------------------------------

df_ledger.drop(columns=["Date_temp", "year_month"], inplace=True)
df_inv.drop(columns=["Date_temp", "year_month"], inplace=True)

In [25]:
df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,units-shipped-t30,units-shipped-t60,units-shipped-t90,Open POs,sell_through,DOS,min_available_qty,max_available_qty,Stock_Status,Instock Rate
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,0.0,0.0,0.0,0.0,1.00,0,30.0,60.0,Understock,0.0
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,0.0,0.0,0.0,0.0,1.00,59,30.0,60.0,Healthy,100.0
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,1.0,15.0,17.0,0.0,0.16,368,4.8,9.6,Overstock,100.0
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,5.0,5.0,5.0,0.0,0.10,0,3.0,6.0,Overstock,100.0
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,0.0,0.0,0.0,0.0,1.00,60,30.0,60.0,Healthy,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,3.0,4.0,4.0,0.0,0.07,0,2.1,4.2,Overstock,100.0
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,1.00,20,30.0,60.0,Understock,0.0
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,1.00,20,30.0,60.0,Understock,100.0
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,5.0,7.0,17.0,0.0,0.16,93,4.8,9.6,Overstock,100.0
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,0.0,0.0,0.0,0.0,1.00,19,30.0,60.0,Understock,100.0

In [26]:
# import pandas as pd

# # Temporary datetime column (keeps original Date intact)
# df_ledger["Date_temp"] = pd.to_datetime(df_ledger["Date"], format="%d-%b-%Y")

# # Create month column
# df_ledger["year_month"] = df_ledger["Date_temp"].dt.to_period("M")

# # Ensure ASIN column name
# df_ledger.rename(columns={'ASIN': 'asin'}, inplace=True)

# # Merge min_available_qty
# df_ledger = df_ledger.merge(
#     df_inv[['asin', 'min_available_qty']],
#     on='asin',
#     how='left'
# )

# # Create in-stock flag (CORE LOGIC UNCHANGED)
# df_ledger['in_stock_flag'] = (
#     df_ledger['Ending Warehouse Balance'] > df_ledger['min_available_qty']
# ).astype(int)

# # ---- COUNT UNIQUE DAYS PER ASIN PER MONTH ----
# days_instock = (
#     df_ledger[df_ledger['in_stock_flag'] == 1]
#     .groupby(['asin','year_month'])['Date_temp']
#     .nunique()
#     .reset_index(name='days_instock')
# )

# total_days = (
#     df_ledger.groupby(['asin','year_month'])['Date_temp']
#     .nunique()
#     .reset_index(name='total_days')
# )

# # Merge counts
# Instock_Rate_df = days_instock.merge(
#     total_days,
#     on=['asin','year_month'],
#     how='right'
# )

# # Calculate rate
# Instock_Rate_df['Instock Rate'] = (
#     Instock_Rate_df['days_instock'].fillna(0) /
#     Instock_Rate_df['total_days'] * 100
# ).round(2)

# # Keep only needed columns
# Instock_Rate_df = Instock_Rate_df[['asin','year_month','Instock Rate']]

# # Merge back to df_inv
# df_inv = df_inv.merge(Instock_Rate_df, on='asin', how='left')

# # Fill missing values
# df_inv['Instock Rate'] = df_inv['Instock Rate'].fillna(0)

# # Remove temp columns
# df_ledger.drop(columns=["Date_temp","year_month"], inplace=True)

In [27]:
df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,units-shipped-t30,units-shipped-t60,units-shipped-t90,Open POs,sell_through,DOS,min_available_qty,max_available_qty,Stock_Status,Instock Rate
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,0.0,0.0,0.0,0.0,1.00,0,30.0,60.0,Understock,0.0
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,0.0,0.0,0.0,0.0,1.00,59,30.0,60.0,Healthy,100.0
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,1.0,15.0,17.0,0.0,0.16,368,4.8,9.6,Overstock,100.0
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,5.0,5.0,5.0,0.0,0.10,0,3.0,6.0,Overstock,100.0
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,0.0,0.0,0.0,0.0,1.00,60,30.0,60.0,Healthy,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,3.0,4.0,4.0,0.0,0.07,0,2.1,4.2,Overstock,100.0
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,1.00,20,30.0,60.0,Understock,0.0
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,0.0,0.0,0.0,0.0,1.00,20,30.0,60.0,Understock,100.0
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,5.0,7.0,17.0,0.0,0.16,93,4.8,9.6,Overstock,100.0
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,0.0,0.0,0.0,0.0,1.00,19,30.0,60.0,Understock,100.0

## OOS wt/wtout Open POs

In [28]:
df_inv['Open POs'] = pd.to_numeric(df_inv['Open POs'], errors='coerce')
df_inv['Open POs'] = df_inv['Open POs'].fillna(0)
df_inv['No/Low Stock wt Open POs'] = (
    (df_inv['Stock_Status'] == 'Understock') &
    (df_inv['Open POs'] > 0)
).astype(int)
df_inv['No/Low Stock wt no Open POs'] = (
    (df_inv['Stock_Status'] == 'Understock') &
    (df_inv['Open POs'] <= 0)
).astype(int)

## last 30 day sale (logic will change after 30 days)

## save orders file

In [29]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\revenue\pattex_orders.txt"

# -------- BASE DESTINATION PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\revenue\orders"

# -------- GET TODAY DATE --------
today = datetime.today()
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

month_name = month_map[month]  # folder name (lowercase)

# -------- CREATE FOLDER PATH --------
folder_path = os.path.join(base_path, str(year), month_name)

# Create folder if not exists
os.makedirs(folder_path, exist_ok=True)

# -------- READ FILE --------
df = pd.read_csv(source_file, sep=None, engine='python', encoding='utf-8')

# -------- CREATE FILE NAME --------
file_name = f"pattex_orders_{month_name}_{year}.txt"
save_path = os.path.join(folder_path, file_name)

df.to_csv(save_path, sep='\t', index=False)

print("File saved at:", save_path)

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\revenue\orders\2026\jun\pattex_orders_jun_2026.txt

## Read orders File

In [30]:
import os
import pandas as pd
from datetime import datetime, timedelta

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\revenue\orders"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP THROUGH SELECTED FOLDERS --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        if file.endswith(".txt"):

            file_path = os.path.join(folder_path, file)

            df = pd.read_csv(file_path, sep="\t")
            df_list.append(df)

# -------- COMBINE --------
df_orders = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_orders.empty:
    df_orders = df_orders[
        df_orders['product-name'].str.contains('pattex|pritt', case=False, na=False)
    ]

    # -------- DATE FORMAT --------
    df_orders["purchase-date"] = pd.to_datetime(
        df_orders["purchase-date"], errors="coerce"
    ).dt.strftime("%d-%b-%Y")

print("Total orders rows:", len(df_orders))

Folders to read: [(2026, 6)]
Total orders rows: 291

In [31]:
df_orders= df_orders[
    df_orders['sales-channel'].str.lower() == 'amazon.ae'
]

In [32]:
df_orders

,amazon-order-id,merchant-order-id,purchase-date,last-updated-date,order-status,fulfillment-channel,sales-channel,order-channel,url,ship-service-level,...,gift-wrap-price,gift-wrap-tax,item-promotion-discount,ship-promotion-discount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,order-item-id
1,402-1283747-1884310,402-1283747-1884310,12-Jun-2026,2026-06-12T02:44:28+00:00,Pending,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Sharjah,NaN,NaN,AE,NaN,64229770651482
6,404-8451473-1208352,404-8451473-1208352,11-Jun-2026,2026-06-11T22:17:09+00:00,Pending,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Ras Al Khaimah,NaN,NaN,AE,NaN,64224809803922
8,404-1815593-3088334,404-1815593-3088334,11-Jun-2026,2026-06-11T22:06:21+00:00,Pending,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,عجمان,NaN,NaN,AE,NaN,64228000021282
11,407-8830582-7428339,407-8830582-7428339,11-Jun-2026,2026-06-11T21:15:26+00:00,Pending,Amazon,Amazon.ae,NaN,NaN,Expedited,...,NaN,NaN,NaN,NaN,Abu Dhabi,NaN,NaN,AE,NaN,64226476590962
12,408-8025785-6243506,408-8025785-6243506,11-Jun-2026,2026-06-11T21:36:45+00:00,Pending,Amazon,Amazon.ae,NaN,NaN,Expedited,...,NaN,NaN,NaN,0.62,Dubai,NaN,NaN,AE,NaN,64225729873202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,406-4115352-1725947,406-4115352-1725947,01-Jun-2026,2026-06-02T17:31:38+00:00,Shipped,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Dubai,NaN,NaN,AE,NaN,63792898008082
954,171-5328729-2919510,171-5328729-2919510,01-Jun-2026,2026-06-01T12:45:22+00:00,Shipped,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Dubai,NaN,NaN,AE,NaN,63791362002122
960,406-5875183-9609931,406-5875183-9609931,01-Jun-2026,2026-06-01T12:45:28+00:00,Shipped,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Abu Dhabi,NaN,NaN,AE,NaN,63787239724962
961,405-0938750-3212361,405-0938750-3212361,31-May-2026,2026-06-01T07:27:03+00:00,Shipped,Amazon,Amazon.ae,NaN,NaN,Expedited,...,NaN,NaN,NaN,2.50,Abu Dhabi,NaN,NaN,AE,NaN,63785723304162
967,171-4259565-4726740,171-4259565-4726740,31-May-2026,2026-06-01T12:45:28+00:00,Shipped,Amazon,Amazon.ae,NaN,NaN,NextDay,...,NaN,NaN,NaN,NaN,Dubai,NaN,NaN,AE,NaN,63785526228442

In [33]:
# -------- PREPARE ORDERS DATA --------

# Convert purchase-date to same Date format
# df_orders["Date"] = pd.to_datetime(df_orders["purchase-date"]).dt.strftime("%d-%b-%Y")
df_orders["Date"] = pd.to_datetime(
    df_orders["purchase-date"], errors="coerce"
).dt.strftime("%d-%b-%Y")

# Aggregate sales per ASIN + Date
sales_df = (
    df_orders
    .groupby(["asin", "Date"], as_index=False)
    .agg({
        "item-price": "sum",
        "quantity": "sum"
    })
    .rename(columns={
        "item-price": "total_sales",
        "quantity": "total_units"
    })
)

# -------- MERGE INTO INVENTORY --------
df_inv = df_inv.merge(
    sales_df,
    on=["asin", "Date"],
    how="left"
)

# Fill missing values
df_inv[["total_sales", "total_units"]] = df_inv[["total_sales", "total_units"]].fillna(0)

In [34]:
df_inv

,sku,fnsku,asin,product-name,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,...,sell_through,DOS,min_available_qty,max_available_qty,Stock_Status,Instock Rate,No/Low Stock wt Open POs,No/Low Stock wt no Open POs,total_sales,total_units
0,30137825,X001ZD8UDN,B09KCJLD4J,"Pritt Glue Stick, Safe & Child-Friendly Craft ...",New,26.00,No,0.0,Yes,1,...,1.00,0,30.0,60.0,Understock,0.0,0,1,0.0,0.0
1,30137829,X001ZD8VU5,B09KCHP2CV,PATTEX SG LIQUID TUBE 1 x 3g,New,30.99,No,0.0,Yes,59,...,1.00,59,30.0,60.0,Healthy,100.0,0,0,0.0,0.0
2,30137830,X001ZD88ET,B0BG2MZ1ZX,"Pattex Superglue Liquide Control, Clear Glue f...",New,25.49,No,0.0,Yes,59,...,0.16,368,4.8,9.6,Overstock,100.0,0,0,0.0,0.0
3,30137831,X001ZD8PU1,B09KCHGRZF,"Pattex Super Glue Power Gel, Strong All Purpos...",New,25.49,No,0.0,Yes,63,...,0.10,0,3.0,6.0,Overstock,100.0,0,0,0.0,0.0
4,30137832,X001ZD6QI9,B09KCGPSPG,Pattex Super Glue Power Gel Control | All Purp...,New,24.99,No,0.0,Yes,60,...,1.00,60,30.0,60.0,Healthy,100.0,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,17.49,No,0.0,Yes,16,...,0.07,0,2.1,4.2,Overstock,100.0,0,0,0.0,0.0
704,90102988,X0028AHAN3,B0DVZ32W2B,Pritt Glue Stick Original SRP 8x11g,New,50.00,No,0.0,Yes,20,...,1.00,20,30.0,60.0,Understock,0.0,0,1,0.0,0.0
705,90103079,X002D88KDT,B0FKBLF14N,"Pritt Original Glue Stick - 11g | Strong-Hold,...",New,18.99,No,0.0,Yes,20,...,1.00,20,30.0,60.0,Understock,100.0,0,1,0.0,0.0
706,90103234,X002IJ7TS5,B0GN246XDP,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,14.49,No,0.0,Yes,16,...,0.16,93,4.8,9.6,Overstock,100.0,0,0,0.0,0.0
707,90103235,X002IIYDHV,B0GN2C54ZK,"Pritt Original Glue Stick - 43g | Strong-Hold,...",New,35.99,No,0.0,Yes,19,...,1.00,19,30.0,60.0,Understock,100.0,0,1,0.0,0.0

In [35]:
df_inv['total_sales'].sum()

np.float64(10043.800000000001)

In [36]:
df_inv['total_units'].sum()

np.float64(406.0)

In [37]:
import pandas as pd
df_inv = df_inv.drop(columns=['product-name'])
# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")
df_inv.rename(columns={"asin": "ASIN"}, inplace=True)

# Convert ASIN to uppercase in both
df_inv["ASIN"] = df_inv["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
df_inv = df_inv.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
df_inv["Pack Size"] = df_inv["Pack Size"].fillna(0).astype(int)
cols_to_fill = ["Product Name", "Category", "Pack Type", "Pack Size", "SC Ideal Price", "VC Ideal Price"]
df_inv[cols_to_fill] = df_inv[cols_to_fill].astype(str)
df_inv.loc[df_inv["ASIN"] == "SPONSORED BRAND", cols_to_fill] = "SPONSORED BRAND"

df_inv.rename(columns= {'Category' : 'Product Category'},inplace= True)

print("Merge completed ✅")

Merge completed ✅

In [38]:
df_inv['Sales Channel'] = "Seller Central"

In [39]:

cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]
cols = [
    "Product Name",
    "Product Category",
    "Pack Type"
]
for col in cols_to_clean:
    df_inv[col] = (
        df_inv[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )

df_inv[cols] = df_inv[cols].fillna("Unavailable")
df_inv = df_inv.fillna(0)

In [40]:
asins_to_remove = [
    "B0DVZ32W2B",
    "B0DVZ5F9D4",
    "B08MXC4KYK",
    "B09KCJLD4J"
]

df_inv = df_inv[~df_inv["ASIN"].isin(asins_to_remove)]
df_inv = df_inv.fillna(0)

In [41]:
df_inv[["SC Ideal Price", "VC Ideal Price"]] = (
    df_inv[["SC Ideal Price", "VC Ideal Price"]]
    .replace("nan", pd.NA).fillna(0)               # fill with 0
)

In [42]:
df_inv['Brand'] = "Pattex"

In [43]:
df_inv

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,total_sales,total_units,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel,Brand
1,30137829,X001ZD8VU5,B09KCHP2CV,New,30.99,No,0.0,Yes,59,59,...,0.0,0.0,Pattex Superglue Liquid,All Purpose SuperGlue,Base ASIN,1,25.00,6.90,Seller Central,Pattex
2,30137830,X001ZD88ET,B0BG2MZ1ZX,New,25.49,No,0.0,Yes,59,59,...,0.0,0.0,Pattex Superglue Liquid Control,All Purpose SuperGlue,Base ASIN,1,24.00,9.90,Seller Central,Pattex
3,30137831,X001ZD8PU1,B09KCHGRZF,New,25.49,No,0.0,Yes,63,60,...,0.0,0.0,Pattex Super Glue Power Gel Tube,All Purpose SuperGlue,Base ASIN,1,24.00,7.90,Seller Central,Pattex
4,30137832,X001ZD6QI9,B09KCGPSPG,New,24.99,No,0.0,Yes,60,60,...,0.0,0.0,Pattex Super Glue Power Gel Control,All Purpose SuperGlue,Base ASIN,1,25.00,10.90,Seller Central,Pattex
5,30137833,X001ZD8G1T,B0BG2KWV13,New,24.99,No,0.0,Yes,40,40,...,0.0,0.0,Pattex Super Glue All Plastics,All Purpose SuperGlue,Base ASIN,1,25.00,12.50,Seller Central,Pattex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,90102779,X0025Y265T,B0DDGX2SFH,New,50.99,No,0.0,Yes,50,50,...,0.0,0.0,Pattex SL100 Acrylic Sealant (White),Sealant,Physical-Bundle,2,50.99,39.00,Seller Central,Pattex
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,New,17.49,No,0.0,Yes,16,15,...,0.0,0.0,Pritt Glue stick 6X11g,Pritt Glue Stick,Physical-Bundle,6,0,18.50,Seller Central,Pattex
705,90103079,X002D88KDT,B0FKBLF14N,New,18.99,No,0.0,Yes,20,20,...,0.0,0.0,Pritt Original 4x11gm,Pritt Glue Stick,Physical-Bundle,4,0,12.50,Seller Central,Pattex
706,90103234,X002IJ7TS5,B0GN246XDP,New,14.49,No,0.0,Yes,16,15,...,0.0,0.0,Pritt Glue Stick Original 2x43g,Pritt Glue Stick,Physical-Bundle,2,0,0,Seller Central,Pattex
707,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0,Seller Central,Pattex

## Save the dataframe

In [44]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\inventory\pattex_inventory_seller_central.csv"

# Read existing CSV
df = pd.read_csv(file_path)

previous_rows = len(df)

# Create temp column (DO NOT modify original Date)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

# Get today's date (normalized)
today = pd.Timestamp.today().normalize()
current_day = today.day

# First day of current month
first_day_current_month = today.replace(day=1)

# Apply logic
if current_day <= 3:
    # Keep only <= last day of previous-to-previous month
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    # Remove current month data
    df = df[df['_temp_date'] < first_day_current_month]

# Metrics after deletion
current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare your new dataframe (ASSUMED NAME: df_inv)
df_inv['_temp_date'] = pd.to_datetime(
    df_inv['Date'], format='%d-%b-%Y', errors='coerce'
).dt.normalize()

rows_appended = len(df_inv)

# Append new data
df = pd.concat([df, df_inv], ignore_index=True)

final_rows = len(df)

# Drop temp column before saving
df.drop(columns=['_temp_date'], inplace=True)

# Save back
df.to_csv(file_path, index=False)

# Metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 4997
Current rows: 4382
Rows deleted: 615
Rows appended: 672
Final rows: 5054

In [45]:
df1 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\inventory\pattex_inventory_seller_central.csv")
df2 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\inventory\output\pattex_inventory.csv")

In [46]:
df = pd.concat([df1,df2],ignore_index=True)
df = df.fillna(0)

In [47]:
df.to_csv("pattex_inventory.csv",index = False)

In [48]:
df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,Aged 90+ Days Sellable Inventory,Aged 90+ Days Sellable Units,Sellable Inventory Amount,Unsellable On Hand Inventory Amount,Unsellable On Hand Units,in_stock_flag,cumulative_instock_days,day_of_month,OOS Date,Date_temp
0,30137829,X001ZD8VU5,B09KCHP2CV,New,24.99,No,0.0,Yes,59.0,59.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
1,30137830,X001ZD88ET,B0BG2MZ1ZX,New,23.99,No,0.0,Yes,57.0,56.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
2,30137831,X001ZD8PU1,B09KCHGRZF,New,22.99,No,0.0,Yes,3.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
3,30137832,X001ZD6QI9,B09KCGPSPG,New,24.99,No,0.0,Yes,60.0,59.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,30137833,X001ZD8G1T,B0BG2KWV13,New,24.99,No,0.0,Yes,40.0,40.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12651,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,5.0,5.0,Instock,0.0
12652,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,6.0,6.0,Instock,0.0
12653,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,7.0,7.0,Instock,0.0
12654,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,8.0,8.0,Instock,0.0
12655,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,9.0,9.0,Instock,0.0

In [49]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_inventory = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_inventory.csv")
print(pattex_inventory.shape)
print(pattex_inventory['Date'].max())
# # -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_inventory):
    pattex_inventory.columns = (
        pattex_inventory.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_inventory

# Apply cleaning
pattex_inventory = clean_columns(pattex_inventory)
pattex_inventory.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Documents\pattex_inventory.csv",index = False)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\3324942129.py:4: DtypeWarning: Columns (0,1,3,5,7,57) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_inventory = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_inventory.csv")

(12656, 66)
31-May-2026

# Push the inventory to the azure

In [50]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_inventory = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_inventory.csv")
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_inventory):
    pattex_inventory.columns = (
        pattex_inventory.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_inventory

# Apply cleaning
pattex_inventory = clean_columns(pattex_inventory)

# -------- STEP 2: AZURE CONNECTION --------
connection_string = "DefaultEndpointsProtocol=https;AccountName=thriveclientdatabase;AccountKey=t3YQjkSXWXafdSIzp48QxNgmuW8BSh+6FzHaEy6VhGbgINYgo7Sica0BZw9sAKEPbwBcjqqhK5p6+AStuxDzSA==;EndpointSuffix=core.windows.net"
container_name = "thrive-client-pattex"
blob_name = "sanity_data/pattex_inventory.csv"   # e.g. folder/file.csv

# Create Blob Service Client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get Blob Client
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# -------- STEP 3: CONVERT DF TO CSV --------
csv_buffer = StringIO()
pattex_inventory.to_csv(csv_buffer, index=False)

# -------- STEP 4: UPLOAD TO AZURE --------
blob_client.upload_blob(csv_buffer.getvalue(), overwrite=True)

print("✅ DataFrame successfully uploaded to Azure Blob Storage!")

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\3427728272.py:4: DtypeWarning: Columns (0,1,3,5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_inventory = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_inventory.csv")

✅ DataFrame successfully uploaded to Azure Blob Storage!

# BuyBox

In [51]:
buybox_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\amazon_buybox_final_result.csv")

In [52]:
buybox_df

,Date,ASIN,Seller,Price,MOQ,BuyBox,Time,Title,Link
0,06-Mar-26,B0DDGRFJ5W,Amazon.ae,12.83,1,YES,NaN,NaN,NaN
1,06-Mar-26,B0DDGRFJ5W,ADD 2 CART_UAE,15.99,1,NO,NaN,NaN,NaN
2,06-Mar-26,B0DDGWXNHC,Amazon.ae,7..90,1,YES,NaN,NaN,NaN
3,06-Mar-26,B0BG2MZ1ZX,Amazon.ae,11,2,YES,NaN,NaN,NaN
4,06-Mar-26,B0BG2MZ1ZX,ADD 2 CART_UAE,23.99,1,NO,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
16634,12-Jun-2026,B09KCHP2CV,ADD 2 CART_UAE,.,1,NO,09:35:46,PATTEX SG LIQUID TUBE 1 x 3g,https://www.amazon.ae/dp/B09KCHP2CV
16635,12-Jun-2026,B0GN246XDP,ADD 2 CART_UAE,14.49,1,YES,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN246XDP
16636,12-Jun-2026,B0GN246XDP,Amazon.ae,.,1,NO,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN246XDP
16637,12-Jun-2026,B0GN2C54ZK,Amazon.ae,29.00,1,YES,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK
16638,12-Jun-2026,B0GN2C54ZK,ADD 2 CART_UAE,.,1,NO,09:35:46,"Pritt Original Glue Stick - 43g | Strong-Hold,...",https://www.amazon.ae/dp/B0GN2C54ZK

In [53]:
import pandas as pd

# buybox_df['Date'] = pd.to_datetime(buybox_df['Date'])

rows = []

for (asin, date), group in buybox_df.groupby(['ASIN','Date']):

    row = {
        "ASIN": asin,
        "Date": date,
        "Time": group['Time'].iloc[0],
        "Title": group['Title'].iloc[0],
        "Link": group['Link'].iloc[0]
    }

    # Owner
    owner = group[group['BuyBox'] == 'YES']

    if not owner.empty:
        owner = owner.iloc[0]
        row["Current Owner"] = owner["Seller"]
        row["Current Owner Price"] = owner["Price"]
        row["Current Owner MOQ"] = owner["MOQ"]

    # Hijackers
    hijackers = group[group['BuyBox'] != 'YES']

    for i, (_, r) in enumerate(hijackers.iterrows(), start=1):
        row[f'Hijacker {i}'] = r['Seller']
        row[f'Hijacker {i} Price'] = r['Price']
        row[f'Hijacker {i} MOQ'] = r['MOQ']

    rows.append(row)

buybox_transposed = pd.DataFrame(rows)

In [54]:
buybox_df = buybox_transposed.copy()

In [55]:
buybox_final_df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\inventory\pattex_inventory_seller_central.csv")

In [56]:
buybox_df = buybox_df.drop(columns=['Time', 'Title','Link'])

In [57]:
# buybox_final_df['Date'] = pd.to_datetime(
#     buybox_final_df['Date'],
#     format='mixed',
#     dayfirst=True
# ).dt.date

# buybox_df['Date'] = pd.to_datetime(
#     buybox_df['Date'],
#     format='mixed',
#     dayfirst=True
# ).dt.date
buybox_final_df["Date"] = pd.to_datetime(
    buybox_final_df["Date"], format="mixed", dayfirst=True
).dt.strftime("%d-%b-%Y")

buybox_df["Date"] = pd.to_datetime(
    buybox_df["Date"], format="mixed", dayfirst=True
).dt.strftime("%d-%b-%Y")

buybox_final_df = pd.merge(
    buybox_final_df,
    buybox_df,
    on=["ASIN", "Date"],
    how="left"
)

In [58]:
buybox_final_df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,30137829,X001ZD8VU5,B09KCHP2CV,New,24.99,No,0.0,Yes,59,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30137830,X001ZD88ET,B0BG2MZ1ZX,New,23.99,No,0.0,Yes,57,56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30137831,X001ZD8PU1,B09KCHGRZF,New,22.99,No,0.0,Yes,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,30137832,X001ZD6QI9,B09KCGPSPG,New,24.99,No,0.0,Yes,60,59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30137833,X001ZD8G1T,B0BG2KWV13,New,24.99,No,0.0,Yes,40,40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5049,90102779,X0025Y265T,B0DDGX2SFH,New,50.99,No,0.0,Yes,50,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5050,90102987,X0028AJ6IZ,B0DVYZDCWZ,New,17.49,No,0.0,Yes,16,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5051,90103079,X002D88KDT,B0FKBLF14N,New,18.99,No,0.0,Yes,20,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5052,90103234,X002IJ7TS5,B0GN246XDP,New,14.49,No,0.0,Yes,16,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5053,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Save Buybox

In [59]:
# Create ASIN -> first Product Sub Category mapping


# Fill missing Product sub Category
buybox_final_df['Sales Channel'] = "Seller Central"
cols = [
    "Product Name",
    "Product Category",
    "Pack Type"
]
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]
for col in cols_to_clean:
    buybox_final_df[col] = (
        buybox_final_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )

buybox_final_df[cols] = buybox_final_df[cols].fillna("Unavailable")
buybox_final_df = buybox_final_df.fillna(0)
buybox_final_df= buybox_final_df.fillna(0)

In [60]:
buybox_final_df.to_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\buybox\pattex_dashboard_amazon_buybox.csv",index = False)

In [61]:
df1 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\output\pattex_dashboard_amazon_buybox.csv")
df2 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\buybox\pattex_dashboard_amazon_buybox.csv")

In [62]:
df1

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,Hijacker 17 MOQ,Hijacker 18,Hijacker 18 Price,Hijacker 18 MOQ,Hijacker 19,Hijacker 19 Price,Hijacker 19 MOQ,Hijacker 20,Hijacker 20 Price,Hijacker 20 MOQ
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,255.11,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
1,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,244.48,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
2,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,129,0.00%,0.00,1009.84,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
3,B08B4T7CXB,Pattex,11039 Building tools,0.00%,244.26,23,106,0.00%,12.43,1020.47,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
4,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.00,0,106,0.00%,0.00,1020.47,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7597,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7598,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7599,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7600,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
7601,B0GN2C54ZK,Pattex,0212 Scrapbooking,0.00%,0.00,0,4,0.00%,0.00,0.00,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0

In [63]:
df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,Aged 90+ Days Sellable Inventory,Aged 90+ Days Sellable Units,Sellable Inventory Amount,Unsellable On Hand Inventory Amount,Unsellable On Hand Units,in_stock_flag,cumulative_instock_days,day_of_month,OOS Date,Date_temp
0,30137829,X001ZD8VU5,B09KCHP2CV,New,24.99,No,0.0,Yes,59.0,59.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
1,30137830,X001ZD88ET,B0BG2MZ1ZX,New,23.99,No,0.0,Yes,57.0,56.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
2,30137831,X001ZD8PU1,B09KCHGRZF,New,22.99,No,0.0,Yes,3.0,0.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
3,30137832,X001ZD6QI9,B09KCGPSPG,New,24.99,No,0.0,Yes,60.0,59.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
4,30137833,X001ZD8G1T,B0BG2KWV13,New,24.99,No,0.0,Yes,40.0,40.0,...,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12651,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,5.0,5.0,Instock,0.0
12652,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,6.0,6.0,Instock,0.0
12653,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,7.0,7.0,Instock,0.0
12654,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,8.0,8.0,Instock,0.0
12655,0,0,B0GN2C54ZK,0,0.00,0,0.0,0,0.0,0.0,...,0.0,0.0,215.0,0.0,0.0,1.0,9.0,9.0,Instock,0.0

In [64]:
df = pd.concat([df1,df2],ignore_index= True)

In [65]:
df = df.fillna(0)

In [66]:
# Convert to string
df['Current Owner Price'] = df['Current Owner Price'].astype(str)

# Condition: detect double dots
mask = df['Current Owner Price'].str.contains(r'\.\.')

# Apply updates
df.loc[mask, 'Current Owner'] = 'Unavailable'
df.loc[mask, 'Current Owner MOQ'] = 0
df.loc[mask, 'Current Owner Price'] = "0"

In [67]:
df.to_csv("pattex_buybox.csv",index= False)

In [68]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_buybox = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_buybox.csv")
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_buybox):
    pattex_buybox.columns = (
        pattex_buybox.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_buybox

# Apply cleaning
pattex_buybox = clean_columns(pattex_buybox)
pattex_buybox.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Documents\pattex_buybox.csv",index = False)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\2497021523.py:4: DtypeWarning: Columns (2,3,7,10,31,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,98,101,102,103,105,107) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_buybox = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_buybox.csv")

## Save buybox to azure

In [69]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_buybox = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_buybox.csv")
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_buybox):
    pattex_buybox.columns = (
        pattex_buybox.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_buybox

# Apply cleaning
pattex_buybox = clean_columns(pattex_buybox)

# -------- STEP 2: AZURE CONNECTION --------
connection_string = "DefaultEndpointsProtocol=https;AccountName=thriveclientdatabase;AccountKey=t3YQjkSXWXafdSIzp48QxNgmuW8BSh+6FzHaEy6VhGbgINYgo7Sica0BZw9sAKEPbwBcjqqhK5p6+AStuxDzSA==;EndpointSuffix=core.windows.net"
container_name = "thrive-client-pattex"
blob_name = "sanity_data/pattex_buybox.csv"   # e.g. folder/file.csv

# Create Blob Service Client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get Blob Client
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# -------- STEP 3: CONVERT DF TO CSV --------
csv_buffer = StringIO()
pattex_buybox.to_csv(csv_buffer, index=False)

# -------- STEP 4: UPLOAD TO AZURE --------
blob_client.upload_blob(csv_buffer.getvalue(), overwrite=True)

print("✅ DataFrame successfully uploaded to Azure Blob Storage!")

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\3350422676.py:4: DtypeWarning: Columns (2,3,7,10,31,45,48,51,54,57,60,63,66,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,98,101,102,103,105,107) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_buybox = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_buybox.csv")

✅ DataFrame successfully uploaded to Azure Blob Storage!

# Revenue

In [70]:
df_inv

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,total_units,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price,Sales Channel,Brand,_temp_date
1,30137829,X001ZD8VU5,B09KCHP2CV,New,30.99,No,0.0,Yes,59,59,...,0.0,Pattex Superglue Liquid,All Purpose SuperGlue,Base ASIN,1,25.00,6.90,Seller Central,Pattex,2026-06-01
2,30137830,X001ZD88ET,B0BG2MZ1ZX,New,25.49,No,0.0,Yes,59,59,...,0.0,Pattex Superglue Liquid Control,All Purpose SuperGlue,Base ASIN,1,24.00,9.90,Seller Central,Pattex,2026-06-01
3,30137831,X001ZD8PU1,B09KCHGRZF,New,25.49,No,0.0,Yes,63,60,...,0.0,Pattex Super Glue Power Gel Tube,All Purpose SuperGlue,Base ASIN,1,24.00,7.90,Seller Central,Pattex,2026-06-01
4,30137832,X001ZD6QI9,B09KCGPSPG,New,24.99,No,0.0,Yes,60,60,...,0.0,Pattex Super Glue Power Gel Control,All Purpose SuperGlue,Base ASIN,1,25.00,10.90,Seller Central,Pattex,2026-06-01
5,30137833,X001ZD8G1T,B0BG2KWV13,New,24.99,No,0.0,Yes,40,40,...,0.0,Pattex Super Glue All Plastics,All Purpose SuperGlue,Base ASIN,1,25.00,12.50,Seller Central,Pattex,2026-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,90102779,X0025Y265T,B0DDGX2SFH,New,50.99,No,0.0,Yes,50,50,...,0.0,Pattex SL100 Acrylic Sealant (White),Sealant,Physical-Bundle,2,50.99,39.00,Seller Central,Pattex,2026-06-12
703,90102987,X0028AJ6IZ,B0DVYZDCWZ,New,17.49,No,0.0,Yes,16,15,...,0.0,Pritt Glue stick 6X11g,Pritt Glue Stick,Physical-Bundle,6,0,18.50,Seller Central,Pattex,2026-06-12
705,90103079,X002D88KDT,B0FKBLF14N,New,18.99,No,0.0,Yes,20,20,...,0.0,Pritt Original 4x11gm,Pritt Glue Stick,Physical-Bundle,4,0,12.50,Seller Central,Pattex,2026-06-12
706,90103234,X002IJ7TS5,B0GN246XDP,New,14.49,No,0.0,Yes,16,15,...,0.0,Pritt Glue Stick Original 2x43g,Pritt Glue Stick,Physical-Bundle,2,0,0,Seller Central,Pattex,2026-06-12
707,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0,Seller Central,Pattex,2026-06-12

## Saving SPAP report

In [71]:
import os
import pandas as pd
from datetime import datetime

# -------- SOURCE FILE --------
source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SPAP\pattex_spap.xlsx"

# -------- BASE DESTINATION PATH --------
base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SPAP"

# -------- GET TODAY DATE --------
today = datetime.today()
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

month_name = month_map[month]  # folder name (lowercase)
# for file name (Mar)

# -------- CREATE FOLDER PATH --------
folder_path = os.path.join(base_path, str(year), month_name)

# Create folder if not exists
os.makedirs(folder_path, exist_ok=True)

# -------- READ FILE --------
df = pd.read_excel(source_file)

# -------- CREATE FILE NAME --------
file_name = f"pattex_spap_{month_name}_{year}.xlsx"

# -------- SAVE FILE --------
save_path = os.path.join(folder_path, file_name)
df.to_excel(save_path, index=False)

print("File saved at:", save_path)

c:\Users\Shubham Verma\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

File saved at: C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SPAP\2026\jun\pattex_spap_jun_2026.xlsx

In [72]:
# import os
# import pandas as pd
# from datetime import datetime

# # -------- SOURCE FILE --------
# source_file = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SB\Sponsored_Brands_Campaign_report.xlsx"

# # -------- BASE DESTINATION PATH --------
# base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SB"

# # -------- GET TODAY DATE --------
# today = datetime.today()
# year = today.year
# month = today.month

# # -------- MONTH MAP --------
# month_map = {
#     1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
#     7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
# }

# month_name = month_map[month]  # folder name (lowercase)
# # for file name (Mar)

# # -------- CREATE FOLDER PATH --------
# folder_path = os.path.join(base_path, str(year), month_name)

# # Create folder if not exists
# os.makedirs(folder_path, exist_ok=True)

# # -------- READ FILE --------
# df = pd.read_excel(source_file)

# # -------- CREATE FILE NAME --------
# file_name = f"pattex_sb_{month_name}_{year}.xlsx"

# # -------- SAVE FILE --------
# save_path = os.path.join(folder_path, file_name)
# df.to_excel(save_path, index=False)

# print("File saved at:", save_path)

## Read SPAP

In [73]:
import os
import pandas as pd
from datetime import datetime, timedelta

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SPAP"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(folder_path, file)

            df = pd.read_excel(file_path)
            df_list.append(df)

# -------- COMBINE --------
df_spap = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_spap.empty:
    df_spap = df_spap[
        df_spap['Portfolio name'].str.contains('pattex|pritt', case=False, na=False)
    ]

    # -------- DATE FORMAT --------
    df_spap["Date"] = pd.to_datetime(
        df_spap["Date"],
        format="%m/%d/%Y",
        errors="coerce"
    ).dt.strftime("%d-%b-%Y")

print("Total SPAP rows:", len(df_spap))

Folders to read: [(2026, 6)]
Total SPAP rows: 387

In [74]:
df_spap

,Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Country,Advertised SKU,Advertised ASIN,Impressions,Clicks,...,7 Day Total Sales,Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),7 Day Total Orders (#),7 Day Total Units (#),7 Day Conversion Rate,7 Day Advertised SKU Units (#),7 Day Other SKU Units (#),7 Day Advertised SKU Sales,7 Day Other SKU Sales
0,04-Jun-2026,Pattex,AED,APSG-SP-M,Phrase,United Arab Emirates,30137831,B09KCHGRZF,11,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0
1,08-Jun-2026,Pattex,AED,SL-SP-M,SL212 - Phrase,United Arab Emirates,30137856,B0937WZHZV,475,8,...,90.95,0.190984,5.236039,1,5,0.125000,5,0,90.95,0.0
2,09-Jun-2026,Pattex,AED,SL-SP-M,SL212 - Phrase,United Arab Emirates,30137856,B0937WZHZV,604,8,...,36.38,0.672622,1.486718,2,2,0.250000,2,0,36.38,0.0
3,10-Jun-2026,Pattex,AED,SL-SP-M,SL212 - Phrase,United Arab Emirates,30137856,B0937WZHZV,539,14,...,36.38,1.326278,0.753990,2,2,0.142857,2,0,36.38,0.0
4,11-Jun-2026,Pattex,AED,SL-SP-M,SL212 - Phrase,United Arab Emirates,30137856,B0937WZHZV,484,6,...,0.00,NaN,0.000000,0,0,0.000000,0,0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,09-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,76,1,...,14.49,0.130435,7.666667,1,1,1.000000,1,0,14.49,0.0
1435,10-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,33,1,...,0.00,NaN,0.000000,0,0,0.000000,0,0,0.00,0.0
1436,11-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,45,2,...,0.00,NaN,0.000000,0,0,0.000000,0,0,0.00,0.0
1437,12-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,4,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0
1438,11-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Exact,Brand Defense,United Arab Emirates,90103234,B0GN246XDP,2,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0

In [75]:
 ### 1) when we merge inv and sale we make sure inv should be current date and sale should be till date and we group by asin the explicityly mention the current date to show 

### 2) if a person selects a range 1 - 13 then it should show the table of max date from inv and also sale of that date it is for revenue page -->

In [76]:
# import os
# import pandas as pd
# from datetime import datetime, timedelta

# base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SB"

# today = datetime.today()
# day = today.day
# year = today.year
# month = today.month

# # -------- MONTH MAP --------
# month_map = {
#     1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
#     7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
# }

# # -------- PREVIOUS MONTH --------
# prev_date = today.replace(day=1) - timedelta(days=1)
# prev_month = prev_date.month
# prev_year = prev_date.year

# # -------- DECIDE FOLDERS --------
# folders_to_read = []

# # Always include current month
# folders_to_read.append((year, month))

# # Include previous month if day ≤ 3
# if day <= 3:
#     folders_to_read.append((prev_year, prev_month))

# print("Folders to read:", folders_to_read)

# df_list = []

# # -------- LOOP --------
# for yr, mon in folders_to_read:

#     folder_path = os.path.join(base_path, str(yr), month_map[mon])

#     if not os.path.exists(folder_path):
#         continue

#     for file in os.listdir(folder_path):

#         if file.endswith(".xlsx"):

#             file_path = os.path.join(folder_path, file)

#             df = pd.read_excel(file_path)
#             df_list.append(df)

# # -------- COMBINE --------
# df_sb = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# # -------- FILTER --------
# if not df_sb.empty:
#     df_sb = df_sb[
#         df_sb['Portfolio name'].str.contains('pattex|pritt', case=False, na=False)
#     ]

#     # -------- DATE FORMAT --------
#     df_sb["Date"] = pd.to_datetime(
#         df_sb["Date"],
#         format="%m/%d/%Y",
#         errors="coerce"
#     ).dt.strftime("%d-%b-%Y")

# print("Total SB rows:", len(df_sb))

In [77]:
ads_df = df_spap.rename(columns={
    "7 Day Total Sales ": "ads_sales",
    "7 Day Total Units (#)": "ads_unit_sold",
    "Advertised ASIN": "ASIN",
    "Spend" : "ads_spend"
})
ads_df = ads_df[["Date","ASIN", "ads_sales", "ads_unit_sold","ads_spend"]]

In [78]:
ads_df

             Date        ASIN  ads_sales  ads_unit_sold  ads_spend
0     04-Jun-2026  B09KCHGRZF       0.00              0       0.00
1     08-Jun-2026  B0937WZHZV      90.95              5      17.37
2     09-Jun-2026  B0937WZHZV      36.38              2      24.47
3     10-Jun-2026  B0937WZHZV      36.38              2      48.25
4     11-Jun-2026  B0937WZHZV       0.00              0      26.99
...           ...         ...        ...            ...        ...
1434  09-Jun-2026  B0GN246XDP      14.49              1       1.89
1435  10-Jun-2026  B0GN246XDP       0.00              0       2.74
1436  11-Jun-2026  B0GN246XDP       0.00              0       2.76
1437  12-Jun-2026  B0GN246XDP       0.00              0       0.00
1438  11-Jun-2026  B0GN246XDP       0.00              0       0.00

[387 rows x 5 columns]

In [79]:
ads_grouped = (
    ads_df
    .groupby(["ASIN", "Date"], as_index=False)[["ads_sales", "ads_unit_sold","ads_spend"]]
    .sum()
)

In [80]:
ads_grouped

          ASIN         Date  ads_sales  ads_unit_sold  ads_spend
0   B08MXBVG7Z  08-Jun-2026       0.00              0       0.00
1   B08MXBVG7Z  09-Jun-2026       0.00              0       0.00
2   B08MXBVG7Z  10-Jun-2026       0.00              0       0.00
3   B08MXBVG7Z  11-Jun-2026       0.00              0       0.00
4   B08MXBVG7Z  12-Jun-2026       0.00              0       0.00
..         ...          ...        ...            ...        ...
73  B0GN246XDP  08-Jun-2026      28.98              2       8.56
74  B0GN246XDP  09-Jun-2026      14.49              1       4.36
75  B0GN246XDP  10-Jun-2026       0.00              0       4.63
76  B0GN246XDP  11-Jun-2026      14.49              1       9.22
77  B0GN246XDP  12-Jun-2026       0.00              0       0.00

[78 rows x 5 columns]

In [81]:
# Clean ASIN columns
df_inv["ASIN"] = df_inv["ASIN"].astype(str).str.strip().str.upper()
ads_grouped["ASIN"] = ads_grouped["ASIN"].astype(str).str.strip().str.upper()

# Create temporary datetime columns for safe merging
df_inv["Date_temp"] = pd.to_datetime(df_inv["Date"], format="mixed", dayfirst=True)
ads_grouped["Date_temp"] = pd.to_datetime(ads_grouped["Date"], format="mixed", dayfirst=True)

# Merge on ASIN + Date_temp
merged_df = df_inv.merge(
    ads_grouped,
    left_on=["ASIN", "Date_temp"],
    right_on=["ASIN", "Date_temp"],
    how="outer",
    suffixes=("", "_ads")
)

# Keep original Date column (prefer df_inv's if present)
merged_df["Date"] = merged_df["Date"].fillna(merged_df["Date_ads"])

# Drop helper/temp columns
cols_to_drop = [c for c in ["Date_temp", "Date_ads"] if c in merged_df.columns]
merged_df.drop(columns=cols_to_drop, inplace=True)

In [82]:
merged_df = merged_df.drop(columns=['Product Name', 'Product Category', 'Pack Type', 'Pack Size',  'SC Ideal Price', 'VC Ideal Price'])

In [83]:
merged_df['total_sales'] = merged_df['total_sales'].fillna(0)
merged_df['ads_sales'] = merged_df['ads_sales'].fillna(0)

merged_df['organic_sale'] = (merged_df['total_sales'] - merged_df['ads_sales']).round(2)
merged_df['ads_spend'] = merged_df['ads_spend'].round(2)
merged_df['organic_sale'].sum()

np.float64(7979.47)

In [84]:
import pandas as pd

# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")

# Convert ASIN to uppercase in both
merged_df["ASIN"] = merged_df["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
merged_df = merged_df.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
merged_df["Pack Size"] = merged_df["Pack Size"].fillna(0).astype(int)
cols_to_fill = ["Product Name", "Category", "Pack Type", "Pack Size", "SC Ideal Price", "VC Ideal Price"]


merged_df.rename(columns= {'Category' : 'Product Category'},inplace= True)

print("Merge completed ✅")

Merge completed ✅

In [85]:
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]

for col in cols_to_clean:
    merged_df[col] = (
        merged_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
        
    )

In [86]:
merged_df['Sales Channel'] = "Seller Central"
cols = [
    "Product Name",
    "Product Category",
    "Pack Type"
]

merged_df[cols] = merged_df[cols].fillna("Unavailable")
merged_df = merged_df.fillna(0)

In [87]:
merged_df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,ads_sales,ads_unit_sold,ads_spend,organic_sale,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0.0,0.0,0.0,Unavailable,Unavailable,Unavailable,0,nan,nan
1,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0.0,0.0,0.0,Unavailable,Unavailable,Unavailable,0,nan,nan
2,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0.0,0.0,0.0,Unavailable,Unavailable,Unavailable,0,nan,nan
3,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0.0,0.0,0.0,Unavailable,Unavailable,Unavailable,0,nan,nan
4,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0.0,0.0,0.0,Unavailable,Unavailable,Unavailable,0,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
668,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
669,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
670,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
671,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0

## Save Revenue Dataframe to local

In [88]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\revenue\orders\pattex_orders.csv"

# Read existing CSV
df = pd.read_csv(file_path)

previous_rows = len(df)

# Create temp column (DO NOT modify original Date)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

# Get today's date (normalized)
today = pd.Timestamp.today().normalize()
current_day = today.day

# First day of current month
first_day_current_month = today.replace(day=1)

# Apply logic
if current_day <= 3:
    # Keep only <= last day of previous-to-previous month
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    # Remove current month data
    df = df[df['_temp_date'] < first_day_current_month]

# Metrics after deletion
current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare your new dataframe (ASSUMED NAME: merged_df)
merged_df['_temp_date'] = pd.to_datetime(
    merged_df['Date'], format='%d-%b-%Y', errors='coerce'
).dt.normalize()

rows_appended = len(merged_df)

# Append new data
df = pd.concat([df, merged_df], ignore_index=True)

final_rows = len(df)

# Drop temp column before saving
df.drop(columns=['_temp_date'], inplace=True)

# Save back
df.to_csv(file_path, index=False)

# Metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 5005
Current rows: 4390
Rows deleted: 615
Rows appended: 672
Final rows: 5062

In [89]:
df1 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\sales\output\pattex_revenue.csv")
df2 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\revenue\orders\pattex_orders.csv")

In [90]:
df2

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,ads_sales,ads_unit_sold,ads_spend,organic_sale,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,30137844,X001ZD8NT9,B08B4T7CXB,New,14.00,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0.0,0.0,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,25.02,12.5
1,30137844,X001ZD8NT9,B08B4T7CXB,New,14.00,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0.0,0.0,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,25.02,12.5
2,30137844,X001ZD8NT9,B08B4T7CXB,New,14.00,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0.0,0.0,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,25.02,12.5
3,30137844,X001ZD8NT9,B08B4T7CXB,New,14.00,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0.0,0.0,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,25.02,12.5
4,30137844,X001ZD8NT9,B08B4T7CXB,New,14.00,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0.0,0.0,Pattex Mounting Tape 80kg,Mounting Tape,Base ASIN,1,25.02,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5057,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19.0,19.0,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0.00,0.0
5058,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19.0,19.0,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0.00,0.0
5059,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19.0,19.0,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0.00,0.0
5060,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19.0,19.0,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0.00,0.0
5061,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19.0,19.0,...,0.0,0.0,0.0,0.0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0.00,0.0

In [91]:
df = pd.concat([df1,df2],ignore_index=True)
df = df.fillna(0)
df

,ASIN,Brand,Product Sub Category,Vendor Confirmation %,PO_received_amount,PO_received_Units,Open POs,Receive_Fill_Rate,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,...,afn-future-supply-buyable,store,reserved_qty,reserved_customerorders,reserved_fc-transfers,reserved_fc-processing,units-shipped-t30,units-shipped-t60,units-shipped-t90,year_month
0,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.0,0.0,39.0,0.00%,0.0,754.72,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.0,0.0,129.0,0.00%,0.0,255.11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.0,0.0,39.0,0.00%,0.0,722.83,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,B08B4T7CXB,Pattex,11039 Building tools,0.00%,0.0,0.0,129.0,0.00%,0.0,244.48,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,B08B4T7CXB,Pattex,11039 Building tools,100.00%,0.0,0.0,39.0,28.57%,0.0,690.94,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13869,B0GN2C54ZK,Pattex,0,0,0.0,0.0,0.0,0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,4.0,0.0
13870,B0GN2C54ZK,Pattex,0,0,0.0,0.0,0.0,0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,3.0,4.0,0.0
13871,B0GN2C54ZK,Pattex,0,0,0.0,0.0,0.0,0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,0.0
13872,B0GN2C54ZK,Pattex,0,0,0.0,0.0,0.0,0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,4.0,0.0
13873,B0GN2C54ZK,Pattex,0,0,0.0,0.0,0.0,0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Save marketing to the azure

In [92]:
df.to_csv("pattex_revenue.csv",index = False)

In [93]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_revenue = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_revenue.csv")
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_revenue):
    pattex_revenue.columns = (
        pattex_revenue.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_revenue

# Apply cleaning
pattex_revenue = clean_columns(pattex_revenue)
pattex_revenue.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Documents\pattex_revenue.csv",index= False)

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\1718024188.py:4: DtypeWarning: Columns (10,41,42,43,45,47) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_revenue = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\DataHive_Codes\Pattex\pattex_revenue.csv")

In [94]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_revenue = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_revenue.csv")
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_revenue):
    pattex_revenue.columns = (
        pattex_revenue.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_revenue

# Apply cleaning
pattex_revenue = clean_columns(pattex_revenue)

# -------- STEP 2: AZURE CONNECTION --------
connection_string = "DefaultEndpointsProtocol=https;AccountName=thriveclientdatabase;AccountKey=t3YQjkSXWXafdSIzp48QxNgmuW8BSh+6FzHaEy6VhGbgINYgo7Sica0BZw9sAKEPbwBcjqqhK5p6+AStuxDzSA==;EndpointSuffix=core.windows.net"
container_name = "thrive-client-pattex"
blob_name = "sanity_data/pattex_revenue.csv"   # e.g. folder/file.csv

# Create Blob Service Client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get Blob Client
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# -------- STEP 3: CONVERT DF TO CSV --------
csv_buffer = StringIO()
pattex_revenue.to_csv(csv_buffer, index=False)

# -------- STEP 4: UPLOAD TO AZURE --------
blob_client.upload_blob(csv_buffer.getvalue(), overwrite=True)

print("✅ DataFrame successfully uploaded to Azure Blob Storage!")

C:\Users\Shubham Verma\AppData\Local\Temp\ipykernel_2564\2561716206.py:4: DtypeWarning: Columns (2,3,7,10,25,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  pattex_revenue = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_revenue.csv")

✅ DataFrame successfully uploaded to Azure Blob Storage!

# Marketing Dataframe

In [95]:
import os
import pandas as pd
from datetime import datetime, timedelta

base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SPAP"

today = datetime.today()
day = today.day
year = today.year
month = today.month

# -------- MONTH MAP --------
month_map = {
    1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
    7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
}

# -------- PREVIOUS MONTH --------
prev_date = today.replace(day=1) - timedelta(days=1)
prev_month = prev_date.month
prev_year = prev_date.year

# -------- DECIDE FOLDERS --------
folders_to_read = []

# Always include current month
folders_to_read.append((year, month))

# Include previous month if day ≤ 3
if day <= 3:
    folders_to_read.append((prev_year, prev_month))

print("Folders to read:", folders_to_read)

df_list = []

# -------- LOOP --------
for yr, mon in folders_to_read:

    folder_path = os.path.join(base_path, str(yr), month_map[mon])

    if not os.path.exists(folder_path):
        continue

    for file in os.listdir(folder_path):

        if file.endswith(".xlsx"):

            file_path = os.path.join(folder_path, file)

            df = pd.read_excel(file_path)
            df_list.append(df)

# -------- COMBINE --------
df_spap = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# -------- FILTER --------
if not df_spap.empty:
    df_spap = df_spap[
        df_spap['Campaign Name'].str.contains('pattex|pritt', case=False, na=False)
    ]

    # -------- DATE FORMAT --------
    df_spap["Date"] = pd.to_datetime(
        df_spap["Date"],
        format="%m/%d/%Y",
        errors="coerce"
    ).dt.strftime("%d-%b-%Y")

print("Total SPAP rows:", len(df_spap))

Folders to read: [(2026, 6)]
Total SPAP rows: 325

In [96]:
# import os
# import pandas as pd
# from datetime import datetime, timedelta

# base_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\input\ads\SB"

# today = datetime.today()
# day = today.day
# year = today.year
# month = today.month

# # -------- MONTH MAP --------
# month_map = {
#     1:"jan",2:"feb",3:"mar",4:"apr",5:"may",6:"jun",
#     7:"jul",8:"aug",9:"sep",10:"oct",11:"nov",12:"dec"
# }

# # -------- PREVIOUS MONTH --------
# prev_date = today.replace(day=1) - timedelta(days=1)
# prev_month = prev_date.month
# prev_year = prev_date.year

# # -------- DECIDE FOLDERS --------
# folders_to_read = []

# # Always include current month
# folders_to_read.append((year, month))

# # Include previous month if day ≤ 3
# if day <= 3:
#     folders_to_read.append((prev_year, prev_month))

# print("Folders to read:", folders_to_read)

# df_list = []

# # -------- LOOP --------
# for yr, mon in folders_to_read:

#     folder_path = os.path.join(base_path, str(yr), month_map[mon])

#     if not os.path.exists(folder_path):
#         continue

#     for file in os.listdir(folder_path):

#         if file.endswith(".xlsx"):

#             file_path = os.path.join(folder_path, file)

#             df = pd.read_excel(file_path)
#             df_list.append(df)

# # -------- COMBINE --------
# df_spap = pd.concat(df_list, ignore_index=True) if df_list else pd.DataFrame()

# # -------- FILTER --------
# if not df_spap.empty:
#     df_spap = df_spap[
#         df_spap['Campaign Name'].str.contains('pattex|pritt', case=False, na=False)
#     ]

#     # -------- DATE FORMAT --------
#     df_spap["Date"] = pd.to_datetime(
#         df_spap["Date"],
#         format="%m/%d/%Y",
#         errors="coerce"
#     ).dt.strftime("%d-%b-%Y")

# print("Total SPAP rows:", len(df_spap))

In [97]:
df_spap

,Date,Portfolio name,Currency,Campaign Name,Ad Group Name,Country,Advertised SKU,Advertised ASIN,Impressions,Clicks,...,7 Day Total Sales,Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),7 Day Total Orders (#),7 Day Total Units (#),7 Day Conversion Rate,7 Day Advertised SKU Units (#),7 Day Other SKU Units (#),7 Day Advertised SKU Sales,7 Day Other SKU Sales
73,06-Jun-2026,Pattex,AED,PATTEX-SP-PT(BO),APSG,United Arab Emirates,90102763,B0DDGS87JD,34,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0
74,07-Jun-2026,Pattex,AED,PATTEX-SP-PT(BO),APSG,United Arab Emirates,90102763,B0DDGS87JD,54,1,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
75,08-Jun-2026,Pattex,AED,PATTEX-SP-PT(BO),APSG,United Arab Emirates,90102763,B0DDGS87JD,74,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
76,09-Jun-2026,Pattex,AED,PATTEX-SP-PT(BO),APSG,United Arab Emirates,90102763,B0DDGS87JD,52,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0
77,10-Jun-2026,Pattex,AED,PATTEX-SP-PT(BO),APSG,United Arab Emirates,90102763,B0DDGS87JD,39,1,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434,09-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,76,1,...,14.49,0.130435,7.666667,1,1,1.0,1,0,14.49,0.0
1435,10-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,33,1,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
1436,11-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,45,2,...,0.00,NaN,0.000000,0,0,0.0,0,0,0.00,0.0
1437,12-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Phrase,Generic | Phrase,United Arab Emirates,90103234,B0GN246XDP,4,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0
1438,11-Jun-2026,Pattex,AED,Pritt | Glue stick | SP | Manual Exact,Brand Defense,United Arab Emirates,90103234,B0GN246XDP,2,0,...,0.00,NaN,NaN,0,0,NaN,0,0,0.00,0.0

In [98]:
ads_df = df_spap.rename(columns={
    "7 Day Total Sales ": "ads_sales",
    "7 Day Total Units (#)": "ads_unit_sold",
    "Advertised ASIN": "ASIN",
    "Spend" : "ads_spend",
    "7 Day Conversion Rate" : "CVR"
})
ads_df = ads_df[["Date","ASIN", "Portfolio name", "ads_sales", "ads_unit_sold","ads_spend","Impressions","Clicks","Click-Thru Rate (CTR)","Cost Per Click (CPC)","Total Advertising Cost of Sales (ACOS) ","Total Return on Advertising Spend (ROAS)","CVR","Campaign Name"]]
ads_df['Campaign Type'] = "SP"

In [99]:
grouped_df = ads_df.groupby(['ASIN', 'Date'], as_index=False).agg({
    'ads_sales': 'sum',
    'ads_unit_sold': 'sum',
    'ads_spend': 'sum',
    'Impressions': 'sum',
    'Clicks': 'sum',

    # Remaining metric columns
    'Click-Thru Rate (CTR)': 'sum',
    'Cost Per Click (CPC)': 'sum',
    'Total Advertising Cost of Sales (ACOS) ': 'sum',
    'Total Return on Advertising Spend (ROAS)': 'sum',
    'CVR': 'sum',

    # Text columns
    'Campaign Name': 'first',
    'Campaign Type': 'first',
    'Portfolio name': 'first'
})

In [100]:
grouped_df['Impressions'].sum()

np.int64(20425)

In [101]:
grouped_df

,ASIN,Date,ads_sales,ads_unit_sold,ads_spend,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Total Advertising Cost of Sales (ACOS),Total Return on Advertising Spend (ROAS),CVR,Campaign Name,Campaign Type,Portfolio name
0,B08MXBVG7Z,08-Jun-2026,0.00,0,0.00,240,0,0.000000,0.000000,0.000000,0.000000,0.000000,PATTEX-SP-M(BD),SP,Pattex
1,B08MXBVG7Z,09-Jun-2026,0.00,0,0.00,460,0,0.000000,0.000000,0.000000,0.000000,0.000000,PATTEX-SP-PT(BO),SP,Pattex
2,B08MXBVG7Z,10-Jun-2026,0.00,0,0.00,390,0,0.000000,0.000000,0.000000,0.000000,0.000000,PATTEX-SP-PT(BO),SP,Pattex
3,B08MXBVG7Z,11-Jun-2026,0.00,0,0.00,404,0,0.000000,0.000000,0.000000,0.000000,0.000000,PATTEX-SP-PT(BO),SP,Pattex
4,B08MXBVG7Z,12-Jun-2026,0.00,0,0.00,91,0,0.000000,0.000000,0.000000,0.000000,0.000000,PATTEX-SP-PT(BO),SP,Pattex
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,B0GN246XDP,08-Jun-2026,28.98,2,8.56,92,3,0.042254,2.853333,0.295376,3.385514,0.666667,Pritt | Glue stick | SP | Manual Exact,SP,Pattex
72,B0GN246XDP,09-Jun-2026,14.49,1,4.36,134,2,0.031015,4.360000,0.130435,7.666667,1.000000,Pritt | Glue stick | SP | Manual Exact,SP,Pattex
73,B0GN246XDP,10-Jun-2026,0.00,0,4.63,108,2,0.043817,4.630000,0.000000,0.000000,0.000000,Pritt | Glue stick | SP | Manual Phrase,SP,Pattex
74,B0GN246XDP,11-Jun-2026,14.49,1,9.22,117,5,0.091319,3.533333,0.445825,2.243034,0.333333,Pritt | Glue stick | SP | Manual Phrase,SP,Pattex
75,B0GN246XDP,12-Jun-2026,0.00,0,0.00,9,0,0.000000,0.000000,0.000000,0.000000,0.000000,Pritt | Glue stick | SP | Manual Exact,SP,Pattex

In [102]:
# Clean ASIN columns
df_inv["ASIN"] = df_inv["ASIN"].astype(str).str.strip().str.upper()
grouped_df["ASIN"] = grouped_df["ASIN"].astype(str).str.strip().str.upper()

# Create temporary datetime columns for safe merging
df_inv["Date_temp"] = pd.to_datetime(df_inv["Date"], format="mixed", dayfirst=True)
grouped_df["Date_temp"] = pd.to_datetime(grouped_df["Date"], format="mixed", dayfirst=True)

# Merge on ASIN + Date_temp
marketing_df = df_inv.merge(
    grouped_df,
    left_on=["ASIN", "Date_temp"],
    right_on=["ASIN", "Date_temp"],
    how="outer",
    suffixes=("", "_ads")
)

# Keep original Date column (prefer df_inv's if present)
marketing_df["Date"] = marketing_df["Date"].fillna(marketing_df["Date_ads"])

# Drop helper/temp columns
cols_to_drop = [c for c in ["Date_temp", "Date_ads"] if c in marketing_df.columns]
marketing_df.drop(columns=cols_to_drop, inplace=True)

In [103]:
marketing_df = marketing_df.drop(columns=['Product Name', 'Product Category', 'Pack Type', 'Pack Size',  'SC Ideal Price', 'VC Ideal Price'])

In [104]:
import pandas as pd
# Read excel file
pack_df = pd.read_excel(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\PATTEX_Item_Master.xlsx")

# Convert ASIN to uppercase in both
marketing_df["ASIN"] = marketing_df["ASIN"].astype(str).str.upper().str.strip()
pack_df["ASIN"] = pack_df["ASIN"].astype(str).str.upper().str.strip()

# Keep required columns
pack_df = pack_df[["ASIN","Product Name", "Category", "Pack Type", "Pack Size","SC Ideal Price","VC Ideal Price"]]

# Convert Pack Size to integer (safe conversion)
pack_df["Pack Size"] = pd.to_numeric(
    pack_df["Pack Size"], errors="coerce"
).fillna(0).astype(int)

# Merge
marketing_df = marketing_df.merge(pack_df, on="ASIN", how="left")

# Ensure merged column is int
marketing_df["Pack Size"] = marketing_df["Pack Size"].fillna(0).astype(int)
cols_to_fill = ["Product Name", "Category", "Pack Type", "Pack Size", "SC Ideal Price", "VC Ideal Price"]



marketing_df.rename(columns= {'Category' : 'Product Category'},inplace= True)

print("Merge completed ✅")

Merge completed ✅

In [105]:
cols_to_clean = [
    'SC Ideal Price',
    'VC Ideal Price',
]

for col in cols_to_clean:
    marketing_df[col] = (
        marketing_df[col]
        .astype(str)
        .str.replace('AED', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.replace('-', '', regex=False)
        .str.strip()
        .replace('', '0')   # Fix: replace empty string with 0
    )

In [106]:
marketing_df['Sales Channel'] = "Seller Central"
cols = [
    "Product Name",
    "Product Category",
    "Pack Type"
]

marketing_df[cols] = marketing_df[cols].fillna("Unavailable")
marketing_df = marketing_df.fillna(0)

In [107]:
marketing_df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,CVR,Campaign Name,Campaign Type,Portfolio name,Product Name,Product Category,Pack Type,Pack Size,SC Ideal Price,VC Ideal Price
0,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0,0,0,Unavailable,Unavailable,Unavailable,0,nan,nan
1,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0,0,0,Unavailable,Unavailable,Unavailable,0,nan,nan
2,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0,0,0,Unavailable,Unavailable,Unavailable,0,nan,nan
3,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0,0,0,Unavailable,Unavailable,Unavailable,0,nan,nan
4,30137827,X001ZD84QB,B001P5IT7A,New,33.00,No,0.0,Yes,10,10,...,0.0,0,0,0,Unavailable,Unavailable,Unavailable,0,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0,0,0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
668,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0,0,0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
669,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0,0,0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
670,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0,0,0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0
671,90103235,X002IIYDHV,B0GN2C54ZK,New,35.99,No,0.0,Yes,19,19,...,0.0,0,0,0,Pritt Glue Stick Original 4x43g,Pritt Glue Stick,Physical-Bundle,4,0,0

## Save the dataframe

In [108]:
import pandas as pd
from datetime import datetime

file_path = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\ads\pattex_ads.csv"

# Read existing CSV
df = pd.read_csv(file_path)

previous_rows = len(df)

# Create temp column (DO NOT modify original Date)
df['_temp_date'] = pd.to_datetime(df['Date'], format='%d-%b-%Y', errors='coerce').dt.normalize()

# Get today's date (normalized)
today = pd.Timestamp.today().normalize()
current_day = today.day

# First day of current month
first_day_current_month = today.replace(day=1)

# Apply logic
if current_day <= 3:
    # Keep only <= last day of previous-to-previous month
    cutoff_date = first_day_current_month - pd.DateOffset(months=1)
    cutoff_date = cutoff_date.replace(day=1) - pd.DateOffset(days=1)

    df = df[df['_temp_date'] <= cutoff_date]

else:
    # Remove current month data
    df = df[df['_temp_date'] < first_day_current_month]

# Metrics after deletion
current_rows = len(df)
rows_deleted = previous_rows - current_rows

# Prepare your new dataframe (ASSUMED NAME: marketing_df)
marketing_df['_temp_date'] = pd.to_datetime(
    marketing_df['Date'], format='%d-%b-%Y', errors='coerce'
).dt.normalize()

rows_appended = len(marketing_df)

# Append new data
df = pd.concat([df, marketing_df], ignore_index=True)

final_rows = len(df)

# Drop temp column before saving
df.drop(columns=['_temp_date'], inplace=True)

# Save back
df.to_csv(file_path, index=False)

# Metrics
print(f"Previous rows: {previous_rows}")
print(f"Current rows: {current_rows}")
print(f"Rows deleted: {rows_deleted}")
print(f"Rows appended: {rows_appended}")
print(f"Final rows: {final_rows}")

Previous rows: 5004
Current rows: 4389
Rows deleted: 615
Rows appended: 672
Final rows: 5061

In [109]:
df1 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\seller_central\uae\output\ads\pattex_ads.csv")
df2 = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\ads\output\pattex_marketing.csv")

In [110]:
df = pd.concat([df1,df2],ignore_index=True)
df = df.fillna(0)

In [111]:
# import pandas as pd
# df = pd.read_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Data analytics_Ecosoul - Central Repository\Visual Studio Codes\Shubham Projects\Pattex_Projects\pattex_marketing.csv")

In [112]:
df

,sku,fnsku,ASIN,condition,your-price,mfn-listing-exists,mfn-fulfillable-quantity,afn-listing-exists,afn-warehouse-quantity,afn-fulfillable-quantity,...,Overall Vendor Lead Time (days),Aged 90+ Days Sellable Inventory,Aged 90+ Days Sellable Units,Sellable Inventory Amount,Unsellable On Hand Inventory Amount,Unsellable On Hand Units,in_stock_flag,cumulative_instock_days,day_of_month,OOS Date
0,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13868,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13869,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13870,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13871,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13872,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [113]:
df.to_csv("pattex_marketing.csv",index = False)

In [114]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_marketing = df.copy()
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_marketing):
    pattex_marketing.columns = (
        pattex_marketing.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_marketing

# Apply cleaning
pattex_marketing = clean_columns(pattex_marketing)
pattex_marketing.to_csv(r"C:\Users\Shubham Verma\OneDrive - EcoSoul Home\Documents\pattex_marketing.csv",index= False)

## Push the data to the azure

In [115]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_marketing = df.copy()
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_marketing):
    pattex_marketing.columns = (
        pattex_marketing.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_marketing

# Apply cleaning
pattex_marketing = clean_columns(pattex_marketing)

# -------- STEP 2: AZURE CONNECTION --------
connection_string = "DefaultEndpointsProtocol=https;AccountName=thriveclientdatabase;AccountKey=t3YQjkSXWXafdSIzp48QxNgmuW8BSh+6FzHaEy6VhGbgINYgo7Sica0BZw9sAKEPbwBcjqqhK5p6+AStuxDzSA==;EndpointSuffix=core.windows.net"
container_name = "thrive-client-pattex"
blob_name = "sanity_data/pattex_marketing.csv"   # e.g. folder/file.csv

# Create Blob Service Client
blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# Get Blob Client
blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# -------- STEP 3: CONVERT DF TO CSV --------
csv_buffer = StringIO()
pattex_marketing.to_csv(csv_buffer, index=False)

# -------- STEP 4: UPLOAD TO AZURE --------
blob_client.upload_blob(csv_buffer.getvalue(), overwrite=True)

print("✅ DataFrame successfully uploaded to Azure Blob Storage!")

✅ DataFrame successfully uploaded to Azure Blob Storage!

In [116]:
import pandas as pd
from azure.storage.blob import BlobServiceClient
from io import StringIO
pattex_marketing = df.copy()
# -------- STEP 1: CLEAN COLUMN NAMES --------
def clean_columns(pattex_marketing):
    pattex_marketing.columns = (
        pattex_marketing.columns
        .str.strip()              # remove leading/trailing spaces
        .str.lower()              # convert to lowercase
        .str.replace(r'[\s\-]+', '_', regex=True)  # replace spaces with underscore
    )
    return pattex_marketing

# Apply cleaning
pattex_marketing = clean_columns(pattex_marketing)

# # -------- STEP 2: AZURE CONNECTION --------
# connection_string = "DefaultEndpointsProtocol=https;AccountName=thrivedatalakegen2;AccountKey=z1Lqqm8+4lyRYdVSSo2a+QIvl93IZ61aumKc6wtuLhK6A38qjtJ0qj91Keoawk/dndv1LCByfOf8+ASt1rzpwg==;BlobEndpoint=https://thrivedatalakegen2.blob.core.windows.net/;QueueEndpoint=https://thrivedatalakegen2.queue.core.windows.net/;TableEndpoint=https://thrivedatalakegen2.table.core.windows.net/;FileEndpoint=https://thrivedatalakegen2.file.core.windows.net/;"
# container_name = "thrive-client-pattex"
# blob_name = "sanity_data/pattex_marketing.csv"   # e.g. folder/file.csv

# # Create Blob Service Client
# blob_service_client = BlobServiceClient.from_connection_string(connection_string)

# # Get Blob Client
# blob_client = blob_service_client.get_blob_client(container=container_name, blob=blob_name)

# # -------- STEP 3: CONVERT DF TO CSV --------
# csv_buffer = StringIO()
# pattex_marketing.to_csv(csv_buffer, index=False)

# # -------- STEP 4: UPLOAD TO AZURE --------
# blob_client.upload_blob(csv_buffer.getvalue(), overwrite=True)

# print("✅ DataFrame successfully uploaded to Azure Blob Storage!")

In [117]:
pattex_marketing

,sku,fnsku,asin,condition,your_price,mfn_listing_exists,mfn_fulfillable_quantity,afn_listing_exists,afn_warehouse_quantity,afn_fulfillable_quantity,...,overall_vendor_lead_time_(days),aged_90+_days_sellable_inventory,aged_90+_days_sellable_units,sellable_inventory_amount,unsellable_on_hand_inventory_amount,unsellable_on_hand_units,in_stock_flag,cumulative_instock_days,day_of_month,oos_date
0,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,30137844,X001ZD8NT9,B08B4T7CXB,New,14.0,No,0.0,Yes,48.0,45.0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13868,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13869,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13870,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13871,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
13872,0,0,SPONSORED BRAND,0,0.0,0,0.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

## Mega Sold

In [118]:
# import time
# import re
# import pandas as pd
# from selenium import webdriver
# from selenium.webdriver.chrome.options import Options
# from selenium.webdriver.common.by import By
# from selenium.webdriver.support.ui import WebDriverWait
# from selenium.webdriver.support import expected_conditions as EC

# INPUT_FILE = r"C:\Users\Shubham Verma\OneDrive - Incircle Ecoproducts Pvt Ltd\Thrivebrands - Client Database\Pattex\vendor_central\uae\BuyBox\input\pattex_buybox_asins.xlsx"      # your input excel file
# OUTPUT_FILE = r"C:\Users\Shubham Verma\Downloads\mega_sale_buybox.xlsx"
# ASIN_COLUMN = "ASIN"                 # change if your column name is different
# AMAZON_BASE = "https://www.amazon.ae/dp/{}"

# def setup_driver():
#     options = Options()
#     options.add_argument("--start-maximized")
#     options.add_argument("--disable-blink-features=AutomationControlled")
#     options.add_argument("--disable-dev-shm-usage")
#     options.add_argument("--no-sandbox")
#     options.add_argument("--lang=en-US")
#     options.add_argument(
#         "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
#         "AppleWebKit/537.36 (KHTML, like Gecko) "
#         "Chrome/124.0.0.0 Safari/537.36"
#     )
#     # options.add_argument("--headless=new")
#     driver = webdriver.Chrome(options=options)
#     driver.set_page_load_timeout(45)
#     return driver

# def normalize_asin(value):
#     if pd.isna(value):
#         return None
#     value = str(value).strip().upper()
#     m = re.search(r"\b([A-Z0-9]{10})\b", value)
#     return m.group(1) if m else None

# def element_is_really_visible(driver, element):
#     try:
#         return driver.execute_script("""
#             const el = arguments[0];
#             if (!el) return false;

#             const rect = el.getBoundingClientRect();
#             if (rect.width === 0 || rect.height === 0) return false;

#             let node = el;
#             while (node && node.nodeType === 1) {
#                 const style = window.getComputedStyle(node);
#                 if (
#                     style.display === 'none' ||
#                     style.visibility === 'hidden' ||
#                     style.visibility === 'collapse' ||
#                     style.opacity === '0' ||
#                     node.hidden ||
#                     node.getAttribute('aria-hidden') === 'true'
#                 ) {
#                     return false;
#                 }
#                 node = node.parentElement;
#             }

#             return true;
#         """, element)
#     except:
#         return False

# def has_visible_mega_deal(driver):
#     candidate_selectors = [
#         "#dealBadge_feature_div",
#         "div[id*='dealBadge']",
#         "div[data-feature-name='dealBadge']",
#         "span.dealBadge",
#         "span.dealBadgeSupportingText",
#     ]

#     keywords = [
#         "mega deal",
#     ]

#     seen = []

#     for selector in candidate_selectors:
#         try:
#             elements = driver.find_elements(By.CSS_SELECTOR, selector)
#         except:
#             elements = []

#         for el in elements:
#             try:
#                 text = " ".join([
#                     (el.text or "").strip(),
#                     (el.get_attribute("textContent") or "").strip()
#                 ]).strip().lower()

#                 if not text:
#                     continue

#                 if not any(k in text for k in keywords):
#                     continue

#                 if not element_is_really_visible(driver, el):
#                     continue

#                 in_price_area = driver.execute_script("""
#                     const el = arguments[0];
#                     const anchors = [
#                         '#corePriceDisplay_desktop_feature_div',
#                         '#corePrice_feature_div',
#                         '#apex_desktop',
#                         '#apex_desktop_newAccordionRow',
#                         '#ppd',
#                         '#centerCol'
#                     ];
#                     for (const sel of anchors) {
#                         const parent = document.querySelector(sel);
#                         if (parent && parent.contains(el)) return true;
#                     }
#                     return false;
#                 """, el)

#                 if in_price_area:
#                     return "yes"

#                 seen.append(text)
#             except:
#                 pass

#     return "no"

# def detect_mega_deal(driver, asin):
#     url = AMAZON_BASE.format(asin)
#     try:
#         driver.get(url)

#         WebDriverWait(driver, 20).until(
#             EC.presence_of_element_located((By.TAG_NAME, "body"))
#         )

#         try:
#             WebDriverWait(driver, 20).until(
#                 lambda d: d.find_elements(By.ID, "productTitle") or
#                           d.find_elements(By.ID, "centerCol") or
#                           d.find_elements(By.ID, "ppd")
#             )
#         except:
#             pass

#         time.sleep(3)

#         title = ""
#         try:
#             title = driver.title.lower()
#         except:
#             pass

#         body_text = ""
#         try:
#             body_text = driver.find_element(By.TAG_NAME, "body").text.lower()
#         except:
#             pass

#         blocked_markers = [
#             "enter the characters you see below",
#             "sorry, we just need to make sure you're not a robot",
#             "captcha",
#             "robot check"
#         ]
#         if any(x in title or x in body_text for x in blocked_markers):
#             return "no"

#         return has_visible_mega_deal(driver)

#     except:
#         return "no"

# def main():
#     df = pd.read_excel(INPUT_FILE)

#     if ASIN_COLUMN not in df.columns:
#         raise ValueError(f"Column '{ASIN_COLUMN}' not found. Found columns: {list(df.columns)}")

#     df[ASIN_COLUMN] = df[ASIN_COLUMN].apply(normalize_asin)
#     df = df[df[ASIN_COLUMN].notna()].drop_duplicates(subset=[ASIN_COLUMN]).copy()

#     driver = setup_driver()
#     results = []

#     try:
#         for asin in df[ASIN_COLUMN]:
#             result = detect_mega_deal(driver, asin)
#             results.append({
#                 "asin": asin,
#                 "mega_deal": result
#             })
#             time.sleep(2)

#     finally:
#         driver.quit()

#     output_df = pd.DataFrame(results)[["asin", "mega_deal"]]
#     output_df.to_excel(OUTPUT_FILE, index=False)

# if __name__ == "__main__":
#     main()